Azure/PSRule.Rules.Azure

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- .vscode/extensions.json
- .vscode/settings.json
- Add GitHub templates.
- Add Visual Studio Code settings.
> Add GitHub templates and VSCode settings

- .azure-pipelines/azure-pipelines.yaml
- .azure-pipelines/stages/build-pipeline.yaml
- .vscode/settings.json
- .vscode/tasks.json
- pipeline.build.ps1
- scripts/pipeline-build.ps1
- Updated Azure DevOps pipeline to include build stage.
> Added updated pipeline with build stage

- .azure-pipelines/azure-pipelines.yaml
- .azure-pipelines/stages/build-pipeline.yaml
- Update CI pipeline strategy.
> Update CI pipeline to fix strategy

- .azure-pipelines/azure-pipelines.yaml
- Fix mapping issue in pipeline.
> Fix pipeline mapping issue

- .azure-pipelines/azure-pipelines.yaml
- .azure-pipelines/stages/build-pipeline.yaml
- Update CI pipeline with variables.
> Update CI pipeline with variables

- .azure-pipelines/azure-pipelines.yaml
- .azure-pipelines/stages/build-pipeline.yaml
> Fix build job parameters

- README.md
- docs/rules/en-US/Azure.md
- docs/scenarios/install-instructions.md
- src/PSRule.Rules.Azure/rules/Azure.AppService.Rule.ps1
- Update usage and add module install instructions.
> Update usage and install instructions

- .azure-pipelines/azure-pipelines.yaml
- .vscode/settings.json
- pipeline.build.ps1
- Add release stage to pipeline.
> Add release pipeline stage

- CHANGELOG.md
- Update change log for release.
> Pre-release v0.1.0-B190536

- CHANGELOG.md
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- Fix cannot find the type for custom attribute error. #21
Fixes #21
> Fix cannot find the type for custom attribute error #21

- README.md
> Add readme examples

- CHANGELOG.md
- Update change log for pre-release.
> Pre-release v0.1.0-B190543

- CHANGELOG.md
- README.md
- docs/rules/en-US/Azure.md
- pipeline.build.ps1
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psd1
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- src/PSRule.Rules.Azure/rules/Azure.Storage.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Cmdlet.Common.Tests.ps1
- Add units tests for Export-AzRuleData #28
- Update wording for Azure.Storage rule descriptions.
- Add code coverage reporting. #29 
Fixes #28 
Fixes #29 
> Add units tests for Export-AzRuleData #28

- .azure-pipelines/azure-pipelines.yaml
- .azure-pipelines/pipeline-build.ps1
- .azure-pipelines/pipeline-deps.ps1
- CHANGELOG.md
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- tests/PSRule.Rules.Azure.Tests/Cmdlet.Common.Tests.ps1
- Fix exported resource data overwritten. #34
Fixes #34 
> Fix exported resource data overwritten #34

- CHANGELOG.md
- Update change log for release.
> Pre-release v0.1.0-B190569

- .azure-pipelines/azure-pipelines.yaml
- Fix old script path in CI pipeline.
> Fix Live script path in CI pipeline

- pipeline.build.ps1
- Fix published module version. #38 
Fixes #38
> Fix CI published module version #38

- docs/scenarios/install-instructions.md
- Updated instructions to include reference to PowerShellGet for pre-release module.
> Added information about PowerShellGet

- CHANGELOG.md
> Pre-release v0.1.0-B190607

- pipeline.build.ps1
- Update to CI process to fix ApiKey reference.
> Fix ApiKey reference

- .azure-pipelines/pipeline-deps.ps1
- pipeline.build.ps1
- Add build tagging to CI pipeline.
> Add CI build tags

- .github/ISSUE_TEMPLATE/rule-request.md
- docs/rules/en-US/Azure.Redis.NonSslPort.md
- docs/rules/en-US/Azure.Storage.SecureTransferRequired.md
- docs/rules/en-US/Azure.Storage.SoftDelete.md
- Added rule request issue template.
- Updated rule documentation.
> Update docs and add rule issue template

- CHANGELOG.md
- docs/rules/en-US/Azure.MySQL.UseSSL.md
- docs/rules/en-US/Azure.PostgreSQL.AllowAzureAccess.md
- docs/rules/en-US/Azure.PostgreSQL.FirewallRuleCount.md
- docs/rules/en-US/Azure.PostgreSQL.UseSSL.md
- docs/rules/en-US/Azure.Redis.NonSslPort.md
- docs/scenarios/install-instructions.md
- pipeline.build.ps1
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psd1
- src/PSRule.Rules.Azure/rules/Azure.MySQL.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.PostgreSQL.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.PostgreSQL.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.PostgreSQL.json
- Added rule to check if allow access to Azure services enabled for PostgreSQL. #50
- Added rule to count the number of database server firewall rules for PostgreSQL. #51
- Added rule to check if SSL is enforced for PostgreSQL. #49
Fixes #50 
Fixes #51 
Fixes #49 
> Added PostgreSQL rules and updates #49 #50 #51

- CHANGELOG.md
- RuleToc.Doc.ps1
- docs/rules/en-US/Azure.md
- pipeline.build.ps1
> Pre-release v0.1.0-B190624

- .azure-pipelines/azure-pipelines.yaml
- README.md
- Add pre-release flag to GitHub release based on branch name.
> Add pre-release flag based on branch name

- CHANGELOG.md
- docs/scenarios/install-instructions.md
> Release v0.1.0

- .azure-pipelines/azure-pipelines.yaml
- docs/scenarios/install-instructions.md
- Updated CI pipeline version to v0.2.0.
> Post v0.1.0 pipeline update

- CHANGELOG.md
> Pre-release v0.2.0-B190604

- .vscode/extensions.json
- .vscode/settings.json
- CHANGELOG.md
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- Fix collection of ASR vault configuration for cmdlet deprecation. #63
Fixes #63 
> Fix collection of ASR vault configuration #63

- CHANGELOG.md
- src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.AppService.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.MySQL.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.PostgreSQL.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.SQL.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.VirtualMachine.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.VirtualNetwork.Rule.ps1
- Updated rules to use `Recommend` keyword instead of `Hint` alias. #71 
Fixes #71 
> Updated rules to use Recommend #71

- README.md
- docs/commands/PSRule.Rules.Azure/en-US/Export-AzRuleData.md
- docs/scenarios/install-instructions.md
> Minor doc updates

- .azure-pipelines/azure-pipelines.yaml
- CHANGELOG.md
- Update change log for release.
> Pre-release v0.2.0-B190706

- CHANGELOG.md
- docs/rules/en-US/Azure.VirtualNetwork.AppGwMinInstance.md
- docs/rules/en-US/Azure.VirtualNetwork.AppGwMinSku.md
- docs/rules/en-US/Azure.VirtualNetwork.AppGwPrevention.md
- src/PSRule.Rules.Azure/rules/Azure.VirtualNetwork.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.VirtualNetwork.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.VirtualNetwork.json
- Added support for Application Gateway v2. #75
Fixes #75 
> Add support for Application Gateway v2 #75

- tests/PSRule.Rules.Azure.Tests/Azure.VirtualMachine.Tests.ps1
- Minor update to unit test to fix typo.
> Minor unit test clean up

- CHANGELOG.md
> Pre-release v0.2.0-B190715

- .azure-pipelines/azure-pipelines.yaml
- .vscode/settings.json
- Update CI pipeline version.
- Add words to dictionary.
> Update CI pipeline post v0.2.0

- CHANGELOG.md
- docs/rules/en-US/Azure.AKS.Version.md
- src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.AKS.json
- Updated AKS version in `Azure.AKS.Version` to 1.13.7. #83
Fixes #83 
> Updated AKS version to 1.13.7 #83

- .vscode/settings.json
- CHANGELOG.md
- RuleToc.Doc.ps1
- docs/rules/en-US/Azure.VirtualMachine.BasicSku.md
- docs/rules/en-US/Azure.VirtualMachine.DiskSizeAlignment.md
- docs/rules/en-US/Azure.VirtualMachine.PromoSku.md
- docs/rules/en-US/Azure.VirtualMachine.UseHybridUseBenefit.md
- docs/rules/en-US/Azure.md
- pipeline.build.ps1
- src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.VirtualMachine.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.VirtualMachine.Tests.ps1
- Added VM SKU rules:
- VMs should avoid using expired promo SKUs. #87
- VMs should avoid using basic SKUs. #69
Fixes #87 
Fixes #69 
> Add VM SKU rules #87 #69

- .vscode/settings.json
- CHANGELOG.md
- src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.Resource.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Resource.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.Resource.json
- Excluded global services from Azure.Resource.AllowedRegions. #96
Fixes #96
> Excluded global services from region check #96

- docs/rules/en-US/Azure.ACR.AdminUser.md
- docs/rules/en-US/Azure.ACR.MinSku.md
- docs/rules/en-US/Azure.AKS.MinNodeCount.md
- docs/rules/en-US/Azure.AKS.UseRBAC.md
- docs/rules/en-US/Azure.AKS.Version.md
- docs/rules/en-US/Azure.AppService.ARRAffinity.md
- docs/rules/en-US/Azure.AppService.MinPlan.md
- docs/rules/en-US/Azure.AppService.PlanInstanceCount.md
- docs/rules/en-US/Azure.AppService.UseHTTPS.md
- docs/rules/en-US/Azure.MySQL.AllowAzureAccess.md
- docs/rules/en-US/Azure.MySQL.FirewallIPRange.md
- docs/rules/en-US/Azure.MySQL.FirewallRuleCount.md
- docs/rules/en-US/Azure.Resource.UseTags.md
- docs/rules/en-US/Azure.Storage.SecureTransferRequired.md
- docs/rules/en-US/Azure.Storage.SoftDelete.md
> Add content id mappings

- .azure-pipelines/azure-pipelines.yaml
- CHANGELOG.md
- pipeline.build.ps1
- Excluded global services from Azure.Resource.AllowedRegions. #96
- Enforce minimum TLS version for App Service. #99
- Updated App Service site rules to include slots. #100
- `Azure.AppService.ARRAffinity` and `Azure.AppService.UseHTTPS` now run against slots.
- Added rule to detect deny all inbound NSG rule. #94
- Added unused resource rules.
- Network security groups that are not associated. #93
- Unattached network interfaces. #92
- Added NSG rule to check for lateral traversal security rules. #103
> Pre-release v0.3.0-B190723

- .azure-pipelines/azure-pipelines.yaml
- pipeline.build.ps1
- Update CI process for PSRule v0.8.0 release.
> Update CI for PSRule 0.8.0

- CHANGELOG.md
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.AKS.json
- Updated `Azure.AKS.Version` to 1.14.5. #109
Fixes #109 
> Updated Azure.AKS.Version to 1.14.5 #109

- CHANGELOG.md
- docs/rules/en-US/Azure.Subscription.LimitMGDelegation.md
- docs/rules/en-US/Azure.Subscription.LimitOwner.md
- docs/rules/en-US/Azure.Subscription.UseGroups.md
- docs/rules/en-US/Azure.Subscription.UseRGDelegation.md
- docs/rules/en-US/Azure.VirtualMachine.DiskAttached.md
- docs/rules/en-US/Azure.VirtualMachine.UniqueDns.md
- docs/rules/en-US/Azure.md
- src/PSRule.Rules.Azure/rules/Azure.Subscription.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.VirtualMachine.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.VirtualNetwork.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Subscription.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.Subscription.json
- Added subscription RBAC delegation rules. #107
- Check for number of subscription owners.
- Check for RBAC inheritance from management groups.
- Check for user RBAC assignments.
- Check for RBAC delegation on individual resources.
Fixes #107 
> Added subscription RBAC delegation rules #107

- CHANGELOG.md
- Updated `Azure.AKS.Version` to 1.14.5. #109
- Added subscription RBAC delegation rules. #107
- Check for number of subscription owners.
- Check for RBAC inheritance from management groups.
- Check for user RBAC assignments.
- Check for RBAC delegation on individual resources.
> Pre-release v0.3.0-B190807

- docs/rules/en-US/Azure.AppService.MinTLS.md
- docs/rules/en-US/Azure.MySQL.UseSSL.md
- docs/rules/en-US/Azure.PostgreSQL.AllowAzureAccess.md
- docs/rules/en-US/Azure.PostgreSQL.FirewallIPRange.md
- docs/rules/en-US/Azure.PostgreSQL.FirewallRuleCount.md
- docs/rules/en-US/Azure.PostgreSQL.UseSSL.md
- docs/rules/en-US/Azure.PublicIP.IsAttached.md
- docs/rules/en-US/Azure.Redis.MinTLS.md
- docs/rules/en-US/Azure.Redis.NonSslPort.md
- docs/rules/en-US/Azure.SQL.AllowAzureAccess.md
- docs/rules/en-US/Azure.SQL.Auditing.md
- docs/rules/en-US/Azure.SQL.FirewallIPRange.md
- docs/rules/en-US/Azure.SQL.FirewallRuleCount.md
- docs/rules/en-US/Azure.SQL.ThreatDetection.md
- docs/rules/en-US/Azure.Storage.UseEncryption.md
- docs/rules/en-US/Azure.Subscription.LimitMGDelegation.md
- docs/rules/en-US/Azure.Subscription.LimitOwner.md
- docs/rules/en-US/Azure.Subscription.SecurityCenterContact.md
- docs/rules/en-US/Azure.Subscription.SecurityCenterProvisioning.md
- docs/rules/en-US/Azure.Subscription.UseGroups.md
- docs/rules/en-US/Azure.Subscription.UseRGDelegation.md
- docs/rules/en-US/Azure.VirtualMachine.ASAlignment.md
- docs/rules/en-US/Azure.VirtualMachine.ASMinMembers.md
- docs/rules/en-US/Azure.VirtualMachine.AcceleratedNetworking.md
- docs/rules/en-US/Azure.VirtualMachine.BasicSku.md
- docs/rules/en-US/Azure.VirtualMachine.DiskAttached.md
- docs/rules/en-US/Azure.VirtualMachine.DiskCaching.md
- Added additional content ids to documentation.
> Added additional content ids

- CHANGELOG.md
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- src/PSRule.Rules.Azure/rules/Azure.SQL.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.SQL.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.SQL.json
- Fix export of additional properties for `Microsoft.Sql/servers`. #114
Fixes #114 
> Fix export of Microsoft.Sql/servers #114

- .azure-pipelines/azure-pipelines.yaml
> Update CI pipeline for v0.4.0

- .gitignore
- .vscode/settings.json
- ps-project.yaml
> Update project files

- .vscode/settings.json
- CHANGELOG.md
- docs/rules/en-US/Azure.VirtualMachine.ADE.md
- docs/rules/en-US/Azure.VirtualMachine.PublicKey.md
- docs/rules/en-US/Azure.VirtualNetwork.LBProbe.md
- docs/rules/en-US/Azure.VirtualNetwork.PeerState.md
- docs/scenarios/install-instructions.md
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psd1
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- src/PSRule.Rules.Azure/en-AU/PSRule-rules.psd1
- src/PSRule.Rules.Azure/en-GB/PSRule-rules.psd1
- src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.SQL.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.Storage.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.VirtualMachine.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.VirtualNetwork.Rule.ps1
- src/PSRule.Rules.Azure/rules/Baseline.Rule.yaml
- tests/PSRule.Rules.Azure.Tests/Azure.VirtualMachine.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.VirtualNetwork.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.Storage.json
- tests/PSRule.Rules.Azure.Tests/Resources.VirtualMachine.json
- tests/PSRule.Rules.Azure.Tests/Resources.VirtualNetwork.json
- tests/PSRule.Rules.Azure.Tests/Rule.Common.Tests.ps1
- Added rule to verify connectivity of VNET peers. #120
- Added rule to check configuration of HTTP/ HTTPS load balancer probes. #121
- Added rule to verify Azure Disk Encryption. #122
- Added rule to check if public key is used for Linux. #123
- Removed dependency on Az.Storage module. #105
Fixes #120 
Fixes #121 
Fixes #122 
Fixes #123 
> Add network connectivity and disk encryption rules #120 #121 #122 #123

- CHANGELOG.md
- Added rule to verify connectivity of VNET peers. #120
- Added rule to check configuration of HTTP/ HTTPS load balancer probes. #121
- Added rule to verify Azure Disk Encryption. #122
- Added rule to check if public key is used for Linux. #123
- Removed dependency on Az.Storage module. #105
> Pre-release v0.4.0-B190902

- CHANGELOG.md
- pipeline.build.ps1
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psd1
- src/PSRule.Rules.Azure/rules/Baseline.Rule.yaml
- tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1
- Added default baseline to module. #126
Fixes #126 
> Add default baseline #126

- CHANGELOG.md
- docs/rules/en-US/Azure.md
What's changed since v0.3.0:
- New rules:
- Virtual machines:
- Added rule to verify Azure Disk Encryption. #122
- Added rule to check if public key is used for Linux. #123
- Virtual networking:
- Added rule to verify connectivity of VNET peers. #120
- Added rule to check configuration of HTTP/ HTTPS load balancer probes. #121
- Removed dependency on Az.Storage module. #105
What's changed since pre-release v0.4.0-B190902:
- Added default baseline to module. #126
> Release v0.4.0

- .azure-pipelines/azure-pipelines.yaml
- CHANGELOG.md
- Update CI version number.
- Fix missing change log entry.
> Update CI post v0.4.0

- README.md
- docs/scenarios/install-instructions.md
- Add instructions for Docker CLI.
> Docker instructions

- .azure-pipelines/azure-pipelines.yaml
> Update pipeline to v0.6.0

- CHANGELOG.md
- src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.AKS.json
- Updated `Azure.AKS.Version` to 1.14.7. #138
Fixes #138 
> Updated Azure.AKS.Version to 1.14.7 #138

- CHANGELOG.md
- src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.AKS.json
- Updated `Azure.AKS.Version` to 1.14.8. #140 
Fixes #140 
> Updated Azure.AKS.Version to 1.14.8

- CHANGELOG.md
- src/PSRule.Rules.Azure/rules/Azure.ACR.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.AppService.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.DataFactory.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.MySQL.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.PostgreSQL.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.PublicIP.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.Redis.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.SQL.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.Storage.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.Subscription.Rule.ps1
- Updated rules to use type pre-conditions. #144 
Fixes #144 
> Update rules to use type pre-conditions #144

- docs/rules/en-US/Azure.VM.Standalone.md
- docs/rules/en-US/Azure.md
- src/PSRule.Rules.Azure/rules/Azure.VirtualMachine.Rule.ps1
> Syntax error fix 's/much/must/g'

- CHANGELOG.md
- Fixed processing of `Azure.VirtualNetwork.NSGAssociated` for templates. #150
- Fixed processing of `Azure.VirtualNetwork.LateralTraversal` when `destinationPortRanges` is used. #149
- Added support for nested templates.
- Added support for `array`, `createArray`, `coalesce`, `intersection`, `dataUri` and `dataUriToString` functions.
> Pre-release v0.6.0-B1911020

- src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
- Minor code cleanup, no functional change.
> Minor code clean up

- CHANGELOG.md
- docs/commands/PSRule.Rules.Azure/en-US/Export-AzTemplateRuleData.md
- src/PSRule.Rules.Azure/Data/Template/Exceptions.cs
- src/PSRule.Rules.Azure/Data/Template/Functions.cs
- src/PSRule.Rules.Azure/Data/Template/Models.cs
- src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.csproj
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- src/PSRule.Rules.Azure/Pipeline/PipelineBuilder.cs
- src/PSRule.Rules.Azure/Pipeline/TemplatePipeline.cs
- src/PSRule.Rules.Azure/Resources/PSRuleResources.Designer.cs
- src/PSRule.Rules.Azure/Resources/PSRuleResources.resx
- tests/PSRule.Rules.Azure.Tests/Cmdlet.Common.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
- tests/PSRule.Rules.Azure.Tests/Resources.Template.json
- tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- Added support for `deployment` function.
> Added deployment function #145

- CHANGELOG.md
- src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
- tests/PSRule.Rules.Azure.Tests/Azure.Resource.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.VirtualNetwork.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Cmdlet.Common.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.Template.json
- tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
> Fix property copy loop #145

- README.md
- docs/scenarios/azure-template-ci/azure-pipelines.yaml
- docs/scenarios/azure-template-ci/azure-template-ci.md
- docs/scenarios/azure-template-ci/parameters.json
- docs/scenarios/azure-template-ci/pipeline-deps.ps1
- docs/scenarios/azure-template-ci/template.json
- docs/scenarios/azure-template-ci/validate-template.ps1
- Added documentation for using `Export-AzTemplateRuleData` in a CI scenario. #145 
Fixes #145
> Add CI template export scenario #145

- CHANGELOG.md
- src/PSRule.Rules.Azure/Data/Template/Exceptions.cs
- src/PSRule.Rules.Azure/Data/Template/ExpressionBuilder.cs
- src/PSRule.Rules.Azure/Data/Template/ExpressionParser.cs
- src/PSRule.Rules.Azure/Data/Template/ExpressionStream.cs
- src/PSRule.Rules.Azure/Data/Template/Functions.cs
- src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
- src/PSRule.Rules.Azure/Resources/PSRuleResources.Designer.cs
- src/PSRule.Rules.Azure/Resources/PSRuleResources.resx
- tests/PSRule.Rules.Azure.Tests/Azure.VirtualNetwork.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/ExpressionParserTests.cs
- Fixed out of order parameter and variables cross reference. #170
- Fixed expression parser race condition. #171
Fixes #170 
Fixes #171 
> Fix template and expression parser #170 #171

- .azure-pipelines/azure-pipelines.yaml
- .gitignore
- CHANGELOG.md
- src/PSRule.Rules.Azure/Data/Template/ExpressionBuilder.cs
- src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs
- src/PSRule.Rules.Azure/Data/Template/ExpressionParser.cs
- src/PSRule.Rules.Azure/Data/Template/ExpressionStream.cs
- src/PSRule.Rules.Azure/Data/Template/Functions.cs
- src/PSRule.Rules.Azure/Data/Template/Models.cs
- src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
- src/PSRule.Rules.Azure/Data/Template/TokenStream.cs
- src/PSRule.Rules.Azure/Resources/PSRuleResources.Designer.cs
- src/PSRule.Rules.Azure/Resources/PSRuleResources.resx
- tests/PSRule.Rules.Azure.Tests/ExpressionBuilderTests.cs
- tests/PSRule.Rules.Azure.Tests/ExpressionParserTests.cs
- tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
- tests/PSRule.Rules.Azure.Tests/Resources.Template.json
- Fixed handling of padding spaces in expressions. #173
- Fixed property of property is parsed incorrectly. #174
- Fixed root variable copy loop handling. #175
Fixed #173 
Fixed #174 
Fixed #175 
> Fix template processing #173 #174 #175

- CHANGELOG.md
- Added support for `deployment` function.
- Fixed property copy loop.
- Fixed `Export-AzTemplateRuleData` does not return FileInfo objects. #162
- Fixed automatically name outputs from `Export-AzTemplateRuleData`. #163
- Fixed resource segmentation issue when ResourceType includes trailing slash. #165
- Fixed expand resource template property as null fails. #167
- Fixed case-sensitivity of variables, parameters and functions. #168
- Fixed out of order parameter and variables cross reference. #170
- Fixed expression parser race condition. #171
- Fixed handling of padding spaces in expressions. #173
- Fixed property of property is parsed incorrectly. #174
- Fixed root variable copy loop handling. #175
> Pre-release v0.6.0-B1911046

- src/PSRule.Rules.Azure/PSRule.Rules.Azure.csproj
- tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
- Update package dependency versions.
- Drop unit test project to .NET Core 2.1 for LTS support.
> Update dependency versions

- ThirdPartyNotices.txt
- pipeline.build.ps1
- Add third party notices for Newtonsoft.Json.
> Add third party notices

- .azure-pipelines/azure-pipelines.yaml
- Update CI pipeline post v0.6.0 release.
> Update CI post v0.6.0

- README.md
- docs/features.md
- docs/rules/en-US/Azure.md
- Added features and FAQ documentation.
> Add features and FAQ

- .vscode/settings.json
- docs/rules/en-US/Azure.ACR.AdminUser.md
- docs/rules/en-US/Azure.ACR.MinSku.md
- docs/rules/en-US/Azure.AppService.ARRAffinity.md
- docs/rules/en-US/Azure.AppService.MinTLS.md
- docs/rules/en-US/Azure.AppService.UseHTTPS.md
- docs/rules/en-US/Azure.MySQL.AllowAzureAccess.md
- docs/rules/en-US/Azure.MySQL.UseSSL.md
- docs/rules/en-US/Azure.PostgreSQL.AllowAzureAccess.md
- docs/rules/en-US/Azure.PostgreSQL.UseSSL.md
- docs/rules/en-US/Azure.SQL.ThreatDetection.md
- docs/rules/en-US/Azure.Storage.SecureTransferRequired.md
- docs/rules/en-US/Azure.Storage.SoftDelete.md
- docs/rules/en-US/Azure.VirtualNetwork.AppGwMinInstance.md
- docs/rules/en-US/Azure.VirtualNetwork.AppGwMinSku.md
- docs/rules/en-US/Azure.md
- src/PSRule.Rules.Azure/rules/Azure.SQL.Rule.ps1
- General improvements and content updates for rule documentation.
> Updates to rule documentation

- CHANGELOG.md
- pipeline.build.ps1
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- Fixed missing cmdlet help. #196
Fixed #196 
> Fixed missing cmdlet help #196

- CHANGELOG.md
- Fixed missing cmdlet help. #196
- Fixed AKS templates without node pool orchestratorVersion fail. #198
> Pre-release v0.7.0-B1912017

- tests/Integration/QuickStartTemplate.Tests.ps1
- Added integration tests for working with the Azure Quick Start templates.
> Add quick start integration tests

- CHANGELOG.md
- src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1
- src/PSRule.Rules.Azure/rules/Baseline.Rule.yaml
- tests/PSRule.Rules.Azure.Tests/Azure.Resource.Tests.ps1
- Fixed handling of tags for sub-resources. #203
- Added custom bindings for common resource properties. #202
Fixes #203 
Fixes #202 
> Added custom field binding #203 #202

- CHANGELOG.md
- Fixed handling of tags for sub-resources. #203
- Added custom bindings for common resource properties. #202
> Pre-release v0.7.0-B1912024

- .azure-pipelines/azure-pipelines.yaml
- Update version after release.
> Updated CI version post v0.7.0

- .github/labeler.yml
- .github/workflows/labeler.yaml
- Add GitHub action to automatically label PRs.
> Add GitHub PR labeler

- CHANGELOG.md
- Added new rule to check automation account use encrypted variables. #211
- Added new rule to check automation account webhook expiry interval. #212
> Pre-release v0.8.0-B1912012

- .ps-rule/Rule.Rule.ps1
- .vscode/tasks.json
- pipeline.build.ps1
- ps-rule.yaml
- Added rules for QA of module rules.
> Added rule QA rules

- .github/PULL_REQUEST_TEMPLATE.md
- Added rule steps to PR template.
> Added rule steps to PR template

- CHANGELOG.md
- src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json
- tests/PSRule.Rules.Azure.Tests/Resources.AKS.json
- Updated `Azure.AKS.Version` to 1.15.5. #217
Fixes #217 
> Updated Azure.AKS.Version to 1.15.5 #217

- CHANGELOG.md
- Fixed Automation account handling with no webhooks or variables. #219
- Rule improvements from PSRule v0.12.0. #220
- Updated `Azure.AKS.Version` to 1.15.5. #217
> Pre-release v0.8.0-B1912026

- CHANGELOG.md
- docs/rules/en/Azure.File.Parameters.md
- docs/rules/en/Azure.File.Template.md
- docs/rules/en/module.md
- src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.File.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.File.Tests.ps1
- Added rules for ARM template and parameter file structure. #225
Fixes #225 
> Added rules for ARM template #225

- CHANGELOG.md
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.File.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.Parameters2.json
- tests/PSRule.Rules.Azure.Tests/Resources.Template2.json
- Fix ARM template and parameter schemas used to detect files. #234
Fixes #234 
> Fix schemas for template and parameter files #234

- CHANGELOG.md
- Fix `Azure.Resource.UseTags` applying to template and parameter files. #230
- Fix ARM template and parameter schemas used to detect files. #234
- Added new rule to check API Management uses secure protocol versions. #237
- Added new rule to check API Management published APIs use HTTPS. #236
- Added new rule to check API Management backend connections use HTTPS. #238]
- Added new rule to check API Management named values are encrypted. #239
- Added new rule to check Azure CDN connections use HTTPS. #242
> Pre-release v0.8.0-B2001018

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- docs/features.md
- Updated readme and feature docs.
- Re-ordered PR template.
> Updated readme and feature docs

- CHANGELOG.md
- docs/rules/en/Azure.Template.ParameterFile.md
- docs/rules/en/Azure.Template.TemplateFile.md
- docs/rules/en/module.md
- src/PSRule.Rules.Azure/rules/Azure.Template.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Template.Tests.ps1
- **Breaking change**: Renamed `Azure.File.*` rules to `Azure.Template.*`. #252
Fixes #252 
> Renamed Azure.File rules #252

- src/PSRule.Rules.Azure/PSRule.Rules.Azure.csproj
- Clean up references to Azure NuGet packages. In the current implementation these are not required.
> Clean up NuGet references

- tests/PSRule.Rules.Azure.Tests/Resources.VirtualNetwork.json
- Added AzureFirewallSubnet for testing of #261.
> Add AzureFirewallSubnet for testing

- CHANGELOG.md
- docs/rules/en/Azure.AppService.MinTLS.md
- docs/rules/en/Azure.Firewall.Mode.md
- docs/rules/en/Azure.FrontDoor.MinTLS.md
- docs/rules/en/Azure.FrontDoor.State.md
- docs/rules/en/Azure.FrontDoor.UseWAF.md
- docs/rules/en/Azure.FrontDoor.WAF.Enabled.md
- docs/rules/en/Azure.FrontDoor.WAF.Mode.md
- docs/rules/en/module.md
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- src/PSRule.Rules.Azure/rules/Azure.VirtualNetwork.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.VirtualNetwork.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.Firewall.json
- tests/PSRule.Rules.Azure.Tests/Resources.FrontDoor.json
- Added new rule to check Azure Firewall threat intelligence is configured as deny. #266
- Added new rule to check Front Door is enabled. #267
- Added new rule to check Front Door uses TLS 1.2. #268
- Added new rule to check Front Door uses WAF. #269
- Added new rule to check Front Door WAF policy is configured in prevention mode. #271
- Added new rule to check Front Door WAF policy is enabled. #270
Fixes #266 
Fixes #267 
Fixes #268 
Fixes #269 
Fixes #270 
Fixes #271
> Added Front Door #266 #267 #268 #269 #270 #271

- docs/rules/en/Azure.NSG.AnyInboundSource.md
- docs/rules/en/Azure.VM.UseHybridUseBenefit.md
- docs/rules/en/Azure.VM.UseManagedDisks.md
- pipeline.build.ps1
- src/PSRule.Rules.Azure/en/PSRule-rules.psd1
- src/PSRule.Rules.Azure/rules/Azure.APIM.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.VirtualMachine.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.VirtualNetwork.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.APIM.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.VirtualMachine.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.VirtualNetwork.Tests.ps1
- Minor improvements to rule documentation.
- Minor improved reasons messages for `Azure.APIM.HTTPBackend`.
> Improve APIM rule docs and reasons

- CHANGELOG.md
- Added new rule to check Azure Firewall threat intelligence is configured as deny. #266
- Added new rule to check Front Door is enabled. #267
- Added new rule to check Front Door uses TLS 1.2. #268
- Added new rule to check Front Door uses WAF. #269
- Added new rule to check Front Door WAF policy is configured in prevention mode. #271
- Added new rule to check Front Door WAF policy is enabled. #270
> Pre-release v0.9.0-B2002019

- CHANGELOG.md
- docs/rules/en/Azure.TrafficManager.Endpoints.md
- docs/rules/en/Azure.TrafficManager.Protocol.md
- docs/rules/en/module.md
- pipeline.build.ps1
- src/PSRule.Rules.Azure/en/PSRule-rules.psd1
- src/PSRule.Rules.Azure/rules/Azure.TrafficManager.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.TrafficManager.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.TrafficManager.json
- Added new rules for Traffic Manager:
- Check web-based endpoints are monitored with HTTPS. #240
- Check at least two endpoints are enabled. #241
Fixes #240 
Fixes #241 
> Add Traffic Manager rules #240 #241

- CHANGELOG.md
- docs/rules/en/Azure.KeyVault.AccessPolicy.md
- docs/rules/en/Azure.KeyVault.PurgeProtect.md
- docs/rules/en/Azure.KeyVault.SoftDelete.md
- src/PSRule.Rules.Azure/en/PSRule-rules.psd1
- src/PSRule.Rules.Azure/rules/Azure.KeyVault.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.KeyVault.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.KeyVault.json
- Added new rules for Key Vault:
- Check soft delete is enabled. #277
- Check purge protection is enabled. #280
- Check least privileges permissions assigned in access policy. #281
Fixes #277 
Fixes #280 
Fixes #281 
> Add Key Vault rules #277 #280 #281

- CHANGELOG.md
- Added new rules for Traffic Manager:
- Check web-based endpoints are monitored with HTTPS. #240
- Check at least two endpoints are enabled. #241
- Added new rules for Key Vault:
- Check soft delete is enabled. #277
- Check purge protection is enabled. #280
- Check least privileges permissions assigned in access policy. #281
> Pre-release v0.9.0-B2002026

- CHANGELOG.md
- README.md
- docs/features.md
- docs/rules/en/Azure.FrontDoor.Logs.md
- docs/rules/en/Azure.KeyVault.Logs.md
- docs/rules/en/Azure.Monitor.ServiceHealth.md
- docs/rules/en/Azure.Storage.SoftDelete.md
- docs/rules/en/Azure.Storage.UseReplication.md
- docs/rules/en/module.md
- pipeline.build.ps1
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psd1
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.KeyVault.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.Storage.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.Subscription.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.VirtualNetwork.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.KeyVault.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Storage.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Subscription.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Template.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.VirtualNetwork.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.FrontDoor.json
- tests/PSRule.Rules.Azure.Tests/Resources.KeyVault.json
- tests/PSRule.Rules.Azure.Tests/Resources.Storage.json
- tests/PSRule.Rules.Azure.Tests/Resources.Subscription.json
- tests/PSRule.Rules.Azure.Tests/Resources.Template2.json
- tests/PSRule.Rules.Azure.Tests/Resources.Template3.json
- Exclude cloud shell storage accounts from data rules. #278
- Added new rule for Subscriptions:
- Check if service health alerts are configured. #290
- Added new rule for Key Vault:
- Check if diagnostic logs are configured. #288
- Added new rule for Front Door:
- Check if diagnostic logs are configured. #289
- Removed module dependency on `Az.Security`. #105
Fixes #278 
Fixes #290 
Fixes #288 
Fixes #289 
Fixes #105
> Add diagnostic log rules #278 #290 #288 #289 #105

- CONTRIBUTING.md
- README.md
- build.ps1
- docs/features.md
- docs/scenarios/install-instructions.md
- Expanded instructions for contributing.
- Added simple `build.ps1` script.
> Expanded contributing instructions

- CHANGELOG.md
- Exclude cloud shell storage accounts from data rules. #278
- Added new rule for Subscriptions:
- Check if service health alerts are configured. #290
- Added new rule for Key Vault:
- Check if diagnostic logs are configured. #288
- Added new rule for Front Door:
- Check if diagnostic logs are configured. #289
- Removed module dependency on `Az.Security`. #105
> Pre-release v0.9.0-B2002036

- docs/rules/en/Azure.KeyVault.Logs.md
- docs/rules/en/Azure.KeyVault.PurgeProtect.md
- docs/rules/en/Azure.KeyVault.SoftDelete.md
- docs/rules/en/Azure.Resource.UseTags.md
- src/PSRule.Rules.Azure/en/PSRule-rules.psd1
- src/PSRule.Rules.Azure/rules/Azure.KeyVault.Rule.ps1
- Corrections and additional links for Key Vault rule documentation.
- Improved documentation for `Azure.Resource.UseTags`
> Updated to Key Vault rule docs

- .azure-pipelines/azure-pipelines.yaml
- Updated CI version to v0.10.0.
> Post v0.9.0 CI update

- .azure-pipelines/azure-pipelines.yaml
- .azure-pipelines/jobs/test.yaml
- .azure-pipelines/jobs/testContainer.yaml
- .vscode/settings.json
- pipeline.build.ps1
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.csproj
- tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
- Added PowerShell 7.0 to CI pipeline.
- Re-organized stages to improve CI performance.
- Added credential scan.
Fixes #299
> Added PowerShell 7.0 to CI pipeline #299

- CHANGELOG.md
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- Improvements to verbose logging of `Export-AzRuleData`. #301
Fixes #301 
> Updates to export rule data verbose logging #301

- CHANGELOG.md
- src/PSRule.Rules.Azure/Data/Template/Functions.cs
- tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
- tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
- Fixed union of object properties in templates. #303
Fixes #303 
> Fixed union of object properties in templates #303

- CHANGELOG.md
- Improvements to verbose logging of `Export-AzRuleData`. #301
- Fixed union of object properties in templates. #303
> Pre-release v0.10.0-B2002023

- docs/rules/en/Azure.AKS.MinNodeCount.md
- docs/rules/en/Azure.SecurityCenter.Provisioning.md
- src/PSRule.Rules.Azure/en/PSRule-rules.psd1
- src/PSRule.Rules.Azure/rules/Azure.Subscription.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.VirtualNetwork.Rule.ps1
- Updates to recommendation docs.
- Added additional reason messages to some rules.
> Improve reasons and recommendation docs

- CHANGELOG.md
- pipeline.build.ps1
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- src/PSRule.Rules.Azure/rules/Azure.VirtualNetwork.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.VirtualNetwork.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.FrontDoor.json
- Fixed detection of diagnostic logging for Front Door. #307
- Fixed Front Door WAF Policy export. #308
Fixes #307 
Fixes #308 
> Fix Front Door and Front Door WAF issue #307 #308

- CHANGELOG.md
- Fixed detection of diagnostic logging for Front Door. #307
- Fixed Front Door WAF Policy export. #308
> Pre-release v0.10.0-B2003004

- .config/CredScanSuppressions.json
- .vscode/settings.json
- CHANGELOG.md
- src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.VirtualMachine.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.VirtualMachine.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.VirtualNetwork.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.VirtualMachine.Template.json
- Fixed unused VM resource false positives in templates. #312
- Fixed handling SKU for accelerated networking. #314
- Fixed detection of hybrid use benefit in templates. #313
Fixes #312 
Fixes #313 
Fixes #314 
> Fixes for VM rules #312 #313 #314

- .azure-pipelines/azure-pipelines.yaml
- .azure-pipelines/jobs/test.yaml
- .azure-pipelines/jobs/testContainer.yaml
- Update CI pipeline to use PowerShell 7.0 GA image. #319 
Fixes #319
> Use PS 7.0 GA image #319

- CHANGELOG.md
- src/PSRule.Rules.Azure/Pipeline/TemplatePipeline.cs
- src/PSRule.Rules.Azure/Resources/PSRuleResources.Designer.cs
- src/PSRule.Rules.Azure/Resources/PSRuleResources.resx
- tests/PSRule.Rules.Azure.Tests/Cmdlet.Common.Tests.ps1
- Fixed exception message when a template or parameter file is not found. #316
Fixes #316 
> Fixed template not found message #316

- CHANGELOG.md
- Fixed unused VM resource false positives in templates. #312
- Fixed handling SKU for accelerated networking. #314
- Fixed detection of hybrid use benefit in templates. #313
- Fixed exception message when a template or parameter file is not found. #316
> Pre-release v0.10.0-B2003032

- docs/features.md
- docs/scenarios/install-instructions.md
- Updates and corrections in FAQ and install instructions.
> Updates and corrections in FAQ

- CHANGELOG.md
- src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json
- tests/PSRule.Rules.Azure.Tests/Resources.AKS.json
- Updated `Azure.AKS.Version` to 1.16.7. #330
Fixes #330 
> Updated Azure.AKS.Version to 1.16.7 #330

- CHANGELOG.md
- Added support for linking parameter and template files for analysis with metadata. #324
- Added `Get-AzRuleTemplateLink` cmdlet to get metadata link to template files.
- See cmdlet help for usage.
- Removed warning message for `azureAllowedRegions` option. #328
- Updated `Azure.AKS.Version` to 1.16.7. #330
> Pre-release v0.10.0-B2003051

- .azure-pipelines/azure-pipelines.yaml
- Update pipeline version post v0.10.0.
> Post v0.10.0 pipeline update

- CHANGELOG.md
What's changed since v0.10.0:
- Bug fixes:
- Fixed false positive for unused public IP in templates. #336
- Fixed false positive for use of managed disks in templates. #337
- Fixed false positive for disk caching when no VM data disks is null in templates. #338
> Release v0.10.1

- CHANGELOG.md
- docs/rules/en/Azure.APIM.CertificateExpiry.md
- docs/rules/en/Azure.APIM.ManagedIdentity.md
- docs/rules/en/Azure.APIM.ProductApproval.md
- docs/rules/en/Azure.APIM.ProductSubscription.md
- docs/rules/en/Azure.APIM.SampleProducts.md
- docs/rules/en/module.md
- pipeline.build.ps1
- ps-rule.yaml
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- src/PSRule.Rules.Azure/en/PSRule-rules.psd1
- src/PSRule.Rules.Azure/rules/Azure.APIM.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.APIM.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/PathBuilderTests.cs
- tests/PSRule.Rules.Azure.Tests/Resources.APIM.json
- New rules:
- Check API Management products require a subscription. #342
- Check API Management products require approval. #343
- Check API Management sample products have been removed. #344
- Check API Management uses a managed identity. #345
- Check API Management certificates are not expired. #346
Fixes #342 
Fixes #343 
Fixes #344 
Fixes #345 
Fixes #346 
> Added APIM rules #342 #343 #344 #345 #346

- .vscode/tasks.json
- README.md
- RuleToc.Doc.ps1
- docs/rules/en/module.md
- docs/rules/en/resource.md
- pipeline.build.ps1
- Update table of contents to include a list of rules by resource.
> Additionally sort rules by resource

- CHANGELOG.md
- New rules:
- Check API Management products require a subscription. #342
- Check API Management products require approval. #343
- Check API Management sample products have been removed. #344
- Check API Management uses a managed identity. #345
- Check API Management certificates are not expired. #346
> Pre-release v0.11.0-B2004005

- .ps-rule/Rule.Rule.ps1
- CHANGELOG.md
- docs/rules/en/Azure.AKS.NodeMinPods.md
- docs/rules/en/module.md
- docs/rules/en/resource.md
- src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1
- Check AKS nodes use a minimum number of pods. #274
Fixes #274 
> Added AKS rule for min number of pods #274

- CHANGELOG.md
- src/PSRule.Rules.Azure/rules/Azure.Template.Rule.ps1
- src/PSRule.Rules.Azure/rules/Baseline.Rule.yaml
- Add name and type bindings for template files. #353
Fixes #353 
> Add name and type bindings for template files #353

- .azure-pipelines/azure-pipelines.yaml
- Update CI pipeline version to use v0.12.0.
> Updated CI pipeline post v0.11.0

- CHANGELOG.md
- docs/rules/en/Azure.Storage.BlobAccessType.md
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- src/PSRule.Rules.Azure/en/PSRule-rules.psd1
- src/PSRule.Rules.Azure/rules/Azure.Storage.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Storage.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.Storage.Parameters.json
- tests/PSRule.Rules.Azure.Tests/Resources.Storage.Template.json
- tests/PSRule.Rules.Azure.Tests/Resources.Storage.json
- Check Storage blob containers use private access type. #365
Fixes #365 
> Use private blob container #365

- CHANGELOG.md
- docs/rules/en/Azure.Policy.Descriptors.md
- docs/rules/en/module.md
- docs/rules/en/resource.md
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- src/PSRule.Rules.Azure/rules/Azure.Policy.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Policy.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.Policy.Parameters.json
- tests/PSRule.Rules.Azure.Tests/Resources.Policy.Template.json
- tests/PSRule.Rules.Azure.Tests/Resources.Policy.json
- Check Policy definitions use descriptive fields. #364
Fixes #364 
> Policy definitions use descriptive fields #364

- CHANGELOG.md
- New rules:
- Storage:
- Check Storage blob containers use private access type. #365
- Policy:
- Check Policy definitions use descriptive fields. #364
> Pre-release v0.12.0-B2005005

- .vscode/settings.json
- CHANGELOG.md
- docs/rules/en/Azure.ERGateway.LegacySKU.md
- docs/rules/en/Azure.VPNGateway.ActiveActive.md
- docs/rules/en/Azure.VPNGateway.LegacySKU.md
- docs/rules/en/module.md
- docs/rules/en/resource.md
- src/PSRule.Rules.Azure/rules/Azure.VirtualNetwork.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.VirtualNetwork.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.ExpressRoute.Parameters.json
- tests/PSRule.Rules.Azure.Tests/Resources.ExpressRoute.Template.json
- tests/PSRule.Rules.Azure.Tests/Resources.VPN.Parameters.json
- tests/PSRule.Rules.Azure.Tests/Resources.VPN.Template.json
- tests/PSRule.Rules.Azure.Tests/Resources.VirtualNetwork.json
- New rules:
- ExpressRoute Gateway:
- Check ExpressRoute Gateway uses current SKU. #369
- VPN Gateway:
- Check VPN Gateway uses current SKU. #370
- Check VPN Gateway uses active-active configuration. #371
Fixes #369 
Fixes #370 
Fixes #371 
> Added VNG rules #369 #370 #371

- .azure-pipelines/azure-pipelines.yaml
- Updated pipeline display names for macOS.
> Update pipeline display names for macOS

- CHANGELOG.md
- New rules:
- Check AKS cluster name requirements. #373
- Check AKS cluster DNS prefix requirements. #373
- Check registry name requirements. #373
- Front Door:
- Check Front Door name requirements. #373
- Load Balancer:
- Check Load Balancer name requirements. #373
- Network Security Group:
- Check NSG name requirements. #373
- Public IP:
- Check Public IP name requirements. #373
- Resource Group:
- Check Resource Group name requirements. #373
- Route table
- Check Route table name requirements. #373
- SignalR Service:
- Check SignalR Service name requirements. #373
- Storage:
- Check Storage Account name requirements. #373
- Check VNET name requirements. #373
- Check VNET subnet name requirements. #373
- Virtual …
> Pre-release v0.12.0-B2005019

- CHANGELOG.md
- docs/rules/en/Azure.SQL.AAD.md
- docs/rules/en/Azure.SQL.AllowAzureAccess.md
- docs/rules/en/Azure.SQL.Auditing.md
- docs/rules/en/Azure.SQL.FirewallIPRange.md
- docs/rules/en/Azure.SQL.FirewallRuleCount.md
- docs/rules/en/Azure.SQL.TDE.md
- docs/rules/en/Azure.SQL.ThreatDetection.md
- docs/rules/en/module.md
- docs/rules/en/resource.md
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- src/PSRule.Rules.Azure/rules/Azure.SQL.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.SQL.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.SQL.json
- New rules:
- Check SQL Database uses TDE. #379
- Check SQL Database uses AAD authentication. #378
Fixes #379 
Fixes #378 
> Added SQL TDE and AAD rules #378 #379

- CHANGELOG.md
- New rules:
- Check SQL Database uses TDE. #379
- Check SQL Database uses AAD authentication. #378
- Bug fixes:
- Fixed handling of subnet sub-resource name with slash. #381
> Pre-release v0.12.0-B2005026

- .azure-pipelines/azure-pipelines.yaml
- Updated CI pipeline version to v0.13.0.
> Update CI pipeline post v0.12.0

- CHANGELOG.md
What's changed since v0.12.0:
- Bug fixes:
- Fixed subnet name check for VNET with no subnets. #386
> Release v0.12.1

- CHANGELOG.md
- pipeline.build.ps1
- src/PSRule.Rules.Azure/rules/Baseline.Rule.yaml
- src/PSRule.Rules.Azure/rules/Config.Rule.yaml
- Fixed module default culture. #390
Fixes #390
> Fixed module default culture #390

- CHANGELOG.md
- Updated `Azure.AKS.Version` to 1.16.9. #394
- Bug fixes:
- Fixed module default culture. #390
> Pre-release v0.13.0-B2006003

- .devcontainer/devcontainer.json
- .vscode/extensions.json
- Add Codespaces settings file.
> Add Codespaces settings file

- docs/features.md
- docs/scenarios/install-instructions.md
- Updated FAQ with links to general PSRule FAQ.
- Updated to install instructions to reference PS 7.0.
> Minor updates to FAQ and install instructions

- src/PSRule.Rules.Azure/PSRule.Rules.Azure.csproj
- tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
- Updated dependencies to latest versions.
> Updated dependency packages

- docs/features.md
- docs/rules/en/Azure.Resource.AllowedRegions.md
- docs/rules/en/Azure.Resource.UseTags.md
- Updated FAQ links to scenarios.
- Minor updates to rule documentation.
> Updated FAQ links and rule documentation

- CHANGELOG.md
- New rules:
- Check AKS clusters use a Standard load balancer SKU. #334
- Check AKS clusters use Managed Identities for cluster infrastructure. #333
- Check AKS clusters use Azure Policy add-on (preview). #405
> Pre-release v0.13.0-B2006017

- CHANGELOG.md
- New rules:
- Public IP:
- Check Public IP domain name label requirements. #389
- Virtual Machines:
- Check Availability Set name requirements. #387
- Check Computer name requirements. #387
- Check Managed Disk name requirements. #387
- Check Network Interface name requirements. #387
- Check Virtual Machine name requirements. #387
- Check Proximity Placement Group name requirements. #387
- Check Computer name requirements. #387
- Check Virtual Machine Scale Set name requirements. #387
> Pre-release v0.13.0-B2006023

- CHANGELOG.md
- src/PSRule.Rules.Azure/Data/Template/Exceptions.cs
- src/PSRule.Rules.Azure/Data/Template/ExpressionBuilder.cs
- src/PSRule.Rules.Azure/Resources/PSRuleResources.Designer.cs
- src/PSRule.Rules.Azure/Resources/PSRuleResources.resx
- tests/PSRule.Rules.Azure.Tests/ExpressionBuilderTests.cs
- Fixed exception message for object property that does not exist. #362
Fixes #362 
> Fixed error for property that does not exist #362

- CHANGELOG.md
- Added `Azure.GA_2020_06` baseline. #399
- Includes rules released before or during June 2020 for Azure GA features.
- Bug fixes:
- Fixed exception message for object property that does not exist. #362
> Pre-release v0.13.0-B2006032

- CHANGELOG.md
- src/PSRule.Rules.Azure/Data/Template/Exceptions.cs
- src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs
- src/PSRule.Rules.Azure/Data/Template/Functions.cs
- src/PSRule.Rules.Azure/Resources/PSRuleResources.Designer.cs
- src/PSRule.Rules.Azure/Resources/PSRuleResources.resx
- tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
- Fixed substring raises an exception processing sub expressions. #413
Fixes #413
> Fix substring error with sub expressions #413

- .azure-pipelines/azure-pipelines.yaml
- Updated CI pipeline version to v0.14.0.
> Update CI pipeline version to v0.14.0

- docs/rules/en/Azure.AKS.NodeMinPods.md
- docs/rules/en/Azure.AKS.PoolVersion.md
- docs/rules/en/Azure.AKS.StandardLB.md
- docs/rules/en/Azure.AKS.UseRBAC.md
- docs/rules/en/Azure.AKS.Version.md
- Updates to AKS rule documentation to fix gramma and add additional links.
> Fixes and updates for AKS rule documentation

- CHANGELOG.md
- docs/baselines/en/Azure.All.md
- docs/baselines/en/Azure.Default.md
- docs/baselines/en/Azure.Preview.md
- docs/rules/en/Azure.RBAC.PIM.md
- src/PSRule.Rules.Azure/en/PSRule-rules.psd1
- src/PSRule.Rules.Azure/rules/Azure.Subscription.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Subscription.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.Subscription.json
- Check subscription is managed by PIM. #422
Fixes #422 
> Check subscription is managed by PIM #422

- docs/features.md
- Fix working in features documentation.
> Minor corrections in features doc

- CHANGELOG.md
- src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json
- tests/PSRule.Rules.Azure.Tests/Resources.AKS.json
- Updated `Azure.AKS.Version` to 1.17.7.
Fixes #427
> Updated Azure.AKS.Version to 1.17.7 #427

- CHANGELOG.md
- New rules:
- Subscriptions:
- Check subscription is managed by PIM. #422
- Updated `Azure.AKS.Version` to 1.17.7. #427
- Updated rule reasons and logic. #424
> Pre-release v0.14.0-B2007020

- .vscode/settings.json
- CHANGELOG.md
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- src/PSRule.Rules.Azure/rules/Azure.VM.Rule.ps1
- Fixed masking for network connection resource configuration. #434
Fixes #434 
> Fixed network connection masking #434

- CHANGELOG.md
- docs/rules/en/Azure.VM.Standalone.md
- src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.VM.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.VM.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.VirtualMachine.json
- Fixed hybrid use benefit rule to exclude Windows client OSs. #433
- Fixed VM standalone rule to exclude Windows client OSs. #442 
Fixes #433 
Fixes #442 
> Fixed rules for client OS #433 #442

- CHANGELOG.md
- New rules:
- Check API Management service name requirements. #437
- Check API Management products have legal terms. #438
- Check API Management products have a display name and description. #439
- Check API Management APIs have a display name and description. #440
- Bug fixes:
- Fixed masking for network connection resource configuration. #434
- Fixed hybrid use benefit rule to exclude Windows client OSs. #433
- Fixed VM standalone rule to exclude Windows client OSs. #442
> Pre-release v0.14.0-B2007031

- .azure-pipelines/azure-pipelines.yaml
- Update CI pipeline version to v0.15.0.
> Post v0.14.0 release update

- CHANGELOG.md
What's changed since v0.14.1:
- Bug fixes:
- Fixed resource tags rule to exclude diagnostic settings. #448
> Release v0.14.1

- pipeline.build.ps1
- ps-project.yaml
- src/PSRule.Rules.Azure/rules/Azure.ACR.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.APIM.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.AppService.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.Redis.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.APIM.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.VM.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.VMSS.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.VirtualNetwork.Tests.ps1
- Updates to rules and tests based on improvements in PSRule. No functional changes.
- Rollback culture workaround. #318 
Fixes #318 
> Use PSRule v0.19.0 improvements #318

- CHANGELOG.md
- src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json
- tests/PSRule.Rules.Azure.Tests/Resources.AKS.json
- Updated Azure.AKS.Version rule to Kubernetes 1.17.9. #452
Fixes #452 
> Updated Azure.AKS.Version to 1.17.9 #452

- .azure-pipelines/azure-pipelines.yaml
- Skip component detection for analysis already done on build.
- Added tests for PowerShell 7.1 preview 5 - ubuntu-18.04.
> Added PowerShell 7.1 preview to tests

- CHANGELOG.md
- New rules:
- Check ARM template parameters are used. #232
- Check ARM template variables are used. #233
- Check ARM template parameters include a metadata description. #360
- Check ARM templates define at least one resource. #359
- Check Storage Accounts reject TLS versions older than 1.2. #455
- Check Storage Accounts only accept authorized requests. #456
- Updated `Azure.AKS.Version` to 1.17.9. #452
> Pre-release v0.15.0-B2008026

- docs/scenarios/install-instructions.md
- Minor updates to install instructions.
> Updated install instructions

- CHANGELOG.md
- src/PSRule.Rules.Azure/rules/Azure.Template.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Template.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.Empty.Template.2.json
- tests/PSRule.Rules.Azure.Tests/Resources.Empty.Template.3.json
- Fixed use variables check when no variables are defined. #462
Fixes #462 
> Fixed use variables check #462

- README.md
- docs/scenarios/azure-template-ci/azure-template-ci.md
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.csproj
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psd1
- Minor updates to module description and doco.
> Updated module description

- docs/baselines/en/Azure.All.md
- docs/baselines/en/Azure.Default.md
- docs/baselines/en/Azure.GA_2020_06.md
- docs/baselines/en/Azure.Preview.md
- docs/rules/en/Azure.AppService.MinTLS.md
- docs/rules/en/Azure.Storage.MinTLS.md
- docs/rules/en/module.md
- docs/rules/en/resource.md
- Updated severity for TLS rules.
> Updated severity for TLS rules

- .azure-pipelines/azure-pipelines.yaml
- Updated CI version to v0.16.0.
> Updated CI pipeline to v0.16.0

- CHANGELOG.md
- src/PSRule.Rules.Azure/Common/JsonConverters.cs
- src/PSRule.Rules.Azure/Data/Template/Exceptions.cs
- src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs
- src/PSRule.Rules.Azure/Data/Template/ExpressionStream.cs
- src/PSRule.Rules.Azure/Data/Template/Functions.cs
- src/PSRule.Rules.Azure/Pipeline/Exceptions.cs
- src/PSRule.Rules.Azure/Pipeline/TemplateLinkPipeline.cs
- src/PSRule.Rules.Azure/Pipeline/TemplatePipeline.cs
- src/PSRule.Rules.Azure/Resources/PSRuleResources.Designer.cs
- src/PSRule.Rules.Azure/Resources/PSRuleResources.resx
- tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
- Improve output of template processing exceptions. #484
Fixes #484 
> Improve output of template processing exceptions #484

- CHANGELOG.md
What's changed since v0.15.0:
- New rules:
- CDN:
- Check CDN endpoint naming requirements. #486
- Check CDN endpoints use TLS 1.2. #487
- Updated rule content to align with Microsoft Azure Well-Architected Framework pillars. #481
- Improve output of template processing exceptions. #484
> Pre-release v0.16.0-B2009004

- CHANGELOG.md
- src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1
- Fixed deprecated `$Rule` properties. #491
Fixes #491 
> Fixed deprecated $Rule properties #491

- .ps-rule/OpenSource.Rule.ps1
- Updated repository validation rules to use improvements in PSRule v0.20.0,
> Updated repo rules for PSRule v0.20.0

- CHANGELOG.md
What's changed since pre-release v0.16.0-B2009004:
- Bug fixes:
- Fixed deprecated `$Rule` properties. #491
> Pre-release v0.16.0-B2009011

- CHANGELOG.md
- src/PSRule.Rules.Azure/Pipeline/TemplateLinkPipeline.cs
- src/PSRule.Rules.Azure/rules/Azure.Template.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.Parameters.json
- Fixed parameter file detection with `2019-04-01` schema. #495
Fixes #495 
> Fixed support for 2019-04-01 parameter file schema #495

- CHANGELOG.md
What's changed since pre-release v0.16.0-B2009011:
- Bug fixes:
- Fixed parameter file detection with `2019-04-01` schema. #495
> Pre-release v0.16.0-B2009019

- CHANGELOG.md
- src/PSRule.Rules.Azure/rules/Azure.DataFactory.Rule.ps1
- Fixed Data Factory version not detected with template. #498
> Fixed ADF version not detected with template #498

- CHANGELOG.md
What's changed since pre-release v0.16.0-B2009019:
- Bug fixed:
- Fixed Data Factory version not detected with template. #498
> Pre-release v0.16.0-B2009024

- CHANGELOG.md
- src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json
- tests/PSRule.Rules.Azure.Tests/Resources.AKS.json
- Updated `Azure.AKS.Version` to 1.18.8. #504
Fixes #504 
> Updated Azure.AKS.Version to 1.18.8 #504

- BaselineToc.Doc.ps1
- CHANGELOG.md
- README.md
- docs/baselines/en/Azure.GA_2020_09.md
- pipeline.build.ps1
- src/PSRule.Rules.Azure/rules/Baseline.Rule.yaml
- tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1
- Added `Azure.GA_2020_09` baseline. #488
- Bump PSRule dependency to v0.20.0.
> Added Azure.GA_2020_09 baseline #488

- CHANGELOG.md
What's changed since pre-release v0.16.0-B2009024:
- Added `Azure.GA_2020_09` baseline. #488
- Includes rules released before or during September 2020 for Azure GA features.
- Marked baseline `Azure.GA_2020_06` as obsolete.
- Updated `Azure.AKS.Version` to 1.18.8. #504
- Engineering:
- Bump PSRule dependency to v0.20.0.
> Pre-release v0.16.0-B2009033

- README.md
- docs/features.md
- Fixes for features/ FAQ/ readme.
> Minor documentation fixes

- .github/ISSUE_TEMPLATE/question.md
- README.md
- SUPPORT.md
> Add support.md

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/question.md
> Updated issue templates

- .github/dependabot.yml
- .github/workflows/analyze.yaml
- pipeline.build.ps1
- ps-rule.yaml
- Added GitHub Actions workflow for repository validation.
- Updated CI process to use PSRule file input to scan repository available in v0.20.0.
> Updated repository validation CI

- .azure-pipelines/azure-pipelines.yaml
- Update CI pipeline version to v0.17.0
> Updated CI pipeline post v0.16.0

- docs/baselines/en/Azure.All.md
- docs/baselines/en/Azure.Default.md
- docs/baselines/en/Azure.GA_2020_06.md
- docs/baselines/en/Azure.GA_2020_09.md
- docs/baselines/en/Azure.Preview.md
- docs/rules/en/Azure.ACR.AdminUser.md
- docs/rules/en/Azure.ACR.MinSku.md
- docs/rules/en/Azure.ACR.Name.md
- docs/rules/en/Azure.MySQL.FirewallIPRange.md
- docs/rules/en/Azure.MySQL.FirewallRuleCount.md
- docs/rules/en/Azure.PostgreSQL.FirewallIPRange.md
- docs/rules/en/Azure.PostgreSQL.FirewallRuleCount.md
- docs/rules/en/Azure.RBAC.PIM.md
- docs/rules/en/Azure.SQL.AllowAzureAccess.md
- docs/rules/en/Azure.SQL.Auditing.md
- docs/rules/en/Azure.SQL.FirewallIPRange.md
- docs/rules/en/Azure.SQL.FirewallRuleCount.md
- docs/rules/en/Azure.SQL.ThreatDetection.md
- docs/rules/en/module.md
- docs/rules/en/resource.md
- Updates to rule documentation including links, display names, and recommendations.
> Rule doc updates

- SECURITY.md
- pipeline.build.ps1
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.csproj
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psd1
- Updated project files with support descriptions.
- Updated security.md with latest version.
> Updated project file descriptions

- CHANGELOG.md
What's changed since v0.16.0:
- Added support for `providers` template function. #177
- Added support for `dateTimeAdd` template function. #516
> Pre-release v0.17.0-B2009009

- CHANGELOG.md
- docs/baselines/en/Azure.All.md
- docs/baselines/en/Azure.Default.md
- docs/baselines/en/Azure.Preview.md
- docs/rules/en/Azure.LogicApp.LimitHTTPTrigger.md
- docs/rules/en/module.md
- docs/rules/en/resource.md
- src/PSRule.Rules.Azure/rules/Azure.LogicApps.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.LogicApp.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.LogicApp.json
- Check Logic App apps limit IP range for HTTP triggers. #526
Fixes #526 
> Limit IP range for Logic App HTTP triggers #526

- CHANGELOG.md
- docs/baselines/en/Azure.All.md
- docs/baselines/en/Azure.Default.md
- docs/baselines/en/Azure.Preview.md
- docs/rules/en/Azure.AppConfig.Name.md
- docs/rules/en/Azure.AppConfig.SKU.md
- docs/rules/en/module.md
- docs/rules/en/resource.md
- src/PSRule.Rules.Azure/rules/Azure.AppConfig.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.AppConfig.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.AppConfig.json
- Check App Configuration stores meet name requirements.
- Check App Configuration stores use standard SKU.
Fixes #528 
> Add rules for App Configuration #528

- docs/baselines/en/Azure.All.md
- docs/baselines/en/Azure.Default.md
- docs/baselines/en/Azure.GA_2020_06.md
- docs/baselines/en/Azure.GA_2020_09.md
- docs/baselines/en/Azure.Preview.md
- docs/rules/en/Azure.ACR.AdminUser.md
- docs/rules/en/Azure.AKS.ManagedIdentity.md
- docs/rules/en/Azure.AKS.UseRBAC.md
- docs/rules/en/Azure.APIM.ManagedIdentity.md
- docs/rules/en/Azure.RBAC.LimitOwner.md
- docs/rules/en/Azure.RBAC.PIM.md
- docs/rules/en/Azure.RBAC.UseGroups.md
- docs/rules/en/Azure.RBAC.UseRGDelegation.md
- docs/rules/en/module.md
- docs/rules/en/resource.md
- src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.APIM.Rule.ps1
- Documentation updates and improvements.
> Documentation updates

- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- Added additional verbose logging for context selection.
> Added verbose logging for context selection

- CHANGELOG.md
- docs/baselines/en/Azure.All.md
- docs/baselines/en/Azure.Default.md
- docs/baselines/en/Azure.Preview.md
- docs/rules/en/Azure.AppService.HTTP2.md
- docs/rules/en/Azure.AppService.ManagedIdentity.md
- docs/rules/en/module.md
- docs/rules/en/resource.md
- src/PSRule.Rules.Azure/rules/Azure.AppService.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.AppService.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.AppService.Template.json
- tests/PSRule.Rules.Azure.Tests/Resources.AppService.json
- Check App Service apps use HTTP/2. #538
- Check App Service apps use managed identities. #537
Fixes #538 
Fixes #537 
> Added App Services rules #538 #537

- CHANGELOG.md
What's changed since pre-release v0.17.0-B2010006:
- New rules:
- App Service:
- Check App Service apps use HTTP/2. #538
- Check App Service apps use managed identities. #537
- Storage:
- Updated `Azure.Storage.UseReplication` for additional use cases.
- Added support for geo-zone-redundant storage. #535
- Exclude storage tagged with `resource-usage = 'azure-functions'` or `resource-usage = 'azure-monitor'`. #534
- Bug fixes:
- Fixed App Service rule site config false positives in templates. #533
> Pre-release v0.17.0-B2010017

- CHANGELOG.md
- src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
- tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
- tests/PSRule.Rules.Azure.Tests/Resources.FrontDoor.Template.json
- tests/PSRule.Rules.Azure.Tests/Resources.Template.json
- tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- Fixed expansion of templates with multiple variables copy blocks. #541
Fixes #541 
> Fixed templates with multiple variables copy blocks #541

- CHANGELOG.md
What's changed since pre-release v0.17.0-B2010017:
- Bug fixes:
- Fixed expansion of templates with multiple variables copy blocks. #541
> Pre-release v0.17.0-B2010022

- CHANGELOG.md
- docs/rules/en/Azure.Storage.SoftDelete.md
- src/PSRule.Rules.Azure/rules/Azure.Storage.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Storage.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.Storage.json
- Fixed HNS storage accounts so they are excluded from blob soft delete rule. #554
Fixes #554 
> Fix HNS blob soft delete #554

- CHANGELOG.md
- docs/baselines/en/Azure.All.md
- docs/baselines/en/Azure.Default.md
- docs/baselines/en/Azure.GA_2020_06.md
- docs/baselines/en/Azure.GA_2020_09.md
- docs/baselines/en/Azure.Preview.md
- docs/rules/en/Azure.FrontDoor.Name.md
- docs/rules/en/Azure.FrontDoor.WAF.Name.md
- docs/rules/en/module.md
- docs/rules/en/resource.md
- src/PSRule.Rules.Azure/rules/Azure.FrontDoor.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.FrontDoor.Tests.ps1
- Check Front Door WAF policy name requirements. #552
Fixes #552 
> Check Front Door WAF policy name requirements #552

- .vscode/settings.json
- CHANGELOG.md
- docs/baselines/en/Azure.All.md
- docs/baselines/en/Azure.Default.md
- docs/baselines/en/Azure.Preview.md
- docs/rules/en/Azure.ACR.ContainerScan.md
- docs/rules/en/Azure.ACR.ContentTrust.md
- docs/rules/en/Azure.ACR.GeoReplica.md
- docs/rules/en/Azure.ACR.ImageHealth.md
- docs/rules/en/Azure.ACR.Quarantine.md
- docs/rules/en/Azure.ACR.Retention.md
- docs/rules/en/Azure.ACR.Usage.md
- docs/rules/en/module.md
- docs/rules/en/resource.md
- src/PSRule.Rules.Azure/en/PSRule-rules.psd1
- src/PSRule.Rules.Azure/rules/Azure.ACR.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.ACR.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.ACR.json
- Check registries use container image scanning.
- Check registries image scanning results are healthy.
- Check registries use content trust.
- Check registries are geo-replicated.
- Check registries uses storage space less than included storage.
- Check registries have a retention set of untagged manifests (preview).
- Check registries use image quarantine pattern (preview).
Fixes #558 
> Additional container registry rules #558

- .vscode/markdown.code-snippets
- Added vscode markdown template with fields for Azure rules.
> Added custom markdown template

- CHANGELOG.md
What's changed since v0.17.0:
- New rules:
- Check registries use container image scanning. #558
- Check registries image scanning results are healthy. #558
- Check registries use content trust. #558
- Check registries are geo-replicated. #558
- Check registries uses storage space less than included storage. #558
- Check registries have a retention set of untagged manifests (preview). #558
- Check registries use image quarantine pattern (preview). #558
- Front Door:
- Check Front Door WAF policy name requirements. #552
- Bug fixes:
- Fixed HNS storage accounts so they are excluded from blob soft delete rule. #554
> Pre-release v0.18.0-B2010016

- CHANGELOG.md
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- Fixed ResourceGroupName property cannot be found on this object. #561
Fixes #561 
> Fixed ResourceGroupName property #561

- CHANGELOG.md
What's changed since pre-release v0.18.0-B2010016:
- Bug fixes:
- Fixed ResourceGroupName property cannot be found on this object. #561
> Pre-release v0.18.0-B2011005

- .azure-pipelines/azure-pipelines.yaml
- .github/dependabot.yml
- Updated CI pipeline for PowerShell 7.1 release.
> Update CI pipeline for PowerShell 7.1

- CHANGELOG.md
- src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
- tests/PSRule.Rules.Azure.Tests/Azure.Template.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
- tests/PSRule.Rules.Azure.Tests/PathBuilderTests.cs
- tests/PSRule.Rules.Azure.Tests/Resources.Template4.json
- tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- Fixed variable property not resolved with copy peer. #571
Fixes #571 
> Fixed variable property not resolved with copy peer #571

- CHANGELOG.md
- docs/rules/en/Azure.Storage.SoftDelete.md
- src/PSRule.Rules.Azure/rules/Azure.Storage.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Storage.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.Storage.json
- Fixed blob soft delete for FileStorage storage accounts. #573
Fixes #573 
> Fixed blob soft delete for FileStorage storage accounts #573

- CHANGELOG.md
- src/PSRule.Rules.Azure/rules/Azure.Template.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Template.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.Copy.Template.1.json
- tests/PSRule.Rules.Azure.Tests/Resources.Copy.Template.2.json
- Fixed top level variable copy detected as unused variable. #569
Fixes #569 
> Fixed variable copy as unused variable #569

- CHANGELOG.md
What's changed since pre-release v0.18.0-B2011005:
- Bug fixes:
- Fixed reason typo on template parameter metadata. #567
- Fixed `Get-AzRuleTemplateLink` reports incorrect parameter with file path. #568
- Fixed variable property not resolved with copy peer. #571
- Fixed blob soft delete for FileStorage storage accounts. #573
- Fixed top level variable copy detected as unused variable. #569
> Pre-release v0.18.0-B2011023

- .azure-pipelines/azure-pipelines.yaml
> Update pipeline version to v0.19.0

- CHANGELOG.md
- docs/baselines/en/Azure.All.md
- docs/baselines/en/Azure.Default.md
- docs/baselines/en/Azure.Preview.md
- docs/rules/en/Azure.MySQL.ServerName.md
- docs/rules/en/Azure.PostgreSQL.ServerName.md
- docs/rules/en/Azure.SQL.DBName.md
- docs/rules/en/Azure.SQL.FGName.md
- docs/rules/en/Azure.SQL.ServerName.md
- docs/rules/en/Azure.SQLMI.Name.md
- docs/rules/en/module.md
- docs/rules/en/resource.md
- src/PSRule.Rules.Azure/rules/Azure.MySQL.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.PostgreSQL.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.SQL.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.SQLMI.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.MySQL.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.PostgreSQL.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.SQL.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.SQLMI.Tests.ps1
- Database for MySQL:
- Check database servers meet name requirements.
- Database for PostgreSQL:
- Check database servers meet name requirements.
- Check SQL logical servers meet name requirements.
- Check SQL failover groups meet name requirements.
- Check SQL databases meet name requirements.
- SQL Managed Instance:
- Check SQL Managed Instances meet name requirements.
Fixes #583 
> Add database name rules #583

- CHANGELOG.md
What's changed since v0.18.0:
- New rules:
- Database for MySQL:
- Check database servers meet name requirements. #583
- Database for PostgreSQL:
- Check database servers meet name requirements. #583 
- Check SQL logical servers meet name requirements. #583
- Check SQL failover groups meet name requirements. #583
- Check SQL databases meet name requirements. #583
- SQL Managed Instance:
- Check SQL Managed Instances meet name requirements. #583
- Added support for `true`, `false`, and `null` template functions. #579
- Added support for `createObject` template function. #580
> Pre-release v0.19.0-B2011008

- .azure-pipelines/azure-pipelines.yaml
- CHANGELOG.md
- pipeline.build.ps1
- ps-project.yaml
- Engineering:
- Bump PSRule dependency to v1.0.0. #588
> Bump PSRule dependency to v1.0.0 #588

- CHANGELOG.md
- src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json
- tests/PSRule.Rules.Azure.Tests/Resources.AKS.json
- Updated `Azure.AKS.Version` to 1.19.3. #590
Fixes #590 
> Updated Azure.AKS.Version to 1.19.3 #590

- .github/ISSUE_TEMPLATE/question.md
- README.md
- SUPPORT.md
- Updates to improve getting started examples.
- Updated support information.
> Improved getting started examples and support doco

- README.md
- Update to readme to add project objectives.
> Add project objectives

- CHANGELOG.md
- src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json
- tests/PSRule.Rules.Azure.Tests/Resources.AKS.json
- Updated `Azure.AKS.Version` to 1.19.6. #603
Fixes #603 
> Updated Azure.AKS.Version to 1.19.6 #603

- CHANGELOG.md
- docs/commands/PSRule.Rules.Azure/en-US/Export-AzTemplateRuleData.md
- src/PSRule.Rules.Azure/Data/Template/Functions.cs
- src/PSRule.Rules.Azure/Data/Template/Models.cs
- src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
- tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
- tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
- tests/PSRule.Rules.Azure.Tests/Resources.FrontDoor.Template.json
- tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- tests/PSRule.Rules.Azure.Tests/environments.json
- Added support for `environment` template function. #517
Fixes #517 
> Added environment template function #517

- CHANGELOG.md
- docs/rules/en/Azure.Template.LocationDefault.md
- src/PSRule.Rules.Azure/rules/Azure.Template.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Template.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.Empty.Template.json
- Check location parameter defaults to resource group. #361
Fixes #361 
> Check location parameter defaults to resource group #361

- docs/baselines/en/Azure.All.md
- docs/baselines/en/Azure.Default.md
- docs/baselines/en/Azure.GA_2020_06.md
- docs/baselines/en/Azure.GA_2020_09.md
- docs/baselines/en/Azure.GA_2020_12.md
- docs/baselines/en/Azure.Preview.md
- docs/rules/en/Azure.Storage.UseEncryption.md
- docs/rules/en/Azure.Template.LocationDefault.md
- docs/rules/en/Azure.Template.ParameterFile.md
- docs/rules/en/Azure.Template.ParameterMetadata.md
- docs/rules/en/Azure.Template.Resources.md
- docs/rules/en/Azure.Template.TemplateFile.md
- docs/rules/en/Azure.Template.UseParameters.md
- docs/rules/en/Azure.Template.UseVariables.md
- docs/rules/en/Azure.VM.ASAlignment.md
- docs/rules/en/Azure.VM.ASMinMembers.md
- docs/rules/en/module.md
- docs/rules/en/resource.md
- Improvements to rule documentation including expanded descriptions and links.
> Update rule documentation

- .azure-pipelines/azure-pipelines.yaml
- pipeline.build.ps1
- Updated CI version to v1.0.0
> Bump CI version to v1.0.0

- CHANGELOG.md
- pipeline.build.ps1
- ps-project.yaml
- Updated PSRule dependency to v1.0.1.
Fixes #611
> Bump PSRule dependency to v1.0.1 #611

- CHANGELOG.md
What's changed since v0.19.0:
- New rules:
- Check location parameter defaults to resource group. #361
- Front Door:
- Check Front Door uses a health probe for each backend pool. #546
- Check Front Door uses a dedicated health probe path backend pools. #547
- Check Front Door uses HEAD requests for backend health probes. #613
- Updated `Azure.AKS.Version` to 1.19.6. #603
- Added support for `environment` template function. #517
- Engineering:
- Bump PSRule dependency to v1.0.1. #611
> Pre-release v1.0.0-B2101006

- CHANGELOG.md
- docs/baselines/en/Azure.All.md
- docs/baselines/en/Azure.Default.md
- docs/baselines/en/Azure.Preview.md
- docs/rules/en/Azure.ServiceFabric.AAD.md
- docs/rules/en/module.md
- docs/rules/en/resource.md
- src/PSRule.Rules.Azure/rules/Azure.ServiceFabric.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.ServiceFabric.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.ServiceFabric.Parameters.json
- tests/PSRule.Rules.Azure.Tests/Resources.ServiceFabric.Template.json
- tests/PSRule.Rules.Azure.Tests/Resources.ServiceFabric.json
- Check Service Fabric clusters use AAD client authentication.
Fixes #619
> Service Fabric clusters use AAD client authentication #619

- CHANGELOG.md
What's changed since pre-release v1.0.0-B2101006:
- New rules:
- Service Fabric:
- Check Service Fabric clusters use AAD client authentication. #619
- Bug fixes:
- Fixed reason `Azure.FrontDoor.ProbePath` so the probe name is included. #617
> Pre-release v1.0.0-B2101016

- docs/rules/en/Azure.ACR.AdminUser.md
- docs/rules/en/Azure.ACR.ContainerScan.md
- Added examples for rule docs for ACR.
> Added rule examples

- .vscode/tasks.json
- CHANGELOG.md
- docs/baselines/en/Azure.All.md
- docs/baselines/en/Azure.Default.md
- docs/baselines/en/Azure.Preview.md
- docs/rules/en/Azure.Template.LocationDefault.md
- docs/rules/en/Azure.Template.ParameterDataTypes.md
- docs/rules/en/module.md
- docs/rules/en/resource.md
- pipeline.build.ps1
- src/PSRule.Rules.Azure/en/PSRule-rules.psd1
- src/PSRule.Rules.Azure/rules/Azure.Template.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Template.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.Empty.Template.json
- Check parameter default value type matches type. #311
Fixes #311
> Check parameter default value type matches type #311

- src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.APIM.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.Automation.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.KeyVault.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.PublicIP.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.Resource.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.SignalR.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.VirtualNetwork.Rule.ps1
- General improvements to rule quality. No functional changes.
> Rule code quality improvements

- docs/CHANGELOG-v1.md
- docs/baselines/en/Azure.All.md
- docs/baselines/en/Azure.Default.md
- docs/baselines/en/Azure.Preview.md
- docs/rules/en/Azure.Template.DebugDeployment.md
- docs/rules/en/Azure.Template.ParameterMinMaxValue.md
- docs/rules/en/module.md
- docs/rules/en/resource.md
- src/PSRule.Rules.Azure/en/PSRule-rules.psd1
- src/PSRule.Rules.Azure/rules/Azure.Template.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Template.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.TTK.Template.1.json
- tests/PSRule.Rules.Azure.Tests/Resources.TTK.Template.2.json
- tests/PSRule.Rules.Azure.Tests/Resources.TTK.Template.3.json
- Check template parameter `minValue` and `maxValue` constraints are valid. #637
- Check increased debug detail is disabled for nested deployments. #638
Fixes #637 
Fixes #638 
> Added template checks #637 #638

- docs/CHANGELOG-v1.md
What's changed since v1.0.0:
- New rules:
- Check template parameters are defined. #631
- Check location parameter is type string. #632
- Check template parameter `minValue` and `maxValue` constraints are valid. #637
- Check template resources do not use hard coded locations. #633
- Check resource group location not referenced instead of location parameter. #634
- Check increased debug detail is disabled for nested deployments. #638
- Engineering:
- Bump PSRule dependency to v1.0.2. #635
> Pre-release v1.0.0-B2102013

- .azure-pipelines/azure-pipelines.yaml
- docs/CHANGELOG-v1.md
- Correct pipeline version and version in change log.
> Fix change log and pipeline version

- docs/CHANGELOG-v1.md
- Update builder number for release.
> Update build number

- docs/CHANGELOG-v1.md
- pipeline.build.ps1
- Bump PSRule dependency to v1.0.3.
Fixed #648
> Bump PSRule dependency to v1.0.3 #648

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.1.0-B2102001:
- Engineering:
- Bump PSRule dependency to v1.0.3. #648
- Bug fixes:
- Fixed `Azure.VM.ADE` to limit rule to exports only. #644
> Pre-release v1.1.0-B2102010

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.1.0-B2102010:
- Bug fixes:
- Fixed `if` condition values evaluation order. #652
- Fixed handling of `int` parameters with large values. #653
- Fixed handling of expressions split over multiple lines. #654
- Fixed handling of bool parameter values within logical expressions. #655
> Pre-release v1.1.0-B2102015

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.1.0-B2102015:
- Exporting template with `Export-AzRuleTemplateData` supports custom resource group and subscription. #651
- Subscription and resource group used for deployment can be specified instead of using defaults.
- `ResourceGroupName` parameter of `Export-AzRuleTemplateData` has been renamed to `ResourceGroup`.
- Added a parameter alias for `ResourceGroupName` on `Export-AzRuleTemplateData`.
> Pre-release v1.1.0-B2102023

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.1.0-B2102023:
- Added support for matching template by name. #661
- `Get-AzRuleTemplateLink` discovers `<templateName>.json` from `<templateName>.parameters.json`.
- Bug fixes:
- Fixed copy loop value does not fall within the expected range. #664
- Fixed template comparison functions handling of large integer values. #666
- Fixed handling of `createArray` function with no arguments. #667
> Pre-release v1.1.0-B2102034

- docs/CHANGELOG-v1.md
- src/PSRule.Rules.Azure/Pipeline/TemplateLinkPipeline.cs
- src/PSRule.Rules.Azure/rules/Azure.Template.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Cmdlet.Common.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.Subscription.Parameters.json
- tests/PSRule.Rules.Azure.Tests/Resources.Subscription.Template.json
- Fixes support for parameter file schemas. #674
Fixes #674 
> Fixes support for parameter file schemas #674

- docs/CHANGELOG-v1.md
What's changed since v1.1.0:
- Bug fixes:
- Fixes support for parameter file schemas. #674
> Release v1.1.1

- .gitignore
- docs/CHANGELOG-v1.md
- src/PSRule.Rules.Azure/Configuration/OutputOption.cs
- src/PSRule.Rules.Azure/Configuration/ResourceGroupOption.cs
- src/PSRule.Rules.Azure/Configuration/SubscriptionOption.cs
- src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
- src/PSRule.Rules.Azure/Pipeline/TemplatePipeline.cs
- tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
- tests/PSRule.Rules.Azure.Tests/Template.Parsing.2.json
- tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- Fixed copy peer property resolve. #677
- Fixed partial resource group or subscription object not populating. #678
- Fixed lazy loading of environment and resource providers. #679
Fixes #677 
Fixes #678 
Fixes #679 
> Fixed copy peer property #677

- docs/CHANGELOG-v1.md
What's changed since v1.1.1:
- Bug fixes:
- Fixed copy peer property resolve. #677
- Fixed partial resource group or subscription object not populating. #678
- Fixed lazy loading of environment and resource providers. #679
> Release v1.1.2

- docs/CHANGELOG-v1.md
What's changed since v1.1.2:
- Bug fixes:
- Fixed parsing of property names for functions across multiple lines. #683
> Release v1.1.3

- docs/CHANGELOG-v1.md
- src/PSRule.Rules.Azure/Configuration/ResourceGroupOption.cs
- src/PSRule.Rules.Azure/Configuration/SubscriptionOption.cs
- src/PSRule.Rules.Azure/Data/Template/ExpressionBuilder.cs
- src/PSRule.Rules.Azure/Data/Template/Functions.cs
- src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
- src/PSRule.Rules.Azure/Data/Template/TokenStream.cs
- src/PSRule.Rules.Azure/Pipeline/TemplatePipeline.cs
- tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
- tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
- tests/PSRule.Rules.Azure.Tests/Template.Parsing.1.json
- tests/PSRule.Rules.Azure.Tests/Template.Parsing.3.json
- tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- Fixed handling of literal index with copyIndex function. #686
- Fixed handling of inner scoped nested deployments. #687
Fixes #686 
Fixes #687 
> Template expansion fixes #686 #687

- docs/CHANGELOG-v1.md
What's changed since v1.1.3:
- Bug fixes:
- Fixed handling of literal index with copyIndex function. #686
- Fixed handling of inner scoped nested deployments. #687
> Release v1.1.4

- .gitignore
- .vscode/tasks.json
- PSRule.Rules.Azure.sln
- docs/CHANGELOG-v1.md
- docs/benchmark/results-pre-1.2.0.md
- docs/commands/PSRule.Rules.Azure/en-US/Export-AzRuleTemplateData.md
- pipeline.build.ps1
- src/PSRule.Rules.Azure.Benchmark/PSRule.Rules.Azure.Benchmark.csproj
- src/PSRule.Rules.Azure.Benchmark/PSRule.cs
- src/PSRule.Rules.Azure.Benchmark/Program.cs
- src/PSRule.Rules.Azure.Benchmark/Template.1.json
- src/PSRule.Rules.Azure.Benchmark/Template.PropertyCopyLoop.json
- src/PSRule.Rules.Azure.Benchmark/Template.UserDefinedFunctions.json
- src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
- tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
- tests/PSRule.Rules.Azure.Tests/Template.Parsing.4.json
- tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- Added support for user defined functions in templates. #682
Fixes #682 
> Added user defined functions in templates #682

- docs/CHANGELOG-v1.md
What's changed since v1.1.4:
- Added support for user defined functions in templates. #682
> Pre-release v1.2.0-B2103024

- docs/CHANGELOG-v1.md
- pipeline.build.ps1
- ps-project.yaml
- Bump PSRule dependency to v1.1.0. #692
Fixes #692 
> Bump PSRule dependency to v1.1.0 #692

- docs/CHANGELOG-v1.md
- docs/baselines/en/Azure.All.md
- docs/baselines/en/Azure.Default.md
- docs/baselines/en/Azure.Preview.md
- docs/rules/en/Azure.KeyVault.KeyName.md
- docs/rules/en/Azure.KeyVault.Name.md
- docs/rules/en/Azure.KeyVault.SecretName.md
- docs/rules/en/module.md
- docs/rules/en/resource.md
- src/PSRule.Rules.Azure/rules/Azure.KeyVault.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.KeyVault.Tests.ps1
- Check vaults, keys, and secrets meet name requirements. #646
Fixes #646 
> Added rule for Key Vault naming #646

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.2.0-B2103024:
- New rules:
- Key Vault:
- Check vaults, keys, and secrets meet name requirements. #646
- Engineering:
- Bump PSRule dependency to v1.1.0. #692
> Pre-release v1.2.0-B2103032

- docs/CHANGELOG-v1.md
- src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json
- tests/PSRule.Rules.Azure.Tests/Resources.AKS.json
- Updated `Azure.AKS.Version` to 1.19.7. #696
Fixes #696 
> Updated Azure.AKS.Version to 1.19.7 #696

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.2.0-B2103032:
- Added `Azure.GA_2021_03` baseline. #673
- Includes rules released before or during March 2021 for Azure GA features.
- Marked baseline `Azure.GA_2020_12` as obsolete.
- Updated `Azure.AKS.Version` to 1.19.7. #696
> Pre-release v1.2.0-B2103044

- .azure-pipelines/azure-pipelines.yaml
- Updated CI pipeline version and docker images to latest versions.
> Bump CI pipeline to v1.3.0

- docs/CHANGELOG-v1.md
- pipeline.build.ps1
- ps-project.yaml
- Bump PSRule dependency to v1.2.0. #713
> Bump PSRule dependency to v1.2.0 #713

- docs/CHANGELOG-v1.md
- src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
- tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
- tests/PSRule.Rules.Azure.Tests/Template.Parsing.5.json
- tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- Fixed export not expanding nested deployments.
Fixes #715
> Fixed export not expanding nested deployments #715

- .azure-pipelines/azure-pipelines.yaml
- docs/CHANGELOG-v1.md
- src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
- tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
- tests/PSRule.Rules.Azure.Tests/Template.Parsing.5.json
- tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
Fix for release v1.2.x
- Fixed export not expanding nested deployments. #715
Fixes #715
> Fixed export not expanding nested deployments #715 (#717)

- docs/CHANGELOG-v1.md
What's changed since v1.2.0:
- Bug fixes:
- Fixed export not expanding nested deployments. #715
> Release v1.2.1

- .azure-pipelines/azure-pipelines.yaml
- docs/CHANGELOG-v1.md
- Merged change log from v1.2.1 release.
> Merge changelog from v1.2.1

- pipeline.build.ps1
- Add force publish option for PowerShell Gallery to CI.
> Add force publish for PowerShell Gallery

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.3.0-B2103007:
- Engineering:
- Bump PSRule dependency to v1.2.0. #713
- Bug fixes:
- Fixed export not expanding nested deployments. #715
> Pre-release v1.3.0-B2104013

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.3.0-B2104013:
- Improved binding support for File inputs. #480
- Template and parameter file names now return a relative path instead of full path.
- Added API version for each module resource. #729
> Pre-release v1.3.0-B2104023

- README.md
- docs/CHANGELOG-v1.md
- docs/baselines/en/Azure.All.md
- docs/baselines/en/Azure.Default.md
- docs/baselines/en/Azure.GA_2020_06.md
- docs/baselines/en/Azure.GA_2020_09.md
- docs/baselines/en/Azure.GA_2020_12.md
- docs/baselines/en/Azure.GA_2021_03.md
- docs/baselines/en/Azure.Preview.md
- docs/concepts/PSRule.Rules.Azure/en-US/about_PSRule_Azure_Configuration.md
- docs/rules/en/Azure.Policy.AssignmentAssignedBy.md
- docs/rules/en/Azure.Policy.AssignmentDescriptors.md
- docs/rules/en/Azure.Policy.Descriptors.md
- docs/rules/en/Azure.Policy.ExemptionDescriptors.md
- docs/rules/en/Azure.Policy.WaiverExpiry.md
- docs/rules/en/module.md
- docs/rules/en/resource.md
- src/PSRule.Rules.Azure/rules/Azure.Policy.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.Policy.Rule.yaml
- src/PSRule.Rules.Azure/rules/Baseline.Rule.yaml
- src/PSRule.Rules.Azure/rules/Config.Rule.yaml
- tests/PSRule.Rules.Azure.Tests/Azure.Policy.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.Policy.Parameters.json
- tests/PSRule.Rules.Azure.Tests/Resources.Policy.Template.json
- tests/PSRule.Rules.Azure.Tests/Resources.Policy.json
- Check policy assignment display name and description are set. #725
- Check policy assignment assigned by metadata is set. #726
- Check policy exemption display name and description are set. #723
- Check policy waiver exemptions have an expiry date set. #724
Fixes #723 
Fixes #724 
Fixes #725 
Fixes #726
> Added policy rules #723 #724 #725 #726

- docs/rules/en/Azure.KeyVault.AccessPolicy.md
- docs/rules/en/Azure.KeyVault.Logs.md
- docs/rules/en/Azure.KeyVault.PurgeProtect.md
- docs/rules/en/Azure.KeyVault.SoftDelete.md
- docs/rules/en/Azure.Storage.BlobAccessType.md
- docs/rules/en/Azure.Storage.BlobPublicAccess.md
- docs/rules/en/Azure.Storage.MinTLS.md
- docs/rules/en/Azure.Storage.Name.md
- docs/rules/en/Azure.Storage.SecureTransfer.md
- Updated rule documentation for storage account and key vault rules.
> Improve rule docs

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.3.0-B2104023:
- New rules:
- Policy:
- Check policy assignment display name and description are set. #725
- Check policy assignment assigned by metadata is set. #726
- Check policy exemption display name and description are set. #723
- Check policy waiver exemptions have an expiry date set. #724
- Engineering:
- Clean up depreciated warning message for configuration option `azureAllowedRegions`. #737
- Clean up depreciated warning message for configuration option `minAKSVersion`. #738
> Pre-release v1.3.0-B2104034

- README.md
- SUPPORT.md
- docs/CHANGELOG-v1.md
- docs/troubleshooting.md
- pipeline.build.ps1
- Fixed could not load file or assembly YamlDotNet. #741
Fixes #741 
> Fixed could not load file or assembly YamlDotNet #741

- .azure-pipelines/azure-pipelines.yaml
- Fix CI release version dependency on PSRule v1.2.0.
> Fix CI pipeline for release

- .azure-pipelines/azure-pipelines.yaml
- pipeline.build.ps1
> Bump CI pipeline to v1.4.0

- docs/CHANGELOG-v1.md
What's changed since v1.3.0:
- Engineering:
- Bump PSRule dependency to v1.3.0. #749
- Bump YamlDotNet dependency to v11.1.1. #742
> Release v1.3.1

- README.md
- Updated versioning info in readme.
> Update readme versioning info

- .vscode/tasks.json
- docs/CHANGELOG-v1.md
- docs/rules/en/Azure.KeyVault.Logs.md
- docs/rules/en/Azure.SQL.AAD.md
- docs/rules/en/Azure.SQL.Auditing.md
- docs/rules/en/Azure.SQL.TDE.md
- docs/rules/en/Azure.SQL.ThreatDetection.md
- docs/rules/en/Azure.Storage.SoftDelete.md
- pipeline.build.ps1
- src/PSRule.Rules.Azure/en/PSRule-rules.psd1
- src/PSRule.Rules.Azure/rules/Azure.SQL.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.Storage.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.SQL.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Storage.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.VM.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.VMSS.Tests.ps1
- Fixed rule reason reported the parameter inputObject is null. #753
Fixes #753 
> Fixed reason inputObject is null #753

- docs/CHANGELOG-v1.md
What's changed since v1.3.1:
- Bug fixes:
- Fixed rule reason reported the parameter inputObject is null. #753
> Release v1.3.2

- docs/CHANGELOG-v1.md
What's changed since v1.3.2:
- Automatically nest template sub-resources for analysis. #746
- Sub-resources such as diagnostic logs or configurations are automatically nested.
- Automatic nesting a resource requires:
- The parent resource is defined in the same template.
- The sub-resource depends on the parent resource.
> Pre-release v1.4.0-B2105020

- .vscode/markdown.code-snippets
- docs/rules/en/Azure.AKS.ManagedIdentity.md
- docs/rules/en/Azure.APIM.ManagedIdentity.md
- docs/rules/en/Azure.AppService.ManagedIdentity.md
- pipeline.build.ps1
- ps-rule.yaml
- Added additional links for rule docs.
- Improved snippets for editing rule docs.
- Adding QA rule file path exclusions.
> Updated rule doc links

- README.md
- docs/CHANGELOG-v1.md
- docs/baselines/en/Azure.All.md
- docs/baselines/en/Azure.Default.md
- docs/baselines/en/Azure.Preview.md
- docs/features.md
- docs/rules/en/Azure.Search.IndexSLA.md
- docs/rules/en/Azure.Search.ManagedIdentity.md
- docs/rules/en/Azure.Search.Name.md
- docs/rules/en/Azure.Search.QuerySLA.md
- docs/rules/en/Azure.Search.SKU.md
- docs/rules/en/module.md
- docs/rules/en/resource.md
- src/PSRule.Rules.Azure/rules/Azure.Search.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.KeyVault.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Search.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.Search.Template.json
- tests/PSRule.Rules.Azure.Tests/Resources.Search.json
- Check search services meet index SLA replica requirement. #761
- Check search services meet query SLA replica requirement. #762
- Check search services meet naming requirements. #763
- Check search services use a minimum SKU. #764
- Check search services use managed identities. #765
Fixes #761 
Fixes #762 
Fixes #763 
Fixes #764 
Fixes #765
> Cognitive Search rules #761 #762 #763 #764 #765

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.4.0-B2105020:
- New rules:
- Cognitive Search:
- Check search services meet index SLA replica requirement. #761
- Check search services meet query SLA replica requirement. #762
- Check search services meet naming requirements. #763
- Check search services use a minimum SKU. #764
- Check search services use managed identities. #765
> Pre-release v1.4.0-B2105027

- docs/troubleshooting.md
- Updated YamlDotNet guidance.
> Update YamlDotNet guidance

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.4.0-B2105027:
- Automatically expand template from parameter files for analysis. #772
- Previously templates needed to be exported with `Export-AzRuleTemplateData`.
- To export template data automatically use PSRule cmdlets with `-Format File`.
- Bug fixes:
- Fixed string index parsing in expressions with whitespace. #775
- Fixed base for DateTimeAdd is not a valid string. #777
> Pre-release v1.4.0-B2105044

- docs/CHANGELOG-v1.md
- src/PSRule.Rules.Azure/Common/JsonExtensions.cs
- src/PSRule.Rules.Azure/Data/Template/TemplateHelper.cs
- src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
- src/PSRule.Rules.Azure/Pipeline/TemplatePipeline.cs
- src/PSRule.Rules.Azure/Runtime/Helper.cs
- tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- Added support for source location references to template files. #781
- Output includes source location to resources exported from a templates.
Fixes #781 
> Added source locations to template files #781

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.4.0-B2105044:
- Added support for source location references to template files. #781
- Output includes source location to resources exported from a templates.
> Pre-release v1.4.0-B2105050

- docs/CHANGELOG-v1.md
- docs/benchmark/results-pre-1.4.0.md
- src/PSRule.Rules.Azure/Common/JsonExtensions.cs
- src/PSRule.Rules.Azure/Configuration/ConfigurationOption.cs
- src/PSRule.Rules.Azure/Configuration/PSRuleOption.cs
- src/PSRule.Rules.Azure/Configuration/ResourceGroupOption.cs
- src/PSRule.Rules.Azure/Configuration/SubscriptionOption.cs
- src/PSRule.Rules.Azure/Data/Template/ExpressionBuilder.cs
- src/PSRule.Rules.Azure/Data/Template/ExpressionParser.cs
- src/PSRule.Rules.Azure/Data/Template/ExpressionStream.cs
- src/PSRule.Rules.Azure/Data/Template/Functions.cs
- src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
- src/PSRule.Rules.Azure/Data/Template/TokenStream.cs
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.csproj
- src/PSRule.Rules.Azure/Pipeline/Output/PSPipelineWriter.cs
- src/PSRule.Rules.Azure/Pipeline/PipelineBuilder.cs
- src/PSRule.Rules.Azure/Pipeline/PipelineWriter.cs
- tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
- tests/PSRule.Rules.Azure.Tests/OptionsTests.cs
- tests/PSRule.Rules.Azure.Tests/PathBuilderTests.cs
- Added source link to project. #783
- Additional refactoring and code clean up. No functional changes.
Fixes #783 
> Add source link to project #783

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.4.0-B2105050:
- New rules:
- Check clusters use AKS-managed Azure AD integration. #436
- Check clusters have local account disabled (preview). #786
- Check clusters have an auto-upgrade channel set (preview). #787
- Check clusters limit access network access to the API server. #788
- Check clusters used Azure RBAC for Kubernetes authorization. #789
- Updated rules
- Updated `Azure.AKS.Version` to 1.20.5. #767
- Engineering:
- Added source link to project. #783
> Pre-release v1.4.0-B2105057

- docs/CHANGELOG-v1.md
What's changed since v1.4.0:
- Bug fixes:
- Fixed boolean string conversion case. #793
- Fixed case sensitive property matching. #794
- Fixed automatic expansion of template parameter files. #796
- Template parameter files are not automatically expanded by default.
- To enable this, set the `AZURE_PARAMETER_FILE_EXPANSION` configuration option.
> Release v1.4.1

- .azure-pipelines/azure-pipelines.yaml
- .github/workflows/docs.yaml
- requirements-docs.txt
- Bump versions for building docs site.
> Bump Python and CI mkdocs versions

- requirements-docs.txt
- Added mdx-truly-sane-lists to requirements.
> Add mdx-truly-sane-lists to requirements

- README.md
- docs/creating-your-pipeline.md
- Updated readme links to doco site.
> Updated readme links

- docs/CHANGELOG-v1.md
- src/PSRule.Rules.Azure/rules/Azure.Template.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.Copy.Template.1.json
- tests/PSRule.Rules.Azure.Tests/Resources.Template.json
- tests/PSRule.Rules.Azure.Tests/Resources.Template3.json
- Fixed detection of parameters and variables with line breaks. #811
Fixes #811 
> Fixes UseParameters and UseVariables #811

- docs/CHANGELOG-v1.md
- docs/en/rules/Azure.Template.DefineParameters.md
- docs/en/rules/Azure.Template.UseLocationParameter.md
- src/PSRule.Rules.Azure/rules/Azure.Template.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Template.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Template.Bicep.1.json
- Exclude not applicable rules for templates generated with Bicep and PSArm. #815
Fixes #815 
> Exclude rules for Bicep and PSArm #815

- docs/CHANGELOG-v1.md
What's changed since v1.4.1:
- New rules:
- Application Insights:
- Check App Insights resources use workspace-based configuration. #813
- Check App Insights resources meet naming requirements. #814
- Exclude not applicable rules for templates generated with Bicep and PSArm. #815
- Engineering:
- Bump YamlDotNet dependency to v11.2.0. #801
- Migrate project to Azure GitHub organization and updated links. #800
- Bug fixes:
- Fixed detection of parameters and variables with line breaks. #811
> Pre-release v1.5.0-B2106018

- mkdocs.yml
- overrides/home.html
- overrides/main.html
- Add social preview image and metadata for docs site.
> Added social preview for docs site

- .azure-pipelines/azure-pipelines.yaml
- .github/ISSUE_TEMPLATE/bug-report.md
- ps-docs.yaml
- ps-rule.yaml
- Updated CI pipeline and repository files.
> Bump CI pipeline

- README.md
> Update README.md and add 's' to Resource

- docs/CHANGELOG-v1.md
- docs/en/rules/Azure.NSG.LateralTraversal.md
- docs/examples.bicep
- src/PSRule.Rules.Azure/Common/PSObjectExtensions.cs
- src/PSRule.Rules.Azure/Data/Network/NetworkSecurityGroupEvaluator.cs
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.csproj
- src/PSRule.Rules.Azure/Runtime/Helper.cs
- src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.VirtualNetwork.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.VirtualNetwork.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.VirtualNetwork.json
- tests/PSRule.Rules.Azure.Tests/RuntimeHelperTests.cs
- Fixes rule does not detect more restrictive NSG rules.
Fixes #831
> Fixes detection of more restrictive NSG rules #831

- docs/CHANGELOG-v1.md
What's changed since v1.5.0:
- Bug fixes:
- Fixes rule does not detect more restrictive NSG rules. #831
> Release v1.5.1

- docs/CHANGELOG-v1.md
- pipeline.build.ps1
- ps-project.yaml
- Bump PSRule dependency to v1.5.0.
Fixes #832
> Bump PSRule dependency to v1.5.0 #832

- docs/CHANGELOG-v1.md
What's changed since v1.5.1:
- New rules:
- Application Gateways:
- Check Application Gateways publish endpoints by HTTPS. #841
- Engineering:
- Bump PSRule dependency to v1.5.0. #832
> Pre-release v1.6.0-B2107028

- docs/en/rules/Azure.Template.LocationDefault.md
- docs/en/rules/Azure.Template.LocationType.md
- Minor updates to rule docs to add examples and notes.
> Minor update to template rule docs

- docs/setup/setup-bicep.md
> Fix Bicep doco link

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.6.0-B2107028:
- **Experimental**: Added support for expansion from Bicep source files. #848 #670
- Bicep support is currently experimental.
- To opt-in set the `AZURE_BICEP_FILE_EXPANSION` configuration to `true`.
- For more information see [Using Bicep](https://azure.github.io/PSRule.Rules.Azure/using-bicep/).
> Pre-release v1.6.0-B2108023

- docs/install-instructions.md
- Updated example code to using pre-releases within CI pipeline.
> Updated CI install docs

- docs/setup/configuring-expansion.md
- docs/using-bicep.md
- Additional detail on bicep support.
- Added doc for excluding files from expansion.
> Minor updates to bicep docs

- .vscode/extensions.json
- README.md
- pipeline.build.ps1
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psd1
- Minor change to links and CI.
> Updated links and CI

- docs/CHANGELOG-v1.md
- docs/using-bicep.md
- src/PSRule.Rules.Azure/Data/Bicep/BicepHelper.cs
- src/PSRule.Rules.Azure/Resources/PSRuleResources.Designer.cs
- src/PSRule.Rules.Azure/Resources/PSRuleResources.resx
- Fixed Bicep expand hangs analysis. #858
Fixes #858 
> Fixed Bicep expand hangs analysis #858

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.6.0-B2108023:
- Bug fixes:
- Fixed Bicep expand hangs analysis. #858
> Pre-release v1.6.0-B2108038

- docs/CHANGELOG-v1.md
- docs/using-bicep.md
- src/PSRule.Rules.Azure/Data/Bicep/BicepHelper.cs
- tests/Bicep/Bicep.Tests.ps1
- tests/Bicep/template.bicep
- Fixed Bicep expand creates deadlock and times out.
Fixes #863
> Fix Bicep deadlock condition #863

- docs/CHANGELOG-v1.md
- pipeline.build.ps1
- ps-project.yaml
- Bump PSRule dependency to v1.6.0.
Fixes #871
> Bump PSRule v1.6.0 #871

- .vscode/settings.json
- CONTRIBUTING.md
- docs/en/rules/Azure.AKS.AutoScaling.md
- Added additionally WAF links for AKS rule.
- Updated contributing guide with additional detail.
> Added AKS WAF references and improved contributing

- docs/CHANGELOG-v1.md
- docs/en/baselines/Azure.All.md
- docs/en/baselines/Azure.Default.md
- docs/en/baselines/Azure.Preview.md
- docs/en/rules/Azure.Storage.BlobPublicAccess.md
- docs/en/rules/Azure.Storage.Firewall.md
- docs/en/rules/Azure.Storage.MinTLS.md
- docs/en/rules/Azure.Storage.SecureTransfer.md
- docs/en/rules/Azure.Storage.SoftDelete.md
- docs/en/rules/module.md
- docs/en/rules/resource.md
- docs/examples.bicep
- docs/examples.json
- src/PSRule.Rules.Azure/rules/Azure.Selector.Rule.yaml
- src/PSRule.Rules.Azure/rules/Azure.Storage.Rule.yaml
- tests/PSRule.Rules.Azure.Tests/Azure.Storage.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.Storage.Template.json
- Check Storage Accounts only accept explicitly allowed network traffic. #884
- Additional improvements to rule documentation for Storage Accounts.
Fixes #884 
> Configure Azure Storage firewall #884

- .ps-rule/Rule.Rule.ps1
- docs/en/rules/Azure.AKS.Name.md
- docs/en/rules/Azure.AKS.NetworkPolicy.md
- docs/en/rules/Azure.AKS.PoolVersion.md
- docs/en/rules/Azure.LogicApp.LimitHTTPTrigger.md
- Improved validation for rules included within PSRule for Azure.
- Fixed existing rule documentation issues.
> Added additional validation for rules

- CONTRIBUTING.md
- Added updates to contributing guide to make authoring clearer.
> Added update to contributing guide

- docs/CHANGELOG-v1.md
- docs/en/baselines/Azure.All.md
- docs/en/baselines/Azure.Default.md
- docs/en/baselines/Azure.Preview.md
- docs/en/rules/Azure.Template.ParameterValue.md
- docs/en/rules/Azure.Template.ValidSecretRef.md
- docs/en/rules/module.md
- docs/en/rules/resource.md
- src/PSRule.Rules.Azure/rules/Azure.Template.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Convention.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Template.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.ParameterFile.Fail5.json
- tests/PSRule.Rules.Azure.Tests/Resources.VPN.Parameters2.json
- tests/PSRule.Rules.Azure.Tests/Resources.VPN.Parameters3.json
- Check template parameters set a value. #896
- Check template parameters use a valid secret reference. #897
Fixes #896 
Fixes #897 
> Added parameter file checks #896 #897

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.7.0-B2108040:
- New rules:
- Check template files use a recent schema. #845
- Check template files use a https schema scheme. #894
- Check template parameter files use a https schema scheme. #894
- Check template parameters set a value. #896
- Check template parameters use a valid secret reference. #897
- Bug fixes:
- Fixed DateTimeAdd function and tests within time zones with DST. #891
> Pre-release v1.7.0-B2108049

- docs/en/rules/Azure.AKS.CNISubnetSize.md
- docs/en/rules/module.md
- docs/setup/configuring-rules.md
Fixed some small typos in my last PR. Must have not paid attention to spell checker 😄 
> Fixed some typos from CNISubnetSize rule

- docs/CHANGELOG-v1.md
- src/PSRule.Rules.Azure/Data/Bicep/BicepHelper.cs
- src/PSRule.Rules.Azure/Pipeline/Exceptions.cs
- src/PSRule.Rules.Azure/Resources/PSRuleResources.Designer.cs
- src/PSRule.Rules.Azure/Resources/PSRuleResources.resx
- src/PSRule.Rules.Azure/rules/Conventions.Rule.ps1
- Added version information to bicep compilation exceptions.
Fixes #903
> Show bicep cli version info #903

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.7.0-B2108049:
- Added version information to bicep compilation exceptions. #903
- Bug fixes:
- Fixed `Azure.Template.ParameterValue` failing on empty value. #901
> Pre-release v1.7.0-B2108059

- README.md
- Minor updates to getting started info examples.
> Updates to readme getting started

- docs/en/baselines/Azure.All.md
- docs/en/baselines/Azure.Default.md
- docs/en/baselines/Azure.Preview.md
- docs/en/rules/Azure.AKS.ContainerInsights.md
- docs/en/rules/module.md
- docs/en/rules/resource.md
- src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json
- tests/PSRule.Rules.Azure.Tests/Resources.AKS.json
Fix #881
Added `Azure.AKS.ContainerInsights` rule for the following types:
- Microsoft.ContainerService/managedClusters
> AKS Container insights rule

- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- tests/PSRule.Rules.Azure.Tests/Cmdlet.Common.Tests.ps1
Fix #920
Added a check to make sure `VisitAKSCluster` function is only using the `vnetSubnetId` property when AzureCNI network plugin is being used. 
Also added some tests for `VisitAKSCluster`, which have been added to a `InModuleScope` for `PSRule.Rules.Azure.psm1` for non-exported private functions. I might create another issue sometime later to add more tests here to cover those functions if thats ok 🙂 . 
> Fixed VisitAKSCluster function so that it checks networkPlugin before using vnetSubnetId property

- .vscode/settings.json
- docs/CHANGELOG-v1.md
- Updated change log with details for #881 and #920.
> Updated change log with #881 #920

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.8.0-B2108013:
- New rules:
- AKS Container insights rule. Thanks [@ArmaanMcleod](https://github.com/ArmaanMcleod). #881
- Bug fixes:
- Fixed export of in-flight AKS related subnets for kubenet clusters. Thanks [@ArmaanMcleod](https://github.com/ArmaanMcleod). #920
> Pre-release v1.8.0-B2108026

- .vscode/settings.json
- README.md
- docs/customization/enforce-codeowners/index.md
- docs/setup/setup-azure-monitor-logs.md
- docs/using-templates.md
- mkdocs.yml
- Added documentation for using PSRule for Azure Monitor.
Fixes #915
> Added docs for Azure Monitor integration #915

- .vscode/settings.json
- docs/en/baselines/Azure.All.md
- docs/en/baselines/Azure.Default.md
- docs/en/baselines/Azure.Preview.md
- docs/en/rules/Azure.AKS.PlatformLogs.md
- docs/en/rules/module.md
- docs/en/rules/resource.md
- docs/setup/configuring-rules.md
- src/PSRule.Rules.Azure/en/PSRule-rules.psd1
- src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json
- tests/PSRule.Rules.Azure.Tests/Resources.AKS.json
- tests/PSRule.Rules.Azure.Tests/ps-rule-options.yaml
Fix #922
Added `Azure.AKS.PlatformLogs` rule for the following types:
- Microsoft.ContainerService/managedClusters
> Added AKS Platform Logs Rule

- .ps-rule/Rule.Rule.ps1
- docs/CHANGELOG-v1.md
- pipeline.build.ps1
- ps-project.yaml
- Bump PSRule dependency to v1.7.0.
- Additional updates to change log.
Fixes #938
> Bump PSRule dependency to v1.7.0 #938

- BaselineToc.Doc.ps1
- pipeline.build.ps1
- Refactor to improve code and add verbose information for generating baseline documentation.
> Refactor baseline doc generate task

- docs/CHANGELOG-v1.md
- docs/en/baselines/Azure.All.md
- docs/en/baselines/Azure.Default.md
- docs/en/baselines/Azure.GA_2020_06.md
- docs/en/baselines/Azure.GA_2020_09.md
- docs/en/baselines/Azure.GA_2020_12.md
- docs/en/baselines/Azure.GA_2021_03.md
- docs/en/baselines/Azure.GA_2021_06.md
- docs/en/baselines/Azure.Preview.md
- pipeline.build.ps1
- ps-project.yaml
- Bump PSRule dependency to v1.7.2.
- Fixed up baseline docs that required regeneration.
Fixes #951
> Bump PSRule dependency to v1.7.2 #951

- docs/CHANGELOG-v1.md
- docs/en/baselines/Azure.All.md
- docs/en/baselines/Azure.Default.md
- docs/en/baselines/Azure.Preview.md
- docs/en/rules/Azure.Cosmos.AccountName.md
- docs/en/rules/Azure.Cosmos.DisableMetadataWrite.md
- docs/en/rules/module.md
- docs/en/rules/resource.md
- docs/examples-cosmos.bicep
- docs/examples-cosmos.json
- src/PSRule.Rules.Azure/rules/Azure.Cosmos.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.Cosmos.Rule.yaml
- tests/PSRule.Rules.Azure.Tests/Azure.Cosmos.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.Cosmos.Parameters.1.json
- tests/PSRule.Rules.Azure.Tests/Resources.Cosmos.Parameters.2.json
- tests/PSRule.Rules.Azure.Tests/Resources.Cosmos.Template.json
- tests/PSRule.Rules.Azure.Tests/Resources.Cosmos.json
- tests/PSRule.Rules.Azure.Tests/test-template-options.yaml
- Check DB account names meet naming requirements. #954
- Check DB accounts use Azure AD identities for resource management operations. #953
Fixes #954 
Fixes #953 
> Added Cosmos DB account rules #954 #953

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.8.0-B2109020:
- New rules:
- Application Gateways:
- Check App Gateways should use availability zones when available. Thanks [@ArmaanMcleod](https://github.com/ArmaanMcleod). #928
- Cosmos DB:
- Check DB account names meet naming requirements. #954
- Check DB accounts use Azure AD identities for resource management operations. #953
- Bug fixes:
- Fixed plan instance count is not applicable to Elastic Premium plans. #946
- Fixed minimum App Service Plan fails Elastic Premium plans. #945
- Fixed App Service Plan should include PremiumV3 plan. #944
- Fixed Azure.VM.NICAttached with private endpoints. #932
- Engineering:
- Bump PSRule dependency to v1.7.2. #951
> Pre-release v1.8.0-B2109046

- docs/en/baselines/Azure.All.md
- docs/en/baselines/Azure.Default.md
- docs/en/baselines/Azure.Preview.md
- docs/en/rules/Azure.LB.AvailabilityZone.md
- docs/en/rules/module.md
- docs/en/rules/resource.md
- docs/examples-vnet.bicep
- docs/examples-vnet.json
- src/PSRule.Rules.Azure/en/PSRule-rules.psd1
- src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.AppGw.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.VNET.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.VNET.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.VirtualNetwork.json
Fix #927
Added `Azure.LB.AvailabilityZone` for the following types:
- Microsoft.Network/loadBalancers
Also fixed small issue with Reason for other AZ rules. 
> Add Load balancer Availability zone rule

- docs/features.md
- docs/setup/configuring-options.md
- docs/working-with-baselines.md
- overrides/home.html
- Documentation updates for baselines and general features.
> Doc updates for baselines and general features

- src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.ACR.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.APIM.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.AppGw.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.AppService.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.FrontDoor.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.KeyVault.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.MySQL.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.PostgreSQL.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Resource.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.SQL.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Storage.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Subscription.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Template.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.TrafficManager.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.VM.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.VNET.Tests.ps1
Fix #960
Added more tests for Reason and refactored existing tests. 
> Added more tests for Reason and refactored existing tests

- BaselineToc.Doc.ps1
- docs/en/baselines/Azure.GA_2020_06.md
- docs/en/baselines/Azure.GA_2020_09.md
- docs/en/baselines/Azure.GA_2020_12.md
- docs/en/baselines/Azure.GA_2021_03.md
- docs/en/baselines/Azure.GA_2021_06.md
- docs/hooks.py
- overrides/reference.html
- Added visible tags to documentation that make it easier to see pillar, resource, rule name and obsolete status from pages.
> Add visible tags to baseline and rule docs

- docs/CHANGELOG-v1.md
- docs/en/baselines/Azure.All.md
- docs/en/baselines/Azure.Default.md
- docs/en/baselines/Azure.GA_2021_09.md
- docs/en/baselines/Azure.Preview.md
- docs/en/rules/Azure.LB.StandardSKU.md
- docs/en/rules/module.md
- docs/en/rules/resource.md
- src/PSRule.Rules.Azure/rules/Azure.VNET.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.VNET.Tests.ps1
Fix #957
Added `Azure.LB.StandardSKU` rule for the following types:
- Microsoft.Network/loadBalancers
> Added load balancer Standard SKU rule

- RuleToc.Doc.ps1
- docs/en/rules/module.md
- docs/en/rules/resource.md
- docs/hooks.py
- Updated docs generation to hide edit pencil for generated docs.
> Updates to docs to exclude edit on generated

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.8.0-B2109060:
- New rules:
- Load Balancer:
- Check Load balancers are using Standard SKU. Thanks [@ArmaanMcleod](https://github.com/ArmaanMcleod). #957
- Engineering:
- Increased test coverage of rule reasons. Thanks [@ArmaanMcleod](https://github.com/ArmaanMcleod). #960
- Bug fixes:
- Fixed Bicep CLI fails with unexpected end of content. #889
- Fixed incomplete reason message for `Azure.Storage.MinTLS`. #971
- Fixed false positive of `Azure.Storage.UseReplication` with large file storage. #965
> Pre-release v1.8.0-B2109086

- docs/CHANGELOG-v1.md
What's changed since v1.7.0:
- Added `Azure.GA_2021_09` baseline. #961
- Includes rules released before or during September 2021 for Azure GA features.
- Marked baseline `Azure.GA_2021_06` as obsolete.
- New rules:
- Check App Gateways should use availability zones when available. Thanks [@ArmaanMcleod](https://github.com/ArmaanMcleod). #928
- Check clusters have control plane audit logs enabled. Thanks [@ArmaanMcleod](https://github.com/ArmaanMcleod). #882
- Check clusters have control plane diagnostics enabled. Thanks [@ArmaanMcleod](https://github.com/ArmaanMcleod). #922
- Check clusters use Container Insights for monitoring workloads. Thanks [@ArmaanMcleod](https://github.com/ArmaanMcleod). #881
- Check clusters use …
> Release v1.8.0

- docs/CHANGELOG-v1.md
- docs/en/rules/Azure.Template.DefineParameters.md
- docs/en/rules/Azure.Template.UseLocationParameter.md
- src/PSRule.Rules.Azure/rules/Azure.Template.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Template.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Template.AzOps.1.json
- tests/PSRule.Rules.Azure.Tests/Template.PSArm.1.json
- Improved processing of AzOps generated templates.
- `Azure.Template.DefineParameters` is ignored for AzOps generated templates.
- `Azure.Template.UseLocationParameter` is ignored for AzOps generated templates.
Fixes #799 
> Improved processing for AzOps #799

- docs/CHANGELOG-v1.md
- docs/en/baselines/Azure.All.md
- docs/en/baselines/Azure.Default.md
- docs/en/baselines/Azure.Preview.md
- docs/en/rules/Azure.VNG.ERAvailabilityZoneSKU.md
- docs/en/rules/Azure.VNG.VPNAvailabilityZoneSKU.md
- docs/en/rules/module.md
- docs/en/rules/resource.md
- src/PSRule.Rules.Azure/en/PSRule-rules.psd1
- src/PSRule.Rules.Azure/rules/Azure.VNET.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.VNET.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.VirtualNetwork.json
Fix #926
Created two rules to check if virtual network gateways are configured with AZ SKU:
- `Azure.VNG.VPNAvailabilityZoneSKU`
- `Azure.VNG.ERAvailabilityZoneSKU`
> Added Virtual network gateway AZ SKU rule

- docs/CHANGELOG-v1.md
What's changed since v1.8.0:
- New rules:
- Public IP Address:
- Check Public IP addresses are configured with zone-redundancy. #958
- Check Public IP addresses are using Standard SKU. #979
- Virtual Network Gateway:
- Check VPN/ExpressRoute gateways are configured with availability zone SKU. #926
- Improved processing of AzOps generated templates. #799]
- `Azure.Template.DefineParameters` is ignored for AzOps generated templates.
- `Azure.Template.UseLocationParameter` is ignored for AzOps generated templates.
- Bug fixes:
- Fixed `ToUpper` fails to convert character. #986
> Pre-release v1.9.0-B2109027

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.9.0-B2109027:
- Bug fixes:
- Fixed handling of comments with template and parameter file rules. #996
- Fixed `Azure.Template.UseLocationParameter` to only apply to templates deployed as RG scope #995
- Fixed expand template fails with `createObject` when no parameters are specified. #1000
> Pre-release v1.9.0-B2110009

- docs/CHANGELOG-v1.md
- docs/using-templates.md
- src/PSRule.Rules.Azure/Data/Template/ExpressionStream.cs
- src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
- src/PSRule.Rules.Azure/Resources/PSRuleResources.Designer.cs
- src/PSRule.Rules.Azure/Resources/PSRuleResources.resx
- tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
- tests/PSRule.Rules.Azure.Tests/Template.Parsing.7.json
- tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- Fixes expression out of range of valid values. #1005
- Fixes template expand fails in nested reference expansion. #1007
Fixes #1005 
Fixes #1007 
> Fixes for template bugs #1005 #1007

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.9.0-B2110009:
- Bug fixes:
- Fixes expression out of range of valid values. #1005
- Fixes template expand fails in nested reference expansion. #1007
> Pre-release v1.9.0-B2110014

- docs/CHANGELOG-v1.md
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- tests/PSRule.Rules.Azure.Tests/Cmdlet.Common.Tests.ps1
- Fixed zones property not found on public IP resource.
Fixes #1070
> Fixed zones property on public IP resource #1070

- docs/CHANGELOG-v1.md
- docs/en/baselines/Azure.All.md
- docs/en/baselines/Azure.Default.md
- docs/en/baselines/Azure.GA_2020_06.md
- docs/en/baselines/Azure.GA_2020_09.md
- docs/en/baselines/Azure.GA_2020_12.md
- docs/en/baselines/Azure.GA_2021_03.md
- docs/en/baselines/Azure.GA_2021_06.md
- docs/en/baselines/Azure.GA_2021_09.md
- docs/en/baselines/Azure.Preview.md
- docs/en/rules/Azure.VM.ASMinMembers.md
- docs/en/rules/module.md
- docs/en/rules/resource.md
- src/PSRule.Rules.Azure/rules/Azure.VM.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.VM.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.VirtualMachine.Template.json
- Fixed Azure.VM.ASMinMembers for template deployments.
Fixes #1064
> Fixed Azure.VM.ASMinMembers for templates #1064

- docs/CHANGELOG-v1.md
- src/PSRule.Rules.Azure/Data/Template/ExpressionBuilder.cs
- tests/PSRule.Rules.Azure.Tests/OptionsTests.cs
- tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
- tests/PSRule.Rules.Azure.Tests/RuntimeHelperTests.cs
- tests/PSRule.Rules.Azure.Tests/Template.Parsing.8.json
- tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- Fixed can not index into resource group tags.
Fixes #1066
> Fixed can not index into resource group tags #1066

- docs/CHANGELOG-v1.md
What's changed since v1.9.0:
- Bug fixes:
- Fixed can not index into resource group tags. #1066
- Fixed `Azure.VM.ASMinMembers` for template deployments. #1064
- Fixed zones property not found on public IP resource. #1070
> Release v1.9.1

- docs/CHANGELOG-v1.md
- pipeline.build.ps1
- ps-project.yaml
- Bump PSRule dependency to v1.9.0.
Fixes #1081
> Bump PSRule dependency to v1.9.0 #1081

- docs/CHANGELOG-v1.md
What's changed since v1.9.1:
- Added support for parameter strong types. #1083
- The value of string parameters can be tested against the expected type.
- When configuring a location strong type, the parameter value must be a valid Azure location.
- When configuring a resource type strong type, the parameter value must be a matching resource Id.
- Engineering:
- Bump PSRule dependency to v1.9.0. #1081
- Bump Microsoft.CodeAnalysis.NetAnalyzers to v6.0.0. #1080
- Bump Microsoft.SourceLink.GitHub to 1.1.1. #1085
> Pre-release v1.10.0-B2111040

- docs/customization/enforce-codeowners/index.md
- docs/customization/enforce-custom-tags/index.md
- docs/customization/storing-custom-rules/index.md
- mkdocs.yml
- Update docs customization navigation.
> Fix customization navigation

- docs/CHANGELOG-v1.md
- pipeline.build.ps1
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psd1
- src/PSRule.Rules.Azure/rules/Config.Rule.yaml
- Updated default baseline to use module configuration.
Fixes #1089
> Default baseline with module configuration #1089

- docs/en/rules/Azure.ACR.AdminUser.md
- docs/en/rules/Azure.ACR.ContainerScan.md
- docs/en/rules/Azure.ACR.ContentTrust.md
- docs/en/rules/Azure.ACR.GeoReplica.md
- docs/en/rules/Azure.ACR.ImageHealth.md
- docs/en/rules/Azure.ACR.MinSku.md
- docs/en/rules/Azure.ACR.Quarantine.md
- docs/en/rules/Azure.ACR.Retention.md
- docs/en/rules/Azure.ACR.Usage.md
- docs/en/rules/module.md
- docs/examples-acr.bicep
- docs/examples-acr.json
- docs/examples-defender.bicep
- docs/examples-defender.json
- src/PSRule.Rules.Azure/rules/Azure.ACR.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.ACR.Rule.yaml
- src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.yaml
- Updates to ACR documentation. #868
- Refactoring of ACR rules to YAML. No function changes.
> ACR docs review and refactor #868

- docs/CHANGELOG-v1.md
- docs/en/baselines/Azure.All.md
- docs/en/baselines/Azure.Default.md
- docs/en/baselines/Azure.Preview.md
- docs/en/rules/Azure.EventGrid.DisableLocalAuth.md
- docs/en/rules/Azure.EventGrid.ManagedIdentity.md
- docs/en/rules/Azure.EventGrid.TopicPublicAccess.md
- docs/en/rules/module.md
- docs/en/rules/resource.md
- docs/examples-eventgrid.bicep
- docs/examples-eventgrid.json
- src/PSRule.Rules.Azure/rules/Azure.EventGrid.Rule.yaml
- tests/PSRule.Rules.Azure.Tests/Azure.EventGrid.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Template.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.EventGrid.Parameters.json
- tests/PSRule.Rules.Azure.Tests/Resources.EventGrid.Template.json
- tests/PSRule.Rules.Azure.Tests/Resources.EventGrid.json
- Check topics and domains use managed identities. #1091
- Check topics and domains use private endpoints. #1092
- Check topics and domains use identity-based authentication. #1093
Fixes #1091 
Fixes #1092 
Fixes #1093 
> Added Event Grid rules #1091 #1092 #1093

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.10.0-B2111040:
- New rules:
- Event Grid:
- Check topics and domains use managed identities. #1091
- Check topics and domains use private endpoints. #1092
- Check topics and domains use identity-based authentication. #1093
- Updated default baseline to use module configuration. #1089
> Pre-release v1.10.0-B2111058

- docs/CHANGELOG-v1.md
- src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
- src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.Resource.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Template.StrongType.1.Parameters.json
- tests/PSRule.Rules.Azure.Tests/Template.StrongType.1.json
- tests/PSRule.Rules.Azure.Tests/Template.StrongType.2.Parameters.json
- tests/PSRule.Rules.Azure.Tests/Template.StrongType.3.Parameters.json
- Fixed expansion of secret references. #1098
- Fixed handling of tagging for deployments. #1099 
- Fixed strong type issue flagged with empty defaultValue string. #1100
Fixes #1098 
Fixes #1099 
Fixes #1100
> Fix templates and deployments #1098 #1099 #1100

- .gitignore
- .vscode/settings.json
- docs/CHANGELOG-v1.md
- docs/en/baselines/Azure.All.md
- docs/en/baselines/Azure.Default.md
- docs/en/baselines/Azure.Preview.md
- docs/en/rules/Azure.Template.ExpressionLength.md
- docs/en/rules/Azure.Template.UseLocationParameter.md
- docs/en/rules/module.md
- docs/en/rules/resource.md
- src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
- src/PSRule.Rules.Azure/Resources/ReasonStrings.Designer.cs
- src/PSRule.Rules.Azure/Resources/ReasonStrings.resx
- src/PSRule.Rules.Azure/rules/Azure.Template.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Template.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
- tests/PSRule.Rules.Azure.Tests/PathBuilderTests.cs
- tests/PSRule.Rules.Azure.Tests/Template.Parsing.10.Parameters.json
- tests/PSRule.Rules.Azure.Tests/Template.Parsing.10.json
- tests/PSRule.Rules.Azure.Tests/Template.Parsing.2.Parameters.json
- tests/PSRule.Rules.Azure.Tests/Template.Parsing.9.Parameters.json
- tests/PSRule.Rules.Azure.Tests/Template.Parsing.9.json
- tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- Check template expressions do not exceed a maximum length.
Fixes #1006
> Check template expression length #1006

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.10.0-B2111058:
- New rules:
- Check template expressions do not exceed a maximum length. #1006
- Bug fixes:
- Fixed expansion of secret references. #1098
- Fixed handling of tagging for deployments. #1099
- Fixed strong type issue flagged with empty `defaultValue` string. #1100
> Pre-release v1.10.0-B2111072

- .vscode/launch.json
- docs/CHANGELOG-v1.md
- docs/en/baselines/Azure.All.md
- docs/en/baselines/Azure.Default.md
- docs/en/baselines/Azure.Preview.md
- docs/en/rules/Azure.Automation.EncryptVariables.md
- docs/en/rules/Azure.Automation.ManagedIdentity.md
- docs/en/rules/Azure.Automation.WebHookExpiry.md
- docs/en/rules/module.md
- docs/en/rules/resource.md
- src/PSRule.Rules.Azure/rules/Azure.Automation.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.Automation.Rule.yaml
- tests/PSRule.Rules.Azure.Tests/Azure.Automation.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.Automation.json
> Added Azure.Automation.ManagedIdentity rule

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.10.0-B2111072:
- New rules:
- Automation Service:
- Automation accounts should use managed identities for authentication. #1074
> Pre-release v1.10.0-B2111081

- docs/CHANGELOG-v1.md
What's changed since v1.9.1:
- Added support for parameter strong types. #1083
- The value of string parameters can be tested against the expected type.
- When configuring a location strong type, the parameter value must be a valid Azure location.
- When configuring a resource type strong type, the parameter value must be a matching resource Id.
- New rules:
- Check template expressions do not exceed a maximum length. #1006
- Automation Service:
- Automation accounts should use managed identities for authentication. #1074
- Event Grid:
- Check topics and domains use managed identities. #1091
- Check topics and domains use private endpoints. #1092
- Check topics and domains use identity-based authentication. #1093
- Updated default …
> Release v1.10.0

- docs/CHANGELOG-v1.md
What's changed since v1.10.0:
- Bug fixes:
- Fixed `Azure.Policy.WaiverExpiry` date conversion. #1118
> Release v1.10.1

- docs/CHANGELOG-v1.md
- src/PSRule.Rules.Azure/rules/Azure.Policy.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Policy.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.Policy.Parameters.2.json
- tests/PSRule.Rules.Azure.Tests/Resources.Policy.Template.2.json
- Fixed `Azure.Policy.WaiverExpiry` date conversion. #1118
> Merge fix from v1.10.1

- .vscode/settings.json
- docs/CHANGELOG-v1.md
- docs/en/baselines/Azure.All.md
- docs/en/baselines/Azure.Default.md
- docs/en/baselines/Azure.Preview.md
- docs/en/rules/Azure.Automation.AuditLogs.md
- docs/en/rules/Azure.Automation.PlatformLogs.md
- docs/en/rules/module.md
- docs/en/rules/resource.md
- docs/setup/configuring-rules.md
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- src/PSRule.Rules.Azure/en/PSRule-rules.psd1
- src/PSRule.Rules.Azure/rules/Azure.Automation.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Automation.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.Automation.json
- tests/PSRule.Rules.Azure.Tests/ps-rule-options.yaml
Fix #1075
Added `Azure.Automation.AuditLogs` and `Azure.Automation.PlatformLogs` rules. 
> Added Automation Account diagnostic log rules

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.11.0-B2111014:
- New rules:
- Check clusters have the HTTP application routing add-on disabled. #1131
- Check clusters use the Secrets Store CSI Driver add-on. #992
- Check clusters autorotation with the Secrets Store CSI Driver add-on. #993
- Automation Account:
- Automation accounts should enable diagnostic logs. #1075
- Update rules:
- Promoted `Azure.AKS.AutoUpgrade` to GA rule set. #1130
- Added support for template function `tenant()`. #1124
- Added support for template function `managementGroup()`. #1125
- Added support for template function `pickZones()`. #518
- Bug fixes:
- Fixed `Azure.Policy.WaiverExpiry` date conversion. #1118
> Pre-release v1.11.0-B2112024

- .vscode/settings.json
- docs/CHANGELOG-v1.md
- docs/en/baselines/Azure.All.md
- docs/en/baselines/Azure.Default.md
- docs/en/baselines/Azure.Preview.md
- docs/en/rules/Azure.Template.UseComments.md
- docs/en/rules/Azure.Template.UseDescriptions.md
- docs/en/rules/module.md
- docs/en/rules/resource.md
- src/PSRule.Rules.Azure/en/PSRule-rules.psd1
- src/PSRule.Rules.Azure/rules/Azure.Template.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Template.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.Template.Bicep1.json
- tests/PSRule.Rules.Azure.Tests/Resources.Template.Bicep2.json
- tests/PSRule.Rules.Azure.Tests/Resources.Template.json
- tests/PSRule.Rules.Azure.Tests/Resources.Template2.json
Fix #969
Added `Azure.Template.UseComments` and `Azure.Template.UseDescriptions` rules.
> Added rules to check comments/descriptions for each template resource

- docs/CHANGELOG-v1.md
- src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
- tests/PSRule.Rules.Azure.Tests/Template.Parsing.11.json
- tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- Fixed copy loop on nested deployment parameters is not handled.
Fixes #1144 
> Fix copy loop on nested deployment params #1144

- docs/CHANGELOG-v1.md
What's changed since v1.10.2:
- Bug fixes:
- Fixed copy loop on nested deployments parameters is not handled. #1144
> Release v1.10.3

- .azure-pipelines/azure-pipelines.yaml
- Updated CI pipeline images to the latest versions.
> Bump pipeline images to the latest

- README.md
- docs/expanding-source-files.md
- docs/faq.md
- docs/features.md
- docs/setup/configuring-options.md
- docs/using-bicep.md
- docs/using-templates.md
- docs/validating-locally.md
- mkdocs.yml
- overrides/home.html
- Updates to documentation for Bicep expansion.
Fixes #1071
> Improve bicep docs #1071

- docs/CHANGELOG-v1.md
- src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
- tests/PSRule.Rules.Azure.Tests/Template.Parsing.11.json
- tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- Fixed outer copy loop of nested deployment.
Fixes #1154
> Fixes outer copy loop of nested deployment #1154

- docs/CHANGELOG-v1.md
What's changed since v1.10.3:
- Bug fixes:
- Fixed outer copy loop of nested deployment. #1154
> Release v1.10.4

- docs/CHANGELOG-v1.md
- docs/en/baselines/Azure.GA_2021_12.md
- docs/en/baselines/Azure.Preview.md
- docs/en/baselines/Azure.Preview_2021_09.md
- docs/en/baselines/Azure.Preview_2021_12.md
- docs/working-with-baselines.md
- src/PSRule.Rules.Azure/rules/Baseline.Rule.yaml
- tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1
- Added baselines containing only Azure preview features. #1129
- Added baseline `Azure.Preview_2021_09`.
- Added baseline `Azure.Preview_2021_12`.
- Added `Azure.GA_2021_12` baseline. #1146
- Includes rules released before or during December 2021 for Azure GA features.
- Marked baseline `Azure.GA_2021_09` as obsolete.
Fixes #1129 
Fixes #1146
> Added quarterly baselines #1129 #1146

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.11.0-B2112024:
- Added baselines containing only Azure preview features. #1129
- Added baseline `Azure.Preview_2021_09`.
- Added baseline `Azure.Preview_2021_12`.
- Added `Azure.GA_2021_12` baseline. #1146
- Includes rules released before or during December 2021 for Azure GA features.
- Marked baseline `Azure.GA_2021_09` as obsolete.
- New rules:
- Check comments for each template resource. #969
- Bug fixes:
- Fixed template function `equals` parameter count mismatch. #1137
- Fixed copy loop on nested deployment parameters is not handled. #1144
> Pre-release v1.11.0-B2112073

- docs/CHANGELOG-v1.md
- src/PSRule.Rules.Azure/Data/Bicep/BicepHelper.cs
- tests/Bicep/Bicep.Tests.ps1
- tests/Bicep/bicepconfig.json
- tests/Bicep/error.bicep
- tests/Bicep/noterror.bicep
- Fixed output of Bicep informational and warning messages in error stream.
Fixes #1157
> Filter out bicep info and warning messages #1157

- docs/CHANGELOG-v1.md
- docs/en/baselines/Azure.Preview_2021_12.md
- src/PSRule.Rules.Azure/rules/Baseline.Rule.yaml
- Fixed obsolete flag for baseline `Azure.Preview_2021_12`.
Fixes #1166
> Fixed obsolete flag on Azure.Preview_2021_12 #1166

- .github/workflows/analyze.yaml
- ps-rule.yaml
- Added CodeQL and DevSkim to code scanning checks/ linting.
> Added GitHub based code scans

- .github/ISSUE_TEMPLATE/bug-report.md
- docs/CHANGELOG-v1.md
- docs/benchmark/results-pre-v1.8.0.md
- docs/benchmark/results-v1.10.4.md
- docs/benchmark/results-v1.11.0.md
- docs/benchmark/results-v1.8.1.md
- docs/benchmark/results-v1.9.1.md
- docs/setup/configuring-expansion.md
- docs/setup/setup-bicep.md
- docs/using-bicep.md
What's changed since v1.10.4:
- Added baselines containing only Azure preview features. #1129
- Added baseline `Azure.Preview_2021_09`.
- Added baseline `Azure.Preview_2021_12`.
- Added `Azure.GA_2021_12` baseline. #1146
- Includes rules released before or during December 2021 for Azure GA features.
- Marked baseline `Azure.GA_2021_09` as obsolete.
- Bicep support promoted from experimental to generally available (GA). #1176
- New rules:
- Check comments for each template resource. #969
- Automation Account:
- Automation accounts should enable diagnostic logs. #1075
- Check clusters have the HTTP application routing add-on disabled. #1131
- Check clusters use the Secrets Store CSI Driver add-on. #992
- Check clusters …
> Release v1.11.0

- .markdownlint.json
- README.md
- docs/creating-your-pipeline.md
- Improvements to readme and documentation samples.
> Updates to documentation

- .github/workflows/analyze.yaml
- .github/workflows/docs.yaml
- .github/workflows/providers.yml
- .github/workflows/stale.yaml
- Added stale issue management.
- Configured permissions for other workflow jobs.
> Added stale issue management

- .devcontainer/container-build.ps1
- .devcontainer/container-start.ps1
- .devcontainer/devcontainer.json
- .vscode/extensions.json
- Added updates to codespaces configuration.
> Added updates for codespaces configuration

- .github/workflows/analyze.yaml
- README.md
- docs/creating-your-pipeline.md
- docs/install-instructions.md
- docs/scenarios/azure-pipelines-ci/azure-pipelines-ci.md
- docs/scenarios/azure-pipelines-ci/azure-pipelines.yaml
- docs/setup/setup-azure-monitor-logs.md
- docs/working-with-baselines.md
- Updated documentation to use latest versions of GitHub Action and Azure Pipelines task.
> Update docs to use latest pipeline versions

- CONTRIBUTING.md
- docs/license-contributing.md
- docs/related-projects.md
- mkdocs.yml
- Updates to contributor documentation.
> Contributor documentation update

- .github/workflows/dependencies.yaml
- Fix the environment variable for working branch.
> Update environment variable

- .github/workflows/dependencies.yaml
- pipeline.build.ps1
- scripts/dependencies.psm1
- Updates to env ref for dependency workflow.
> Fix dependency env reference

- scripts/dependencies.psm1
- Update dependency update script action.
> Update dependency bump

- scripts/dependencies.psm1
- Fixes for dependency update script.
> Fixes for dependency update

- .github/workflows/dependencies.yaml
- scripts/dependencies.psm1
- Updated dependency PR creation with body and update automation.
> Update PR creation

- docs/CHANGELOG-v1.md
- docs/en/baselines/Azure.All.md
- docs/en/baselines/Azure.Default.md
- docs/en/baselines/Azure.Preview.md
- docs/en/rules/Azure.ADX.DiskEncryption.md
- docs/en/rules/Azure.ADX.ManagedIdentity.md
- docs/en/rules/Azure.ADX.SLA.md
- docs/en/rules/Azure.APIM.ManagedIdentity.md
- docs/en/rules/Azure.AppService.ManagedIdentity.md
- docs/en/rules/module.md
- docs/en/rules/resource.md
- docs/examples-adx.bicep
- docs/examples-adx.json
- docs/examples-apim.bicep
- docs/examples-apim.json
- docs/examples-appservice.bicep
- docs/examples-appservice.json
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- src/PSRule.Rules.Azure/rules/Azure.ADX.Rule.yaml
- tests/PSRule.Rules.Azure.Tests/Azure.ADX.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.ADX.json
- Check clusters use Managed Identities. [#1207](https://github.com/Azure/PSRule.Rules.Azure/issues/1207)
- Check clusters use a SKU with a SLA. [#1208](https://github.com/Azure/PSRule.Rules.Azure/issues/1208)
- Check clusters use disk encryption. [#1209](https://github.com/Azure/PSRule.Rules.Azure/issues/1209)
> Added rules for ADX #1207 #1208 #1209

- docs/CHANGELOG-v1.md
- docs/en/baselines/Azure.All.md
- docs/en/baselines/Azure.Default.md
- docs/en/baselines/Azure.GA_2020_06.md
- docs/en/baselines/Azure.GA_2020_09.md
- docs/en/baselines/Azure.GA_2020_12.md
- docs/en/baselines/Azure.GA_2021_03.md
- docs/en/baselines/Azure.GA_2021_06.md
- docs/en/baselines/Azure.GA_2021_09.md
- docs/en/baselines/Azure.GA_2021_12.md
- docs/en/baselines/Azure.Preview.md
- docs/en/rules/Azure.Storage.BlobAccessType.md
- docs/en/rules/module.md
- docs/en/rules/resource.md
- docs/examples-storage.bicep
- docs/examples-storage.json
- src/PSRule.Rules.Azure/rules/Azure.Storage.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.Storage.Rule.yaml
- tests/PSRule.Rules.Azure.Tests/Resources.Storage.json
- Fixed false positive of blob container with access unspecified.
Fixes #1212
> Fixes false positive of container access #1212

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.12.0-B2201054:
- New rules:
- Data Explorer:
- Check clusters use Managed Identities. #1207
- Check clusters use a SKU with a SLA. #1208
- Check clusters use disk encryption. #1209
- Bug fixes:
- Fixed false positive of blob container with access unspecified. #1212
> Pre-release v1.12.0-B2201067

- README.md
- docs/analyzing-resources.md
- docs/creating-your-pipeline.md
- docs/export-rule-data.md
- docs/faq.md
- docs/setup/configuring-options.md
- mkdocs.yml
- Added documentation for in-flight analysis.
- Updated links to PSRule docs.
> Add in-flight documentation

- docs/CHANGELOG-v1.md
- docs/en/baselines/Azure.All.md
- docs/en/baselines/Azure.Default.md
- docs/en/baselines/Azure.Preview.md
- docs/en/rules/module.md
- docs/en/rules/resource.md
What's changed since pre-release v1.12.0-B2201067:
- New rules:
- Data Explorer:
- Check clusters are in use with databases. #1215
- Event Hub:
- Check namespaces are in use with event hubs. #1216
- Check namespaces only accept identity-based authentication. #1217
- Azure Recovery Services Vault:
- Check vaults use geo-redundant storage. #5
- Service Bus:
- Check namespaces are in use with queues and topics. #1218
- Check namespaces only accept identity-based authentication. #1219
> Pre-release v1.12.0-B2201086

- .azure-pipelines/azure-pipelines.yaml
> Bump CI version

- docs/en/rules/Azure.VM.UseHybridUseBenefit.md
- docs/examples-vm.bicep
- docs/examples-vm.json
- docs/faq.md
- Updates to FAQ and Azure Hybrid Benefit documentation.
> Added doc updates to FAQ and Azure Hybrid Benefit

- docs/CHANGELOG-v1.md
- src/PSRule.Rules.Azure/rules/Conventions.Rule.ps1
- Fix Bicep already exists with PSRule v2.
Fixes #1232
> Fixes Bicep install with PSRule v2 #1232

- docs/CHANGELOG-v1.md
What's changed since v1.12.0:
- Bug fixes:
- Fixed Bicep already exists with PSRule v2. #1232
> Release v1.12.1

- docs/CHANGELOG-v1.md
- src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
- tests/PSRule.Rules.Azure.Tests/Azure.Resource.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Cmdlet.Common.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
- tests/PSRule.Rules.Azure.Tests/Template.Bicep.2.json
- tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- Fixed detect strong type requirements for nested deployments.
Fixes #1235
> Fix strong type on nested deployments #1235

- docs/CHANGELOG-v1.md
What's changed since v1.12.1:
- Bug fixes:
- Fixed detect strong type requirements for nested deployments. #1235
> Release v1.12.2

- docs/CHANGELOG-v1.md
- docs/en/baselines/Azure.All.md
- docs/en/baselines/Azure.Default.md
- docs/en/baselines/Azure.GA_2020_06.md
- docs/en/baselines/Azure.GA_2020_09.md
- docs/en/baselines/Azure.GA_2020_12.md
- docs/en/baselines/Azure.GA_2021_03.md
- docs/en/baselines/Azure.GA_2021_06.md
- docs/en/baselines/Azure.GA_2021_09.md
- docs/en/baselines/Azure.GA_2021_12.md
- docs/en/baselines/Azure.Preview.md
- docs/en/rules/Azure.RSV.ReplicationAlert.md
- docs/en/rules/Azure.RSV.StorageType.md
- docs/en/rules/module.md
- docs/en/rules/resource.md
- src/PSRule.Rules.Azure/rules/Azure.RSV.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.RSV.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.RSV.json
Adding a new rule to check if RSVs have replication alerts configured. Related to issue: #7 
> New rule - RSVs should have replication alerts configured

- docs/setup/setup-bicep.md
- Fix broken links to Bicep documentation.
> Fix links to Bicep documentation

- .github/workflows/docs.yaml
- README.md
- docs/creating-your-pipeline.md
- docs/features.md
- docs/setup/configuring-options.md
- mkdocs.yml
- overrides/home.html
- Update docs that describe setting configuration options.
> Update to configuration docs

- .editorconfig
- .vscode/settings.json
- src/PSRule.Rules.Azure/Common/DictionaryExtensions.cs
- src/PSRule.Rules.Azure/Common/EnvironmentHelper.cs
- src/PSRule.Rules.Azure/Common/JsonExtensions.cs
- src/PSRule.Rules.Azure/Common/ResourceHelper.cs
- src/PSRule.Rules.Azure/Configuration/ConfigurationOption.cs
- src/PSRule.Rules.Azure/Configuration/ManagementGroupOption.cs
- src/PSRule.Rules.Azure/Configuration/OutputOption.cs
- src/PSRule.Rules.Azure/Configuration/ResourceGroupOption.cs
- src/PSRule.Rules.Azure/Configuration/SubscriptionOption.cs
- src/PSRule.Rules.Azure/Configuration/TenantOption.cs
- src/PSRule.Rules.Azure/Data/Bicep/BicepHelper.cs
- src/PSRule.Rules.Azure/Data/Network/NetworkSecurityGroupEvaluator.cs
- src/PSRule.Rules.Azure/Data/Template/ExpressionBuilder.cs
- src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs
- src/PSRule.Rules.Azure/Data/Template/ExpressionParser.cs
- src/PSRule.Rules.Azure/Data/Template/Functions.cs
- src/PSRule.Rules.Azure/Data/Template/ResourceProviderHelper.cs
- src/PSRule.Rules.Azure/Data/Template/TemplateLinkHelper.cs
- src/PSRule.Rules.Azure/Data/Template/TemplateValidator.cs
- src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
- src/PSRule.Rules.Azure/Pipeline/Output/PSPipelineWriter.cs
- src/PSRule.Rules.Azure/Pipeline/PathBuilder.cs
- src/PSRule.Rules.Azure/Pipeline/TemplateLinkPipeline.cs
- src/PSRule.Rules.Azure/Pipeline/TemplatePipeline.cs
- src/PSRule.Rules.Azure/Runtime/Helper.cs
- tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
Added `.editorconfig` from PSRule and did some refactoring
> Csharp code refactoring

- docs/CHANGELOG-v1.md
- src/PSRule.Rules.Azure/rules/Azure.LogicApps.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.LogicApp.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.LogicApp.json
- Fixes error with empty logic app trigger.
Fixes #1249
> Fix error with empty logic app trigger #1249

- docs/CHANGELOG-v1.md
- docs/en/baselines/Azure.All.md
- docs/en/baselines/Azure.Preview.md
- docs/en/rules/Azure.KeyVault.AutoRotationPolicy.md
- docs/en/rules/module.md
- docs/en/rules/resource.md
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- src/PSRule.Rules.Azure/en/PSRule-rules.psd1
- src/PSRule.Rules.Azure/rules/Azure.KeyVault.Rule.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.KeyVault.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Template.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.KeyVault.json
- tests/PSRule.Rules.Azure.Tests/Resources.Template2.json
Fixes #1159.
Added `Azure.KeyVault.AutoRotationPolicy` rule.
> Added key auto-rotation rule

- docs/CHANGELOG-v1.md
- docs/setup/configuring-expansion.md
- docs/setup/setup-bicep.md
- docs/using-bicep.md
- docs/using-templates.md
- src/PSRule.Rules.Azure/Data/Bicep/BicepHelper.cs
- src/PSRule.Rules.Azure/Runtime/Helper.cs
- tests/Bicep/Bicep.Tests.ps1
- tests/Bicep/template.parameters.json
- tests/PSRule.Rules.Azure.Tests/Azure.Template.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
- tests/PSRule.Rules.Azure.Tests/PathBuilderTests.cs
- tests/PSRule.Rules.Azure.Tests/TemplateLinkTests.cs
- tests/PSRule.Rules.Azure.Tests/Tests.Bicep.1.Parameters.json
- tests/PSRule.Rules.Azure.Tests/Tests.Bicep.1.bicep
- Added support expanding Bicep from parameter files.
Fixes #1160
> Expand Bicep from parameter files #1160

- docs/CHANGELOG-v1.md
- docs/en/baselines/Azure.All.md
- docs/en/baselines/Azure.Preview.md
- docs/en/rules/Azure.ContainerApp.Insecure.md
- docs/en/rules/module.md
- docs/en/rules/resource.md
- docs/examples-containerapp.bicep
- docs/examples-containerapp.json
- src/PSRule.Rules.Azure/rules/Azure.ContainerApp.Rule.yaml
- tests/PSRule.Rules.Azure.Tests/Azure.ContainerApp.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.ContainerApp.json
- Check insecure ingress is not enabled for container apps (preview).
Fixes #1252
> Check insecure ingress is not enabled #1252

- docs/CHANGELOG-v1.md
- docs/setup/configuring-expansion.md
- src/PSRule.Rules.Azure/Common/DictionaryExtensions.cs
- src/PSRule.Rules.Azure/Configuration/ConfigurationOption.cs
- src/PSRule.Rules.Azure/Configuration/ParameterDefaultsOption.cs
- src/PSRule.Rules.Azure/Configuration/ResourceGroupOption.cs
- src/PSRule.Rules.Azure/Configuration/SubscriptionOption.cs
- src/PSRule.Rules.Azure/Data/Template/Functions.cs
- src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
- tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- tests/PSRule.Rules.Azure.Tests/ps-rule-options.yaml
- Added support for setting defaults for required parameters.
Fixes #1065
> Added defaults for required parameters #1065

- docs/CHANGELOG-v1.md
What's changed since v1.12.2:
- Added support for setting defaults for required parameters. #1065
- When specified, the value will be used when a parameter value is not provided.
- Added support expanding Bicep from parameter files. #1160
- New rules:
- Check insecure ingress is not enabled (preview). #1252
- Key Vault:
- Check key auto-rotation is enabled (preview). #1159
- Recovery Services Vault:
- Check vaults have replication alerts configured. #7
- Bug fixes:
- Fixed error with empty logic app trigger. #1249
> Pre-release v1.13.0-B2202063

- docs/CHANGELOG-v1.md
- docs/en/baselines/Azure.All.md
- docs/en/baselines/Azure.Default.md
- docs/en/baselines/Azure.Preview.md
- docs/en/rules/Azure.Redis.PublicNetworkAccess.md
- docs/en/rules/module.md
- docs/en/rules/resource.md
- src/PSRule.Rules.Azure/rules/Azure.Redis.Rule.ps1
- src/PSRule.Rules.Azure/rules/Azure.Redis.Rule.yaml
- tests/PSRule.Rules.Azure.Tests/Azure.Redis.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.Redis.json
Fixes #935.
Added `Azure.Redis.PublicNetworkAccess` rule.
Also refactored some rules into YAML. #1109
> Added Azure.Redis.PublicNetworkAccess rule and refactored Redis YAML rules.

- docs/CHANGELOG-v1.md
- src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
- tests/PSRule.Rules.Azure.Tests/Template.Bicep.2.json
- tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- Fixed empty value with strong type.
Fixes #1258
> Fixes empty value with strong type #1258

- docs/CHANGELOG-v1.md
- src/PSRule.Rules.Azure/Data/Template/TemplateValidator.cs
- src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
- src/PSRule.Rules.Azure/Runtime/Helper.cs
- tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
- tests/PSRule.Rules.Azure.Tests/Template.Parsing.12.json
- tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- Fixed out of order parameters.
Fixes #1257
> Fixed out of order parameters #1257

- .github/ISSUE_TEMPLATE/docs-update.md
- .github/ISSUE_TEMPLATE/question.md
- Updates to issue templates including updating wording for questions and adding a documentation template.
> Updates to issue template

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.13.0-B2202090:
- Engineering:
- Bump PSRule dependency to v1.11.1. #1269
- Bug fixes:
- Fixed out of order parameters. #1257
> Pre-release v1.13.0-B2202103

- docs/CHANGELOG-v1.md
- src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs
- src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
- tests/PSRule.Rules.Azure.Tests/Template.Bicep.2.json
- tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- Fixed mapping default configuration causes cast exception.
Fixes #1274
> Fixed mapping default config cast exception #1274

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.13.0-B2202103:
- Bug fixes:
- Fixed mapping default configuration causes cast exception. #1274
> Pre-release v1.13.0-B2202108

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.13.0-B2202108:
- Bug fixes:
- Fixed resource id is incorrectly built for sub resource types. #1279
> Pre-release v1.13.0-B2202113

- docs/CHANGELOG-v1.md
- src/PSRule.Rules.Azure/Data/Template/ExpressionStream.cs
- tests/PSRule.Rules.Azure.Tests/ExpressionBuilderTests.cs
- Fixed parsing of nested quote pairs within JSON function. #1288
Fixes #1288 
> Fix quote pairs #1288

- docs/CHANGELOG-v1.md
What's changed since v1.13.0:
- Bug fixes:
- Fixed parsing of nested quote pairs within JSON function. #1288
> Release v1.13.1

- docs/CHANGELOG-v1.md
- src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
- tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
- tests/PSRule.Rules.Azure.Tests/Template.Parsing.13.json
- tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- Fixed nested resource loops. #1293
Fixes #1293
> Fixes nested resource loops #1293

- docs/CHANGELOG-v1.md
What's changed since v1.13.1:
- Bug fixes:
- Fixed nested resource loops. #1293
> Release v1.13.2

- docs/CHANGELOG-v1.md
- docs/setup/configuring-expansion.md
- docs/setup/configuring-options.md
- docs/setup/setup-bicep.md
- docs/troubleshooting.md
- src/PSRule.Rules.Azure/Data/Bicep/BicepHelper.cs
- src/PSRule.Rules.Azure/Runtime/Helper.cs
- src/PSRule.Rules.Azure/rules/Conventions.Rule.ps1
- Fixed bicep build timeout for complex deployments.
Fixes #1299
> Fix bicep build timeout #1299

- docs/CHANGELOG-v1.md
What's changed since v1.13.2:
- Bug fixes:
- Fixed bicep build timeout for complex deployments. #1299
> Release v1.13.3

- docs/CHANGELOG-v1.md
- docs/en/baselines/Azure.All.md
- docs/en/baselines/Azure.Default.md
- docs/en/baselines/Azure.Preview.md
- docs/en/rules/Azure.ADX.SLA.md
- docs/en/rules/Azure.SignalR.ManagedIdentity.md
- docs/en/rules/Azure.SignalR.Name.md
- docs/en/rules/Azure.SignalR.SLA.md
- docs/en/rules/Azure.WebPubSub.ManagedIdentity.md
- docs/en/rules/Azure.WebPubSub.SLA.md
- docs/en/rules/module.md
- docs/en/rules/resource.md
- docs/examples-signalr.bicep
- docs/examples-signalr.json
- docs/examples-webpubsub.bicep
- docs/examples-webpubsub.json
- src/PSRule.Rules.Azure/rules/Azure.SignalR.Rule.yaml
- src/PSRule.Rules.Azure/rules/Azure.WebPubSub.Rule.yaml
- tests/PSRule.Rules.Azure.Tests/Azure.WebPubSub.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.SignalR.Template.json
- tests/PSRule.Rules.Azure.Tests/Resources.SignalR.json
- tests/PSRule.Rules.Azure.Tests/Resources.WebPubSub.Template.json
- tests/PSRule.Rules.Azure.Tests/Resources.WebPubSub.json
- SignalR Service:
- Check services use Managed Identities. #1306
- Check services use a SKU with an SLA. #1307
- Web PubSub Service:
- Check services use Managed Identities. #1308
- Check services use a SKU with an SLA. #1309
Fixes #1306 
Fixes #1307 
Fixes #1308 
Fixes #1309
> Added rules for SignalR #1306 #1307 #1308 #1309

- docs/using-bicep.md
Minor updates to Bicep docs to reduce confusion around expansion options in examples which are not required for use with parameter files.
> Minor updates to Bicep examples

- docs/CHANGELOG-v1.md
What's changed since v1.13.3:
- Bug fixes:
- Fixed virtual network without any subnets is invalid. #1303
- Fixed container registry rules that require a premium tier. #1304
- Rules `Azure.ACR.Retention` and `Azure.ACR.ContentTrust` are now only run against premium instances.
> Release v1.13.4

- docs/CHANGELOG-v1.md
- Merges change log updates from release v1.13.4.
> Merge change log updates from v1.13.4

- docs/CHANGELOG-v1.md
- docs/en/rules/Azure.AKS.Version.md
- docs/examples-aks.bicep
- docs/examples-aks.json
- docs/setup/configuring-rules.md
- src/PSRule.Rules.Azure/rules/Config.Rule.yaml
- tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json
- tests/PSRule.Rules.Azure.Tests/Resources.AKS.json
- Updated `Azure.AKS.Version` to use latest stable version `1.21.9`.
Fixes #1318
> Bumped stable AKS version to 1.21.9 #1318

- docs/CHANGELOG-v1.md
What's changed since v1.13.4:
- Added support for referencing resources in template. #1315
- The `reference()` function can be used to reference resources in template.
- A placeholder value is still used for resources outside of the template.
- New rules:
- SignalR Service:
- Check services use Managed Identities. #1306
- Check services use a SKU with an SLA. #1307
- Web PubSub Service:
- Check services use Managed Identities. #1308
- Check services use a SKU with an SLA. #1309
- Updated `Azure.AKS.Version` to use latest stable version `1.21.9`. #1318
- Bug fixes:
- Fixed processing of deployment outputs. #1316
> Pre-release v1.14.0-B2203066

- README.md
- docs/install-instructions.md
- Correction to docs on updating modules using `Update-Module`.
> Correct update module docs

- docs/CHANGELOG-v1.md
- src/PSRule.Rules.Azure/Data/Template/Functions.cs
- tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
- tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
- tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- tests/PSRule.Rules.Azure.Tests/Tests.Bicep.3.bicep
- tests/PSRule.Rules.Azure.Tests/Tests.Bicep.3.dns.bicep
- tests/PSRule.Rules.Azure.Tests/Tests.Bicep.3.json
- tests/PSRule.Rules.Azure.Tests/Tests.Bicep.3.pe.bicep
- Fixed index was out of range with split on mock properties.
Fixes #1327
> Fix split on mock properties #1327

- .gitignore
- docs/CHANGELOG-v1.md
- src/PSRule.Rules.Azure/Common/JsonExtensions.cs
- src/PSRule.Rules.Azure/Common/ResourceHelper.cs
- src/PSRule.Rules.Azure/Common/StringExtensions.cs
- src/PSRule.Rules.Azure/Data/Policy/Models.cs
- src/PSRule.Rules.Azure/Data/Template/Functions.cs
- src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
- src/PSRule.Rules.Azure/PSRule.Rules.Azure.csproj
- tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
- tests/PSRule.Rules.Azure.Tests/PathBuilderTests.cs
- tests/PSRule.Rules.Azure.Tests/ResourceHelperTests.cs
- tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- tests/PSRule.Rules.Azure.Tests/Tests.Bicep.3.bicep
- tests/PSRule.Rules.Azure.Tests/Tests.Bicep.3.json
- tests/PSRule.Rules.Azure.Tests/Tests.Bicep.4.bicep
- tests/PSRule.Rules.Azure.Tests/Tests.Bicep.4.id.bicep
- tests/PSRule.Rules.Azure.Tests/Tests.Bicep.4.json
- tests/PSRule.Rules.Azure.Tests/Tests.Bicep.4.vault.bicep
- Fixed mock objects with no properties. #1347
- Fixed sub-resources nesting by scope regression. #1348
Fixes #1347 
Fixes #1348 
> Fixes for pre-releases #1347 #1348

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.14.0-B2203117:
- Bug fixes:
- Fixed mock objects with no properties. #1347
- Fixed sub-resources nesting by scope regression. #1348
> Pre-release v1.14.0-B2204007

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.14.0-B2204007:
- Engineering:
- Cleanup of additional alias metadata. #1351
> Pre-release v1.14.0-B2204013

- .vscode/settings.json
- Added VSCode settings for PSRule extension to link to documentation.
> Add VSCode settings for docs

- docs/CHANGELOG-v1.md
What's changed since v1.14.0:
- Bug fixes:
- Fixed unable to set parameter defaults option with type object. #1355
> Release v1.14.1

- docs/CHANGELOG-v1.md
- src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
- tests/PSRule.Rules.Azure.Tests/Azure.KeyVault.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.Resource.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Azure.VNET.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Cmdlet.Common.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.Template2.json
- tests/PSRule.Rules.Azure.Tests/Resources.VNET.Template.json
- tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- tests/PSRule.Rules.Azure.Tests/Tests.Bicep.3.bicep
- tests/PSRule.Rules.Azure.Tests/Tests.Bicep.3.blob.bicep
- tests/PSRule.Rules.Azure.Tests/Tests.Bicep.3.json
- Fixed handling of parent resources when sub resource is in a separate deployment.
Fixes #1360
> Fixed resource move for cross module #1360

- docs/CHANGELOG-v1.md
What's changed since v1.14.1:
- Bug fixes:
- Fixed handling of parent resources when sub resource is in a separate deployment. #1360
> Release v1.14.2

- docs/CHANGELOG-v1.md
- docs/en/rules/Azure.Firewall.Mode.md
- docs/examples-firewall.bicep
- docs/examples-firewall.json
- src/PSRule.Rules.Azure/rules/Azure.Firewall.Rule.yaml
- tests/PSRule.Rules.Azure.Tests/Azure.Firewall.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.Firewall.Template.json
- Fixed Azure Firewall threat intel mode reported for Secure VNET hubs.
Fixed #1365
> Fixed Azure Firewall threat intel #1365

- docs/CHANGELOG-v1.md
- src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs
- src/PSRule.Rules.Azure/Data/Template/Functions.cs
- tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
- tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
- tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- tests/PSRule.Rules.Azure.Tests/Tests.Bicep.5.bicep
- tests/PSRule.Rules.Azure.Tests/Tests.Bicep.5.firewall.bicep
- tests/PSRule.Rules.Azure.Tests/Tests.Bicep.5.json
- tests/PSRule.Rules.Azure.Tests/Tests.Bicep.5.vnet.bicep
- Fixed array function handling with mock objects.
Fixes #1367
> Fixed array handling #1367

- docs/CHANGELOG-v1.md
What's changed since v1.14.2:
- Bug fixes:
- Fixed Azure Firewall threat intel mode reported for Secure VNET hubs. #1365
- Fixed array function handling with mock objects. #1367
> Release v1.14.3

- GitVersion.yml
- Added GitVersion config file.
> Added GitVersion config

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/workflows/analyze.yaml
- .vscode/markdown.code-snippets
- .vscode/yaml.code-snippets
- CONTRIBUTING.md
- README.md
- Minor updates to repository files.
> Repository file updates

- pipeline.build.ps1
- scripts/dependencies.psm1
- Update CI to install a specific dependency version.
> Install specific dependency version

- docs/CHANGELOG-v1.md
- docs/en/rules/Azure.AKS.Version.md
- docs/examples-aks.bicep
- docs/examples-aks.json
- src/PSRule.Rules.Azure/rules/Config.Rule.yaml
- tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1
- tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json
- tests/PSRule.Rules.Azure.Tests/Resources.AKS.json
- tests/PSRule.Rules.Azure.Tests/ps-rule-options.yaml
- tests/PSRule.Rules.Azure.Tests/ps-rule-options2.yaml
- Update Azure.AKS.Version to 1.22.6.
Fixes #1386
> Update Azure.AKS.Version to 1.22.6 #1386

- docs/CHANGELOG-v1.md
What's changed since v1.14.3:
- Updated `Azure.AKS.Version` to use latest stable version `1.22.6`. #1386
- Engineering:
- Added code signing of module. #1379
- Added SBOM manifests to module. #1380
- Bug fixes:
- Fixed dependency chain order when dependsOn copy. #1381
> Pre-release v1.15.0-B0022
