pipeline.build.ps1
Fix CI bug with no deps manifest.
=> Fix no deps CI bug

docs/CHANGELOG-v1.md
What's changed since pre-release v1.15.0-B0022:
- **Important change**: Added `Azure.Resource.SupportsTags` selector. #1339
- Use this selector in custom rules to filter rules to only run against resources that support tags.
- This selector replaces the `SupportsTags` PowerShell function.
- Using the `SupportsTag` function will now result in a warning.
- The `SupportsTags` function will be removed in v2.
- Engineering:
- Embedded provider and alias information as manifest resources. #1383
- Resources are minified and compressed to improve size and speed.
- Added additional `nodeps` manifest that does not include dependencies for Az modules. #1392
- Bump Az.Accounts to 2.7.6. #1338
- Bump Az.Resources to 5.6.0. #1338
- Bump PSRule to 2.1.0. #1338
- Bump Pester to 5.3.3. …
=> Pre-release v1.15.0-B0053

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/rules/Azure.Redis.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.Redis.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.Redis.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.Redis.json
- Fixed cannot bind argument to parameter 'Sku' because it is an empty string.
Fixes #1407
=> Fixed Azure.Redis.MaxMemoryReserved #1407

.github/workflows/docs.yaml, docs/integrations.md, mkdocs.yml
- Updated docs to reference AzGovViz as an integration using PSRule for Azure.
=> Add a link to AzGovViz

.vscode/settings.json, docs/creating-your-pipeline.md, docs/setup/setup-azure-monitor-logs.md, docs/using-bicep.md
- Added docs to provide examples for working with a bicep private registry.
=> Update bicep registry docs

docs/CHANGELOG-v1.md
What's changed since v1.15.2:
- New rules:
- App Service:
- Check web apps have insecure FTP disabled by @BernieWhite.
#1436
- Check web apps use a dedicated health probe by @BernieWhite.
#1437
- Engineering:
- Bump Microsoft.NET.Test.Sdk to v17.2.0.
#1410
- Bug fixes:
- Fixed `Azure.Template.UseVariables` does not accept function variables names by @BernieWhite.
#1427
=> Pre-release v1.16.0-B0017

.ps-rule/Rule.Rule.ps1, docs/CHANGELOG-v1.md, docs/assets/stylesheets/extra.css, docs/en/rules/metadata.json, docs/hooks.py, mkdocs.yml, pipeline.build.ps1, src/PSRule.Rules.Azure/rules/Azure.ACR.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.ACR.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.ADX.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.ADX.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.APIM.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.APIM.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.AppConfig.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.AppGw.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.AppGw.Rule.yaml
- Updated built documentation to include rule ref and metadata. #1432
- Added ref properties for several rules. #1430
Fixes #1432 
=> Added ref and doc updates #1432 #1430

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/PSRule.Rules.Azure.psd1, src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- Fixed dependency issue within Azure Pipelines `AzurePowerShell` task.
- Removed dependency on `Az.Accounts` and `Az.Resources` from manifest.
Pre-install these modules to use export cmdlets.
Fixes #1447 
- [x Change is not breaking
=> Remove dependencies #1447

docs/CHANGELOG-v1.md
What's changed since v1.15.2:
- Bug fixes:
- Fixed dependency issue within Azure Pipelines `AzurePowerShell` task by @BernieWhite. #1447
- Removed dependency on `Az.Accounts` and `Az.Resources` from manifest.
Pre-install these modules to use export cmdlets.
=> Release v1.15.3

README.md, docs/CHANGELOG-v1.md, docs/export-rule-data.md, docs/install-instructions.md, docs/scenarios/azure-pipelines-ci/azure-pipelines-ci.md, docs/scenarios/azure-pipelines-ci/azure-pipelines.yaml, docs/troubleshooting.md, docs/working-with-baselines.md, modules.json, pipeline.build.ps1, src/PSRule.Rules.Azure/PSRule.Rules.Azure.psd1, src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- Fixed dependency issue within Azure Pipelines `AzurePowerShell` task.
- Removed dependency on `Az.Accounts` and `Az.Resources` from manifest.
Pre-install these modules to use export cmdlets.
Fixes #1447
=> Remove Az dependencies #1447

docs/CHANGELOG-v1.md
What's changed since pre-release v1.16.0-B0041:
- Engineering:
- Update CI checks to include required ref property by @BernieWhite.
[#1431](https://github.com/Azure/PSRule.Rules.Azure/issues/1431)
- Added ref properties for rules by @BernieWhite.
[#1430](https://github.com/Azure/PSRule.Rules.Azure/issues/1430)
- Bug fixes:
- Fixed dependency issue within Azure Pipelines `AzurePowerShell` task by @BernieWhite.
[#1447](https://github.com/Azure/PSRule.Rules.Azure/issues/1447)
- Removed dependency on `Az.Accounts` and `Az.Resources` from manifest.
Pre-install these modules to use export cmdlets.
=> Pre-release v1.16.0-B0072

.vscode/settings.json
- Added additional VSCode settings for branch protection.
=> Added branch protection setting for VSCode

docs/CHANGELOG-v1.md
What's changed since v1.16.0:
- Bug fixes:
- Fixed TLS 1.3 support in `Azure.AppGw.SSLPolicy` by @BernieWhite.
[#1469](https://github.com/Azure/PSRule.Rules.Azure/issues/1469)
- Fixed Application Gateway referencing a WAF policy by @BernieWhite.
[#1466](https://github.com/Azure/PSRule.Rules.Azure/issues/1466)
=> Release v1.16.1

.vscode/settings.json, PSRule.Rules.Azure.sln, src/PSRule.Common.props, src/PSRule.Rules.Azure.BuildTool/PSRule.Rules.Azure.BuildTool.csproj, src/PSRule.Rules.Azure/PSRule.Rules.Azure-nodeps.psd1, src/PSRule.Rules.Azure/PSRule.Rules.Azure.csproj, src/PSRule.Rules.Azure/PSRule.Rules.Azure.psd1, src/SDK/README.md, src/SDK/SDK.csproj
- Updates to project files for NuGet packaging of module files.
=> Updates to packaging for #1428

pipeline.build.ps1, src/PSRule.Rules.Azure/PSRule.Rules.Azure.csproj
- Update CI and project files for NuGet publishing.
=> Updates for packaging

docs/CHANGELOG-v1.md
- Update change log bug fix for #1505
=> Update change log

docs/CHANGELOG-v1.md
What's changed since pre-release v1.17.0-B0035:
- Engineering:
- Updated provider data for analysis.
[#1502](https://github.com/Azure/PSRule.Rules.Azure/pull/1502)
- Bump PSRule to v2.2.0.
[#1444](https://github.com/Azure/PSRule.Rules.Azure/pull/1444)
- Bug fixes:
- Fixed TDE property status to state by @Dylan-Prins.
[#1505](https://github.com/Azure/PSRule.Rules.Azure/pull/1505)
=> Pre-release v1.17.0-B0064

docs/CHANGELOG-v1.md, src/PSRule.Common.props, src/SDK/SDK.csproj
- Added readme and tags to NuGet.
Fixes #1513.
=> Added readme and tags #1513

docs/CHANGELOG-v1.md, docs/en/rules/Azure.VM.Standalone.md, docs/examples-vm.bicep, docs/examples-vm.json, src/PSRule.Rules.Azure/rules/Azure.VM.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.VM.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.VM.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.VirtualMachine.Template.json
- Fixed missing zones in test for standalone VM.
Fixes #1506 
=> Fixed missing zones in test #1506

docs/CHANGELOG-v1.md
What's changed since v1.17.0:
- Bug fixes:
- Fixed union returns null when merged with built-in expansion objects by @BernieWhite.
[#1515](https://github.com/Azure/PSRule.Rules.Azure/issues/1515)
- Fixed missing zones in test for standalone VM by @BernieWhite.
[#1506](https://github.com/Azure/PSRule.Rules.Azure/issues/1506)
=> Release v1.17.1

docs/CHANGELOG-v1.md, docs/en/rules/Azure.VM.Standalone.md, docs/examples-vm.bicep, docs/examples-vm.json, src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs, src/PSRule.Rules.Azure/Data/Template/Functions.cs, src/PSRule.Rules.Azure/rules/Azure.VM.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.VM.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.VM.Tests.ps1, tests/PSRule.Rules.Azure.Tests/FunctionTests.cs, tests/PSRule.Rules.Azure.Tests/Resources.VirtualMachine.Template.json
- Merge changes from patch release v1.17.1.
=> Merge changes from v1.17.1

docs/CHANGELOG-v1.md
What's changed since v1.17.1:
- Engineering:
- Added readme and tags to NuGet by @BernieWhite.
[#1513](https://github.com/Azure/PSRule.Rules.Azure/issues/1513)
=> Pre-release v1.18.0-B0002

mkdocs.yml, requirements-docs.txt
- Added `mdx-truly-sane-lists` module back after mkdocs patch.
=> Fix doc lists

docs/CHANGELOG-v1.md, docs/en/baselines/Azure.All.md, docs/en/baselines/Azure.Default.md, docs/en/baselines/Azure.GA_2020_06.md, docs/en/baselines/Azure.GA_2020_09.md, docs/en/baselines/Azure.GA_2020_12.md, docs/en/baselines/Azure.GA_2021_03.md, docs/en/baselines/Azure.GA_2021_06.md, docs/en/baselines/Azure.GA_2021_09.md, docs/en/baselines/Azure.GA_2021_12.md, docs/en/baselines/Azure.GA_2022_03.md, docs/en/baselines/Azure.GA_2022_06.md, docs/en/baselines/Azure.Preview.md, docs/en/rules/Azure.Cognitive.DisableLocalAuth.md, docs/en/rules/Azure.Cognitive.ManagedIdentity.md, docs/en/rules/Azure.Cognitive.PrivateEndpoints.md, docs/en/rules/Azure.Cognitive.PublicAccess.md, docs/en/rules/module.md, docs/en/rules/resource.md, docs/examples-cognitive.bicep, docs/examples-cognitive.json, src/PSRule.Rules.Azure/rules/Azure.Cognitive.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.EventGrid.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.Cognitive.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.Cognitive.json, tests/PSRule.Rules.Azure.Tests/cognitive.tests.bicep, tests/PSRule.Rules.Azure.Tests/cognitive.tests.json
- Check accounts use network access restrictions.
- Check accounts use managed identities to access Azure resources.
- Check accounts only accept requests using Azure AD identities.
- Check accounts disable access using public endpoints.
Fixes #1532 
=> Added cognitve services rules #1532

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs, src/PSRule.Rules.Azure/Data/Template/Functions.cs, src/PSRule.Rules.Azure/Resources/PSRuleResources.Designer.cs, src/PSRule.Rules.Azure/Resources/PSRuleResources.resx, tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
- Added support for `join` ARM function.
Fixes #1535 
=> Added support for join ARM function #1535

README.md, docs/faq.md, docs/features.md, docs/samples.md, docs/support.md, mkdocs.yml, overrides/home.html
=> Updates to docs

docs/CHANGELOG-v1.md
What's changed since pre-release v1.18.0-B0010:
- New rules:
- Cognitive Services:
- Check accounts use network access restrictions by @BernieWhite.
[#1532](https://github.com/Azure/PSRule.Rules.Azure/issues/1532)
- Check accounts use managed identities to access Azure resources by @BernieWhite.
[#1532](https://github.com/Azure/PSRule.Rules.Azure/issues/1532)
- Check accounts only accept requests using Azure AD identities by @BernieWhite.
[#1532](https://github.com/Azure/PSRule.Rules.Azure/issues/1532)
- Check accounts disable access using public endpoints by @BernieWhite.
[#1532](https://github.com/Azure/PSRule.Rules.Azure/issues/1532)
- Added support for array `indexOf`, `lastIndexOf`, and `items` ARM functions by @BernieWhite. …
=> Pre-release v1.18.0-B0027

docs/CHANGELOG-v1.md
What's changed since v1.17.1:
- New rules:
- Cognitive Services:
- Check accounts use network access restrictions by @BernieWhite.
[#1532](https://github.com/Azure/PSRule.Rules.Azure/issues/1532)
- Check accounts use managed identities to access Azure resources by @BernieWhite.
[#1532](https://github.com/Azure/PSRule.Rules.Azure/issues/1532)
- Check accounts only accept requests using Azure AD identities by @BernieWhite.
[#1532](https://github.com/Azure/PSRule.Rules.Azure/issues/1532)
- Check accounts disable access using public endpoints by @BernieWhite.
[#1532](https://github.com/Azure/PSRule.Rules.Azure/issues/1532)
- Added support for array `indexOf`, `lastIndexOf`, and `items` ARM functions by @BernieWhite. …
=> Release v1.18.0

docs/CHANGELOG-v1.md, src/PSRule.Common.props, src/PSRule.Rules.Azure/PSRule.Rules.Azure.csproj, src/SDK/SDK.csproj
- Added publishing of symbols for NuGet packages.
Fixes #1549
=> Added NuGet symbols #1549

.vscode/tasks.json, RuleToc.Doc.ps1, docs/CHANGELOG-v1.md, docs/en/rules/index.md, docs/en/rules/module.md, docs/en/rules/resource.md, docs/faq.md, docs/hooks.py, mkdocs.yml, pipeline.build.ps1, src/PSRule.Rules.Azure/rules/Azure.APIM.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.Template.Rule.ps1
- Updated rule level for the following rules:
- Set `Azure.APIM.APIDescriptors` to warning from error.
- Set `Azure.APIM.ProductDescriptors` to warning from error.
- Set `Azure.Template.UseLocationParameter` to warning from error.
- Set `Azure.Template.UseComments` to information from error.
- Set `Azure.Template.UseDescriptions` to information from error.
- Updates documentation to show levels and reference index.
Fixes #1551
=> Update rule level for specific cases #1551

README.md, RuleToc.Doc.ps1, docs/concepts/about_PSRule_Azure_Configuration.md, docs/creating-your-pipeline.md, docs/customization/enforce-custom-tags.md, docs/features.md, docs/install-instructions.md, docs/setup/setup-azure-monitor-logs.md, docs/troubleshooting.md, docs/using-bicep.md, docs/using-templates.md, docs/working-with-baselines.md, mkdocs.yml
- Improvements to documentation.
=> Improvements to documentation

docs/CHANGELOG-v1.md, docs/en/rules/Azure.APIM.HTTPBackend.md, src/PSRule.Rules.Azure/rules/Azure.APIM.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.APIM.Tests.ps1, tests/PSRule.Rules.Azure.Tests/apim.tests.bicep, tests/PSRule.Rules.Azure.Tests/apim.tests.json
- Fixed `Azure.APIM.HTTPBackend` reports failure when service URL is not defined.
Fixes #1555
=> Fixes backend failure with empty service URL #1555

.markdownlint.json, docs/CHANGELOG-v1.md, docs/en/rules/Azure.SQL.AAD.md, docs/examples-sql.bicep, docs/examples-sql.json, src/PSRule.Rules.Azure/Runtime/Helper.cs, src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.SQL.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.SQL.Tests.ps1, tests/PSRule.Rules.Azure.Tests/sql.tests.bicep, tests/PSRule.Rules.Azure.Tests/sql.tests.json
- Fixed `Azure.SQL.AAD` failure with newer API.
Fixes #1302 
=> Fixes Azure.SQL.AAD with newer API #1302

docs/CHANGELOG-v1.md
What's changed since v1.18.0:
- Bug fixes:
- Fixed `Azure.APIM.HTTPBackend` reports failure when service URL is not defined by @BernieWhite.
[#1555](https://github.com/Azure/PSRule.Rules.Azure/issues/1555)
- Fixed `Azure.SQL.AAD` failure with newer API by @BernieWhite.
[#1302](https://github.com/Azure/PSRule.Rules.Azure/issues/1302)
=> Release v1.18.1

docs/setup/setup-azure-monitor-logs.md
=> Added sample KQL queries for Azure Monitor logs

RuleToc.Doc.ps1, docs/en/rules/index.md, docs/en/rules/module.md
- Added additional information about preview rules to reference landing page in docs.
=> Added rule preview information block

.vscode/settings.json, docs/CHANGELOG-v1.md, docs/en/rules/Azure.ACR.ContainerScan.md, src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.ACR.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.ADX.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.AppGw.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.AppGw.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.AppInsights.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.AppService.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.AppService.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.Automation.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.Automation.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.CDN.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1, src/PSRule.Rules.Azure/rules/Common.Selector.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.ACR.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Azure.ADX.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Azure.ASG.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Azure.AppConfig.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Azure.AppGw.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Azure.AppInsights.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Azure.AppService.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Azure.Automation.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Azure.CDN.Tests.ps1
- This update improves the property path PSRule uses for reporting failures. This is part 1.
Related to #1429
=> Improve path reporting #1429

docs/CHANGELOG-v0.md, docs/CHANGELOG-v1.md, docs/about.md, docs/deprecations.md, docs/en/rules/index.md, docs/features.md, docs/hooks.py, docs/integrations.md, docs/license-contributing.md, docs/related-projects.md, docs/samples.md, docs/support.md, docs/troubleshooting.md, docs/upgrade-notes.md, mkdocs.yml, overrides/main.html, overrides/partials/giscus.html, overrides/reference.html, pipeline.build.ps1
Added comment system to pages.
=> Added Giscus comment system to pages

docs/creating-your-pipeline.md
=> Add minor doc updates

docs/creating-your-pipeline.md, docs/expanding-source-files.md, docs/export-rule-data.md, docs/hooks.py, docs/setup/setup-bicep.md, docs/troubleshooting.md, docs/using-bicep.md, docs/using-templates.md, docs/validating-locally.md, mkdocs.yml
- Updates to troubleshooting docs and links.
=> Updates to troubleshooting docs

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Common/JsonExtensions.cs, src/PSRule.Rules.Azure/Common/StringExtensions.cs, src/PSRule.Rules.Azure/Data/Template/ResourceValue.cs, src/PSRule.Rules.Azure/Data/Template/RuleDataExportVisitor.cs, src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs, src/PSRule.Rules.Azure/Pipeline/PathBuilder.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.8.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.8.blob.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.8.json, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.8.storage.bicep
- Fixed handling of storage accounts sub-resources with CMK.
Fixes #1575 
=> Fixes storage account CMK with sub-resources #1575

src/PSRule.Rules.Azure/Configuration/ConfigurationOption.cs, src/PSRule.Rules.Azure/Configuration/DeploymentOption.cs, src/PSRule.Rules.Azure/Configuration/ManagementGroupOption.cs, src/PSRule.Rules.Azure/Configuration/OutputOption.cs, src/PSRule.Rules.Azure/Configuration/PSRuleOption.cs, src/PSRule.Rules.Azure/Configuration/ParameterDefaultsOption.cs, src/PSRule.Rules.Azure/Configuration/ResourceGroupOption.cs, src/PSRule.Rules.Azure/Configuration/SubscriptionOption.cs, src/PSRule.Rules.Azure/Configuration/TenantOption.cs
- Updates to improve API documentation within public classes and interfaces.
=> Updates to API documentation

docs/CHANGELOG-v1.md
What's changed since pre-release v1.19.0-B0010:
- Improve reporting of failing resource property for rules by @BernieWhite.
[#1429](https://github.com/Azure/PSRule.Rules.Azure/issues/1429)
- Engineering:
- Bump PSRule to v2.3.2.
[#1574](https://github.com/Azure/PSRule.Rules.Azure/pull/1574)
- Bump support projects to .NET 6 by @BernieWhite.
[#1560](https://github.com/Azure/PSRule.Rules.Azure/issues/1560)
- Bump BenchmarkDotNet to v0.13.2.
[#1593](https://github.com/Azure/PSRule.Rules.Azure/pull/1593)
- Bump BenchmarkDotNet.Diagnostics.Windows to v0.13.2.
[#1594](https://github.com/Azure/PSRule.Rules.Azure/pull/1594)
- Updated provider data for analysis.
[#1598](https://github.com/Azure/PSRule.Rules.Azure/pull/1598)
- Bug fixes:
- Fixed parameter files linked to …
=> Pre-release v1.19.0-B0042

docs/en/rules/Azure.AKS.UptimeSLA.md, src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.AKS.json
- Added new rule for Azure Kubernetes Service (AKS) Uptime SLA.
Fixes #1601
- This is my first PR in this project. I hope I have done everything right, please reach out if something is not alligned with project and I'll adjust accordingly. 
=> Added Azure.AKS.UptimeSLA rule

docs/CHANGELOG-v1.md
What's changed since v1.19.0:
- Bug fixes:
- Fixed `Azure.VNET.UseNSGs` is missing exceptions by @BernieWhite.
[#1609](https://github.com/Azure/PSRule.Rules.Azure/issues/1609)
- Added exclusions for `RouteServerSubnet` and any subnet with a dedicated HSM delegation.
=> Release v1.19.1

docs/CHANGELOG-v1.md
What's changed since v1.19.1:
- New rules:
- Azure Resources:
- Check that nested deployments securely pass through administrator usernames by @ms-sambell.
[#1479](https://github.com/Azure/PSRule.Rules.Azure/issues/1479)
- Engineering:
- Bump Microsoft.NET.Test.Sdk to v17.3.1.
[#1603](https://github.com/Azure/PSRule.Rules.Azure/pull/1603)
=> Pre-release v1.20.0-B0004

.azure-pipelines/azure-pipelines.yaml
- Updated CI pipeline versions.
=> Updated CI versions

data/workbook.json, docs/setup/setup-azure-monitor-logs.md
Creating a sample Azure Workbook which can be used to visualize data published to an Azure Log Analytics workbook (using the native integration). 
=> PSRule for Azure sample Azure workbook

docs/CHANGELOG-v1.md, docs/en/rules/Azure.AKS.Version.md, docs/en/rules/Azure.EventGrid.DisableLocalAuth.md, docs/en/rules/Azure.KeyVault.AutoRotationPolicy.md, src/PSRule.Rules.Azure/rules/Azure.EventGrid.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.KeyVault.Rule.ps1, src/PSRule.Rules.Azure/rules/Config.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json, tests/PSRule.Rules.Azure.Tests/Resources.AKS.json, tests/PSRule.Rules.Azure.Tests/ps-rule-options.yaml, tests/PSRule.Rules.Azure.Tests/ps-rule-options2.yaml
- Updated `Azure.AKS.Version` to use latest stable version `1.23.8`.
- Promoted `Azure.EventGrid.DisableLocalAuth` to GA rule set.
- Promoted `Azure.KeyVault.AutoRotationPolicy` to GA rule set.
Fixes #1627 
Fixes #1628 
Fixes #1629 
=> Promote and update rules #1627 #1628 #1629

docs/CHANGELOG-v1.md
What's changed since v1.19.1:
- Bug fixes:
- Fixed function `dateTimeAdd` errors handling `utcNow` output by @BernieWhite.
[#1637](https://github.com/Azure/PSRule.Rules.Azure/issues/1637)
=> Release v1.19.2

.devcontainer/Dockerfile, .devcontainer/container-build.ps1, .devcontainer/devcontainer.json
- Updated code spaces configuration.
=> Updates to codespaces

NuGet.config
- Added config for NuGet to setup package sources.
=> Add NuGet config

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentHelper.cs, src/PSRule.Rules.Azure/Pipeline/PolicyAssignmentPipeline.cs, src/PSRule.Rules.Azure/Resources/PSRuleResources.Designer.cs, src/PSRule.Rules.Azure/Resources/PSRuleResources.resx
- Fixes continue processing policy assignments on error.
Fixes #1651 
=> Fixed continue processing policy assignments #1651

.ps-rule/Rule.Rule.ps1, docs/en/rules/Azure.AppGw.AvailabilityZone.md, docs/en/rules/Azure.AppGw.MinInstance.md, docs/en/rules/Azure.AppGw.MinSku.md, docs/en/rules/Azure.AppGw.OWASP.md, docs/en/rules/Azure.AppGw.Prevention.md, docs/en/rules/Azure.AppGw.SSLPolicy.md, docs/en/rules/Azure.AppGw.UseHTTPS.md, docs/en/rules/Azure.AppGw.UseWAF.md, docs/en/rules/Azure.AppGw.WAFEnabled.md, docs/en/rules/Azure.AppGw.WAFRules.md, docs/examples-appgw.bicep, docs/examples-appgw.json
Updating the App Gateway docs and adding bicep references.
Issue: [1608](https://github.com/Azure/PSRule.Rules.Azure/issues/1608)
=> Update App Gateway rule docs

docs/en/asb-v3.md, mkdocs.yml
- Added reference documentation for ASB.
=> Add ASB reference docs

CHANGELOG.md, docs/CHANGELOG-v1.md
- Updated change log to add recent changes from hackathon.
=> Updates to change log

docs/CHANGELOG-v1.md, docs/en/rules/Azure.ContainerApp.Insecure.md, src/PSRule.Rules.Azure/rules/Azure.ContainerApp.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Resources.ContainerApp.json
=> Update Container Apps rules to use new resource type

docs/CHANGELOG-v1.md
=> Update CHANGELOG-v1.md for #1667

docs/CHANGELOG-v1.md
=> Updated change log

scripts/security-baseline.ps1
- Added script for exporting security only baseline for BPA.
=> Add script for security only baseline

src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitor.cs, tests/PSRule.Rules.Azure.Tests/PolicyAssignmentVisitorTests.cs
- Further improvements to continue processing policy assignments on error related to #1651.
=> Fixes to further address #1651

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitor.cs, tests/PSRule.Rules.Azure.Tests/PolicyAssignmentVisitorTests.cs
- Fixed handling of runtime assessment data.
Fixes #1707
=> Fix policy export of runtime assessment data #1707

docs/examples-appgw.bicep, docs/examples-appgw.json, docs/examples-frontdoor.bicep, docs/examples-frontdoor.json
- Added bicep examples for building docs.
=> Additional WAF examples

docs/CHANGELOG-v1.md, docs/en/rules/Azure.ASG.Name.md, docs/en/rules/Azure.AppConfig.DisableLocalAuth.md, docs/en/rules/Azure.AppConfig.Name.md, docs/en/rules/Azure.AppConfig.SKU.md, docs/en/rules/Azure.NSG.AnyInboundSource.md, docs/en/rules/Azure.NSG.Associated.md, docs/en/rules/Azure.NSG.DenyAllInbound.md, docs/examples-appconfig.bicep, docs/examples-appconfig.json, docs/examples-vnet.bicep, docs/examples-vnet.json, src/PSRule.Rules.Azure/rules/Azure.ASG.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.AppConfig.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.AppGw.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.EventGrid.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.FrontDoor.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.MySQL.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.PostgreSQL.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.SQL.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.Storage.Rule.yaml
- Additional updates to rule metadata and docs.
=> Additional quality update for rules and docs

docs/CHANGELOG-v1.md
What's changed since pre-release v1.20.0-B0028:
- New rules:
- Check the number of firewall rules for caches by @jonathanruiz.
[#544](https://github.com/Azure/PSRule.Rules.Azure/issues/544)
- Check the number of IP addresses in firewall rules for caches by @jonathanruiz.
[#544](https://github.com/Azure/PSRule.Rules.Azure/issues/544)
- Check identity-based authentication is used for configuration stores by @pazdedav.
[#1691](https://github.com/Azure/PSRule.Rules.Azure/issues/1691)
- Check soft delete policy is enabled by @bengeset96.
[#1674](https://github.com/Azure/PSRule.Rules.Azure/issues/1674)
- Check Microsoft Defender for Cloud is enabled for Containers by @jdewisscher. …
=> Pre-release v1.20.0-B0085

README.md, docs/CHANGELOG-v1.md, docs/en/baselines/Azure.All.md, docs/en/baselines/Azure.Default.md, docs/en/baselines/Azure.GA_2020_06.md, docs/en/baselines/Azure.GA_2020_09.md, docs/en/baselines/Azure.GA_2020_12.md, docs/en/baselines/Azure.GA_2021_03.md, docs/en/baselines/Azure.GA_2021_06.md, docs/en/baselines/Azure.GA_2021_09.md, docs/en/baselines/Azure.GA_2021_12.md, docs/en/baselines/Azure.GA_2022_03.md, docs/en/baselines/Azure.GA_2022_06.md, docs/en/baselines/Azure.Preview.md, docs/en/baselines/Azure.Preview_2021_12.md, docs/en/baselines/Azure.Preview_2022_03.md, docs/en/baselines/Azure.Preview_2022_06.md, docs/en/rules/Azure.NSG.LateralTraversal.md, docs/en/rules/index.md, docs/en/rules/module.md, docs/en/rules/resource.md, docs/features.md, docs/hooks.py, docs/license-contributing/hackathons.md, docs/license-contributing/index.md, docs/license-contributing/writing-documentation.md, mkdocs.yml, overrides/home.html
- Added contributing doc updates and hack page.
=> Added contributing updates

docs/CHANGELOG-v1.md
What's changed since pre-release v1.20.0-B0085:
- New rules:
- Check app configuration store audit diagnostic logs are enabled by @bengeset96.
[#1690](https://github.com/Azure/PSRule.Rules.Azure/issues/1690)
- Engineering:
- Bump Microsoft.NET.Test.Sdk to v17.3.2.
[#1719](https://github.com/Azure/PSRule.Rules.Azure/pull/1719)
- Bug fixes:
- Fixed error expanding with `json()` and single quotes by @BernieWhite.
[#1656](https://github.com/Azure/PSRule.Rules.Azure/issues/1656)
=> Pre-release v1.20.0-B0148

docs/CHANGELOG-v1.md, docs/en/baselines/Azure.All.md, docs/en/baselines/Azure.Default.md, docs/en/baselines/Azure.GA_2022_06.md, docs/en/baselines/Azure.GA_2022_09.md, docs/en/baselines/Azure.Preview.md, docs/en/baselines/Azure.Preview_2022_09.md, docs/en/rules/Azure.Redis.FirewallIPRange.md, docs/en/rules/Azure.Redis.FirewallRuleCount.md, docs/en/rules/index.md, docs/en/rules/module.md, docs/en/rules/resource.md, src/PSRule.Rules.Azure/rules/Baseline.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1
- Added September 2022 baselines.
Fixes #1738 
=> Added September 2022 baselines #1738

docs/CHANGELOG-v1.md
What's changed since pre-release v1.20.0-B0148:
- Added September 2022 baselines `Azure.GA_2022_09` and `Azure.Preview_2022_09` by @BernieWhite.
[#1738](https://github.com/Azure/PSRule.Rules.Azure/issues/1738)
- Includes rules released before or during September 2022.
- Marked `Azure.GA_2022_06` and `Azure.Preview_2022_06` baselines as obsolete.
- New rules:
- Check app configuration store has one or more replicas by @bengeset96.
[#1688](https://github.com/Azure/PSRule.Rules.Azure/issues/1688)
- Engineering:
- Bump PSRule to v2.4.1.
[#1636](https://github.com/Azure/PSRule.Rules.Azure/pull/1636)
- Bump Az.Resources to v6.2.0.
[#1636](https://github.com/Azure/PSRule.Rules.Azure/pull/1636)
- Bump PSScriptAnalyzer to v1.21.0. …
=> Pre-release v1.20.0-B0223

docs/CHANGELOG-v1.md, docs/en/rules/Azure.FrontDoorWAF.Enabled.md, docs/en/rules/Azure.FrontDoorWAF.Exclusions.md, docs/en/rules/Azure.FrontDoorWAF.PreventionMode.md, docs/en/rules/Azure.FrontDoorWAF.RuleGroups.md, docs/examples-frontdoor.bicep, docs/examples-frontdoor.json, src/PSRule.Rules.Azure/rules/Azure.AppGwWAF.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.FrontDoorWAF.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.FrontDoorWAF.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.AppGwWAF.json, tests/PSRule.Rules.Azure.Tests/Resources.FrontDoorWAF.json
- Fixed `Azure.FrontDoorWAF.Exclusions` reports exclusions when none are specified.
Fixes #1751 
=> Fixes Azure.FrontDoorWAF.Exclusions #1751

docs/CHANGELOG-v1.md, docs/en/rules/Azure.Deployment.AdminUsername.md, docs/examples-vm.bicep, docs/examples-vm.json, src/PSRule.Rules.Azure/Data/Template/Functions.cs, src/PSRule.Rules.Azure/Data/Template/TemplateHelper.cs, src/PSRule.Rules.Azure/Data/Template/TokenStream.cs, src/PSRule.Rules.Azure/Data/Template/TokenStreamValidator.cs, src/PSRule.Rules.Azure/Runtime/Helper.cs, src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.Deployment.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.Deployment.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.Deployments.json, tests/PSRule.Rules.Azure.Tests/TokenStreamValidatorTests.cs
- Fixed `Azure.Deployment.AdminUsername` does not match the pattern.
Fixes #1758 
=> Fixes Azure.Deployment.AdminUsername #1758

docs/CHANGELOG-v1.md
What's changed since pre-release v1.20.0-B0223:
- Engineering:
- Bump PSRule to v2.4.2.
[#1753](https://github.com/Azure/PSRule.Rules.Azure/pull/1753)
[#1748](https://github.com/Azure/PSRule.Rules.Azure/issues/1748)
- Bug fixes:
- Fixed `Azure.FrontDoorWAF.Exclusions` reports exclusions when none are specified by @BernieWhite.
[#1751](https://github.com/Azure/PSRule.Rules.Azure/issues/1751)
- Fixed `Azure.Deployment.AdminUsername` does not match the pattern by @BernieWhite.
[#1758](https://github.com/Azure/PSRule.Rules.Azure/issues/1758)
- Consider private offerings when checking that a VM or VMSS has Linux by @verabe.
[#1725](https://github.com/Azure/PSRule.Rules.Azure/issues/1725)
=> Pre-release v1.20.0-B0304

docs/CHANGELOG-v1.md
What's changed since pre-release v1.20.0-B0304:
- New rules:
- Check app configuration store has purge protection enabled by @bengeset96.
[#1689](https://github.com/Azure/PSRule.Rules.Azure/issues/1689)
- Bug fixes:
- Fixed `Azure.Deployment.AdminUsername` incorrectly fails with nested deployments by @BernieWhite.
[#1762](https://github.com/Azure/PSRule.Rules.Azure/issues/1762)
=> Pre-release v1.20.0-B0389

.github/ISSUE_TEMPLATE/bug-report.md, README.md, docs/CHANGELOG-v1.md, docs/creating-your-pipeline.md, docs/install-instructions.md, docs/license-contributing/hackathons.md, docs/setup/setup-azure-monitor-logs.md, docs/troubleshooting.md, docs/using-bicep.md, docs/working-with-baselines.md
What's changed since pre-release v1.19.2:
- Added September 2022 baselines `Azure.GA_2022_09` and `Azure.Preview_2022_09` by @BernieWhite.
[#1738](https://github.com/Azure/PSRule.Rules.Azure/issues/1738)
- Includes rules released before or during September 2022.
- Marked `Azure.GA_2022_06` and `Azure.Preview_2022_06` baselines as obsolete.
- New rules:
- AKS:
- Check clusters use Ephemeral OS disk by @bengeset96.
[#1618](https://github.com/Azure/PSRule.Rules.Azure/issues/1618)
- Check app configuration store has purge protection enabled by @bengeset96.
[#1689](https://github.com/Azure/PSRule.Rules.Azure/issues/1689)
- Check app configuration store has one or more replicas by @bengeset96.
[#1688](https://github.com/Azure/PSRule.Rules.Azure/issues/1688) …
=> Release v1.20.0

src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.VM.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.VM.Rule.yaml
Refactoring of rules to YAML. Related to #1109
=> Convert VM rules to YAML #1109

docs/license-contributing/hackathons.md
=> Updates to hack contrib based on recent merges

docs/CHANGELOG-v1.md
What's changed since pre-release v1.20.0:
- Bug fixes:
- Fixed expand bicep source when reading JsonContent into a parameter by @BernieWhite.
[#1780](https://github.com/Azure/PSRule.Rules.Azure/issues/1780)
=> Release v1.20.1

docs/CHANGELOG-v1.md
What's changed since pre-release v1.21.0-B0011:
- New rules:
- Deployment:
- Check sensitive resource values use secure parameters by @VeraBE @BernieWhite.
[#1773](https://github.com/Azure/PSRule.Rules.Azure/issues/1773)
- Service Bus:
- Check service bus namespaces uses TLS 1.2 version by @bengeset96.
[#1777](https://github.com/Azure/PSRule.Rules.Azure/issues/1777)
=> Pre-release v1.21.0-B0027

docs/CHANGELOG-v1.md, docs/integrations.md
- Update integrations list in docs.
=> Update list of integrations

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.11.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.11.child.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.11.child.child.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.11.json
- Fixed multiple nested parameter loops returns stack empty exception.
Fixes #1811 
=> Fixes nested loops returns stack empty #1811

docs/CHANGELOG-v1.md
What's changed since v1.21.0:
- Bug fixes:
- Fixed multiple nested parameter loops returns stack empty exception by @BernieWhite.
[#1811](https://github.com/Azure/PSRule.Rules.Azure/issues/1811)
- Fixed `Azure.ACR.ContentTrust` when customer managed keys are enabled by @BernieWhite.
[#1810](https://github.com/Azure/PSRule.Rules.Azure/issues/1810)
=> Release v1.21.1

README.md, docs/creating-your-pipeline.md, docs/en/baselines/Azure.All.md, docs/en/baselines/Azure.Default.md, docs/en/baselines/Azure.Preview.md, docs/en/rules/index.md, docs/en/rules/module.md, docs/en/rules/resource.md, docs/es/rules/index.md, docs/es/rules/module.md, docs/es/rules/resource.md, docs/hooks.py, docs/install-instructions.md, docs/setup/setup-azure-monitor-logs.md, docs/troubleshooting.md, docs/using-bicep.md, docs/working-with-baselines.md, mkdocs.yml
- Fix GitHub user links in docs.
=> Fix link_user GitHub links

docs/CHANGELOG-v1.md, docs/en/rules/Azure.ACR.ContentTrust.md, src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs, src/PSRule.Rules.Azure/rules/Azure.ACR.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.ACR.Tests.ps1, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/Resources.ACR.json, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.11.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.11.child.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.11.child.child.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.11.json
Merge patch release v1.21.1:
- Bug fixes:
- Fixed multiple nested parameter loops returns stack empty exception by @BernieWhite.
[#1811](https://github.com/Azure/PSRule.Rules.Azure/issues/1811)
- Fixed `Azure.ACR.ContentTrust` when customer managed keys are enabled by @BernieWhite.
[#1810](https://github.com/Azure/PSRule.Rules.Azure/issues/1810)
Fixes #1811 
Fixes #1810
=> Merge patch release v1.21.1

docs/CHANGELOG-v1.md, docs/en/baselines/Azure.All.md, docs/en/baselines/Azure.Default.md, docs/en/baselines/Azure.Preview.md, docs/en/rules/Azure.NSG.AnyInboundSource.md, docs/en/rules/Azure.VNET.BastionSubnet.md, docs/en/rules/Azure.VNET.FirewallSubnet.md, docs/en/rules/Azure.VNET.LocalDNS.md, docs/en/rules/Azure.VNET.SingleDNS.md, docs/en/rules/index.md, docs/en/rules/module.md, docs/en/rules/resource.md, docs/es/rules/index.md, docs/es/rules/module.md, docs/es/rules/resource.md, docs/examples-vnet.bicep, docs/examples-vnet.json, src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.VNET.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.VNET.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.VNET.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.VirtualNetwork.json
- Check VNETs with a GatewaySubnet also has an AzureFirewallSubnet.
Fixes #875
=> Check for AzureFirewallSubnet #875

docs/CHANGELOG-v1.md
What's changed since v1.21.0:
- New rules:
- App Service Environment:
- Check app service environments uses version 3 (ASEv3) instead of classic version 1 (ASEv1) and version 2 (ASEv2) by @bengeset96.
[#1805](https://github.com/Azure/PSRule.Rules.Azure/issues/1805)
- Front Door:
- Check front door uses caching by @bengeset96.
[#548](https://github.com/Azure/PSRule.Rules.Azure/issues/548)
- Check VNETs with a GatewaySubnet also has an AzureFirewallSubnet by @BernieWhite.
[#875](https://github.com/Azure/PSRule.Rules.Azure/issues/875)
=> Pre-release v1.22.0-B0011

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.VM.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Azure.VMSS.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.VMSS.json, tests/PSRule.Rules.Azure.Tests/Resources.VirtualMachine.json
- Fixed non-Linux VM images flagged as Linux.
Fixes #1825 
=> Fixed non-Linux VM images flagged as Linux #1825

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/CloudEnvironment.cs, src/PSRule.Rules.Azure/Data/Template/Functions.cs, tests/PSRule.Rules.Azure.Tests/FunctionTests.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.12.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.12.child.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.12.json
- Fixed failed to expand with last function on runtime property.
Fixes #1830 
=> Fixes last function on runtime property #1830

docs/CHANGELOG-v1.md
What's changed since v1.21.1:
- Bug fixes:
- Fixed non-Linux VM images flagged as Linux by @BernieWhite.
[#1825](https://github.com/Azure/PSRule.Rules.Azure/issues/1825)
- Fixed failed to expand with last function on runtime property by @BernieWhite.
[#1830](https://github.com/Azure/PSRule.Rules.Azure/issues/1830)
=> Release v1.21.2

docs/CHANGELOG-v1.md, docs/en/rules/Azure.VM.SQLServerDisk.md, src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.VM.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.VM.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.VirtualMachine.json
Fixes #9 
Added Azure.VM.SQLServerDisk rule.
=> Added Azure.VM.SQLServerDisk

docs/CHANGELOG-v1.md, docs/en/rules/Azure.PostgreSQL.GeoRedundantBackup.md, src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.PostgreSQL.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.PostgreSQL.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.PostgreSQL.json
Fixes #285
Added Azure.PostgreSQL.GeoRedundantBackup rule.
=> Added Azure.PostgreSQL.GeoRedundantBackup

.azure-pipelines/azure-pipelines.yaml, .azure-pipelines/jobs/testContainer.yaml, .github/workflows/build.yaml, tests/PSRule.Rules.Azure.Tests/Azure.MySQL.Tests.ps1
- Update CI to use a specific PowerShell image for build.
=> Fix CI PowerShell version

docs/CHANGELOG-v1.md, docs/creating-your-pipeline.md
What's changed since pre-release v1.22.0-B0026:
- New rules:
- Azure Database for MariaDB:
- Check Azure Database for MariaDB servers only uses TLS 1.2 version by @BenjaminEngeset.
[#1853](https://github.com/Azure/PSRule.Rules.Azure/issues/1853)
- Check Azure Database for MariaDB servers only accept encrypted connections by @BenjaminEngeset.
[#1852](https://github.com/Azure/PSRule.Rules.Azure/issues/1852)
- Check Azure Database for MariaDB servers have Microsoft Defender configured by @BenjaminEngeset.
[#1850](https://github.com/Azure/PSRule.Rules.Azure/issues/1850)
- Check Azure Database for MariaDB servers have geo-redundant backup configured by @BenjaminEngeset.
[#1848](https://github.com/Azure/PSRule.Rules.Azure/issues/1848)
- Check Azure Database for …
=> Pre-release v1.22.0-B0062

docs/CHANGELOG-v1.md, pipeline.build.ps1, src/PSRule.Rules.Azure/Data/Policy/PolicyJsonRuleMapper.cs, tests/PSRule.Rules.Azure.Tests/emittedJsonRulesData.jsonc, tests/PSRule.Rules.Azure.Tests/emittedJsonRulesPrefixData.jsonc
- Fixed ref and name duplicated part of #1876.
=> Fixes ref and name duplicated #1876

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentHelper.cs, src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitor.cs, tests/PSRule.Rules.Azure.Tests/Policy.assignment.json, tests/PSRule.Rules.Azure.Tests/PolicyAssignmentVisitorTests.cs
- Fixed an item with the same key for parameters.
Fixes #1871 
=> Fixes an item with the same key parameters #1871

docs/CHANGELOG-v1.md, docs/en/rules/Azure.APIM.MultiRegion.md, src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.APIM.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.APIM.Tests.ps1
Fixes #1030 
Added Azure.APIM.MultiRegion rule.
=> Added Azure.APIM.MultiRegion

docs/CHANGELOG-v1.md
What's changed since pre-release v1.22.0-B0062:
- New rules:
- Check API management instances uses multi-region deployment by @BenjaminEngeset.
[#1030](https://github.com/Azure/PSRule.Rules.Azure/issues/1030)
- Azure Database for MariaDB:
- Check Azure Database for MariaDB servers, databases, firewall rules and VNET rules names meet naming requirements by @BenjaminEngeset.
[#1854](https://github.com/Azure/PSRule.Rules.Azure/issues/1854)
- Engineering:
- Bump PSRule to v2.6.0.
[#1883](https://github.com/Azure/PSRule.Rules.Azure/pull/1883)
- Bump Az.Resources to v6.4.1.
[#1883](https://github.com/Azure/PSRule.Rules.Azure/pull/1883)
- Bug fixes:
- Fixed ref and name duplicated by @BernieWhite.
[#1876](https://github.com/Azure/PSRule.Rules.Azure/issues/1876)
- Fixed an item …
=> Pre-release v1.22.0-B0106

docs/CHANGELOG-v1.md
What's changed since pre-release v1.22.0-B0106:
- Bug fixes:
- Fixed managed identity flagged as secret by `Azure.Deployment.OutputSecretValue` by @BernieWhite.
[#1826](https://github.com/Azure/PSRule.Rules.Azure/issues/1826)
[#1886](https://github.com/Azure/PSRule.Rules.Azure/issues/1886)
=> Pre-release v1.22.0-B0153

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/rules/Conventions.Rule.ps1
- Added additional debug logging improvements to allow troubleshooting of Bicep expansion.
Related to #1901 
=> Added debug logging improvements for Bicep #1901

docs/CHANGELOG-v1.md
What's changed since pre-release v1.22.0-B0153:
- Added debug logging improvements for Bicep expansion by @BernieWhite.
[#1901](https://github.com/Azure/PSRule.Rules.Azure/issues/1901)
- Bug fixes:
- Fixed `Azure.AppService.WebProbe` with non-boolean value set by @BernieWhite.
[#1906](https://github.com/Azure/PSRule.Rules.Azure/issues/1906)
=> Pre-release v1.22.0-B0203

docs/CHANGELOG-v1.md, docs/en/rules/Azure.APIM.MultiRegionGateway.md, src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.APIM.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.APIM.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.APIM.json
Fixes #1910 
Added Azure.APIM.MultiRegionGateway rule.
=> Added Azure.APIM.MultiRegionGateway

docs/CHANGELOG-v1.md, docs/en/rules/Azure.MariaDB.AllowAzureAccess.md, src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.MariaDB.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.MariaDB.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.MariaDB.json
Fixes #1857 
Added Azure.MariaDB.AllowAzureAccess rule.
=> Added Azure.MariaDB.AllowAzureAccess

docs/en/rules/Azure.MariaDB.FirewallRuleCount.md, src/PSRule.Rules.Azure/rules/Azure.MariaDB.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.MariaDB.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.MariaDB.json
Fixes #1855
Added Azure.MariaDB.FirewallRuleCount rule.
=> Added Azure.MariaDB.FirewallRuleCount

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.2.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.2.json
- Fixes template parameter does not use the required format.
Fixes #1930 
=> Fixes template parameters with Bicep v0.13 #1930

docs/CHANGELOG-v1.md, docs/en/rules/Azure.MariaDB.FirewallIPRange.md, src/PSRule.Rules.Azure/rules/Azure.MariaDB.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.MariaDB.Tests.ps1
Fixes #1856
Added Azure.MariaDB.FirewallIPRange rule.
=> Added Azure.MariaDB.FirewallIPRange

docs/CHANGELOG-v1.md
What's changed since v1.22.0:
- Bug fixes:
- Fixes template parameter does not use the required format by @BernieWhite.
[#1930](https://github.com/Azure/PSRule.Rules.Azure/issues/1930)
=> Release v1.22.1

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.2.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.2.json
Merge fix from patch v1.22.1.
- Fixes template parameter does not use the required format.
Fixes #1930
=> Merge fixes from patch v1.22.1

docs/CHANGELOG-v1.md, docs/en/rules/Azure.VM.AMA.md, src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.VM.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.VM.Tests.ps1
Fixes #1868
Added Azure.VM.AMA rule.
=> Added Azure.VM.AMA

docs/CHANGELOG-v1.md
What's changed since v1.22.1:
- New rules:
- Check API management instances has multi-region deployment gateways enabled by @BenjaminEngeset.
[#1910](https://github.com/Azure/PSRule.Rules.Azure/issues/1910)
- Azure Database for MariaDB:
- Check Azure Database for MariaDB servers limits the amount of firewall permitted IP addresses by @BenjaminEngeset.
[#1856](https://github.com/Azure/PSRule.Rules.Azure/issues/1856)
- Check Azure Database for MariaDB servers limits the amount of firewall rules allowed by @BenjaminEngeset.
[#1855](https://github.com/Azure/PSRule.Rules.Azure/issues/1855)
- Check Azure Database for MariaDB servers does not have Azure services bypassed on firewall by @BenjaminEngeset.
[#1857](https://github.com/Azure/PSRule.Rules.Azure/issues/1857)
- Virtual …
=> Pre-release v1.23.0-B0009

docs/CHANGELOG-v1.md, docs/en/rules/Azure.VMSS.AMA.md, src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.VMSS.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.VMSS.Tests.ps1
Fixes #1867
Added Azure.VMSS.AMA rule.
=> Added Azure.VMSS.AMA

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/Functions.cs, tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
- Added support for Bicep flatten.
Working towards #1536 
=> Added support for Bicep flatten #1536

docs/CHANGELOG-v1.md
What's changed since pre-release v1.23.0-B0009:
- New rules:
- Check Application Gateways names meet naming requirements by @BenjaminEngeset.
[#1943](https://github.com/Azure/PSRule.Rules.Azure/issues/1943)
- Check Azure Cache for Redis instances uses Redis 6 by @BenjaminEngeset.
[#1077](https://github.com/Azure/PSRule.Rules.Azure/issues/1077)
- Check virtual machine scale sets has Azure Monitor Agent installed by @BenjaminEngeset.
[#1867](https://github.com/Azure/PSRule.Rules.Azure/issues/1867)
- Added support to export exemptions related to policy assignments by @BernieWhite.
[#1888](https://github.com/Azure/PSRule.Rules.Azure/issues/1888)
- Added support for Bicep `flatten` function by …
=> Pre-release v1.23.0-B0025

docs/CHANGELOG-v1.md
What's changed since v1.22.1:
- Bug fixes:
- Fixed `Azure.Deployment.SecureValue` with `reference` function expression by @BernieWhite.
[#1882](https://github.com/Azure/PSRule.Rules.Azure/issues/1882)
=> Release v1.22.2

docs/CHANGELOG-v1.md, docs/en/rules/Azure.AppGw.Name.md, docs/en/rules/Azure.Redis.Version.md, modules.json, src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.AppGw.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.Redis.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.AppGw.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Azure.Redis.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.Redis.json
Merge fixes from patch v1.22.2.
- Fixed `Azure.Deployment.SecureValue` with `reference` function expression.
Fixes #1882
=> Merge patch v1.22.2

README.md, docs/en/baselines/Azure.All.md, docs/en/baselines/Azure.Default.md, docs/en/baselines/Azure.Preview.md, docs/en/rules/Azure.RSV.ReplicationAlert.md, docs/en/rules/Azure.RSV.StorageType.md, docs/en/rules/Azure.VMSS.PublicKey.md, docs/en/rules/index.md, docs/en/rules/module.md, docs/en/rules/resource.md, docs/es/rules/index.md, docs/es/rules/module.md, docs/es/rules/resource.md, docs/features.md, overrides/home.html
=> Update rule docs

docs/CHANGELOG-v1.md
What's changed since pre-release v1.23.0-B0025:
- New rules:
- Bastion:
- Check Bastion hosts names meet naming requirements by @BenjaminEngeset.
[#1950](https://github.com/Azure/PSRule.Rules.Azure/issues/1950)
- Recovery Services Vault:
- Check Recovery Services vaults names meet naming requirements by @BenjaminEngeset.
[#1953](https://github.com/Azure/PSRule.Rules.Azure/issues/1953)
- Bug fixes:
- Fixed `Azure.Deployment.SecureValue` with `reference` function expression by @BernieWhite.
[#1882](https://github.com/Azure/PSRule.Rules.Azure/issues/1882)
=> Pre-release v1.23.0-B0046

docs/CHANGELOG-v1.md, docs/creating-your-pipeline.md, docs/en/baselines/Azure.All.md, docs/en/baselines/Azure.Default.md, docs/en/baselines/Azure.GA_2022_12.md, docs/en/baselines/Azure.Preview.md, docs/en/baselines/Azure.Preview_2022_12.md, docs/en/rules/Azure.AKS.CNISubnetSize.md, docs/en/rules/Azure.AKS.ContainerInsights.md, docs/en/rules/Azure.AKS.EphemeralOSDisk.md, docs/en/rules/Azure.AKS.ManagedIdentity.md, docs/en/rules/Azure.AKS.Version.md, docs/en/rules/index.md, docs/en/rules/module.md, docs/en/rules/resource.md, docs/es/rules/index.md, docs/es/rules/module.md, docs/es/rules/resource.md, docs/examples-aks.bicep, docs/working-with-baselines.md, src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.yaml, src/PSRule.Rules.Azure/rules/Baseline.Rule.yaml, src/PSRule.Rules.Azure/rules/Config.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json, tests/PSRule.Rules.Azure.Tests/Resources.AKS.json, tests/PSRule.Rules.Azure.Tests/ps-rule-options.yaml, tests/PSRule.Rules.Azure.Tests/ps-rule-options2.yaml
- Added December 2022 baselines `Azure.GA_2022_12` and `Azure.Preview_2022_12`.
- Updated `Azure.AKS.Version` to use latest stable version `1.25.4`.
Fixes #1960 
Fixes #1961 
=> Updated AKS version and baselines #1961 #1960

docs/creating-your-pipeline.md, docs/setup/configuring-options.md, docs/setup/configuring-rules.md, docs/troubleshooting.md, docs/upgrade-notes.md
Added docs information for continue on error of pipeline.
Fixes #1933
=> Add continue on error for pipeline docs #1933

src/PSRule.Rules.Azure/Common/TaskExtensions.cs, src/PSRule.Rules.Azure/Data/CloudEnvironment.cs, src/PSRule.Rules.Azure/Data/Metadata/ITemplateLink.cs, src/PSRule.Rules.Azure/Data/Network/NetworkSecurityGroupEvaluator.cs, src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitor.cs, src/PSRule.Rules.Azure/Data/ResourceProvider.cs, src/PSRule.Rules.Azure/Data/Template/Functions.cs, src/PSRule.Rules.Azure/Pipeline/PolicyAssignmentSearchPipeline.cs, src/PSRule.Rules.Azure/Pipeline/ResourceDataPipeline.cs
=> Code quality updates

src/PSRule.Rules.Azure/Data/Template/Exceptions.cs
Improved inline class documentation of code.
=> Improved code docs

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs, src/PSRule.Rules.Azure/Data/Template/Functions.cs, src/PSRule.Rules.Azure/Data/Template/RuleDataExportVisitor.cs, src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs, tests/PSRule.Rules.Azure.Tests/ExpressionHelpersTests.cs, tests/PSRule.Rules.Azure.Tests/ExpressionParserTests.cs, tests/PSRule.Rules.Azure.Tests/FunctionTests.cs, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.8.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.8.json
- Fixed failed to expand nested deployment with runtime shallow parameter.
Fixes #2004 
=> Fixes expand of runtime shallow param #2004

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitor.cs, src/PSRule.Rules.Azure/Data/Template/TokenStream.cs, tests/PSRule.Rules.Azure.Tests/PolicyAssignmentVisitorTests.cs
- Fixed simple cases for field type expressions.
Progress towards #1323 
=> Fixes for simple field cases #1323

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Common/JsonExtensions.cs, src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitor.cs, tests/PSRule.Rules.Azure.Tests/PolicyAssignmentVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/emittedJsonRulesData.jsonc
- Added optimization for policy type conditions.
Fixes #1966 
=> Optimize policy type conditions #1966

docs/CHANGELOG-v1.md
What's changed since pre-release v1.24.0-B0013:
- Added support for Bicep lambda functions by @BernieWhite.
[#1536](https://github.com/Azure/PSRule.Rules.Azure/issues/1536)
- Bicep `filter`, `map`, `reduce`, and `sort` are supported.
- Support for `flatten` was previously added in v1.23.0.
- Added optimization for policy type conditions by @BernieWhite.
[#1966](https://github.com/Azure/PSRule.Rules.Azure/issues/1966)
- Engineering:
- Updated resource providers and policy aliases.
[#1736](https://github.com/Azure/PSRule.Rules.Azure/pull/1736)
- Bug fixes:
- Fixed failed to expand nested deployment with runtime shallow parameter by @BernieWhite.
[#2004](https://github.com/Azure/PSRule.Rules.Azure/issues/2004)
- Fixed `apiVersion` comparison of `requestContext` by …
=> Pre-release v1.24.0-B0035

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Common/JsonExtensions.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.15.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.15.json
- Fixes Bicep expand object or null.
Fixes #2021 
=> Fixes Bicep expand object or null #2021

docs/CHANGELOG-v1.md
What's changed since v1.24.0:
- Bug fixes:
- Fixes Bicep expand object or null by @BernieWhite.
[#2021](https://github.com/Azure/PSRule.Rules.Azure/issues/2021)
=> Release v1.24.1

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Common/JsonExtensions.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.15.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.15.json
Merge bug fixes from v1.24.1.
- Bug fixes:
- Fixes Bicep expand object or null by @BernieWhite.
[#2021](https://github.com/Azure/PSRule.Rules.Azure/issues/2021)
Fixes #2021
=> Merge bug fixes from v1.24.1

.azure-pipelines/pipeline-deps.ps1, .github/workflows/analyze.yaml, .github/workflows/build.yaml, ps-rule.yaml
=> Update GitHub Actions build CI

docs/about.md, docs/creating-your-pipeline.md, docs/faq.md, docs/learn/learn-video-series.md, mkdocs.yml
- Added learn links to video series.
- Updates to FAQ.
Progress towards #1261
=> Added learn and FAQ updates

README.md, docs/about.md, docs/features.md, overrides/home.html
- Update feature, about, and readme docs.
=> Updated feature docs

docs/setup/setup-bicep.md, docs/using-bicep.md
- Update to docs relating to Bicep private registries.
=> Updated private registry docs

docs/learn/offical.md, docs/learn/official.md, mkdocs.yml
- Added links for official blog posts to docs.
=> Added official blog posts

docs/CHANGELOG-v1.md
What's changed since v1.24.1:
- Added `Azure.MCSB.v1` which include rules aligned to the Microsoft Cloud Security Benchmark by @BernieWhite.
[#1634](https://github.com/Azure/PSRule.Rules.Azure/issues/1634)
- New rules:
- Virtual machines should be fully deallocated and not stopped by @dcrreynolds.
[#88](https://github.com/Azure/PSRule.Rules.Azure/issues/88)
- Added support for Bicep custom types by @BernieWhite.
[#2026](https://github.com/Azure/PSRule.Rules.Azure/issues/2026)
- Engineering:
- Updated build to use GitHub Actions by @BernieWhite.
[#1696](https://github.com/Azure/PSRule.Rules.Azure/issues/1696)
- Bump BenchmarkDotNet to v0.13.4.
[#1992](https://github.com/Azure/PSRule.Rules.Azure/pull/1992)
- Bump …
=> Pre-release v1.25.0-B0013

docs/CHANGELOG-v1.md
Merge the updated change log for v1.24.2.
=> Merge change log for v1.24.2

.vscode/settings.json, BaselineToc.Doc.ps1, docs/CHANGELOG-v1.md, docs/en/baselines/Azure.All.md, docs/en/baselines/Azure.Default.md, docs/en/baselines/Azure.GA_2022_09.md, docs/en/baselines/Azure.GA_2022_12.md, docs/en/baselines/Azure.MCSB.v1.md, docs/en/baselines/Azure.Preview.md, docs/en/mcsb-v1.md, docs/en/rules/Azure.Defender.Arm.md, docs/en/rules/Azure.Defender.Containers.md, docs/en/rules/Azure.Defender.Dns.md, docs/en/rules/Azure.Defender.KeyVault.md, docs/en/rules/Azure.Defender.SQL.md, docs/en/rules/Azure.Defender.SQLOnVM.md, docs/en/rules/index.md, docs/en/rules/module.md, docs/en/rules/resource.md, docs/es/rules/index.md, docs/es/rules/module.md, docs/es/rules/resource.md, docs/examples-defender.bicep, docs/hooks.py, docs/working-with-baselines.md, src/PSRule.Rules.Azure/rules/Azure.Defender.Rule.yaml, src/PSRule.Rules.Azure/rules/MCSB.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.Defender.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.Defender.json
- Check Microsoft Defender for Key Vault is enabled.
- Check Microsoft Defender for DNS is enabled.
- Check Microsoft Defender for ARM is enabled.
Release to #1632
=> Added rules for Defender for Cloud #1632

docs/CHANGELOG-v1.md
What's changed since pre-release v1.25.0-B0013:
- New rules:
- Check Microsoft Defender for Key Vault is enabled by @BernieWhite.
[#1632](https://github.com/Azure/PSRule.Rules.Azure/issues/1632)
- Check Microsoft Defender for DNS is enabled by @BernieWhite.
[#1632](https://github.com/Azure/PSRule.Rules.Azure/issues/1632)
- Check Microsoft Defender for ARM is enabled by @BernieWhite.
[#1632](https://github.com/Azure/PSRule.Rules.Azure/issues/1632)
- Added support for configuring a minimum version of Bicep by @BernieWhite.
[#1935](https://github.com/Azure/PSRule.Rules.Azure/issues/1935)
- Configure this option to increase the visibility of the version of the Bicep CLI used by PSRule for Azure.
- Set `AZURE_BICEP_CHECK_TOOL` to `true` to check …
=> Pre-release v1.25.0-B0035

docs/en/rules/Azure.AppGw.SSLPolicy.md
Improve example code and a more detailed description. 
Fixes #2063
=> improve tls recommendation doc

docs/CHANGELOG-v1.md
What's changed since pre-release v1.25.0-B0035:
- Added support for Bicep `toObject` function by @BernieWhite.
[#2014](https://github.com/Azure/PSRule.Rules.Azure/issues/2014)
- Engineering:
- Bump BenchmarkDotNet to v0.13.5.
[#2052](https://github.com/Azure/PSRule.Rules.Azure/pull/2052)
- Bump BenchmarkDotNet.Diagnostics.Windows to v0.13.5.
[#2052](https://github.com/Azure/PSRule.Rules.Azure/pull/2052)
- Bump Microsoft.NET.Test.Sdk to v17.5.0.
[#2055](https://github.com/Azure/PSRule.Rules.Azure/pull/2055)
- Bug fixes:
- Fixed SQL transparent data Encryption (TDE) works properly on all resources including exported resources by @zilberd.
[#2059](https://github.com/Azure/PSRule.Rules.Azure/issues/2059)
=> Pre-release v1.25.0-B0065

docs/CHANGELOG-v1.md
What's changed since pre-release v1.25.0-B0065:
- New rules:
- Key Vault:
- Check if firewall is set to deny by @zilberd.
[#2067](https://github.com/Azure/PSRule.Rules.Azure/issues/2067)
=> Pre-release v1.25.0-B0100

docs/CHANGELOG-v1.md, docs/en/rules/Azure.IoTHub.MinTLS.md, src/PSRule.Rules.Azure/rules/Azure.IoTHub.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.IoTHub.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.IoTHub.json
Fixes #1996 
Added Azure.IoTHub.MinTLS rule.
=> Added Azure.IoTHub.MinTLS

docs/CHANGELOG-v1.md, docs/en/rules/Azure.ServiceBus.AuditLogs.md, src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.ServiceBus.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.ServiceBus.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.ServiceBus.json
Fixes #1862
Added Azure.ServiceBus.AuditLogs rule.
=> Added Azure.ServiceBus.AuditLogs

docs/CHANGELOG-v1.md, docs/en/rules/Azure.Deployment.Name.md, src/PSRule.Rules.Azure/rules/Azure.Deployment.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.Deployment.Tests.ps1
Fixes #1915
Added Azure.Deployment.Name rule.
Covers nested and linked templates.
=> Added Azure.Deployment.Name

docs/CHANGELOG-v1.md, docs/en/rules/Azure.ContainerApp.ManagedIdentity.md, src/PSRule.Rules.Azure/rules/Azure.ContainerApp.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.ContainerApp.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.ContainerApp.json
Fixes #2096 
Added Azure.ContainerApp.ManagedIdentity rule.
=> Added Azure.ContainerApp.ManagedIdentity

docs/CHANGELOG-v1.md, docs/en/rules/Azure.ContainerApp.Name.md, src/PSRule.Rules.Azure/rules/Azure.ContainerApp.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.ContainerApp.Tests.ps1
Fixes #2094 
Added Azure.ContainerApp.Name rule.
=> Added Azure.ContainerApp.Name

docs/CHANGELOG-v1.md
What's changed since v1.25.0:
- New rules:
- Check that the names of container apps meets the naming requirements by @BenjaminEngeset.
[#2094](https://github.com/Azure/PSRule.Rules.Azure/issues/2094)
- Check that managed identity for container apps are configured by @BenjaminEngeset.
[#2096](https://github.com/Azure/PSRule.Rules.Azure/issues/2096)
- Check that public network access for container apps environments are disabled by @BenjaminEngeset.
[#2098](https://github.com/Azure/PSRule.Rules.Azure/issues/2098)
- Deployment:
- Check that the names of nested deployments meets the naming requirements of deployments by @BenjaminEngeset.
[#1915](https://github.com/Azure/PSRule.Rules.Azure/issues/1915)
- IoT Hub:
- Check IoT Hubs in supported regions only uses TLS 1.2 version …
=> Pre-release v1.26.0-B0011

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Common/ResourceHelper.cs, src/PSRule.Rules.Azure/Data/Template/Functions.cs, src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs, src/PSRule.Rules.Azure/Pipeline/ResourceDataPipeline.cs, tests/PSRule.Rules.Azure.Tests/FunctionTests.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.17.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.17.json, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.17.kv.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.17.ws.bicep
- Fixed dependency issue of deployments across resource group scopes.
Fixes #2111 
=> Fixes deployment dependency across scope #2111

docs/CHANGELOG-v1.md
What's changed since v1.25.0:
- Bug fixes:
- Fixed dependency issue of deployments across resource group scopes by @BernieWhite.
[#2111](https://github.com/Azure/PSRule.Rules.Azure/issues/2111)
=> Release v1.25.1

docs/en/rules/Azure.KeyVault.Firewall.md
- Minor updates to Azure.KeyVault.Firewall docs.
=> Minor update to Azure.KeyVault.Firewall docs

docs/CHANGELOG-v1.md, docs/en/rules/Azure.SQLMI.ManagedIdentity.md, src/PSRule.Rules.Azure/rules/Azure.SQLMI.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.SQLMI.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.SQLMI.json
Fixes #2120 
Added Azure.SQLMI.ManagedIdentity rule.
=> Added Azure.SQLMI.ManagedIdentity

docs/CHANGELOG-v1.md, docs/en/rules/Azure.AKS.DefenderProfile.md, src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.AKS.json
Fixes #2123 
Added Azure.AKS.DefenderProfile rule.
=> Added Azure.AKS.DefenderProfile

docs/CHANGELOG-v1.md, docs/en/baselines/Azure.All.md, docs/en/baselines/Azure.GA_2022_12.md, docs/en/baselines/Azure.GA_2023_03.md, docs/en/baselines/Azure.MCSB.v1.md, docs/en/baselines/Azure.Preview.md, docs/en/baselines/Azure.Preview_2023_03.md, docs/en/rules/index.md, docs/en/rules/module.md, docs/en/rules/resource.md, docs/es/rules/index.md, docs/es/rules/module.md, docs/es/rules/resource.md, src/PSRule.Rules.Azure/rules/Baseline.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1
- Add baselines for March 2023.
Fixes #2138
=> Add baselines for March 2023 #2138

docs/CHANGELOG-v1.md
What's changed since pre-release v1.26.0-B0011:
- Added March 2023 baselines `Azure.GA_2023_03` and `Azure.Preview_2023_03` by @BernieWhite.
[#2138](https://github.com/Azure/PSRule.Rules.Azure/issues/2138)
- Includes rules released before or during March 2023.
- Marked `Azure.GA_2022_12` and `Azure.Preview_2022_12` baselines as obsolete.
- New rules:
- Check that wildcard `*` for any configuration option in CORS policies settings is not in use by @BenjaminEngeset.
[#2073](https://github.com/Azure/PSRule.Rules.Azure/issues/2073)
- Check that the Defender profile with Azure Kubernetes Service clusters are enabled by @BenjaminEngeset.
[#2123](https://github.com/Azure/PSRule.Rules.Azure/issues/2123)
- Check that …
=> Pre-release v1.26.0-B0040

.markdownlint.json, .vscode/settings.json, README.md, docs/creating-your-pipeline.md, docs/install-instructions.md, docs/setup/setup-azure-monitor-logs.md, docs/troubleshooting.md, docs/using-bicep.md, docs/working-with-baselines.md
Updated docs for anonymous pull access to a registry.
Fixes #2134
=> Doc updates #2134

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Pipeline/Export/ResourceExportVisitor.cs
- Improved export of in-flight deeply nested API Management policies.
Fixes #2153
=> Improved APIM export #2153

docs/CHANGELOG-v1.md
What's changed since pre-release v1.26.0-B0040:
- Improved export of in-flight deeply nested API Management policies by @BernieWhite.
[#2153](https://github.com/Azure/PSRule.Rules.Azure/issues/2153)
- Engineering:
- Updated resource providers and policy aliases.
[#2144](https://github.com/Azure/PSRule.Rules.Azure/pull/2144)
- Bump PSRule to v2.8.1.
[#2155](https://github.com/Azure/PSRule.Rules.Azure/pull/2155)
- Bump Az.Resources to v6.6.0.
[#2155](https://github.com/Azure/PSRule.Rules.Azure/pull/2155)
- Bump Pester to v5.4.1.
[#2155](https://github.com/Azure/PSRule.Rules.Azure/pull/2155)
- Bug fixes:
- Fixed false positives for `Azure.AppService.AlwaysOn` with Functions and Workflows by @BernieWhite.
[#943](https://github.com/Azure/PSRule.Rules.Azure/issues/943)
=> Pre-release v1.26.0-B0078

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/Functions.cs, tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
- Fixed null union with first value being null.
Fixes #2075 
=> Fixes null union #2075

docs/CHANGELOG-v1.md, docs/en/rules/Azure.Resource.UseTags.md, docs/examples-rg.bicep, docs/examples-rg.json, src/PSRule.Rules.Azure/Data/Template/Functions.cs, src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.Resource.Rule.ps1, src/PSRule.Rules.Azure/rules/Common.Selector.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Common.Selector.Tests.ps1, tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
Merge patches from v1.26.1:
- Bug fixes:
- Fixed null union with first value being null by @BernieWhite.
[#2075](https://github.com/Azure/PSRule.Rules.Azure/issues/2075)
- Fixed `Azure.Resource.UseTags` for additional resources that don't support tags by @BernieWhite.
[#2129](https://github.com/Azure/PSRule.Rules.Azure/issues/2129)
Fixes #2075 
Fixes #2129 
=> Merge patch v1.26.1

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/ExpressionBuilder.cs, src/PSRule.Rules.Azure/Data/Template/Mocks.cs, src/PSRule.Rules.Azure/Data/Template/RuleDataExportVisitor.cs, tests/PSRule.Rules.Azure.Tests/ExpressionBuilderTests.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.13.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.13.child.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.13.json
- Fixed reference for runtime subnet ID property.
Fixes #2159 
=> Fixes runtime subnet ID with filter #2159

docs/CHANGELOG-v1.md
What's changed since v1.26.1:
- Updated `Azure.APIM.EncryptValues` to check all API Management named values are encrypted with Key Vault secrets @BenjaminEngeset.
[#2146](https://github.com/Azure/PSRule.Rules.Azure/issues/2146)
- Bug fixes:
- Fixed reference for runtime subnet ID property by @BernieWhite.
[#2159](https://github.com/Azure/PSRule.Rules.Azure/issues/2159)
=> Pre-release v1.27.0-B0003

docs/en/baselines/Azure.All.md, docs/en/baselines/Azure.Default.md, docs/en/baselines/Azure.MCSB.v1.md, docs/en/baselines/Azure.Preview.md, docs/en/rules/Azure.APIM.CORSPolicy.md, docs/en/rules/index.md, docs/en/rules/module.md, docs/en/rules/resource.md, docs/es/rules/index.md, docs/es/rules/module.md, docs/es/rules/resource.md, docs/examples-apim-policy.xml, docs/examples-apim.bicep, docs/examples-apim.json, docs/hooks.py
Updates to API Management documentation.
=> Documentation improvements

docs/CHANGELOG-v1.md, docs/en/baselines/Azure.All.md, docs/en/baselines/Azure.Default.md, docs/en/baselines/Azure.GA_2023_03.md, docs/en/baselines/Azure.MCSB.v1.md, docs/en/baselines/Azure.Preview.md, docs/en/baselines/Azure.Preview_2022_03.md, docs/en/baselines/Azure.Preview_2022_06.md, docs/en/baselines/Azure.Preview_2022_09.md, docs/en/baselines/Azure.Preview_2022_12.md, docs/en/baselines/Azure.Preview_2023_03.md, docs/en/rules/Azure.ContainerApp.Insecure.md, docs/en/rules/index.md, docs/en/rules/module.md, docs/en/rules/resource.md, docs/es/rules/index.md, docs/es/rules/module.md, docs/es/rules/resource.md, docs/examples-containerapp.bicep, docs/examples-containerapp.json, docs/features.md, docs/setup/configuring-options.md, docs/setup/setup-bicep.md, src/PSRule.Rules.Azure/rules/Azure.ContainerApp.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1
- Promoted `Azure.ContainerApp.Insecure` to GA rule set.
Fixes #2174
=> Promote Azure.ContainerApp.Insecure to GA #2174

docs/setup/configuring-options.md, docs/troubleshooting.md
Minor fixes for documentation.
=> Documentation fixes

docs/CHANGELOG-v1.md, docs/en/rules/Azure.Arc.Kubernetes.Defender.md, src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.Arc.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.Arc.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.Arc.json
Fixes #2124 
Added Azure.Arc.Kubernetes.Defender rule.
=> Added Azure.Arc.Kubernetes.Defender

docs/CHANGELOG-v1.md, docs/en/rules/Azure.Arc.Server.MaintenanceConfig.md, src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.Arc.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.Arc.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.Arc.json
Fixes #2122 
Added Azure.Arc.Server.MaintenanceConfig rule.
=> Added Azure.Arc.Server.MaintenanceConfig

docs/CHANGELOG-v1.md, docs/en/rules/Azure.VM.MaintenanceConfig.md, docs/setup/defender.bicep, src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.VM.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.VM.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.VirtualMachine.json
Fixes #2121
Added Azure.VM.MaintenanceConfig rule.
=> Added Azure.VM.MaintenanceConfig

docs/CHANGELOG-v1.md, docs/en/rules/Azure.Defender.Api.md, src/PSRule.Rules.Azure/rules/Azure.Defender.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.Defender.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.Defender.json
Fixes #2186
Added Azure.Defender.Api rule.
=> Added Azure.Defender.Api

docs/CHANGELOG-v1.md, docs/en/rules/Azure.AppGw.MigrateV2.md, src/PSRule.Rules.Azure/rules/Azure.AppGw.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.AppGw.Tests.ps1
Fixes #2185
Added Azure.AppGw.MigrateV2 rule.
=> Added Azure.AppGw.MigrateV2

docs/CHANGELOG-v1.md, docs/en/rules/Azure.Defender.Api.md
Fixes #2209 
Fixed typing error in `Azure.Defender.Api` documentation,
=> Fixed typing error in Azure.Defender.Api documentation

docs/CHANGELOG-v1.md, docs/en/rules/Azure.ContainerApp.DisableAffinity.md, src/PSRule.Rules.Azure/rules/Azure.ContainerApp.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.ContainerApp.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.ContainerApp.json
Fixes #2188 
Added Azure.ContainerApp.DisableAffinity rule.
=> Added Azure.ContainerApp.DisableAffinity

docs/CHANGELOG-v1.md, docs/en/rules/Azure.Defender.CosmosDb.md, src/PSRule.Rules.Azure/rules/Azure.Defender.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.Defender.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.Defender.json
Fixes #2204
Fixes a topic within #1632 
Added Azure.Defender.CosmosDb rule.
=> Added Azure.Defender.CosmosDb

docs/CHANGELOG-v1.md, docs/en/rules/Azure.Defender.Storage.md, src/PSRule.Rules.Azure/rules/Azure.Defender.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.Defender.json
Fixes #2205
Updated Azure.Defender.Storage rule.
=> Updated Azure.Defender.Storage

docs/CHANGELOG-v1.md, docs/concepts/about_PSRule_Azure_Configuration.md, docs/en/rules/Azure.Cosmos.DefenderCloud.md, requirements-docs.txt, src/PSRule.Rules.Azure/rules/Azure.Cosmos.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.Cosmos.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.Cosmos.json, tests/PSRule.Rules.Azure.Tests/ps-rule-options.yaml
Fixes #2203
Added Azure.Cosmos.DefenderCloud rule.
=> Added Azure.Cosmos.DefenderCloud

docs/CHANGELOG-v1.md
What's changed since pre-release v1.27.0-B0015:
- New rules:
- Check that Application Gateways uses a v2 SKU by @BenjaminEngeset.
[#2185](https://github.com/Azure/PSRule.Rules.Azure/issues/2185)
- Arc-enabled Kubernetes cluster:
- Check that Microsoft Defender for Containers extension for Arc-enabled Kubernetes clusters is configured by @BenjaminEngeset.
[#2124](https://github.com/Azure/PSRule.Rules.Azure/issues/2124)
- Arc-enabled server:
- Check that a maintenance configuration for Arc-enabled servers is associated by @BenjaminEngeset.
[#2122](https://github.com/Azure/PSRule.Rules.Azure/issues/2122)
- Check that container apps has disabled session affinity to prevent unbalanced distribution by @BenjaminEngeset. …
=> Pre-release v1.27.0-B0050

docs/CHANGELOG-v1.md, docs/en/rules/Azure.Storage.DefenderCloud.MalwareScan.md, src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.Storage.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.Storage.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.Storage.json
Part of #2206
Added Azure.Storage.DefenderCloud.MalwareScan rule.
=> Added Azure.Storage.DefenderCloud.MalwareScan

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/CloudEnvironment.cs, src/PSRule.Rules.Azure/Data/Template/Functions.cs, src/PSRule.Rules.Azure/Data/Template/RuleDataExportVisitor.cs, src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.19.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.19.json, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.20.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.20.json
- Fixed left-side `or` function evaluation.
[#2220](https://github.com/Azure/PSRule.Rules.Azure/issues/2220)
- Fixed interdependent variable copy loop count.
[#2221](https://github.com/Azure/PSRule.Rules.Azure/issues/2221)
Fixes #2220 
Fixes #2221 
=> Fixes for expansion issues #2220 #2221

.vscode/settings.json, .vscode/tasks.json, docs/CHANGELOG-v1.md, docs/commands/Export-AzPolicyAssignmentData.md, docs/commands/Export-AzPolicyAssignmentRuleData.md, docs/commands/Export-AzRuleData.md, docs/commands/Export-AzRuleTemplateData.md, docs/commands/Get-AzPolicyAssignmentDataSource.md, docs/commands/Get-AzRuleTemplateLink.md, docs/en/rules/index.md, docs/en/rules/module.md, docs/en/rules/resource.md, docs/es/rules/index.md, docs/es/rules/module.md, docs/es/rules/resource.md, docs/setup/configuring-expansion.md, docs/using-bicep.md, docs/versioning.md, src/PSRule.Rules.Azure/Configuration/ConfigurationOption.cs, src/PSRule.Rules.Azure/Data/Bicep/BicepHelper.cs, src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1, src/PSRule.Rules.Azure/Pipeline/TemplatePipeline.cs, src/PSRule.Rules.Azure/Pipeline/TemplateSource.cs, src/PSRule.Rules.Azure/Runtime/Helper.cs, src/PSRule.Rules.Azure/Runtime/RuntimeService.cs, src/PSRule.Rules.Azure/rules/Config.Rule.yaml, src/PSRule.Rules.Azure/rules/Conventions.Rule.ps1, tests/Bicep/Bicep.Tests.ps1, tests/Bicep/bicepconfig.json, tests/Bicep/template.bicepparam
Added support for expanding deployments from `.bicepparam` files.
Fixes #2132
=> Added support for .bicepparam files #2132

docs/CHANGELOG-v1.md
What's changed since pre-release v1.27.0-B0050:
- **Experimental:** Added support for expanding deployments from `.bicepparam` files by @BernieWhite.
[#2132](https://github.com/Azure/PSRule.Rules.Azure/issues/2132)
- See [Using Bicep source](https://aka.ms/ps-rule-azure/bicep) for details.
- New rules:
- Check that Malware Scanning in Microsoft Defender for Storage is enabled for storage accounts by @BenjaminEngeset.
- Check that Malware Scanning in Microsoft Defender for Storage is enabled by @BenjaminEngeset.
[#2206](https://github.com/Azure/PSRule.Rules.Azure/issues/2206)
- Bug fixes:
- Fixed left-side `or` function evaluation by @BernieWhite.
[#2220](https://github.com/Azure/PSRule.Rules.Azure/issues/2220)
- Fixed interdependent …
=> Pre-release v1.27.0-B0091

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/rules/Azure.ADX.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.APIM.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.AppService.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.Automation.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.Cognitive.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.ContainerApp.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.EventGrid.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.SQLMI.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Resources.APIM.json
- Fixed false positive on managed identity without space.
Fixes #2235 
=> Fixed false positive on managed identity #2235

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Common/JsonExtensions.cs, src/PSRule.Rules.Azure/Data/Template/DeploymentSymbol.cs, src/PSRule.Rules.Azure/Data/Template/ResourceValue.cs, src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.3.json, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.7.json
Added support for Bicep symbolic names.
Fixes #2238
=> Add support for Bicep symbolic names #2238

docs/CHANGELOG-v1.md, docs/en/rules/Azure.Defender.Storage.SensitiveData.md, src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.Defender.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.Defender.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.Defender.json
Part of #2207 
Added Azure.Defender.Storage.SensitiveData rule.
=> Added Azure.Defender.Storage.SensitiveData

docs/CHANGELOG-v1.md
What's changed since pre-release v1.27.0-B0091:
- New rules:
- Check that sensitive data threat detection in Microsoft Defender for Storage is enabled by @BenjaminEngeset.
[#2207](https://github.com/Azure/PSRule.Rules.Azure/issues/2207)
- Added support for Bicep symbolic names by @BernieWhite.
[#2238](https://github.com/Azure/PSRule.Rules.Azure/issues/2238)
- Bug fixes:
- Fixed false positive on managed identity without space by @BernieWhite.
[#2235](https://github.com/Azure/PSRule.Rules.Azure/issues/2235)
=> Pre-release v1.27.0-B0136

docs/CHANGELOG-v1.md
What's changed since pre-release v1.27.0-B0136:
- New rules:
- Check that APIs published in Azure API Management are onboarded to Microsoft Defender for APIs by @BenjaminEngeset.
[#2187](https://github.com/Azure/PSRule.Rules.Azure/issues/2187)
- Key Vault:
- Check that key vaults uses Azure RBAC as the authorization system for the data plane by @BenjaminEngeset.
[#1916](https://github.com/Azure/PSRule.Rules.Azure/issues/1916)
- Check that Microsoft Defender for Storage is enabled for storage accounts by @BenjaminEngeset.
[#2225](https://github.com/Azure/PSRule.Rules.Azure/issues/2225)
- Check that sensitive data threat detection in Microsoft Defender for Storage is enabled for storage accounts by @BenjaminEngeset. …
=> Pre-release v1.27.0-B0186

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Common/ResourceDependencyComparer.cs, src/PSRule.Rules.Azure/Data/Template/ResourceValue.cs, tests/PSRule.Rules.Azure.Tests/ResourceDependencyComparerTests.cs, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- Fixed depends on ordering fails to expand deployment.
Fixes #2255 
=> Fixes depends on ordering #2255

docs/CHANGELOG-v1.md
What's changed since v1.27.0:
- Bug fixes:
- Fixed depends on ordering fails to expand deployment by @BernieWhite.
[#2255](https://github.com/Azure/PSRule.Rules.Azure/issues/2255)
=> Release v1.27.1

docs/CHANGELOG-v1.md, docs/en/rules/Azure.MySQL.AAD.md, src/PSRule.Rules.Azure/rules/Azure.MySQL.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.MySQL.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.MySQL.json
Fixes #2226 
Added Azure.MySQL.AAD rule.
=> Added Azure.MySQL.AAD

docs/CHANGELOG-v1.md
What's changed since v1.27.1:
- New rules:
- Check that Azure AD authentication is configured for Azure Database for MySQL databases by @BenjaminEngeset.
[#2226](https://github.com/Azure/PSRule.Rules.Azure/issues/2226)
- Check that Azure AD-only authentication is configured for Azure Database for PostgreSQL databases by @BenjaminEngeset.
[#2250](https://github.com/Azure/PSRule.Rules.Azure/issues/2250)
- Check that Azure AD authentication is configured for Azure Database for PostgreSQL databases by @BenjaminEngeset.
[#2249](https://github.com/Azure/PSRule.Rules.Azure/issues/2249)
- Engineering:
- Updated resource providers and policy aliases.
[#2261](https://github.com/Azure/PSRule.Rules.Azure/pull/2261)
- Bump …
=> Pre-release v1.28.0-B0010

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs, tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
- Fixed union function for merge of object properties.
Fixes #2264
=> Fixes union function property merge #2264

docs/CHANGELOG-v1.md
What's changed since v1.27.1:
- Bug fixes:
- Fixed union function for merge of object properties by @BernieWhite.
[#2264](https://github.com/Azure/PSRule.Rules.Azure/issues/2264)
- Fixed length function counting properties in object by @BernieWhite.
[#2263](https://github.com/Azure/PSRule.Rules.Azure/issues/2263)
=> Release v1.27.2

docs/CHANGELOG-v1.md
What's changed since pre-release v1.28.0-B0010:
- Bug fixes:
- Fixed union function for merge of object properties by @BernieWhite.
[#2264](https://github.com/Azure/PSRule.Rules.Azure/issues/2264)
- Fixed length function counting properties in object by @BernieWhite.
[#2263](https://github.com/Azure/PSRule.Rules.Azure/issues/2263)
=> Pre-release v1.28.0-B0024

docs/en/rules/Azure.ACR.AdminUser.md, docs/en/rules/Azure.ACR.MinSku.md, docs/en/rules/Azure.ACR.Name.md, docs/en/rules/Azure.ACR.Quarantine.md, docs/en/rules/Azure.ACR.Retention.md, docs/en/rules/Azure.ACR.SoftDelete.md, docs/en/rules/index.md, docs/es/rules/Azure.ACR.AdminUser.md, docs/es/rules/Azure.ACR.ContentTrust.md, docs/es/rules/Azure.ACR.MinSku.md, docs/es/rules/Azure.ACR.Name.md, docs/es/rules/Azure.ACR.Quarantine.md, docs/es/rules/Azure.ACR.Retention.md, docs/es/rules/index.md, docs/examples-acr.bicep, docs/examples-acr.json, src/PSRule.Rules.Azure/rules/Azure.ACR.Rule.ps1
Quality update for rule documentation.
=> Quality updates for documentation

docs/CHANGELOG-v1.md, docs/en/rules/Azure.AppService.MinPlan.md, docs/examples-appservice.bicep, docs/examples-appservice.json, src/PSRule.Rules.Azure/rules/Azure.AppService.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.AppService.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.AppService.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.AppService.Template.json
- Fixed false positive of `IsolatedV2` with `Azure.AppService.MinPlan`.
Fixes #2277
=> Fixes false positive with IsolatedV2 #2277

docs/CHANGELOG-v1.md
What's changed since v1.27.2:
- Bug fixes:
- Fixed false positive of `IsolatedV2` with `Azure.AppService.MinPlan` by @BernieWhite.
[#2277](https://github.com/Azure/PSRule.Rules.Azure/issues/2277)
=> Release v1.27.3

docs/CHANGELOG-v1.md, docs/en/rules/Azure.AppService.MinPlan.md, docs/examples-appservice.bicep, docs/examples-appservice.json, src/PSRule.Rules.Azure/rules/Azure.AppService.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.AppService.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.AppService.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.AppService.Template.json
Merge bug fixes from patch release v1.27.3:
- Bug fixes:
- Fixed false positive of `IsolatedV2` with `Azure.AppService.MinPlan` by @BernieWhite.
[#2277](https://github.com/Azure/PSRule.Rules.Azure/issues/2277)
Fixes #2277
=> Merge patch v1.27.3

docs/en/rules/Azure.Search.IndexSLA.md, docs/en/rules/Azure.Search.ManagedIdentity.md, docs/en/rules/Azure.Search.Name.md, docs/en/rules/Azure.Search.QuerySLA.md, docs/en/rules/Azure.Search.SKU.md, docs/en/rules/Azure.SignalR.Name.md, docs/en/rules/module.md, docs/es/rules/module.md, docs/examples-search.bicep, docs/examples-search.json, src/PSRule.Rules.Azure/rules/Azure.Search.Rule.ps1
- Review and update documentation for Cognitive Search.
Fixes #1720.
=> Update Cognitive Search docs

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/CidrParsing.cs, src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs, src/PSRule.Rules.Azure/Data/Template/Functions.cs, src/PSRule.Rules.Azure/Resources/PSRuleResources.Designer.cs, src/PSRule.Rules.Azure/Resources/PSRuleResources.resx, tests/PSRule.Rules.Azure.Tests/CidrParsingTests.cs, tests/PSRule.Rules.Azure.Tests/FunctionTests.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.13.child.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.13.json
- Added support for Bicep CIDR functions.
Fixes #2279 
=> Added support for Bicep CIDR functions #2279

docs/CHANGELOG-v1.md
What's changed since pre-release v1.28.0-B0079:
- Added support for Bicep CIDR functions by @BernieWhite.
[#2279](https://github.com/Azure/PSRule.Rules.Azure/issues/2279)
- Added support for `parseCidr`, `cidrSubnet`, and `cidrHost`.
=> Pre-release v1.28.0-B0115

.github/workflows/analyze.yaml, .github/workflows/dependencies.yaml, .github/workflows/docs.yaml, .github/workflows/providers.yml, .vscode/settings.json
=> Updates to CI

docs/en/rules/Azure.Redis.AvailabilityZone.md, docs/en/rules/Azure.Redis.FirewallIPRange.md, docs/en/rules/Azure.Redis.FirewallRuleCount.md, docs/en/rules/Azure.Redis.MaxMemoryReserved.md, docs/en/rules/Azure.Redis.MinSKU.md, docs/en/rules/Azure.Redis.MinTLS.md, docs/en/rules/Azure.Redis.NonSslPort.md, docs/en/rules/Azure.Redis.PublicNetworkAccess.md, docs/en/rules/Azure.Redis.Version.md, docs/examples-redis.bicep, docs/examples-redis.json
Improvements to Redis documentation.
Fixes #2078
=> Improvements to Redis rule docs

.vscode/settings.json, docs/CHANGELOG-v1.md, docs/en/rules/Azure.Redis.FirewallIPRange.md, docs/en/rules/Azure.Redis.FirewallRuleCount.md, docs/examples-redis.bicep, docs/examples-redis.json, src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.Redis.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.Redis.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.Redis.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.Redis.json
- Fixed Redis firewall rules can not bind to start.
Fixes #2303 
=> Fixes Redis firewall rules binding #2303

docs/CHANGELOG-v1.md, docs/en/baselines/Azure.GA_2023_06.md, docs/en/baselines/Azure.Preview_2023_03.md, docs/en/baselines/Azure.Preview_2023_06.md, docs/en/rules/index.md, docs/es/rules/index.md, src/PSRule.Rules.Azure/rules/Baseline.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1
- Added June 2023 baselines `Azure.GA_2023_06` and `Azure.Preview_2023_06`.
Fixes #2310 
=> Added June 2023 baselines #2310

README.md, docs/about.md, docs/customization/enforce-codeowners.md, docs/customization/enforce-custom-tags.md, docs/faq.md
Added more links to quick start repo and fixed some links that are redirecting.
=> Doc updates

src/PSRule.Rules.Azure/rules/Azure.Databricks.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.ML.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.Databricks.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Azure.ML.Tests.ps1
Added placeholder files for AML and Databricks.
=> Added placeholder files

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs, src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.22.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.22.json
- Fixed null condition handling
Fixes #2316
- [ x] PR has a meaningful title
=> Fixes null condition handling #2316

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.15.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.15.json
- Fixed reference expression in property name.
Fixes #2321 
=> Fixed reference expression in name #2321

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/Mocks.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.23.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.23.json
- Fixed handling of nested mock objects.
Fixes #2325 
=> Fixes handling of nested mock objects #2325

.vscode/markdown.code-snippets, docs/en/rules/Azure.AppConfig.AuditLogs.md, docs/en/rules/Azure.AppConfig.DisableLocalAuth.md, docs/en/rules/Azure.AppConfig.GeoReplica.md, docs/en/rules/Azure.AppConfig.PurgeProtect.md, docs/en/rules/Azure.AppConfig.SKU.md, docs/examples-appconfig-br.bicep, docs/examples-appconfig.bicep, docs/examples-appconfig.json
=> Added doc quality updates

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Common/JsonExtensions.cs, src/PSRule.Rules.Azure/Data/Policy/PolicyAliasProviderHelper.cs, src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitor.cs, src/PSRule.Rules.Azure/Data/Template/TokenStream.cs, tests/PSRule.Rules.Azure.Tests/PolicyAliasProviderHelperTests.cs, tests/PSRule.Rules.Azure.Tests/PolicyAssignmentVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/emittedJsonRulesData.jsonc
- Fixed length cannot be less than zero when converting policy to rules.
Fixes #1802
=> Fixes length cannot be less than zero #1802

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Common/JsonExtensions.cs, src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitor.cs, tests/PSRule.Rules.Azure.Tests/PolicyAssignmentVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/emittedJsonRulesData.jsonc, tests/PSRule.Rules.Azure.Tests/emittedJsonRulesPrefixData.jsonc
- Fixed policy rules with no effect conditions are evaluated incorrectly.
Fixes #2346 
=> Fixes no effect policy rules #2346

docs/CHANGELOG-v1.md
What's changed since v1.28.1:
- Bug fixes:
- Fixed policy rules with no effect conditions are evaluated incorrectly by @BernieWhite.
[#2346](https://github.com/Azure/PSRule.Rules.Azure/issues/2346)
=> Release v1.28.2

CONTRIBUTING.md, docs/CHANGELOG-v1.md, docs/en/rules/Azure.Databricks.SecureConnectivity.md, docs/examples-databricks.bicep, docs/examples-databricks.json, src/PSRule.Rules.Azure/rules/Azure.Databricks.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.Databricks.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.Databricks.json
- Check that workspaces use secure cluster connectivity.
Fixes #2334
=> Databricks should use secure cluster connectivity #2334

docs/en/rules/Azure.SQL.AAD.md, docs/en/rules/Azure.SQL.AADOnly.md, docs/en/rules/Azure.SQL.Auditing.md, docs/en/rules/Azure.SQL.MinTLS.md, docs/examples-sql.bicep, docs/examples-sql.json, tests/PSRule.Rules.Azure.Tests/Azure.SQL.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.SQL.json
Updates to docs and tests for SQL Database.
=> Quality updates for SQL rules

.devcontainer/devcontainer.json
Add markdownlint dev container extension.
=> Add markdownlint for dev container

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitor.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/Policy.assignment.3.json, tests/PSRule.Rules.Azure.Tests/PolicyAssignmentVisitorTests.cs
- Fixed policy expansion with unquoted field property.
Fixes #2352 
=> Fixes policy expansion with unquoted field #2352

docs/CHANGELOG-v1.md
What's changed since v1.28.2:
- New rules:
- Databricks:
- Check that workspaces use secure cluster connectivity by @BernieWhite.
[#2334](https://github.com/Azure/PSRule.Rules.Azure/issues/2334)
- Use policy definition name when generating a rule from it by @BernieWhite.
[#1959](https://github.com/Azure/PSRule.Rules.Azure/issues/1959)
- Bug fixes:
- Fixed policy expansion with unquoted field property by @BernieWhite.
[#2352](https://github.com/Azure/PSRule.Rules.Azure/issues/2352)
=> Pre-release v1.29.0-B0015

.vscode/settings.json, src/PSRule.Rules.Azure/rules/Azure.Defender.Rule.yaml
=> Metadata improvements MDC

docs/about.md, docs/creating-your-pipeline.md, docs/en/baselines/Azure.All.md, docs/en/baselines/Azure.Default.md, docs/en/baselines/Azure.MCSB.v1.md, docs/en/baselines/Azure.Preview.md, docs/en/rules/index.md, docs/en/rules/module.md, docs/en/rules/resource.md, docs/es/rules/index.md, docs/es/rules/module.md, docs/es/rules/resource.md, docs/setup/setup-azure-monitor-logs.md, docs/setup/setup-bicep.md, docs/using-bicep.md, docs/working-with-baselines.md
Minor improvements to documentation.
=> Additional improvements to documentation

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Pipeline/Export/ExportDataContext.cs, src/PSRule.Rules.Azure/Pipeline/Export/ResourceExportContext.cs, src/PSRule.Rules.Azure/Pipeline/Export/ResourceExportVisitor.cs, src/PSRule.Rules.Azure/Pipeline/Export/SubscriptionExportContext.cs
- Added export in-flight data for Defender for Storage from Storage Accounts.
- Added export in-flight data for Defender for APIs from API Management.
Fixes #2248 
Fixes #2247 
=> Added in-flight export of defender #2248 #2247

docs/CHANGELOG-v1.md
What's changed since pre-release v1.29.0-B0015:
- Added export in-flight data for Defender for Storage from Storage Accounts by @BernieWhite.
[#2248](https://github.com/Azure/PSRule.Rules.Azure/issues/2248)
- Added export in-flight data for Defender for APIs from API Management by @BernieWhite.
[#2247](https://github.com/Azure/PSRule.Rules.Azure/issues/2247)
=> Pre-release v1.29.0-B0036

README.md
Adding the two June 2023 baselines to readme
=> Add June 2023 baselines to readme

.vscode/settings.json, docs/concepts/policy-as-rules.md, docs/concepts/suppression.md, mkdocs.yml, pipeline.build.ps1, src/PSRule.Rules.Azure/Configuration/ConfigurationOption.cs
- Add documentation for policy as rules feature.
=> Add documentation for Policy as Rules #1650

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/Functions.cs, tests/PSRule.Rules.Azure.Tests/FunctionTests.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.24.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.24.json
- Fixed array contains with JArray.
Fixes #2368.
=> Fixes array contains with JArray #2368

docs/CHANGELOG-v1.md
What's changed since pre-release v1.29.0-B0036:
- Bug fixes:
- Fixed array contains with JArray by @BernieWhite.
[#2368](https://github.com/Azure/PSRule.Rules.Azure/issues/2368)
- Fixed index out of bounds of array with first function on empty array by @BernieWhite.
[#2372](https://github.com/Azure/PSRule.Rules.Azure/issues/2372)
=> Pre-release v1.29.0-B0062

docs/CHANGELOG-v1.md, docs/en/rules/Azure.RSV.Immutable.md, src/PSRule.Rules.Azure/rules/Azure.RSV.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.RSV.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.RSV.json
Fixes #2386
Added Azure.RSV.Immutable rule.
=> Added Azure.RSV.Immutable

docs/CHANGELOG-v1.md, docs/en/rules/Azure.BV.Immutable.md, src/PSRule.Rules.Azure/rules/Azure.BV.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.BV.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.BV.json
Fixes #2387
Added Azure.BV.Immutable rule.
=> Added Azure.BV.Immutable

.devcontainer/devcontainer.json, .vscode/extensions.json
- Updates extension suggested by VSCode and dev container.
=> Update repository extensions

docs/CHANGELOG-v1.md
What's changed since v1.29.0:
- New rules:
- Check that Azure AD-only authentication is configured for Azure Database for MySQL databases by @BenjaminEngeset.
[#2227](https://github.com/Azure/PSRule.Rules.Azure/issues/2227)
- Azure Firewall:
- Check that Azure Firewall polices has configured threat intelligence-based filtering in `alert and deny` mode by @BenjaminEngeset.
[#2354](https://github.com/Azure/PSRule.Rules.Azure/issues/2354)
- Backup vault:
- Check that immutability is configured for Backup vaults by @BenjaminEngeset.
[#2387](https://github.com/Azure/PSRule.Rules.Azure/issues/2387)
- Front Door:
- Check that managed identity for Azure Front Door instances are configured by @BenjaminEngeset.
[#2378](https://github.com/Azure/PSRule.Rules.Azure/issues/23 …
=> Pre-release v1.30.0-B0011

docs/CHANGELOG-v1.md, docs/en/rules/Azure.ContainerApp.APIVersion.md, docs/en/rules/Azure.ContainerApp.MigrateAPIVersion.md, src/PSRule.Rules.Azure/Data/Template/RuleDataExportVisitor.cs, src/PSRule.Rules.Azure/rules/Azure.ContainerApp.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.ContainerApp.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.ContainerApp.json
Fixes #2398
Added Azure.ContainerApp.MigrateAPIVersion rule.
=> Added Azure.ContainerApp.APIVersion

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitor.cs, src/PSRule.Rules.Azure/rules/Common.Selector.Rule.yaml, tests/PSRule.Rules.Azure.Tests/PolicyAssignmentVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/emittedJsonRulesData.jsonc, tests/PSRule.Rules.Azure.Tests/emittedJsonRulesPrefixData.jsonc
- Fixed non-resource group rule triggering for a resource group.
Fixes #2401
=> Fixed selector for indexed Azure policies #2401

docs/CHANGELOG-v1.md
What's changed since pre-release v1.30.0-B0011:
- New rules:
- Azure Container Apps:
- Check that Container Apps uses a supported API version by @BenjaminEngeset.
[#2398](https://github.com/Azure/PSRule.Rules.Azure/issues/2398)
- Bug fixes:
- Fixed non-resource group rule triggering for a resource group by @BernieWhite.
[#2401](https://github.com/Azure/PSRule.Rules.Azure/issues/2401)
=> Pre-release v1.30.0-B0026

docs/CHANGELOG-v1.md, docs/en/rules/Azure.Storage.SecureTransfer.md, docs/examples-storage.bicep, docs/examples-storage.json, src/PSRule.Rules.Azure/rules/Azure.Storage.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Resources.Storage.Template.json
- Fixed false positive with `Azure.Storage.SecureTransfer` on new API versions.
Fixes #2414
=> Fixed Azure.Storage.SecureTransfer #2414

docs/CHANGELOG-v1.md, docs/en/rules/Azure.ACR.AnonymousAccess.md, src/PSRule.Rules.Azure/rules/Azure.ACR.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.ACR.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.ACR.json
Fixes #2422
Added Azure.ACR.AnonymousAccess rule.
=> feat(new): Added Azure.ACR.AnonymousAccess

docs/CHANGELOG-v1.md, docs/en/rules/Azure.ACR.Firewall.md, src/PSRule.Rules.Azure/rules/Azure.ACR.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.ACR.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.ACR.json
Fixes #2423
Added Azure.ACR.Firewall rule.
=> feat(new): Added Azure.ACR.Firewall

.devcontainer/devcontainer.json, README.md, docs/CHANGELOG-v1.md, docs/about.md, docs/features.md, docs/hooks.py, docs/working-with-baselines.md, overrides/home.html, pipeline.build.ps1
- Added source link for rule in docs.
Fixes #2115
=> Add source link for rule in docs #2115

docs/CHANGELOG-v1.md
What's changed since pre-release v1.30.0-B0080:
- Added September 2023 baselines `Azure.GA_2023_09` and `Azure.Preview_2023_09` by @BernieWhite.
[#2451](https://github.com/Azure/PSRule.Rules.Azure/issues/2451)
- Includes rules released before or during September 2023.
- Marked `Azure.GA_2023_06` and `Azure.Preview_2023_06` baselines as obsolete.
- New rules:
- Azure Container Registry:
- Check that Container Registries restricts network access by @BenjaminEngeset.
[#2423](https://github.com/Azure/PSRule.Rules.Azure/issues/2423)
- Check that Container Registries disables anonymous pull access by @BenjaminEngeset.
[#2422](https://github.com/Azure/PSRule.Rules.Azure/issues/2422)
- Updated `Azure.AKS.Version` to use latest stable …
=> Pre-release v1.30.0-B0127

docs/CHANGELOG-v1.md
What's changed since v1.30.0:
- Bug fixes:
- Fixed `Azure.Resource.AllowedRegions` which was failing when no allowed regions were configured by @BernieWhite.
[#2461](https://github.com/Azure/PSRule.Rules.Azure/issues/2461)
=> Release v1.30.1

.github/workflows/build.yaml, docs/CHANGELOG-v1.md, docs/install.md, pipeline.build.ps1, src/PSRule.Rules.Azure.Benchmark/PSRule.Rules.Azure.Benchmark.csproj, src/PSRule.Rules.Azure.BuildTool/PSRule.Rules.Azure.BuildTool.csproj, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
Update development tools to .NET 7.0.
Fixes #1870
=> Update development tools to .NET 7.0 #1870

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
Update dev container to include .NET 7.0.
=> Update dev container for .NET 7

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.27.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.27.child.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.27.json
- Fixed nullable parameters for built-in types.
Fixes #2488
=> Fixes nullable param for built-in types #2488

docs/CHANGELOG-v1.md
What's changed since v1.30.2:
- Bug fixes:
- Fixed nullable parameters for built-in types by @BernieWhite.
[#2488](https://github.com/Azure/PSRule.Rules.Azure/issues/2488)
=> Release v1.30.3

.devcontainer/devcontainer.json, .vscode/extensions.json
Added extensions for project development.
=> Added recommended extensions

docs/en/rules/Azure.Defender.Storage.MalwareScan.md, docs/en/rules/Azure.Defender.Storage.SensitiveData.md, docs/en/rules/Azure.Defender.Storage.md, docs/en/rules/Azure.DefenderCloud.Contact.md, docs/examples-defender.bicep, docs/examples-defender.json, src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitor.cs, src/PSRule.Rules.Azure/rules/Azure.Defender.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.Subscription.Rule.ps1
- Updates to documentation.
- Minor clean up to code and reorganize.
=> Code quality clean

.vscode/markdown.code-snippets, docs/CHANGELOG-v1.md, docs/en/rules/Azure.Deployment.SecureParameter.md, src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.Deployment.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.Deployment.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.Deployments.json
- Check parameters potentially containing secure values.
Fixes #1476
=> Add secure value check #1476

.github/workflows/analyze.yaml
Upload SARIF output during scans.
=> Upload SARIF files for scanning tools

docs/CHANGELOG-v1.md
What's changed since v1.30.3:
- New rules:
- Deployment:
- Check parameters potentially containing secure values by @BernieWhite.
[#1476](https://github.com/Azure/PSRule.Rules.Azure/issues/1476)
- Machine Learning:
- Check compute instances are configured for an idle shutdown by @batemansogq.
[#2484](https://github.com/Azure/PSRule.Rules.Azure/issues/2484)
- Check workspace compute has local authentication disabled by @batemansogq.
[#2484](https://github.com/Azure/PSRule.Rules.Azure/issues/2484)
- Check workspace compute is connected to a VNET by @batemansogq.
[#2484](https://github.com/Azure/PSRule.Rules.Azure/issues/2484)
- Check public access to a workspace is disabled by @batemansogq.
[#2484](https://github.com/Azure/PSRule.Rules.Azure/issues/2484)
- Check workspaces use a …
=> Pre-release v1.31.0-B0020

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/ResourceValue.cs, src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs, src/PSRule.Rules.Azure/Data/Template/TypeDefinition.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/ResourceDependencyComparerTests.cs, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.14.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.14.json, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.25.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.25.json, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.26.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.26.child1.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.26.child2.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.26.json, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.27.child.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.27.json
- Fixed dependency ordering with symbolic name.
- Fixed nullable parameters for custom types.
Fixes #2505
Fixes #2489 
=> Fixes Bicep expand issues #2505 #2489

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/Mocks.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.29.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.29.child.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.29.json
- Fixed API Connection might be missing dynamic properties.
Fixes #2424 
=> Fixed API Connection might be missing dynamic properties #2424

docs/CHANGELOG-v1.md
What's changed since pre-release v1.31.0-B0020:
- Engineering:
- Bump BenchmarkDotNet to v0.13.10.
[#2518](https://github.com/Azure/PSRule.Rules.Azure/pull/2518)
- Bump BenchmarkDotNet.Diagnostics.Windows to v0.13.10.
[#2508](https://github.com/Azure/PSRule.Rules.Azure/pull/2508)
- Bump xunit to v2.6.1.
[#2514](https://github.com/Azure/PSRule.Rules.Azure/pull/2514)
- Bump xunit.runner.visualstudio to v2.5.3.
[#2486](https://github.com/Azure/PSRule.Rules.Azure/pull/2486)
- Bug fixes:
- Fixed dependency ordering with symbolic name by @BernieWhite.
[#2505](https://github.com/Azure/PSRule.Rules.Azure/issues/2505)
- Fixed nullable parameters for custom types by @BernieWhite.
[#2489](https://github.com/Azure/PSRule.Rules.Azure/issues/2489)
- Fixed API Connection might be missing dynamic …
=> Pre-release v1.31.0-B0048

README.md, SECURITY.md, src/PSRule.Rules.Azure/README.md
Updates to template files for notices.
=> Updated template file

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/Functions.cs, tests/PSRule.Rules.Azure.Tests/FunctionTests.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.30.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.30.json
- Fixed incorrect handling of expressions with contains with JValue string.
Fixes #2531 
=> Fixes contains handling of JValue string #2531

docs/CHANGELOG-v1.md
What's changed since v1.31.0:
- Bug fixes:
- Fixed additional non-sensitive parameter name patterns by `Azure.Deployment.SecureParameter` by @BernieWhite.
[#2528](https://github.com/Azure/PSRule.Rules.Azure/issues/2528)
- Added support for configuration of the rule by setting `AZURE_DEPLOYMENT_NONSENSITIVE_PARAMETER_NAMES`.
- Fixed incorrect handling of expressions with contains with JValue string by @BernieWhite.
[#2531](https://github.com/Azure/PSRule.Rules.Azure/issues/2531)
=> Release v1.31.1

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.27.child.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.27.json
- Fixed nullable parameters with JValue null.
Working towards #2535
Also see microsoft/PSRule#1640
=> Fixed nullable parameters with JValue null #2535

docs/CHANGELOG-v1.md
What's changed since v1.31.1:
- Bug fixes:
- Fixed nullable parameters with JValue null by @BernieWhite.
[#2535](https://github.com/Azure/PSRule.Rules.Azure/issues/2535)
=> Release v1.31.2

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/DeploymentScope.cs, src/PSRule.Rules.Azure/Data/Template/ResourceValue.cs, src/PSRule.Rules.Azure/Data/Template/RuleDataExportVisitor.cs, src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.31.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.31.child.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.31.json
- Fixed incorrect scope generated for subscription aliases.
Fixes #2545
=> Fixes scoping of subscription aliases #2545

docs/CHANGELOG-v1.md
What's changed since v1.31.2:
- Bug fixes:
- Fixed incorrect scope generated for subscription aliases by @BernieWhite.
[#2545](https://github.com/Azure/PSRule.Rules.Azure/issues/2545)
- Fixed null dereferenced properties in map lambda by @BernieWhite.
[#2535](https://github.com/Azure/PSRule.Rules.Azure/issues/2535)
- Fixed handling of for array index symbols by @BernieWhite.
[#2548](https://github.com/Azure/PSRule.Rules.Azure/issues/2548)
=> Release v1.31.3

CONTRIBUTING.md, README.md, docs/customization/enforce-codeowners.md, docs/customization/enforce-custom-tags.md, docs/customization/storing-custom-rules.md, docs/en/mcsb-v1.md, docs/en/rules/Azure.ACR.ContainerScan.md, docs/expanding-source-files.md, docs/faq.md, docs/setup/configuring-rules.md, docs/using-bicep.md, mkdocs.yml
- Fixes for documentation links.
Fixes #2557
=> Fixes for documentation links including #2557

docs/CHANGELOG-v1.md
What's changed since v1.31.3:
- Updates to documentation by @BernieWhite.
[#2557](https://github.com/Azure/PSRule.Rules.Azure/issues/2557)
- Engineering:
- Bump Microsoft.NET.Test.Sdk to v17.8.0.
[#2527](https://github.com/Azure/PSRule.Rules.Azure/pull/2527)
- Bump xunit to v2.6.2.
[#2544](https://github.com/Azure/PSRule.Rules.Azure/pull/2544)
- Bug fixes:
- Fixed additional false positives of `Azure.Deployment.SecureParameter` by @BernieWhite.
[#2556](https://github.com/Azure/PSRule.Rules.Azure/issues/2556)
- Fixed expansion with sub-resource handling of deployments with duplicate resources by @BernieWhite.
[#2564](https://github.com/Azure/PSRule.Rules.Azure/issues/2564)
=> Pre-release v1.32.0-B0021

.devcontainer/Dockerfile, docs/customization/enforce-codeowners.md, docs/en/baselines/Azure.MCSB.v1.md, docs/en/rules/index.md, docs/en/rules/module.md, docs/es/rules/index.md, docs/es/rules/module.md
Updates for code ownership sample to more clearly explain the context.
=> Update code ownership sample

.devcontainer/devcontainer.json
Update codespaces configuration to add spellcheck and improve selection of PowerShell version.
=> Minor updates to codespace config

docs/CHANGELOG-v1.md, docs/en/rules/Azure.AKS.Version.md, docs/setup/configuring-options.md, docs/setup/configuring-rules.md, src/PSRule.Rules.Azure/rules/Config.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json, tests/PSRule.Rules.Azure.Tests/Resources.AKS.json
- Updated `Azure.AKS.Version` to use latest stable version `1.27.7`.
Fixes #2581
=> Updated AKS minimum version to 1.27.7 #2581

docs/CHANGELOG-v1.md, docs/en/rules/Azure.AppConfig.DisableLocalAuth.md, docs/en/rules/Azure.AppConfig.GeoReplica.md, docs/en/rules/Azure.AppConfig.Name.md, docs/en/rules/Azure.AppConfig.PurgeProtect.md, docs/en/rules/Azure.AppConfig.SKU.md, docs/examples-appconfig.bicep, docs/examples-appconfig.json, src/PSRule.Rules.Azure/rules/Azure.AppConfig.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.AppConfig.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1
- Promoted `Azure.AppConfig.GeoReplica` to GA rule set.
Fixes #2592
=> Promoted Azure.AppConfig.GeoReplica to GA #2592

docs/en/baselines/Azure.All.md, docs/en/baselines/Azure.Default.md, docs/en/baselines/Azure.GA_2020_06.md, docs/en/baselines/Azure.GA_2020_09.md, docs/en/baselines/Azure.GA_2020_12.md, docs/en/baselines/Azure.GA_2021_03.md, docs/en/baselines/Azure.GA_2021_06.md, docs/en/baselines/Azure.GA_2021_09.md, docs/en/baselines/Azure.GA_2021_12.md, docs/en/baselines/Azure.GA_2022_03.md, docs/en/baselines/Azure.GA_2022_06.md, docs/en/baselines/Azure.GA_2022_09.md, docs/en/baselines/Azure.GA_2022_12.md, docs/en/baselines/Azure.GA_2023_03.md, docs/en/baselines/Azure.GA_2023_06.md, docs/en/baselines/Azure.GA_2023_09.md, docs/en/baselines/Azure.Preview.md, docs/en/rules/index.md, docs/en/rules/module.md, docs/en/rules/resource.md, docs/es/rules/index.md, docs/es/rules/module.md, docs/es/rules/resource.md, mkdocs.yml, requirements-docs.txt
Updated contributors plugin for updates to pages.
=> Updated docs change plugins

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/ExpressionParser.cs, src/PSRule.Rules.Azure/Data/Template/ExpressionStream.cs, tests/PSRule.Rules.Azure.Tests/ExpressionBuilderTests.cs, tests/PSRule.Rules.Azure.Tests/ExpressionParserTests.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.33.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.33.json
- Fixed quotes get incorrectly duplicated.
Fixes #2593 
=> Fixes quotes get incorrectly duplicated #2593

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/Template.Policy.WithDeployment.json, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- Fixed failure to expand copy loop in a Azure Policy deployment.
Fixes #2605 
=> Fixes policy deployment copy loop #2605

bicepconfig.json, docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs, src/PSRule.Rules.Azure/Data/Template/Functions.cs, src/PSRule.Rules.Azure/Data/Template/RuleDataExportVisitor.cs, tests/PSRule.Rules.Azure.Tests/FunctionTests.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.34.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.34.child.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.34.json
- Fixed cast exception when expanding the union of an array and mock.
Fixes #2614
=> Fixes cast with union array and mock #2614

docs/CHANGELOG-v1.md
What's changed since v1.32.0:
- Bug fixes:
- Fixed quotes get incorrectly duplicated by @BernieWhite.
[#2593](https://github.com/Azure/PSRule.Rules.Azure/issues/2593)
- Fixed failure to expand copy loop in a Azure Policy deployment by @BernieWhite.
[#2605](https://github.com/Azure/PSRule.Rules.Azure/issues/2605)
- Fixed cast exception when expanding the union of an array and mock by @BernieWhite.
[#2614](https://github.com/Azure/PSRule.Rules.Azure/issues/2614)
=> Release v1.32.1

README.md, docs/assets/stylesheets/extra.css, docs/en/baselines/Azure.All.md, docs/en/baselines/Azure.Default.md, docs/en/baselines/Azure.GA_2022_09.md, docs/en/baselines/Azure.GA_2023_03.md, docs/en/baselines/Azure.GA_2023_06.md, docs/en/baselines/Azure.GA_2023_09.md, docs/en/baselines/Azure.GA_2023_12.md, docs/en/baselines/Azure.MCSB.v1.md, docs/en/baselines/Azure.Preview.md, docs/en/baselines/Azure.Preview_2022_09.md, docs/en/baselines/Azure.Preview_2022_12.md, docs/en/baselines/Azure.Preview_2023_03.md, docs/en/baselines/Azure.Preview_2023_09.md, docs/en/baselines/Azure.Preview_2023_12.md, docs/en/rules/index.md, docs/en/rules/module.md, docs/en/rules/resource.md, docs/es/rules/index.md, docs/es/rules/module.md, docs/es/rules/resource.md, docs/hooks/shortcodes.py, docs/setup/configuring-expansion.md, docs/setup/configuring-rules.md, docs/working-with-baselines.md, mkdocs.yml
Improve linking to rule configuration.
=> Improve doc config links

.vscode/settings.json, docs/CHANGELOG-v1.md, docs/en/rules/Azure.Cognitive.ManagedIdentity.md, docs/examples-cognitive.bicep, docs/examples-cognitive.json, pipeline.build.ps1, src/PSRule.Rules.Azure/rules/Azure.Cognitive.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.Cognitive.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.Cognitive.json, tests/PSRule.Rules.Azure.Tests/cognitive.tests.bicep, tests/PSRule.Rules.Azure.Tests/cognitive.tests.json
- Relax `Azure.Cognitive.ManagedIdentity` to required configurations.
Fixes #2559.
=> Relax Azure.Cognitive.ManagedIdentity to required configurations #2559

pipeline.build.ps1
- Fix docs build with rule source path.
=> Fix docs build

.github/workflows/docs.yaml, data/policy-ignore.json, docs/CHANGELOG-v1.md, docs/en/rules/Azure.ACR.AdminUser.md, docs/en/rules/Azure.ACR.AnonymousAccess.md, docs/en/rules/Azure.ADX.ManagedIdentity.md, docs/en/rules/Azure.AKS.ManagedIdentity.md, docs/en/rules/Azure.APIM.ManagedIdentity.md, docs/en/rules/Azure.AppService.ManagedIdentity.md, docs/en/rules/Azure.Cognitive.ManagedIdentity.md, docs/en/rules/Azure.FrontDoor.State.md, docs/en/rules/Azure.ML.ComputeIdleShutdown.md, docs/en/rules/Azure.VM.AMA.md, docs/en/rules/Azure.VM.UseManagedDisks.md, docs/en/rules/Azure.VMSS.AMA.md, docs/es/rules/Azure.ACR.AdminUser.md, docs/examples-acr.bicep, docs/examples-acr.json, docs/examples-vm.bicep, docs/examples-vm.json, src/PSRule.Rules.Azure/rules/Azure.ACR.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.VM.Rule.ps1
- Updates to docs and rules working towards #2570.
=> Update to rules and docs #2570

.github/workflows/docs.yaml
=> Fix docs pipeline env

docs/concepts/policy-as-rules.md
Update docs to flag exist rule limitation related to #2482.
=> Flag existing rules limitation #2482

docs/CHANGELOG-v1.md
What's changed since v1.32.1:
- Updated `Azure.AppGwWAF.RuleGroups` to use the rule sets by @BenjaminEngeset.
[#2629](https://github.com/Azure/PSRule.Rules.Azure/issues/2629)
- The latest Bot Manager rule set is now `1.0`.
- The latest OWASP rule set is now `3.2`.
- Cognitive Services:
- Relaxed `Azure.Cognitive.ManagedIdentity` to configurations that require managed identities by @BernieWhite.
[#2559](https://github.com/Azure/PSRule.Rules.Azure/issues/2559)
- Checks for Azure Hybrid Benefit `Azure.VM.UseHybridUseBenefit` are not enabled by default by @BernieWhite.
[#2493](https://github.com/Azure/PSRule.Rules.Azure/issues/2493)
- To enable, set the `AZURE_VM_USE_HYBRID_USE_BENEFIT` option to `true`.
- Added …
=> Pre-release v1.33.0-B0023

docs/CHANGELOG-v1.md, docs/en/rules/Azure.Databricks.PublicAccess.md, docs/en/rules/Azure.Databricks.SKU.md, docs/faq.md, src/PSRule.Rules.Azure/rules/Azure.Databricks.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.Databricks.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.Databricks.json
- 2 ADB rules added, min SKU and Public Access
- 
- minor text update
=> Databricks - New Rules added

docs/CHANGELOG-v1.md
What's changed since pre-release v1.33.0-B0023:
- New rules:
- Databricks:
- Check that Databricks workspaces use a non-trial SKU by @batemansogq.
[#2646](https://github.com/Azure/PSRule.Rules.Azure/issues/2646)
- Check that Databricks workspaces require use of private endpoints by @batemansogq.
[#2646](https://github.com/Azure/PSRule.Rules.Azure/issues/2646)
- Engineering:
- Bump xunit to v2.6.6.
[#2645](https://github.com/Azure/PSRule.Rules.Azure/pull/2645)
- Bump BenchmarkDotNet to v0.13.12.
[#2636](https://github.com/Azure/PSRule.Rules.Azure/pull/2636)
- Bump BenchmarkDotNet.Diagnostics.Windows to v0.13.12.
[#2636](https://github.com/Azure/PSRule.Rules.Azure/pull/2636)
=> Pre-release v1.33.0-B0053

docs/en/rules/Azure.EventGrid.DisableLocalAuth.md, docs/en/rules/Azure.EventGrid.ManagedIdentity.md, docs/en/rules/Azure.EventGrid.TopicPublicAccess.md, docs/examples-eventgrid.bicep, docs/examples-eventgrid.json
Updates to Event Grid docs related to #2570.
=> Updated Event Grid docs

docs/CHANGELOG-v1.md, docs/en/rules/Azure.DevBox.ProjectLimit.md, docs/examples-devbox.bicep, docs/examples-devbox.json, src/PSRule.Rules.Azure/Pipeline/Export/ResourceExportVisitor.cs, src/PSRule.Rules.Azure/rules/Azure.DevBox.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.DevBox.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.DevBox.json
- Check that projects limit the number of Dev Boxes per user.
Fixes #2654 
=> Check for dev box project limits #2654

docs/CHANGELOG-v1.md
What's changed since pre-release v1.33.0-B0053:
- New rules:
- Dev Box:
- Check that projects limit the number of Dev Boxes per user by @BernieWhite.
[#2654](https://github.com/Azure/PSRule.Rules.Azure/issues/2654)
- Bug fixes:
- Fixed `Azure.VM.DiskSizeAlignment` does not handle smaller sizes and ultra disks by @BernieWhite.
[#2656](https://github.com/Azure/PSRule.Rules.Azure/issues/2656)
=> Pre-release v1.33.0-B0088

docs/CHANGELOG-v1.md
What's changed since pre-release v1.33.0-B0088:
- Bug fixes:
- Fixed `Azure.Template.TemplateFile` to support with `languageVersion` 2.0 template properties by @MrRoundRobin.
[#2660](https://github.com/Azure/PSRule.Rules.Azure/issues/2660)
=> Pre-release v1.33.0-B0126

docs/en/rules/Azure.KeyVault.PurgeProtect.md, docs/en/rules/Azure.KeyVault.RBAC.md, docs/en/rules/Azure.KeyVault.SoftDelete.md, docs/examples-keyvault.bicep, docs/examples-keyvault.json
WAF alignment updates for Key Vault rule docs. Related to #2570
=> Updates to Key Vault rules docs

docs/CHANGELOG-v1.md, docs/en/rules/Azure.ACR.Usage.md, src/PSRule.Rules.Azure/Pipeline/Export/ResourceExportVisitor.cs, src/PSRule.Rules.Azure/rules/Azure.ACR.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.ACR.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.ACR.json
- Fixed inconclusive result reported for `Azure.ACR.Usage`.
- Fixed export of Front Door resource data is incomplete.
Fixes #2494
Fixes #2668 
=> Fixes for ACR usage and Front Door export #2494 #2668

docs/CHANGELOG-v1.md
What's changed since v1.33.1:
- Bug fixes:
- Fixed false positive of `Azure.Resource.AllowedRegions` raised during assertion call by @BernieWhite.
[#2687](https://github.com/Azure/PSRule.Rules.Azure/issues/2687)
=> Release v1.33.2

docs/CHANGELOG-v1.md, docs/en/rules/Azure.Resource.AllowedRegions.md, src/PSRule.Rules.Azure/rules/Azure.Resource.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.Resource.Tests.ps1
Merge fixes from v1.33.2:
- Bug fixes:
- Fixed false positive of `Azure.Resource.AllowedRegions` raised during assertion call by @BernieWhite.
[#2687](https://github.com/Azure/PSRule.Rules.Azure/issues/2687)
Fixes #2687
=> Merge fixes from v1.33.2

docs/en/rules/Azure.EventHub.DisableLocalAuth.md, docs/en/rules/Azure.EventHub.MinTLS.md, docs/en/rules/Azure.NSG.AnyInboundSource.md, docs/examples-eventhub.bicep, docs/examples-eventhub.json, docs/examples-vnet.bicep, docs/examples-vnet.json, src/PSRule.Rules.Azure/rules/Azure.EventHub.Rule.yaml, src/PSRule.Rules.Azure/rules/Azure.NSG.Rule.ps1
Documentation and metadata updates for rules.
=> Documentation and metadata updates

.ps-rule/Rule.Rule.ps1, .vscode/markdown.code-snippets, .vscode/powershell.code-snippets, docs/en/rules/Azure.MySQL.UseFlexible.md, docs/en/rules/Azure.RSV.StorageType.md, src/PSRule.Rules.Azure/rules/Azure.MySQL.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.RSV.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.SQL.Rule.ps1
- Completed adding pillar metadata to each rule.
- Flipped CI checks to fail on new rules that don't set this tag metadata.
Fixes #1772
=> Complete pillar metadata

docs/CHANGELOG-v1.md
What's changed since v1.33.2:
- New rules:
- Check that user mode pools have a minimum number of nodes by @BernieWhite.
[#2683](https://github.com/Azure/PSRule.Rules.Azure/issues/2683)
- Added configuration to support changing the minimum number of node and to exclude node pools.
- Set `AZURE_AKS_CLUSTER_USER_POOL_MINIMUM_NODES` to set the minimum number of user nodes.
- Set `AZURE_AKS_CLUSTER_USER_POOL_EXCLUDED_FROM_MINIMUM_NODES` to exclude a specific node pool by name.
- Updated `Azure.AKS.MinNodeCount` the count nodes system node pools by @BernieWhite.
[#2683](https://github.com/Azure/PSRule.Rules.Azure/issues/2683)
- Improved guidance and examples specifically for system node pools.
- Added configuration to …
=> Pre-release v1.34.0-B0022

.vscode/settings.json, docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/PSRule.Rules.Azure.csproj, src/PSRule.Rules.Azure/README.md, src/SDK/SDK.csproj
- Improved debugging experience by providing symbols for .NET code.
Fixes #2712 
=> Add symbols for .NET code #2712

bicepconfig.json, docs/CHANGELOG-v1.md, docs/troubleshooting.md, src/PSRule.Rules.Azure/Data/Template/CustomTypeDependencyGraph.cs, src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs, src/PSRule.Rules.Azure/Data/Template/TypeDefinition.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.28.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.28.child.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.28.export.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.28.json
- Added support for type/ variable/ and function imports from Bicep files.
Fixes #2537
=> Added support for Bicep imports #2537

docs/CHANGELOG-v1.md
What's changed since pre-release v1.34.0-B0022:
- Added support for type/ variable/ and function imports from Bicep files by @BernieWhite.
[#2537](https://github.com/Azure/PSRule.Rules.Azure/issues/2537)
- Engineering:
- Improved debugging experience by providing symbols for .NET code by @BernieWhite.
[#2712](https://github.com/Azure/PSRule.Rules.Azure/issues/2712)
=> Pre-release v1.34.0-B0047

.vscode/markdown.code-snippets, .vscode/yaml.code-snippets, data/policy-ignore.json, docs/CHANGELOG-v1.md, docs/en/rules/Azure.Cognitive.DisableLocalAuth.md, docs/en/rules/Azure.ContainerApp.Insecure.md, docs/en/rules/Azure.ContainerApp.ManagedIdentity.md, docs/en/rules/Azure.Storage.BlobAccessType.md, docs/en/rules/Azure.Storage.BlobPublicAccess.md, docs/en/rules/Azure.Storage.MinTLS.md, docs/en/rules/Azure.Storage.SecureTransfer.md, src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitor.cs, src/PSRule.Rules.Azure/Data/Template/TokenStream.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/Policy.assignment.5.json, tests/PSRule.Rules.Azure.Tests/PolicyAssignmentVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/PolicyIgnoreDataTests.cs
- Added duplicate policies to default ignore list.
- Fixes for policy as rules.
Progress towards #1731 #181 #1323
=> Fixes for policy as rule and policy ignore #1731 #181 #1323

data/policy-ignore.json, docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Common/JsonExtensions.cs, src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitor.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/Policy.assignment.6.json, tests/PSRule.Rules.Azure.Tests/Policy.assignment.7.json, tests/PSRule.Rules.Azure.Tests/PolicyAssignmentVisitorTests.cs
- Fixed policy as rules export issues.
Fixes #2724 
Fixes #2725 
Fixes #2726
Fixes #2727
=> Fixes for policy as rules export issues #2724 #2725 #2726

docs/CHANGELOG-v1.md, docs/en/rules/Azure.PostgreSQL.AAD.md, src/PSRule.Rules.Azure/Pipeline/Export/ResourceExportVisitor.cs
- Fixed export of in-flight data for flexible PostgreSQL servers.
Fixes #2744
=> Fixes in-flight export of PostgreSql #2744

docs/CHANGELOG-v1.md
What's changed since v1.34.1:
- Bug fixes:
- Fixed export of in-flight data for flexible PostgreSQL servers by @BernieWhite.
[#2744](https://github.com/Azure/PSRule.Rules.Azure/issues/2744)
=> Release v1.34.2

data/policy-ignore.json, docs/CHANGELOG-v1.md, docs/en/rules/Azure.SQL.AAD.md, docs/en/rules/Azure.ServiceBus.DisableLocalAuth.md, docs/en/rules/Azure.ServiceBus.MinTLS.md, docs/examples-servicebus.bicep, docs/examples-servicebus.json, src/PSRule.Rules.Azure/rules/Azure.ServiceBus.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.ServiceBus.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.ServiceBus.Tests.ps1
- Documentation improvements towards #2570
=> Documentation improvements #2570

BaselineToc.Doc.ps1, docs/en/rules/Azure.ACR.Retention.md, docs/en/rules/Azure.ADX.Usage.md, docs/en/rules/Azure.VM.DiskAttached.md, docs/en/rules/Azure.VM.PromoSku.md, docs/en/rules/Azure.VM.ShouldNotBeStopped.md, docs/examples-acr.bicep, docs/examples-acr.json, src/PSRule.Rules.Azure/rules/Azure.VM.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.VM.Tests.ps1
- Documentation improvements related to #2570.
=> WAF documentation improvements #2570

.devcontainer/container-start.ps1
- Add bicep CLI to dev container.
=> Copy bicep in dev container

docs/en/rules/Azure.Search.IndexSLA.md, docs/en/rules/Azure.Search.ManagedIdentity.md, docs/en/rules/Azure.Search.Name.md, docs/en/rules/Azure.Search.QuerySLA.md, docs/en/rules/Azure.Search.SKU.md, src/PSRule.Rules.Azure/rules/Azure.Search.Rule.ps1
Renaming in documentation Cognitive Search to AI Search.
=> Update documentation naming for AI Search

docs/CHANGELOG-v1.md
What's changed since pre-release v1.35.0-B0012:
- Add rule severity to rule documentation pages by @BernieWhite.
[#1243](https://github.com/Azure/PSRule.Rules.Azure/issues/1243)
- Add documentation redirects for renamed rules by @BernieWhite.
[#2757](https://github.com/Azure/PSRule.Rules.Azure/issues/2757)
- Engineering:
- Bump coverlet.collector to v6.0.2.
[#2754](https://github.com/Azure/PSRule.Rules.Azure/pull/2754)
- Bug fixes:
- Fixed false negative from `Azure.LB.AvailabilityZone` when zone list is empty or null by @jtracey93.
[#2759](https://github.com/Azure/PSRule.Rules.Azure/issues/2759)
=> Pre-release v1.35.0-B0030

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/Mocks.cs, src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.35.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.35.child.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.35.json
- Fixed failed to expand JObject value with invalid key.
Fixes #2751 
=> Fixes expand issue with JObject key #2751

data/policy-ignore.json, docs/CHANGELOG-v1.md, docs/en/rules/Azure.AKS.AutoUpgrade.md, docs/en/rules/Azure.AKS.AzurePolicyAddOn.md, docs/en/rules/Azure.AKS.LocalAccounts.md, docs/en/rules/Azure.AKS.Version.md, docs/examples-aks.bicep, docs/examples-aks.json, docs/setup/configuring-options.md, docs/setup/configuring-rules.md, src/PSRule.Rules.Azure/rules/Config.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json, tests/PSRule.Rules.Azure.Tests/Resources.AKS.json
- Updated `Azure.AKS.Version` to use `1.27.9` as the minimum version.
- Quality updates to rule documentation towards #2570.
- Additional policies added to default ignore list towards #1731.
Fixes #2771.
=> Updated AKS version to 1.27.9 #2771 #1731 #2570

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Pipeline/Export/ResourceExportVisitor.cs
- Improved export of in-flight data for Event Grid and Azure Firewall Policies.
Fixes #2774
=> Improve export of Event Grid and Firewall Policies #2774

docs/en/baselines/Azure.All.md, docs/en/baselines/Azure.Default.md, docs/en/baselines/Azure.GA_2020_12.md, docs/en/baselines/Azure.GA_2021_03.md, docs/en/baselines/Azure.GA_2021_06.md, docs/en/baselines/Azure.GA_2021_09.md, docs/en/baselines/Azure.GA_2021_12.md, docs/en/baselines/Azure.GA_2022_03.md, docs/en/baselines/Azure.GA_2022_06.md, docs/en/baselines/Azure.GA_2022_09.md, docs/en/baselines/Azure.GA_2022_12.md, docs/en/baselines/Azure.GA_2023_03.md, docs/en/baselines/Azure.GA_2023_06.md, docs/en/baselines/Azure.GA_2023_09.md, docs/en/baselines/Azure.GA_2023_12.md, docs/en/baselines/Azure.Pillar.OperationalExcellence.md, docs/en/baselines/Azure.Preview.md, docs/en/rules/index.md, docs/en/rules/module.md, docs/en/rules/resource.md, docs/es/rules/index.md, docs/es/rules/module.md, docs/es/rules/resource.md, docs/faq.md, docs/versioning.md
Updated docs on change and versioning.
=> Update docs on versioning and changes

docs/CHANGELOG-v1.md
What's changed since pre-release v1.35.0-B0055:
- Improved export of in-flight data for Event Grid and Azure Firewall Policies by @BernieWhite.
[#2774](https://github.com/Azure/PSRule.Rules.Azure/issues/2774)
=> Pre-release v1.35.0-B0084

docs/CHANGELOG-v1.md, docs/en/baselines/Azure.All.md, docs/en/baselines/Azure.Default.md, docs/en/baselines/Azure.GA_2022_09.md, docs/en/baselines/Azure.GA_2022_12.md, docs/en/baselines/Azure.GA_2023_03.md, docs/en/baselines/Azure.GA_2023_06.md, docs/en/baselines/Azure.GA_2023_09.md, docs/en/baselines/Azure.GA_2023_12.md, docs/en/baselines/Azure.GA_2024_03.md, docs/en/baselines/Azure.MCSB.v1.md, docs/en/baselines/Azure.Preview.md, docs/en/baselines/Azure.Preview_2024_03.md, docs/en/rules/index.md, docs/en/rules/module.md, docs/en/rules/resource.md, docs/es/rules/index.md, docs/es/rules/module.md, docs/es/rules/resource.md, src/PSRule.Rules.Azure/rules/Baseline.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1
- Added March 2024 baselines `Azure.GA_2024_03` and `Azure.Preview_2024_03`.
- Includes rules released before or during March 2024.
- Marked `Azure.GA_2023_12` and `Azure.Preview_2023_12` baselines as obsolete.
Fixes #2781
=> Added March 2024 baselines #2781

docs/CHANGELOG-v1.md
What's changed since pre-release v1.35.0-B0084:
- Added March 2024 baselines `Azure.GA_2024_03` and `Azure.Preview_2024_03` by @BernieWhite.
[#2781](https://github.com/Azure/PSRule.Rules.Azure/issues/2781)
- Includes rules released before or during March 2024.
- Marked `Azure.GA_2023_12` and `Azure.Preview_2023_12` baselines as obsolete.
- Renamed Cognitive Services rules to Azure AI by @BernieWhite.
[#2776](https://github.com/Azure/PSRule.Rules.Azure/issues/2776)
- Rules that were previously named `Azure.Cognitive.*` have been renamed to `Azure.AI.*`.
- For each rule that has been renamed, an alias has been added to reference the old name.
=> Pre-release v1.35.0-B0116

CONTRIBUTING.md, docs/en/rules/Azure.EventGrid.DisableLocalAuth.md, docs/en/rules/Azure.EventGrid.ManagedIdentity.md, docs/en/rules/Azure.EventGrid.TopicPublicAccess.md, docs/hooks/shortcodes.py
Added short code to link to AVM modules from rule docs.
=> Add support for AVM references

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.27.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.27.child.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.27.json
- Fixed null parameter overrides default value.
Fixes #2795 
=> Fixes null parameter overrides default #2795

docs/CHANGELOG-v1.md
What's changed since v1.35.0:
- Bug fixes:
- Fixed null parameter overrides default value by @BernieWhite.
[#2795](https://github.com/Azure/PSRule.Rules.Azure/issues/2795)
=> Release v1.35.1

docs/CHANGELOG-v1.md
What's changed since v1.35.1:
- Bug fixes:
- Fixed regression when handing ambiguous mock array outputs by @BernieWhite.
[#2801](https://github.com/Azure/PSRule.Rules.Azure/issues/2801)
=> Release v1.35.2

docs/CHANGELOG-v1.md, docs/en/rules/Azure.ContainerApp.AvailabilityZone.md, docs/en/rules/Azure.ContainerApp.DisableAffinity.md, docs/en/rules/Azure.ContainerApp.ExternalIngress.md, docs/en/rules/Azure.ContainerApp.Insecure.md, docs/en/rules/Azure.ContainerApp.ManagedIdentity.md, docs/en/rules/Azure.ContainerApp.Name.md, docs/en/rules/Azure.ContainerApp.PublicAccess.md, docs/en/rules/Azure.ContainerApp.RestrictIngress.md, docs/examples-containerapp.bicep, docs/examples-containerapp.json, src/PSRule.Rules.Azure/rules/Azure.ContainerApp.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.ContainerApp.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.ContainerApp.json
- Check that Container App environments are zone redundant.
Fixes #2791
=> Check that Container App environments are zone redundant #2791

docs/en/rules/Azure.ACR.AdminUser.md, docs/en/rules/Azure.ACR.AnonymousAccess.md, docs/en/rules/Azure.ACR.ContainerScan.md, docs/en/rules/Azure.ACR.ContentTrust.md, docs/en/rules/Azure.ACR.SoftDelete.md, docs/hooks/shortcodes.py
- Add and enable AVM links in docs.
=> Enable AVM links

docs/hooks/shortcodes.py
=> Fix AVM shortcode

docs/hooks/shortcodes.py
Fix call to external in docs shortcode.
=> Fix external reference

docs/CHANGELOG-v1.md, docs/en/rules/Azure.LB.AvailabilityZone.md, docs/examples-vnet.bicep, docs/examples-vnet.json, src/PSRule.Rules.Azure/rules/Azure.LB.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.LB.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.VirtualNetwork.json
- Fixed false positive with load balancers that use a public IP.
Fixes #2814
=> Fixed false positive with load balancers that use a public IP #2814

docs/CHANGELOG-v1.md
What's changed since v1.35.2:
- Bug fixes:
- Fixed false positive with load balancers that use a public IP by @BernieWhite.
[#2814](https://github.com/Azure/PSRule.Rules.Azure/issues/2814)
=> Release v1.35.3

docs/CHANGELOG-v1.md, docs/en/rules/Azure.LB.AvailabilityZone.md, docs/examples-vnet.bicep, docs/examples-vnet.json, src/PSRule.Rules.Azure/rules/Azure.LB.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.LB.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.VirtualNetwork.json
Merge patch updates from v1.35.3:
- Bug fixes:
- Fixed false positive with load balancers that use a public IP by @BernieWhite.
Fixes #2814
=> Merge patch v1.35.3

.github/workflows/docs.yaml, docs/en/rules/Azure.LB.Probe.md, docs/en/rules/Azure.LB.StandardSKU.md, docs/examples-vnet.bicep, docs/examples-vnet.json
Updates to load balancer rule docs.
=> Updates to LB rule docs

.github/workflows/docs.yaml
- Fixes for docs pipeline.
- [ x] PR has a meaningful title
=> Fixes for docs pipeline

docs/CHANGELOG-v1.md
What's changed since v1.35.3:
- New rules:
- Check that Container Apps have a minimum number of replicas by @BernieWhite.
[#2790](https://github.com/Azure/PSRule.Rules.Azure/issues/2790)
- Check that Container App environments are zone redundant by @BernieWhite.
[#2791](https://github.com/Azure/PSRule.Rules.Azure/issues/2791)
- Cosmos DB:
- Check that database accounts only accept a minimum of TLS 1.2 by @BernieWhite.
[#2809](https://github.com/Azure/PSRule.Rules.Azure/issues/2809)
- Quality updates to documentation by @lukemurraynz @BernieWhite.
[#2789](https://github.com/Azure/PSRule.Rules.Azure/pull/2789)
[#2570](https://github.com/Azure/PSRule.Rules.Azure/issues/2570)
- Additional policies added to default ignore list by @BernieWhite. …
=> Pre-release v1.36.0-B0020

.vscode/settings.json, docs/CHANGELOG-v1.md, docs/en/rules/Azure.EntraDS.NTLM.md, docs/en/rules/Azure.EntraDS.RC4.md, docs/en/rules/Azure.EntraDS.TLS.md, docs/examples-entrads.bicep, docs/examples-entrads.json, src/PSRule.Rules.Azure/rules/Azure.EntraDS.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.DevBox.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Azure.EntraDS.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.EntraDS.json
- Entra Domain Services:
- Check that instances use a minimum version of NTLM.
- Check that instances use a minimum version of TLS.
- Check that instances do not use RC4 encryption.
Fixes #2837
=> Add Entra Domain Service rules #2837

docs/CHANGELOG-v1.md
What's changed since pre-release v1.36.0-B0046:
- New rules:
- Entra Domain Services:
- Check that instances use a minimum version of NTLM by @BernieWhite.
[#2837](https://github.com/Azure/PSRule.Rules.Azure/issues/2837)
- Check that instances use a minimum version of TLS by @BernieWhite.
[#2837](https://github.com/Azure/PSRule.Rules.Azure/issues/2837)
- Check that instances do not use RC4 encryption by @BernieWhite.
[#2837](https://github.com/Azure/PSRule.Rules.Azure/issues/2837)
- **Important change**: Deprecated rules with no clear WAF alignment by @BernieWhite.
[#2493](https://github.com/Azure/PSRule.Rules.Azure/issues/2493)
- The following rules are deprecated:
- `Azure.Template.UseParameters`
- `Azure.Template.UseVariables`
- `Azure.Template.DefineParameters` …
=> Pre-release v1.36.0-B0077

.vscode/settings.json, docs/CHANGELOG-v1.md, docs/en/rules/Azure.AKS.AvailabilityZone.md, docs/en/rules/Azure.APIM.AvailabilityZone.md, docs/en/rules/Azure.APIM.CORSPolicy.md, docs/en/rules/Azure.APIM.MultiRegion.md, docs/en/rules/Azure.AppGw.AvailabilityZone.md, docs/en/rules/Azure.AppGw.MinInstance.md, docs/en/rules/Azure.AppInsights.Workspace.md, docs/en/rules/Azure.AppService.ARRAffinity.md, docs/en/rules/Azure.AppService.AlwaysOn.md, docs/en/rules/Azure.AppService.HTTP2.md, docs/en/rules/Azure.AppService.MinTLS.md, docs/en/rules/Azure.Cosmos.MinTLS.md, docs/en/rules/Azure.MariaDB.MinTLS.md, docs/en/rules/Azure.MySQL.MinTLS.md, docs/en/rules/Azure.PublicIP.AvailabilityZone.md, docs/en/rules/Azure.Redis.MinTLS.md, docs/en/rules/Azure.RedisEnterprise.MinTLS.md, docs/en/rules/Azure.SQL.MinTLS.md, docs/en/rules/Azure.Storage.MinTLS.md
- Quality updates to documentation.
Working towards #2570
=> Quality updates to rule documentation #2570

data/policy-ignore.json, docs/CHANGELOG-v1.md, docs/en/rules/Azure.Cosmos.DisableMetadataWrite.md, docs/en/rules/Azure.Cosmos.SLA.md, docs/examples-cosmos.bicep, docs/examples-cosmos.json, src/PSRule.Rules.Azure/rules/Azure.Cosmos.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.Cosmos.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.Cosmos.json
- Check that database accounts use a paid tier.
Fixes #2845
=> Check that database accounts use a paid tier #2845

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.38.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.38.child.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.38.json, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.38.site.bicep
- Fixed dependency ordering for cross scope deployments.
Fixes #2850
- [x PR has a meaningful title
=> Fixed dependency ordering for cross scope deployments #2850

docs/CHANGELOG-v1.md, docs/en/rules/Azure.AppGw.MigrateWAFPolicy.md, docs/en/rules/Azure.AppGw.WAF.MigratePolicy.md, src/PSRule.Rules.Azure/rules/Azure.AppGw.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.AppGw.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.AppGw.json
Fixes #2877
Added Azure.AppGw.MigrateWAFPolicy.
=> feat(new): Added Azure.AppGw.MigrateWAFPolicy

docs/CHANGELOG-v1.md
What's changed since pre-release v1.37.0-B0009:
- Added support for new Bicep language features introduced in v0.27.1 by @BernieWhite.
[#2860](https://github.com/Azure/PSRule.Rules.Azure/issues/2860)
[#2859](https://github.com/Azure/PSRule.Rules.Azure/issues/2859)
- Added support for `shallowMerge`, `groupBy`, `objectKeys`, and `mapValues`.
- Updated syntax for Bicep lambda usage of `map`, `reduce`, and `filter` which now support indices.
- Added support for spread operator.
- New rules:
- Check that WAF v2 doesn't use legacy WAF configuration by @BenjaminEngeset.
[#2877](https://github.com/Azure/PSRule.Rules.Azure/issues/2877)
- Azure Managed Grafana:
- Check that Azure Managed Grafana workspaces uses Grafana version 10 by @BenjaminEngeset. …
=> Pre-release v1.37.0-B0034

docs/CHANGELOG-v1.md, docs/en/rules/Azure.VMSS.AutoInstanceRepairs.md, src/PSRule.Rules.Azure/rules/Azure.VMSS.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.VMSS.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.VMSS.json
Fixes #2895
Added Azure.Azure.VMSS.AutoInstanceRepairs.
=> feat(new): Added Azure.Azure.VMSS.AutoInstanceRepairs

docs/CHANGELOG-v1.md, docs/en/rules/Azure.Redis.EntraID.md, src/PSRule.Rules.Azure/rules/Azure.Redis.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.Redis.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.Redis.json
Fixes #2899
Added Azure.Redis.EntraID.
=> feat(new): Added Azure.Redis.EntraID

docs/CHANGELOG-v1.md, docs/en/rules/Azure.APIM.MultiRegion.md, src/PSRule.Rules.Azure/rules/Azure.APIM.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.APIM.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1
Fixes #2787 
Updated Azure.APIM.MultiRegion to improve detection for non-premium SKUs.
=> feat: Updated Azure.APIM.MultiRegion

docs/en/rules/Azure.Redis.AvailabilityZone.md, docs/en/rules/Azure.Redis.MaxMemoryReserved.md, docs/en/rules/Azure.Redis.MinSKU.md, docs/en/rules/Azure.Redis.MinTLS.md, docs/en/rules/Azure.Redis.NonSslPort.md, docs/en/rules/Azure.Redis.PublicNetworkAccess.md, docs/en/rules/Azure.VNET.UseNSGs.md, docs/en/rules/Azure.VNG.ERLegacySKU.md, docs/en/rules/Azure.VNG.VPNActiveActive.md, docs/en/rules/Azure.VNG.VPNAvailabilityZoneSKU.md, docs/en/rules/Azure.VNG.VPNLegacySKU.md, docs/examples-vng.bicep, docs/examples-vng.json, src/PSRule.Rules.Azure/rules/Azure.VNG.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.VNG.Rule.yaml
=> Rule docs quality updates

docs/CHANGELOG-v1.md
What's changed since pre-release v1.37.0-B0034:
- New rules:
- App Service:
- Check that applications uses supported Node.js runtime versions by @BenjaminEngeset.
[#2879](https://github.com/Azure/PSRule.Rules.Azure/issues/2879)
- Verify that cache instances have Entra ID authentication enabled by @BenjaminEngeset.
[#2899](https://github.com/Azure/PSRule.Rules.Azure/issues/2899)
- Log Analytics:
- Check that workspaces have workspace replication enabled by @BenjaminEngeset.
[#2893](https://github.com/Azure/PSRule.Rules.Azure/issues/2893)
- Check that automatic instance repairs are enabled by @BenjaminEngeset.
[#2895](https://github.com/Azure/PSRule.Rules.Azure/issues/2895)
- **Important change**: …
=> Pre-release v1.37.0-B0071

docs/CHANGELOG-v1.md, docs/en/rules/Azure.VNG.MaintenanceConfig.md, src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.VNG.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.VNG.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.VirtualNetwork.json
Fixes #2910
Added Azure.VNG.MaintenanceConfig.
=> feat(new): Added Azure.VNG.MaintenanceConfig

CONTRIBUTING.md, README.md
Minor updates to readme and contributing docs.
=> Minor fixes to project docs

docs/CHANGELOG-v1.md, docs/en/rules/Azure.VM.MaintenanceConfig.md, docs/examples-vm.bicep, docs/examples-vm.json, src/PSRule.Rules.Azure/rules/Azure.VM.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1
- Updated `Azure.VM.MaintenanceConfig` to align to the reliability pillar.
Fixes #2925
=> Updated Azure.VM.MaintenanceConfig #2925

docs/CHANGELOG-v1.md, modules.json
=> Bump PowerShell dependencies.

docs/CHANGELOG-v1.md, docs/en/rules/Azure.MySQL.ZoneRedundantHA.md, src/PSRule.Rules.Azure/rules/Azure.MySQL.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.MySQL.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.MySQL.json
Fixes #2914
Added Azure.MySQL.ZoneRedundantHA.
=> feat(new): Added Azure.MySQL.ZoneRedundantHA

docs/CHANGELOG-v1.md, docs/en/rules/Azure.PostgreSQL.ZoneRedundantHA.md, src/PSRule.Rules.Azure/rules/Azure.PostgreSQL.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.PostgreSQL.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.PostgreSQL.json
Fixes #2932
Added Azure.PostgreSQL.ZoneRedundantHA.
=> feat: Added Azure.PostgreSQL.ZoneRedundantHA

docs/CHANGELOG-v1.md
What's changed since v1.37.0:
- New rules:
- Verify that Azure Database for MySQL servers have a customer-controlled maintenance window configured by @BenjaminEngeset.
[#2916](https://github.com/Azure/PSRule.Rules.Azure/issues/2916)
- Verify that servers have zone-redundant high availability (HA) configured by @BenjaminEngeset.
[#2914](https://github.com/Azure/PSRule.Rules.Azure/issues/2914)
- Verify that Azure Database for PostgreSQL servers have a customer-controlled maintenance window configured by @BenjaminEngeset.
[#2927](https://github.com/Azure/PSRule.Rules.Azure/issues/2927)
- Verify that servers have zone-redundant high availability (HA) configured by @BenjaminEngeset. …
=> Pre-release v1.38.0-B0011

docs/en/rules/Azure.AKS.NodeAutoUpgrade.md, src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.AKS.json
Added new rule to fix AKS NodeOSAutoUpgrade as part of WAF Security Pillar. 
Fix #2445.
- [ X] PR has a meaningful title
- [X ] Summarized changes
- [X ] Change is not breaking
=> New Rule Implemented for Issue-2445

data/policy-ignore.json, docs/CHANGELOG-v1.md, docs/en/rules/Azure.KeyVault.AccessPolicy.md, docs/en/rules/Azure.KeyVault.AutoRotationPolicy.md, docs/en/rules/Azure.KeyVault.Firewall.md, docs/en/rules/Azure.KeyVault.KeyName.md, docs/en/rules/Azure.KeyVault.PurgeProtect.md, docs/en/rules/Azure.KeyVault.RBAC.md, docs/en/rules/Azure.KeyVault.SoftDelete.md, docs/examples-keyvault.json, src/PSRule.Rules.Azure/rules/Azure.KeyVault.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.KeyVault.Rule.yaml, tests/PSRule.Rules.Azure.Tests/PolicyAssignmentVisitorTests.cs
- Refactoring and rule updates for #2570.
=> Refactoring and doc updates for Key Vault

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/DeploymentValue.cs, src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.40.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.40.child.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.40.json
- Fixed failed to expand with direct outputs reference.
Fixes #2935
=> Fixes expand with direct outputs reference #2935

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/TokenStreamValidator.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.9.goodStreamingJobs.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.9.json, tests/PSRule.Rules.Azure.Tests/TokenStreamValidatorTests.cs
- Fixed identification of `list*` function false positive with resource.
Fixes #2919
=> Fixed identification of list function false positive with resource #2919

docs/CHANGELOG-v1.md, docs/en/rules/Azure.ContainerApp.PublicAccess.md, docs/en/rules/Azure.ContainerApp.RestrictIngress.md, docs/examples-containerapp.bicep, docs/examples-containerapp.json
- Fixed documentation bugs for container apps.
Fixes #2876
=> Fixed documentation bugs for container apps #2876

docs/CHANGELOG-v1.md, docs/en/rules/Azure.VMSS.AvailabilityZone.md, src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.VMSS.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.VMSS.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.VMSS.json
Fixes #2902
Azure.VMSS.AvailabilityZone.
=> feat: Added Azure.VMSS.AvailabilityZone

docs/CHANGELOG-v1.md, docs/en/rules/Azure.AVD.ScheduleAgentUpdate.md, docs/examples-avd.bicep, docs/examples-avd.json, pipeline.build.ps1, src/PSRule.Rules.Azure/rules/Azure.AVD.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.AVD.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.AVD.json
- Added check for scheduled agent updates on host pools.
Fixes #2946
=> Added AVD agent update schedule #2946

docs/CHANGELOG-v1.md, docs/en/rules/Azure.VMSS.ZoneBalance.md, src/PSRule.Rules.Azure/rules/Azure.VMSS.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.VMSS.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.VMSS.json
Fixes #2901
Added Azure.VMSS.ZoneBalance.
=> feat(new): Added Azure.VMSS.ZoneBalance

bicepconfig.json, docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitor.cs, src/PSRule.Rules.Azure/Data/Template/ArrayDeploymentSymbol.cs, src/PSRule.Rules.Azure/Data/Template/Functions.cs, src/PSRule.Rules.Azure/Data/Template/ITemplateContext.cs, src/PSRule.Rules.Azure/Data/Template/NestedTemplateContext.cs, src/PSRule.Rules.Azure/Data/Template/ObjectDeploymentSymbol.cs, src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs, tests/PSRule.Rules.Azure.Tests/Bicep/SymbolicNameTestCases/Tests.Bicep.1.bicep, tests/PSRule.Rules.Azure.Tests/Bicep/SymbolicNameTestCases/Tests.Bicep.1.child.bicep, tests/PSRule.Rules.Azure.Tests/Bicep/SymbolicNameTestCases/Tests.Bicep.1.json, tests/PSRule.Rules.Azure.Tests/Bicep/SymbolicNameTestCases/bicepconfig.json, tests/PSRule.Rules.Azure.Tests/FunctionTests.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- Fixed support for `references` function.
Fixes #2922
=> Fixed support for references function #2922

docs/install.md
=> Documentation quality updates

.vscode/settings.json, docs/CHANGELOG-v1.md, docs/assets/stylesheets/extra.css, docs/faq.md, docs/setup/configuring-expansion.md, docs/setup/configuring-exports.md, docs/setup/configuring-rules.md, docs/setup/index.md, docs/setup/setup-bicep.md, docs/troubleshooting.md, mkdocs.yml, src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- Add a suppression for the `Az.Resources` import warning.
Fixes #2887
=> Add suppression for import warning

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs, src/PSRule.Rules.Azure/Data/Template/Functions.cs, src/PSRule.Rules.Azure/Data/Template/Mocks.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.13.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.13.json
- Fixed `filter` on unknown runtime property.
Fixes #2966
=> Fixed filter on unknown runtime property #2966

docs/CHANGELOG-v1.md, docs/en/rules/Azure.Cosmos.ContinuousBackup.md, src/PSRule.Rules.Azure/rules/Azure.Cosmos.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.Cosmos.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.Cosmos.json
Fixes #2954
Added Azure.Cosmos.ContinuousBackup.
=> feat(new): Added Azure.Cosmos.ContinuousBackup

docs/CHANGELOG-v1.md, docs/concepts/policy-as-rules.md, docs/install.md, docs/troubleshooting.md, modules.json, src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
- Rollback Az.Resources to v6.16.2.
Fixes #2970
=> Rollback Az.Resources #2970

docs/CHANGELOG-v1.md, docs/en/rules/Azure.SQL.MaintenanceWindow.md, src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.SQL.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.SQL.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.SQL.json
Fixes #2956
Added Azure.SQL.MaintenanceWindow.
=> feat(new): Added Azure.SQL.MaintenanceWindow

docs/CHANGELOG-v1.md, docs/en/rules/Azure.SQLMI.MaintenanceWindow.md, src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.SQLMI.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.SQLMI.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.SQLMI.json
Fixes #2979
Added Azure.SQLMI.MaintenanceWindow.
=> feat(new): Added Azure.SQLMI.MaintenanceWindow

docs/CHANGELOG-v1.md, docs/en/rules/Azure.AppService.AvailabilityZone.md, src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.AppService.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.AppService.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.AppService.json
Fixes #2964
Added Azure.AppService.AvailabilityZone.
=> feat(new): Added Azure.AppService.AvailabilityZone

docs/CHANGELOG-v1.md, docs/en/rules/Azure.ASE.AvailabilityZone.md, src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.ASE.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.ASE.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.ASE.json
Fixes #2964
Added Azure.ASE.AvailabilityZone.
=> feat(new): Added Azure.ASE.AvailabilityZone

src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.AppService.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.AppService.Tests.ps1
Fixes #2986
Updated Azure.AppService.AvailabilityZone with default reason.
=> feat: Updated Azure.AppService.AvailabilityZone

docs/CHANGELOG-v1.md, docs/en/rules/Azure.ServiceBus.GeoReplica.md, src/PSRule.Rules.Azure/rules/Azure.ServiceBus.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.ServiceBus.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.ServiceBus.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.ServiceBus.json
Working towards #2988
Added Azure.ServiceBus.GeoReplica.
=> feat(new): Added Azure.ServiceBus.GeoReplica

docs/CHANGELOG-v1.md, docs/en/rules/Azure.AKS.AuditAdmin.md, src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1
Fixes #2450
Added Azure.AKS.AuditAdmin.
=> feat(new): Added Azure.AKS.AuditAdmin

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/rules/Azure.VNET.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.VNET.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.VirtualNetwork.json
Fixes #3007
Updated Azure.VNET.UseNSGs.
=> Updated Azure.VNET.UseNSGs

.vscode/settings.json, docs/CHANGELOG-v1.md, docs/en/rules/Azure.VNET.FirewallSubnetNAT.md, docs/setup/configuring-rules.md, src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.VNET.Rule.ps1, src/PSRule.Rules.Azure/rules/Config.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.VNET.Tests.ps1, tests/PSRule.Rules.Azure.Tests/OptionsTests.cs, tests/PSRule.Rules.Azure.Tests/Resources.VirtualNetwork.json
Fixes #3005
Added Azure.VNET.FirewallSubnetNAT.
=> feat(new): Added Azure.VNET.FirewallSubnetNAT

.vscode/settings.json, docs/CHANGELOG-v1.md, docs/en/rules/Azure.VNET.PrivateSubnet.md, src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.VNET.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.VNET.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.VirtualNetwork.json
Fixes #3001
Added Azure.VNET.PrivateSubnet.
=> feat(new): Added Azure.VNET.PrivateSubnet

docs/CHANGELOG-v1.md, docs/en/rules/Azure.VM.PublicIPAttached.md, src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.VM.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.VM.Tests.ps1
=> Added Azure.VM.PublicIPAttached

.github/workflows/build.yaml, .github/workflows/docs.yaml, docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Common/ResourceHelper.cs, src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs, src/PSRule.Rules.Azure/rules/Common.Selector.Rule.yaml, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.31.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.31.child2.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.31.child3.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.31.child4.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.31.json
- Fixed expansion with deployments by resource ID at management group.
- Ignore resource tags for subscription aliases which don't support it.
Fixes #3013 
Fixes #3021
=> Fixed MG scope deployment link #3013

docs/CHANGELOG-v1.md
What's changed since pre-release v1.39.0-B0029:
- New rules:
- Verify that virtual machines does not have public IPs attached by @BenjaminEngeset.
[#11](https://github.com/Azure/PSRule.Rules.Azure/issues/11)
- Verify that virtual machine scale set instances does not have public IPs attached by @BenjaminEngeset.
[#3014](https://github.com/Azure/PSRule.Rules.Azure/issues/3014)
- Engineering:
- Bump development tools to .NET 8.0 SDK by @BernieWhite.
[#3017](https://github.com/Azure/PSRule.Rules.Azure/issues/3017)
- Bug fixed:
- Fixed expansion with deployments by resource ID at management group by @BernieWhite
[#3013](https://github.com/Azure/PSRule.Rules.Azure/issues/3013)
- Fixed subscription aliases don't support tags by @BernieWhite. …
=> Pre-release v1.39.0-B0055

docs/CHANGELOG-v1.md, docs/en/rules/Azure.VM.MultiTenantHosting.md, docs/setup/configuring-rules.md, src/PSRule.Rules.Azure/en/PSRule-rules.psd1, src/PSRule.Rules.Azure/rules/Azure.VM.Rule.ps1, src/PSRule.Rules.Azure/rules/Config.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.VM.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.VirtualMachine.json
Fixes #432
Added Azure.VM.MultiTenantHosting.
=> Added Azure.VM.MultiTenantHosting

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Common/DictionaryExtensions.cs, src/PSRule.Rules.Azure/Common/PSObjectExtensions.cs, src/PSRule.Rules.Azure/Configuration/DeploymentOption.cs, src/PSRule.Rules.Azure/Configuration/ManagementGroupOption.cs, src/PSRule.Rules.Azure/Configuration/ParameterDefaultsOption.cs, src/PSRule.Rules.Azure/Configuration/ResourceGroupOption.cs, src/PSRule.Rules.Azure/Configuration/SubscriptionOption.cs, src/PSRule.Rules.Azure/Configuration/TenantOption.cs, src/PSRule.Rules.Azure/Runtime/Helper.cs, src/PSRule.Rules.Azure/Runtime/IRuntimeService.cs, src/PSRule.Rules.Azure/Runtime/RuntimeService.cs, src/PSRule.Rules.Azure/rules/Conventions.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Global.cs, tests/PSRule.Rules.Azure.Tests/RuntimeServiceTests.cs
- Fixed loading of expansion options from non-default options.
Fixes #3033
=> Fixed loading of expansion options from non-default options #3033

docs/deprecations.md, docs/en/rules/Azure.AKS.AuditAdmin.md, docs/en/rules/Azure.AKS.AuditLogs.md, docs/en/rules/Azure.AKS.AutoUpgrade.md, docs/en/rules/Azure.AKS.AzurePolicyAddOn.md, docs/en/rules/Azure.AKS.AzureRBAC.md, docs/en/rules/Azure.AKS.LocalAccounts.md, docs/en/rules/Azure.AKS.ManagedAAD.md, docs/examples-aks.bicep, docs/examples-aks.json
Documentation quality updates.
=> AKS rule documentation quality updates

.gitignore, docs/customization/using-custom-rules.md, docs/en/rules/Azure.VMSS.ZoneBalance.md, docs/hooks/shortcodes.py, pipeline.build.ps1
Add a reference for the latest AVM module version.
=> Add docs reference for AVM latest version

docs/analyzing-resources.md, docs/creating-your-pipeline.md, docs/en/rules/Azure.AI.DisableLocalAuth.md, docs/en/rules/Azure.AI.ManagedIdentity.md, docs/en/rules/Azure.AI.PrivateEndpoints.md, docs/en/rules/Azure.AI.PublicAccess.md, docs/en/rules/Azure.AKS.SecretStore.md, docs/en/rules/Azure.AKS.SecretStoreRotation.md, docs/en/rules/Azure.AKS.UptimeSLA.md, docs/en/rules/Azure.APIM.MultiRegion.md, docs/en/rules/Azure.APIM.MultiRegionGateway.md, docs/en/rules/Azure.APIM.Protocols.md, docs/hooks/shortcodes.py, docs/setup/configuring-expansion.md
Added improvements to how we link to AVM, providing more complete information to customers.
=> Improvements to AVM documentation links

docs/en/rules/Azure.AKS.HttpAppRouting.md, docs/en/rules/Azure.AppGw.UseWAF.md, docs/en/rules/Azure.AppGw.WAFEnabled.md, docs/en/rules/Azure.Cosmos.DisableLocalAuth.md, docs/en/rules/Azure.FrontDoor.WAF.Enabled.md, docs/en/rules/Azure.Storage.Firewall.md, docs/en/rules/Azure.VM.ScriptExtensions.md, docs/en/rules/Azure.VMSS.ScriptExtensions.md
Updates to WAF categories in rule docs.
=> Quality updates for WAF #2570

docs/CHANGELOG-v1.md
What's changed since pre-release v1.39.0-B0118:
- Container Apps:
- Updated `Azure.ContainerApp.AvailabilityZone` to check for infrastructure subnet by @BernieWhite.
[#3068](https://github.com/Azure/PSRule.Rules.Azure/issues/3068)
- Configuring an infrastructure subnet is a requirement for enabling zone redundancy.
Both rule and documentation have been updated to clearly call this out.
- Updated resource providers and policy aliases.
[#3074](https://github.com/Azure/PSRule.Rules.Azure/pull/3074)
- Engineering:
- Quality updates to rule documentation by @BernieWhite.
[#2570](https://github.com/Azure/PSRule.Rules.Azure/issues/2570)
- Bug fixes:
- Fixed TLS defaults for `Azure.Redis.MinTLS` and `Azure.RedisEnterprise.MinTLS` by @BernieWhite. …
=> Pre-release v1.39.0-B0182

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Common/JsonExtensions.cs, src/PSRule.Rules.Azure/Common/ResourceHelper.cs, src/PSRule.Rules.Azure/Common/TemplateTokenAnnotation.cs, src/PSRule.Rules.Azure/Data/Policy/LazyParameter.cs, src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitor.cs, src/PSRule.Rules.Azure/Data/Template/ArrayDeploymentSymbol.cs, src/PSRule.Rules.Azure/Data/Template/DeploymentSymbol.cs, src/PSRule.Rules.Azure/Data/Template/DeploymentValue.cs, src/PSRule.Rules.Azure/Data/Template/Exceptions.cs, src/PSRule.Rules.Azure/Data/Template/ExistingResourceValue.cs, src/PSRule.Rules.Azure/Data/Template/IDeploymentSymbol.cs, src/PSRule.Rules.Azure/Data/Template/IResourceValue.cs, src/PSRule.Rules.Azure/Data/Template/ITemplateContext.cs, src/PSRule.Rules.Azure/Data/Template/ITemplateContextExtensions.cs, src/PSRule.Rules.Azure/Data/Template/NestedTemplateContext.cs, src/PSRule.Rules.Azure/Data/Template/ObjectDeploymentSymbol.cs, src/PSRule.Rules.Azure/Data/Template/ResourceValue.cs, src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs, tests/PSRule.Rules.Azure.Tests/Bicep/SymbolicNameTestCases/Tests.Bicep.2.bicep, tests/PSRule.Rules.Azure.Tests/Bicep/SymbolicNameTestCases/Tests.Bicep.2.child.bicep, tests/PSRule.Rules.Azure.Tests/Bicep/SymbolicNameTestCases/Tests.Bicep.2.json, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/ResourceHelperTests.cs, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- Fixed symbolic expand for existing with conditional cases.
Fixes #2917
=> Handle symbolic expand for existing conditional cases #2917

docs/CHANGELOG-v1.md
What's changed since pre-release v1.39.0-B0182:
- Bug fixes:
- Fixed symbolic expand for existing with conditional cases by @BernieWhite.
[#2917](https://github.com/Azure/PSRule.Rules.Azure/issues/2917)
=> Pre-release v1.39.0-B0249

docs/CHANGELOG-v1.md, tests/PSRule.Rules.Azure.Tests/Bicep/SecretTestCases/Tests.Bicep.1.bicep, tests/PSRule.Rules.Azure.Tests/Bicep/SecretTestCases/Tests.Bicep.1.child.bicep, tests/PSRule.Rules.Azure.Tests/Bicep/SecretTestCases/Tests.Bicep.1.json, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- Fixed conditional secret as parameter or placeholder.
Fixes #2054
=> Fixes conditional secret as parameter or placeholder #2054

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs, src/PSRule.Rules.Azure/Data/Template/UserDefinedFunctionContext.cs, tests/PSRule.Rules.Azure.Tests/Bicep/UserDefinedFunctionTestCases/Tests.Bicep.1.bicep, tests/PSRule.Rules.Azure.Tests/Bicep/UserDefinedFunctionTestCases/Tests.Bicep.1.child.bicep, tests/PSRule.Rules.Azure.Tests/Bicep/UserDefinedFunctionTestCases/Tests.Bicep.1.child2.bicep, tests/PSRule.Rules.Azure.Tests/Bicep/UserDefinedFunctionTestCases/Tests.Bicep.1.json, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
- Fixes UDF reference to exported variable.
Fixes #3120
=> Fixes UDF reference to exported variable #3120

docs/CHANGELOG-v1.md
What's changed since v1.39.1:
- Bug fixes:
- Fixed user-defined function reference to exported variable by @BernieWhite.
[#3120](https://github.com/Azure/PSRule.Rules.Azure/issues/3120)
- Fixed name expand of existing resource references by @BernieWhite.
[#3123](https://github.com/Azure/PSRule.Rules.Azure/issues/3123)
=> Release v1.39.2

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/ExistingResourceValue.cs, src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs, src/PSRule.Rules.Azure/Data/Template/UserDefinedFunctionContext.cs, tests/PSRule.Rules.Azure.Tests/Bicep/SymbolicNameTestCases/Tests.Bicep.1.bicep, tests/PSRule.Rules.Azure.Tests/Bicep/SymbolicNameTestCases/Tests.Bicep.3.bicep, tests/PSRule.Rules.Azure.Tests/Bicep/SymbolicNameTestCases/Tests.Bicep.3.json, tests/PSRule.Rules.Azure.Tests/Bicep/UserDefinedFunctionTestCases/Tests.Bicep.1.bicep, tests/PSRule.Rules.Azure.Tests/Bicep/UserDefinedFunctionTestCases/Tests.Bicep.1.child.bicep, tests/PSRule.Rules.Azure.Tests/Bicep/UserDefinedFunctionTestCases/Tests.Bicep.1.child2.bicep, tests/PSRule.Rules.Azure.Tests/Bicep/UserDefinedFunctionTestCases/Tests.Bicep.1.json, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.38.bicep
Merged from patch v1.39.2:
- Bug fixes:
- Fixed user-defined function reference to exported variable by @BernieWhite.
[#3120](https://github.com/Azure/PSRule.Rules.Azure/issues/3120)
- Fixed name expand of existing resource references by @BernieWhite.
[#3123](https://github.com/Azure/PSRule.Rules.Azure/issues/3123)
=> Merge patch v1.39.2

.github/dependabot.yml, docs/install.md, docs/related-projects.md, src/PSRule.Rules.Azure.Benchmark/PSRule.Rules.Azure.Benchmark.csproj, src/SDK/SDK.csproj, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
- Update PowerShell components for development.
=> Update PowerShell dependencies

src/PSRule.Rules.Azure.Benchmark/PSRule.Rules.Azure.Benchmark.csproj, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
Update PowerShell components for development.
=> Update PowerShell components

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/DeploymentSymbol.cs, src/PSRule.Rules.Azure/Data/Template/TemplateHelper.cs, src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs, tests/PSRule.Rules.Azure.Tests/Bicep/ExtensibilityTestCases/BicepExtensibilityTests.cs, tests/PSRule.Rules.Azure.Tests/Bicep/SecretTestCases/BicepSecretTests.cs, tests/PSRule.Rules.Azure.Tests/Bicep/SymbolicNameTestCases/BicepSymbolicNameTests.cs, tests/PSRule.Rules.Azure.Tests/Bicep/SymbolicNameTestCases/Tests.Bicep.4.bicep, tests/PSRule.Rules.Azure.Tests/Bicep/SymbolicNameTestCases/Tests.Bicep.4.json, tests/PSRule.Rules.Azure.Tests/Bicep/UserDefinedFunctionTestCases/BicepUserDefinedFunctionTests.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTestsBase.cs
- Fixed index out of bounds for existing symbolic name reference.
Fixes #3129
=> Fixes index out of bounds for existing symbol #3129

docs/CHANGELOG-v1.md
What's changed since v1.39.2:
- Bug fixes:
- Fixed index out of bounds for existing symbolic name reference by @BernieWhite.
[#3129](https://github.com/Azure/PSRule.Rules.Azure/issues/3129)
=> Release v1.39.3

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/DeploymentSymbol.cs, src/PSRule.Rules.Azure/Data/Template/TemplateHelper.cs, src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs, tests/PSRule.Rules.Azure.Tests/Bicep/ExtensibilityTestCases/BicepExtensibilityTests.cs, tests/PSRule.Rules.Azure.Tests/Bicep/SecretTestCases/BicepSecretTests.cs, tests/PSRule.Rules.Azure.Tests/Bicep/SymbolicNameTestCases/BicepSymbolicNameTests.cs, tests/PSRule.Rules.Azure.Tests/Bicep/SymbolicNameTestCases/Tests.Bicep.4.bicep, tests/PSRule.Rules.Azure.Tests/Bicep/SymbolicNameTestCases/Tests.Bicep.4.json, tests/PSRule.Rules.Azure.Tests/Bicep/UserDefinedFunctionTestCases/BicepUserDefinedFunctionTests.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTestsBase.cs
What's changed since v1.39.2:
- Bug fixes:
- Fixed index out of bounds for existing symbolic name reference by @BernieWhite.
[#3129](https://github.com/Azure/PSRule.Rules.Azure/issues/3129)
Fixes #3129
=> Merge patch v1.39.3

docs/en/rules/Azure.PublicIP.StandardSKU.md, docs/en/rules/Azure.Storage.ContainerSoftDelete.md, docs/en/rules/Azure.Storage.FileShareSoftDelete.md, docs/en/rules/Azure.Storage.SoftDelete.md, docs/en/rules/Azure.Storage.UseReplication.md, docs/examples/resources/public-ip.bicep, docs/examples/resources/public-ip.json, docs/examples/resources/storage.bicep, docs/examples/resources/storage.json
Minor improvements to rule docs.
=> Rule doc improvements

.github/dependabot.yml
Group PowerShell dependencies.
=> Group PowerShell dependencies

docs/CHANGELOG-v1.md, docs/en/rules/Azure.Deployment.SecureParameter.md, src/PSRule.Rules.Azure/rules/Azure.Deployment.Rule.ps1
- Updated `Azure.Deployment.SecureParameter` to reduce false positives.
Fixes #3149
=> Improve false positives from Azure.Deployment.SecureParameter #3149

.github/dependabot.yml, .gitignore, docs/assets/stylesheets/extra.css, docs/en/rules/Azure.Deployment.AdminUsername.md, docs/en/rules/Azure.Deployment.OuterSecret.md, docs/en/rules/Azure.Deployment.OutputSecretValue.md, docs/en/rules/Azure.Deployment.SecureValue.md, docs/hooks/shortcodes.py, includes/en/abbreviations.md, includes/en/security-notes/rotate-secret.md, mkdocs.yml, packages/bicep-syntax/README.md, packages/bicep-syntax/__init__.py, packages/bicep-syntax/lexer.py, packages/bicep-syntax/pyproject.toml, requirements-docs.txt
Improve rule docs by adding a security note in the rule documentation to call out secret rotation.
=> Add security note to rule documentation

docs/en/rules/Azure.APIM.HTTPBackend.md, docs/en/rules/Azure.APIM.HTTPEndpoint.md, docs/en/rules/Azure.AppService.UseHTTPS.md, docs/en/rules/Azure.CDN.HTTP.md, docs/en/rules/Azure.CDN.MinTLS.md, docs/en/rules/Azure.CDN.UseFrontDoor.md
Minor quality updates to rule documentation.
=> Rule documentation quality updates

docs/learn/official.md
=> Update feedback on links

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/ExistingResourceValue.cs, src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs, src/PSRule.Rules.Azure/Data/Template/Functions.cs, src/PSRule.Rules.Azure/Data/Template/ParameterType.cs, src/PSRule.Rules.Azure/Data/Template/RuleDataExportVisitor.cs, src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs, src/PSRule.Rules.Azure/Data/Template/TypeHelpers.cs, src/PSRule.Rules.Azure/JsonExtensions.cs, tests/PSRule.Rules.Azure.Tests/Bicep/AVMTestCases/BicepAVMTests.cs, tests/PSRule.Rules.Azure.Tests/Bicep/AVMTestCases/Tests.Bicep.1.bicep, tests/PSRule.Rules.Azure.Tests/Bicep/AVMTestCases/Tests.Bicep.1.json, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
- Fixed output map expansion with resource IDs.
Fixes #3153
=> Fixed output map expansion with resource IDs #3153

docs/CHANGELOG-v1.md
What's changed since v1.39.3:
- Deployment:
- Updated `Azure.Deployment.SecureValue` to check additional resource types by @BernieWhite.
[#2650](https://github.com/Azure/PSRule.Rules.Azure/issues/2650)
[#2651](https://github.com/Azure/PSRule.Rules.Azure/issues/2651)
- Added support for container apps secret properties.
- Added support for deployment script secret properties.
- Updated `Azure.Deployment.SecureParameter` to reduce false positives by @BernieWhite.
[#3149](https://github.com/Azure/PSRule.Rules.Azure/issues/3149)
- Parameters named ending with `name`, `uri`, `url`, `path`, `type`, `id`, or `options` are ignored.
- The `customerManagedKey` parameter is ignored.
- Engineering:
- Migrated Azure samples into PSRule for Azure by …
=> Pre-release v1.40.0-B0029

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Runtime/Helper.cs, src/PSRule.Rules.Azure/rules/Azure.Deployment.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.Deployment.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Bicep/SymbolicNameTestCases/Tests.Bicep.5.bicep, tests/PSRule.Rules.Azure.Tests/Bicep/SymbolicNameTestCases/Tests.Bicep.5.json, tests/PSRule.Rules.Azure.Tests/TokenStreamValidatorTests.cs
- Fixed evaluation of `Azure.Deployment.AdminUsername` with symbolic references.
Fixes #3146
=> Fixed symbolic references with Azure.Deployment.AdminUsername #3146

docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Data/Template/RuleDataExportVisitor.cs
- Fixed projection of default role authorization property `principalType`
Fixes #3163
=> Fixed projection of principalType #3163

docs/CHANGELOG-v1.md, docs/en/rules/Azure.Defender.SecurityContact.md, docs/en/rules/Azure.MySQL.FirewallIPRange.md, docs/en/rules/Azure.NSG.DenyAllInbound.md, docs/en/rules/Azure.SQL.DefenderCloud.md, docs/en/rules/Azure.SQL.FirewallIPRange.md, docs/en/rules/Azure.VM.AcceleratedNetworking.md, docs/en/rules/Azure.VM.DiskCaching.md, src/PSRule.Rules.Azure/rules/Azure.NSG.Rule.ps1
- Additional quality updates to documentation.
Working towards #3102
=> Rule documentation quality updates #3102

docs/CHANGELOG-v1.md
What's changed since pre-release v1.40.0-B0063:
- Added support for expanding from `.jsonc` parameter files by @BernieWhite.
[#2053](https://github.com/Azure/PSRule.Rules.Azure/issues/2053)
- Previously only parameter files with the `.json` extension where automatically expanded.
- This feature adds support so that JSON parameter files with the `.jsonc` extension are also discovered and expanded.
- No additional configuration is required if expansion of JSON parameter files is enabled.
- To enable parameter file expansion set the `AZURE_PARAMETER_FILE_EXPANSION` configuration option to `true`.
- Additional quality updates to documentation by @BernieWhite.
[#3102](https://github.com/Azure/PSRule.Rules.Azure/issues/3102)
- Bug fixes:
- Fixed …
=> Pre-release v1.40.0-B0103

.devcontainer/container-build.ps1, .devcontainer/devcontainer.json
=> Fix codespace build

docs/en/rules/Azure.AppService.RemoteDebug.md, docs/en/rules/Azure.AppService.WebProbe.md, docs/en/rules/Azure.AppService.WebProbePath.md, docs/en/rules/Azure.AppService.WebSecureFtp.md
=> Additional AVM links

docs/CHANGELOG-v1.md
What's changed since pre-release v1.40.0-B0147:
- Added first time contributor guide in docs by @that-ar-guy.
[#3097](https://github.com/Azure/PSRule.Rules.Azure/issues/3097)
- Engineering:
- Quality updates to rule documentation by @BernieWhite.
[#3102](https://github.com/Azure/PSRule.Rules.Azure/issues/3102)
- Bug fixes:
- Fixed evaluation of APIM policies when using embedded C# with quotes by @BernieWhite.
[#3184](https://github.com/Azure/PSRule.Rules.Azure/issues/3184)
- Fixed Resource group ID is incorrect under subscription scope by @BernieWhite.
[#3198](https://github.com/Azure/PSRule.Rules.Azure/issues/3198)
=> Pre-release v1.40.0-B0206

docs/CHANGELOG-v1.md
What's changed since v1.40.0:
- Added December 2024 baselines `Azure.GA_2024_12` and `Azure.Preview_2024_12` by @BernieWhite.
[#3165](https://github.com/Azure/PSRule.Rules.Azure/issues/3165)
- Includes rules released before or during December 2024.
- Marked `Azure.GA_2024_09` and `Azure.Preview_2024_09` baselines as obsolete.
- Updated `Azure.AKS.Version` to use `1.30.6` as the minimum version by @BernieWhite.
[#3206](https://github.com/Azure/PSRule.Rules.Azure/issues/3206)
- Updated documentation and promoted `Azure.ACR.AnonymousAccess` to GA by @BernieWhite.
[#3119](https://github.com/Azure/PSRule.Rules.Azure/issues/3119)
- **Important change**: …
=> Pre-release v1.41.0-B0015

docs/CHANGELOG-v1.md
What's changed since v1.41.0:
- Bug fixes:
- Fixed incorrect generation of resource ID for tenant scoped deployments by @BernieWhite.
[#3237](https://github.com/Azure/PSRule.Rules.Azure/issues/3237)
- Fixed in-flight export of subscription resource type `Microsoft.Subscription` by @BernieWhite.
[#3231](https://github.com/Azure/PSRule.Rules.Azure/issues/3231)
=> Release v1.41.1

docs/CHANGELOG-v1.md
What's changed since v1.41.1:
- Bug fixes:
- Fixed recursive lookup of cross module resources in the deployment by @BernieWhite.
[#3251](https://github.com/Azure/PSRule.Rules.Azure/issues/3251)
- This improves the ability to reference resource properties in the same parent deployment.
- Additionally, projection of runtime properties has been improved.
- Fixed literal strings may be incorrectly interpreted as expressions by @BernieWhite.
[#3252](https://github.com/Azure/PSRule.Rules.Azure/issues/3252)
=> Release v1.41.2

.vscode/settings.json, docs/CHANGELOG-v1.md, src/PSRule.Rules.Azure/Common/ResourceHelper.cs, src/PSRule.Rules.Azure/Data/APIM/APIMPolicyReader.cs, src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs, src/PSRule.Rules.Azure/Data/Template/FunctionDescriptor.cs, src/PSRule.Rules.Azure/Data/Template/FunctionErrorType.cs, src/PSRule.Rules.Azure/Data/Template/Functions.cs, src/PSRule.Rules.Azure/Data/Template/ITemplateContext.cs, src/PSRule.Rules.Azure/Data/Template/RuleDataExportVisitor.cs, src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs, src/PSRule.Rules.Azure/DictionaryExtensions.cs, src/PSRule.Rules.Azure/JsonExtensions.cs, src/PSRule.Rules.Azure/Resources/PSRuleResources.Designer.cs, src/PSRule.Rules.Azure/Resources/PSRuleResources.resx, tests/PSRule.Rules.Azure.Tests/Bicep/AVMTestCases/BicepAVMTests.cs, tests/PSRule.Rules.Azure.Tests/Bicep/AVMTestCases/Tests.Bicep.2.bicep, tests/PSRule.Rules.Azure.Tests/Bicep/AVMTestCases/Tests.Bicep.2.child1.bicep, tests/PSRule.Rules.Azure.Tests/Bicep/AVMTestCases/Tests.Bicep.2.child2.bicep, tests/PSRule.Rules.Azure.Tests/Bicep/AVMTestCases/Tests.Bicep.2.json, tests/PSRule.Rules.Azure.Tests/ExpressionHelpersTests.cs, tests/PSRule.Rules.Azure.Tests/JsonExtensionsTests.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/ResourceHelperTests.cs, tests/PSRule.Rules.Azure.Tests/StringExtensionsTests.cs, tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
Merge patch v1.41.1:
- Bug fixes:
- Fixed recursive lookup of cross module resources in the deployment by @BernieWhite.
[#3251](https://github.com/Azure/PSRule.Rules.Azure/issues/3251)
- This improves the ability to reference resource properties in the same parent deployment.
- Additionally, projection of runtime properties has been improved.
- Fixed literal strings may be incorrectly interpreted as expressions by @BernieWhite.
[#3252](https://github.com/Azure/PSRule.Rules.Azure/issues/3252)
Fixes #3251
Fixes #3252
=> Merge patch v1.41.2

docs/CHANGELOG-v1.md
What's changed since v1.41.2:
- Bug fixes:
- Fixed ordering of symbolic copy loop dependencies by @BernieWhite.
[#3257](https://github.com/Azure/PSRule.Rules.Azure/issues/3257)
=> Release v1.41.3

docs/CHANGELOG-v1.md
What's changed since v1.41.3:
- Bug fixes:
- Fixed Azure VM Standalone failing on data disks check by @BernieWhite.
[#3263](https://github.com/Azure/PSRule.Rules.Azure/issues/3263)
- Fixed in-flight analysis of key rotation policy fails due to missing data by @BernieWhite.
[#3261](https://github.com/Azure/PSRule.Rules.Azure/issues/3261)
- Disabled export of `keys` from management plane API because the data is incomplete for this rule.
=> Release v1.41.4

data/resource-type-mapping.json, scripts/resource-type-mapping.ps1
Add display name to the rule mapping and sort the output to make the order deterministic for reviews.
=> Added displayName to mapping

docs/CHANGELOG-v1.md, docs/en/rules/Azure.SQL.MaintenanceWindow.md, docs/en/rules/Azure.SQL.VAScan.md, docs/examples/resources/sql.bicep, docs/examples/resources/sql.json, src/PSRule.Rules.Azure/Pipeline/Export/ResourceExportVisitor.cs, src/PSRule.Rules.Azure/rules/Azure.SQL.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.SQL.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.SQL.json
- Check that logical SQL servers have vulnerability assessment enabled.
Fixes #3196
=> Add SQL VS scan check #3196

docs/CHANGELOG-v1.md, docs/en/rules/Azure.AppService.AvailabilityZone.md, src/PSRule.Rules.Azure/rules/Azure.AppService.Rule.ps1
=> Add Azure.AppService.AvailabilityZone support for missing SKU's 

data/policy-ignore.json, docs/CHANGELOG-v1.md, docs/concepts/about_PSRule_Azure_Configuration.md, docs/en/rules/Azure.AKS.AutoUpgrade.md, docs/en/rules/Azure.AKS.NodeAutoUpgrade.md, docs/en/rules/Azure.AKS.Version.md, docs/en/rules/Azure.SQL.VAScan.md, docs/examples/resources/aks.bicep, docs/examples/resources/aks.json, docs/setup/configuring-rules.md, src/PSRule.Rules.Azure/rules/Config.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json, tests/PSRule.Rules.Azure.Tests/Resources.AKS.json
- Updated `Azure.AKS.Version` to use `1.30.10` as the minimum version.
Fixes #3301
=> Updated Azure.AKS.Version to 1.30.10 #3301

docs/CHANGELOG-v1.md, docs/en/rules/Azure.EventGrid.DomainTLS.md, docs/en/rules/Azure.EventGrid.TopicTLS.md, docs/en/rules/Azure.EventHub.MinTLS.md, docs/examples/resources/eventgrid.bicep, docs/examples/resources/eventgrid.json, src/PSRule.Rules.Azure/rules/Azure.EventGrid.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Azure.EventGrid.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.EventGrid.json
- Check that topics and domains use a minimum of TLS 1.2.
Fixes #3306
=> Check that topics and domains use a minimum of TLS 1.2 #3306

docs/troubleshooting.md, src/PSRule.Rules.Azure/Configuration/DeployerOption.cs, src/PSRule.Rules.Azure/Configuration/ResourceGroupOption.cs, src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitor.cs, src/PSRule.Rules.Azure/Data/Template/CopyIndexState.cs, src/PSRule.Rules.Azure/Data/Template/CopyIndexStore.cs, src/PSRule.Rules.Azure/Data/Template/DeploymentValue.cs, src/PSRule.Rules.Azure/Data/Template/ExistingResourceValue.cs, src/PSRule.Rules.Azure/Data/Template/ExpressionBuilder.cs, src/PSRule.Rules.Azure/Data/Template/FunctionDescriptor.cs, src/PSRule.Rules.Azure/Data/Template/Functions.cs, src/PSRule.Rules.Azure/Data/Template/IResourceValue.cs, src/PSRule.Rules.Azure/Data/Template/ITemplateContext.cs, src/PSRule.Rules.Azure/Data/Template/NestedTemplateContext.cs, src/PSRule.Rules.Azure/Data/Template/ResourceValue.cs, src/PSRule.Rules.Azure/Data/Template/RuleDataExportVisitor.cs, src/PSRule.Rules.Azure/Data/Template/StringExpression_T.cs, src/PSRule.Rules.Azure/Data/Template/TemplateHelper.cs, src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs, src/PSRule.Rules.Azure/Data/Template/TokenStream.cs, tests/PSRule.Rules.Azure.Tests/DependencyMapTests.cs, tests/PSRule.Rules.Azure.Tests/ExpressionBuilderTests.cs, tests/PSRule.Rules.Azure.Tests/FunctionTests.cs, tests/PSRule.Rules.Azure.Tests/OptionsTests.cs, tests/PSRule.Rules.Azure.Tests/ps-rule-options.yaml
Code refactoring for improving code quality and readability.
=> Refactoring

data/resource-type-mapping.json, docs/CHANGELOG-v1.md
What's changed since v1.41.4:
- Added March 2025 baselines `Azure.GA_2025_03` and `Azure.Preview_2025_03` by @BernieWhite.
[#3304](https://github.com/Azure/PSRule.Rules.Azure/issues/3304)
- Includes rules released before or during March 2025.
- Marked `Azure.GA_2024_12` and `Azure.Preview_2024_12` baselines as obsolete.
- New rules:
- Azure DNS:
- Check that public zones use DNSSEC by @BernieWhite.
[#3201](https://github.com/Azure/PSRule.Rules.Azure/issues/3201)
- Azure SQL Database:
- Check that logical SQL servers have vulnerability assessment enabled by @BernieWhite.
[#3196](https://github.com/Azure/PSRule.Rules.Azure/issues/3196)
- Event Grid:
- Check that topics and domains use a minimum of TLS 1.2 by @BernieWhite. …
=> Release v1.42.0

CONTRIBUTING.md
Updated contributing with additional details.
=> Updated contributing

data/secret-property.json, docs/CHANGELOG-v1.md
- Updated `Azure.Deployment.SecureValue` to check additional resource types and properties.
- Added support for `Microsoft.Kusto/clusters/databases/scripts` resource type.
- Added support for `Microsoft.ContainerInstance/containerGroupProfiles` resource type.
- Added new sensitive properties to `Microsoft.ContainerInstance/containerGroups`.
Fixes #3321
=> Updated Azure.Deployment.SecureValue #3321

docs/CHANGELOG-v1.md, docs/en/rules/Azure.Deployment.OutputSecretValue.md, docs/en/rules/Azure.Deployment.SecretLeak.md, docs/en/rules/Azure.Deployment.SecureParameter.md, includes/en/security-notes/non-secret-values.md, src/PSRule.Rules.Azure/rules/Azure.Deployment.Rule.ps1, tests/PSRule.Rules.Azure.Tests/Azure.Deployment.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.9.bicep, tests/PSRule.Rules.Azure.Tests/Tests.Bicep.9.json
Check if sensitive values have been passed to non-secure parameters that might leak the value.
Fixes #3319
=> Check if sensitive values have been passed to non-secure parameters #3319

README.md, RuleToc.Doc.ps1, docs/about.md, docs/creating-your-pipeline.md, docs/features.md, docs/working-with-baselines.md, overrides/home.html
Minor quality updates to documentation.
=> Quality updates to docs

docs/changelog.md, docs/faq.md, docs/hooks/updates.py, docs/license-contributing.md, docs/samples.md, docs/setup/configuring-expansion.md, docs/setup/configuring-exports.md, docs/setup/configuring-rules.md, docs/setup/setup-bicep.md, docs/troubleshooting.md, docs/versioning.md
Minor metadata updates to docs.
=> Metadata updates for docs

docs/changelog.md
What's changed since v1.42.0:
- New rules:
- AI Search:
- Check if resource name matches the configured name format by @BernieWhite.
[#3325](https://github.com/Azure/PSRule.Rules.Azure/issues/3325)
- The name format can be configured by the `AZURE_AI_SEARCH_NAME_FORMAT` configuration option.
- AI Service:
- Check if resource name matches the configured name format by @BernieWhite.
[#3325](https://github.com/Azure/PSRule.Rules.Azure/issues/3325)
- The name format can be configured by the `AZURE_AI_SERVICES_NAME_FORMAT` configuration option.
- Check if resource tags match the required tags by @BernieWhite.
[#3325](https://github.com/Azure/PSRule.Rules.Azure/issues/3325)
- The required tags can be configured by the `AZURE_RESOURCE_REQUIRED_TAGS` configuration option.
- …
=> Pre-release v1.43.0-B0017

docs/license-contributing/expansion-internals.md, docs/setup/configuring-expansion.md, docs/specs/inflight-export-spec.md, mkdocs.yml
Add documentation about expansion for contributors and developers.
=> Add expansion documentation

data/secret-property.json, docs/changelog.md, docs/examples/resources/fleet.bicep, docs/examples/resources/fleet.json, docs/updates/v1.44.md
- Updated `Azure.Deployment.SecureValue` to check additional resource types and properties.
- Added support for new resource types:
- `Microsoft.AzureFleet/fleets`
- `Microsoft.Web/staticSites`
- `Microsoft.Web/staticSites/basicAuth`
Fixes #3342
=> Updated Azure.Deployment.SecureValue with additional resources #3342

docs/changelog.md
What's changed since v1.43.0:
- Added support for the `buildUri` and `parseUri` functions during Bicep expansion by @BernieWhite.
[#3345](https://github.com/Azure/PSRule.Rules.Azure/issues/3345)
- Deployment:
- Updated `Azure.Deployment.OutputSecretValue` to support secure outputs by @BernieWhite.
[#3357](https://github.com/Azure/PSRule.Rules.Azure/issues/3357)
- Updated `Azure.Deployment.SecureValue` to check additional resource types and properties by @BernieWhite.
[#3342](https://github.com/Azure/PSRule.Rules.Azure/issues/3342)
- Added support for new resource types:
- `Microsoft.AzureFleet/fleets`
- `Microsoft.Web/staticSites`
- `Microsoft.Web/staticSites/basicAuth`
- Bug fixes:
- Fixed identification of secure parameters with custom type for …
=> Pre-release v1.44.0-B0011

data/secret-property.json, docs/changelog.md, docs/en/rules/Azure.EntraDS.MinReplicas.md, docs/en/rules/Azure.EntraDS.NTLM.md, docs/en/rules/Azure.EntraDS.RC4.md, docs/en/rules/Azure.EntraDS.ReplicaLocation.md, docs/en/rules/Azure.EntraDS.SKU.md, docs/en/rules/Azure.EntraDS.TLS.md, docs/en/rules/Azure.Resource.AllowedRegions.md, docs/examples/resources/entrads.bicep, docs/examples/resources/entrads.json, docs/setup/configuring-rules.md, docs/updates/v1.43.md, docs/updates/v1.44.md, src/PSRule.Rules.Azure/rules/Azure.EntraDS.Rule.ps1, src/PSRule.Rules.Azure/rules/Azure.EntraDS.Rule.yaml, tests/PSRule.Rules.Azure.Tests/Azure.EntraDS.Tests.ps1, tests/PSRule.Rules.Azure.Tests/Resources.EntraDS.json
- New rules:
- Entra Domain Services:
- Check that the SKU supports geo-replication by @BernieWhite.
[#3355](https://github.com/Azure/PSRule.Rules.Azure/issues/3355)
- Check that at least two replicas are configured by @BernieWhite.
[#3364](https://github.com/Azure/PSRule.Rules.Azure/issues/3364)
- Check that replicas are located in allowed locations by @BernieWhite.
[#3365](https://github.com/Azure/PSRule.Rules.Azure/issues/3365)
- Deployment:
- Updated `Azure.Deployment.SecureValue` to check additional resource types and properties by @BernieWhite.
[#3366](https://github.com/Azure/PSRule.Rules.Azure/issues/3366)
- Added new sensitive properties to:
- `Microsoft.AAD/domainServices`
Fixes #3355 
Fixes #3364
Fixes #3365 
Fixes #3366
=> Added Entra DS rules and updates #3355 #3364 #3365 #3366

data/secret-property.json, docs/changelog.md
Updated `Azure.Deployment.SecureValue` to support `Microsoft.DocumentDB/mongoClusters`.
Fixes #3368
=> Check for mongo cluster password property #3368

.devcontainer/devcontainer.json, .github/dependabot.yml, src/PSRule.Rules.Azure.Benchmark/PSRule.Rules.Azure.Benchmark.csproj, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
Updates to PowerShell dependency for development builds.
=> Update PowerShell versions for dev

docs/changelog.md
What's changed since pre-release v1.44.0-B0027:
- Added support for the `toPhysicalZone`, `toPhysicalZones`, `toLogicalZone`, `toLogicalZones` Bicep functions by @BernieWhite.
[#3346](https://github.com/Azure/PSRule.Rules.Azure/issues/3346)
- Added the `userPrincipalName` property to the `deployer()` object by @BernieWhite.
[#3390](https://github.com/Azure/PSRule.Rules.Azure/issues/3390)
- New rules:
- Service Fabric:
- Check that Service Fabric clusters use encrypted and signed node-to-node communication by @BernieWhite.
[#3356](https://github.com/Azure/PSRule.Rules.Azure/issues/3356)
- Updated documentation and promoted `Azure.VNET.PrivateSubnet` to GA by @BernieWhite.
[#3386](https://github.com/Azure/PSRule.Rules.Azure/issues/3386)
- …
=> Pre-release v1.44.0-B0052

docs/changelog.md
What's changed since pre-release v1.44.0-B0052:
- Added support for optionally exporting in-flight security alerts from Microsoft Defender for Cloud by @BernieWhite.
[#3238](https://github.com/Azure/PSRule.Rules.Azure/issues/3238)
- To export security alerts use the `-ExportSecurityAlerts` switch when running `Export-AzRuleData`.
- New rules:
- Microsoft Defender for Cloud:
- Check if subscriptions have active security alerts in Microsoft Defender for Cloud by @BernieWhite.
[#3238](https://github.com/Azure/PSRule.Rules.Azure/issues/3238)
=> Pre-release v1.44.0-B0081

docs/hooks/updates.py, docs/updates/v1.44.md
Updates to docs for patch v1.44.1.
=> Updates for patch

docs/changelog.md, docs/export-rule-data.md, src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1, src/PSRule.Rules.Azure/Pipeline/AccessToken.cs, src/PSRule.Rules.Azure/Pipeline/Export/AccessTokenCache.cs, src/PSRule.Rules.Azure/Pipeline/Export/ExportDataContext.cs, src/PSRule.Rules.Azure/Pipeline/Export/ResourceExportVisitor.cs, src/PSRule.Rules.Azure/Pipeline/ResourceDataPipeline.cs, tests/PSRule.Rules.Azure.Tests/ResourceExportVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/TestResourceExportContext.cs
Fixed compatibility with newer Az.Accounts modules
Fixes #3420
=> Fixed compatibility with newer Az.Accounts modules #3420

docs/changelog.md, docs/export-rule-data.md, docs/updates/v1.44.md
What's changed since v1.44.1:
- Bug fixes:
- Fixed compatibility with newer `Az.Accounts` modules by @BernieWhite.
[#3420](https://github.com/Azure/PSRule.Rules.Azure/issues/3420)
=> Release v1.44.2

docs/changelog.md, docs/updates/v1.45.md, src/PSRule.Rules.Azure/Data/Policy/LoggerExtensions.cs, src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitor.cs, src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitorExtensions.cs, tests/PSRule.Rules.Azure.Tests/Data/Policy/PolicyAssignmentVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/Policy.assignment.11.json, tests/PSRule.Rules.Azure.Tests/emittedJsonRulesData.jsonc
- Optimize generation of nested allOf/ anyOf condition in policy as rules.
Fixes #1965
=> Optimize nested allOf/ anyOf #1965

docs/changelog.md, src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitor.cs, tests/PSRule.Rules.Azure.Tests/Data/Policy/PolicyAssignmentVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj, tests/PSRule.Rules.Azure.Tests/Policy.assignment.11.json, tests/PSRule.Rules.Azure.Tests/Policy.assignment.12.json, tests/PSRule.Rules.Azure.Tests/emittedJsonRulesData.jsonc, tests/PSRule.Rules.Azure.Tests/emittedJsonRulesPrefixData.jsonc
- Fixed string boolean values not converted during evaluation of policy as rules.
Fixes #3426
=> Fixed string boolean values not converted during evaluation #3426

docs/changelog.md
What's changed since v1.44.2:
- Optimize generation of nested allOf/ anyOf condition in policy as rules by @BernieWhite.
[#1965](https://github.com/Azure/PSRule.Rules.Azure/issues/1965)
- Bug fixes:
- Fixed incorrect inversion of policy as rules conditions by @BernieWhite.
[#3419](https://github.com/Azure/PSRule.Rules.Azure/issues/3419)
- Fixed string boolean values not converted during evaluation of policy as rules by @BernieWhite.
[#3426](https://github.com/Azure/PSRule.Rules.Azure/issues/3426)
=> Pre-release v1.45.0-B0017

docs/changelog.md
What's changed since pre-release v1.45.0-B0017:
- Bug fixes:
- Fixed secure outputs objects may not be fully mocked by @BernieWhite.
[#3434](https://github.com/Azure/PSRule.Rules.Azure/issues/3434)
=> Pre-release v1.45.0-B0037

data/resource-type-mapping.json
=> Update resource types

docs/changelog.md
What's changed since pre-release v1.45.0-B0068:
- New rules:
- Event Grid:
- Check namespaces use a minimum of TLS 1.2 by @BernieWhite.
[#3354](https://github.com/Azure/PSRule.Rules.Azure/issues/3354)
- Monitor Alerts:
- Check that metric alerts are configured to automatically mitigate by @BernieWhite.
[#3457](https://github.com/Azure/PSRule.Rules.Azure/issues/3457)
- Check that scheduled query alerts are configured for lower frequency by @BernieWhite.
[#3458](https://github.com/Azure/PSRule.Rules.Azure/issues/3458)
- Native support for exporting policy as rules by @BernieWhite.
[#2971](https://github.com/Azure/PSRule.Rules.Azure/issues/2971)
[#2970](https://github.com/Azure/PSRule.Rules.Azure/issues/2970)
- This removes the dependency on the `Az.Resources` module …
=> Pre-release v1.45.0-B0104

.github/copilot-instructions.md
=> Add instructions

.github/workflows/copilot-setup-steps.yml, docs/export-rule-data.md, docs/install.md, docs/setup/configuring-exports.md, docs/troubleshooting.md, modules.json
This improves copilot's performance by making it easier for it to build the solution.
=> Add workflow to help copilot build the project

docs/changelog.md, docs/updates/v1.45.md
What's changed since v1.45.0:
- Bug fixes:
- Fixed imported user defined function is unable to access local variable by @BernieWhite.
[#3483](https://github.com/Azure/PSRule.Rules.Azure/issues/3483)
=> Release v1.45.1

modules.json
Update Pester test dependency to 5.7.1.
=> Bump Pester module

docs/changelog.md, src/PSRule.Rules.Azure/Arm/Deployments/MaterializedDeploymentVisitor.cs, src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitor.cs, src/PSRule.Rules.Azure/JsonExtensions.cs, src/PSRule.Rules.Azure/Pipeline/Export/PolicyAssignmentExpandVisitor.cs, tests/PSRule.Rules.Azure.Tests/Bicep/AVMTestCases/BicepAVMTests.cs, tests/PSRule.Rules.Azure.Tests/Bicep/AVMTestCases/Tests.Bicep.5.bicep, tests/PSRule.Rules.Azure.Tests/Bicep/AVMTestCases/Tests.Bicep.5.json, tests/PSRule.Rules.Azure.Tests/Data/Policy/PolicyAssignmentVisitorTests.cs, tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
- Fixed false negative for App Service `web` configuration cases set with `siteConfig`
Related to #3521
=> Fixed false negative for App Service web config #3521
