CHANGELOG.md
docs/rules/en-US/Azure.MySQL.AllowAzureAccess.md
docs/rules/en-US/Azure.MySQL.FirewallRuleCount.md
src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
src/PSRule.Rules.Azure/rules/Azure.MySQL.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.MySQL.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.MySQL.json
tests/PSRule.Rules.Azure.Tests/Rule.Common.Tests.ps1

- Added rule to check if allow access to Azure services enabled for MySQL. #4
- Added rule to count the number of database server firewall rules for MySQL. #2
Fixes #4 
Fixes #2 

Added rules for MySQL firewall #2 #4

---

CHANGELOG.md
docs/commands/PSRule.Rules.Azure/en-US/Export-AzRuleData.md
src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Cmdlet.Common.Tests.ps1

- Fix rule `Azure.AKS.UseRBAC` returns null. #60
- Added parameters to filter resource export by resource group and/ or tag. #59
- Added `-ResourceGroupName` and `-Tag` parameters to `Export-AzRuleData` cmdlet.
Fixes #60 
Fixes #59 

Added filtering by tag and resource group and fix AKS rule #60 #59

---

CHANGELOG.md
src/PSRule.Rules.Azure/rules/Azure.Storage.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.ACR.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.AppService.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.DataFactory.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.MySQL.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.PostgreSQL.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.PublicIP.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Redis.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Resource.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.SQL.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Storage.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Subscription.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.VirtualMachine.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.VirtualNetwork.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.Storage.json

- Fix rule `Azure.Storage.SoftDelete` and `Azure.Storage.SecureTransferRequired` returns null. #64
Fixes #64 

Fix rule Azure.Storage.SoftDelete returns null #64

---

CHANGELOG.md
docs/rules/en-US/Azure.MySQL.FirewallIPRange.md
docs/rules/en-US/Azure.MySQL.FirewallRuleCount.md
docs/rules/en-US/Azure.PostgreSQL.FirewallIPRange.md
docs/rules/en-US/Azure.PostgreSQL.FirewallRuleCount.md
docs/rules/en-US/Azure.SQL.FirewallIPRange.md
docs/rules/en-US/Azure.SQL.FirewallRuleCount.md
docs/rules/en-US/Azure.md
pipeline.build.ps1
src/PSRule.Rules.Azure/PSRule.Rules.Azure.psd1
src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.MySQL.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.PostgreSQL.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.SQL.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.MySQL.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.PostgreSQL.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.SQL.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.MySQL.json
tests/PSRule.Rules.Azure.Tests/Resources.PostgreSQL.json
tests/PSRule.Rules.Azure.Tests/Resources.SQL.json

- Added SQL firewall rule range check to determine an excessive number of permitted IP addresses. #3 #10 #54
- The rules `Azure.SQL.FirewallIPRange`, `Azure.MySQL.FirewallIPRange` and `Azure.PostgreSQL.FirewallIPRange` were added to check SQL, MySQL and PostgreSQL.
Fixes #3 
Fixes #10 
Fixes #54 

Add SQL firewall rule range check #3 #10 #54

---

.vscode/settings.json
CHANGELOG.md
RuleToc.Doc.ps1
docs/rules/en-US/Azure.VirtualNetwork.AppGwOWASP.md
docs/rules/en-US/Azure.VirtualNetwork.AppGwWAFEnabled.md
docs/rules/en-US/Azure.VirtualNetwork.AppGwWAFRules.md
docs/rules/en-US/Azure.VirtualNetwork.LocalDNS.md
docs/rules/en-US/Azure.md
src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.VirtualNetwork.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.VirtualNetwork.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.VirtualNetwork.json

- Added VNET rule to check for local DNS. #68
- Added WAF hardening rules for Application Gateway. #78
- Application Gateways use OWASP 3.x rules.
- Application Gateways have WAF enabled.
- Application Gateways have all OWASP rules enabled.
Fixes #68 
Fixes #78 

Added rules for AppGw and VNET DNS #68 #78

---

CHANGELOG.md
src/PSRule.Rules.Azure/rules/Azure.VirtualNetwork.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.VirtualNetwork.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.VirtualNetwork.json

- Fix handling of empty DNS servers in `Azure.VirtualNetwork.LocalDNS`. #84 
Fixes #84 

Fix handling of empty DNS servers #84

---

CHANGELOG.md
src/PSRule.Rules.Azure/rules/Azure.VirtualNetwork.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.VirtualNetwork.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.VirtualNetwork.json

- Fix handling of no peering connections in `Azure.VirtualNetwork.LocalDNS`. #89 
Fixes #89 

Fix handling of peering in Azure.VirtualNetwork.LocalDNS #89

---

CHANGELOG.md

- Fix handling of empty DNS servers in `Azure.VirtualNetwork.LocalDNS`. #84
- Fix handling of no peering connections in `Azure.VirtualNetwork.LocalDNS`. #89
- Updated AKS version in `Azure.AKS.Version` to 1.13.7. #83
- Added VM SKU rules:
- VMs should avoid using expired promo SKUs. #87
- VMs should avoid using basic SKUs. #69

Pre-release v0.3.0-B190710

---

.vscode/settings.json
CHANGELOG.md
docs/rules/en-US/Azure.VirtualNetwork.LateralTraversal.md
docs/rules/en-US/Azure.VirtualNetwork.NICAttached.md
docs/rules/en-US/Azure.VirtualNetwork.NSGAssociated.md
docs/rules/en-US/Azure.VirtualNetwork.NSGDenyAllInbound.md
docs/rules/en-US/Azure.md
src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.VirtualNetwork.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.VirtualNetwork.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.VirtualNetwork.json

- Added rule to detect deny all inbound NSG rule. #94
- Added unused resource rules.
- Network security groups that are not associated. #93
- Unattached network interfaces. #92
- Added NSG rule to check for lateral traversal security rules. #103)
Fixes #94 
Fixes #93 
Fixes #92 
Fixes #103 

Deny all inbound NSG rule #94 #93 #92 #103

---

CHANGELOG.md
pipeline.build.ps1

- Added rule to verify Windows automatic updates are enabled. #132
- Added rule to verify VM agent is automatically provisioned. #131
- Updated `Azure.AKS.Version` to 1.14.6. #130
- **Breaking change**: Renamed `Azure.VirtualMachine.*` rules to `Azure.VM.*` #119

Pre-release v0.5.0-B1910004

---

CHANGELOG.md

- Updated `Azure.AKS.Version` to 1.14.8. #140
- Updated rules to use type pre-conditions. #144
- **Experimental**: Added support for exporting rule data from templates. #145
- Added `Export-AzTemplateRuleData` cmdlet to export templates. See cmdlet help for limitations.
- Template and parameters are merged, resolving functions, copy loops and conditions.

Pre-release v0.6.0-B1911011

---

CHANGELOG.md
src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.VirtualNetwork.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.VirtualNetwork.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Cmdlet.Common.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.VirtualNetwork.json
tests/PSRule.Rules.Azure.Tests/Rule.Common.Tests.ps1

- Fix processing of `Azure.VirtualNetwork.NSGAssociated` for templates. #150
- Fix processing of `Azure.VirtualNetwork.LateralTraversal` when `destinationPortRanges` is used. #149
Fixes #149 
Fixes #150 

Fix VNET rule processing #149 #150

---

CHANGELOG.md
docs/commands/PSRule.Rules.Azure/en-US/Export-AzTemplateRuleData.md
src/PSRule.Rules.Azure/Data/Template/Exceptions.cs
src/PSRule.Rules.Azure/Data/Template/ExpressionBuilder.cs
src/PSRule.Rules.Azure/Data/Template/ExpressionStream.cs
src/PSRule.Rules.Azure/Data/Template/Functions.cs
src/PSRule.Rules.Azure/Data/Template/Models.cs
src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
src/PSRule.Rules.Azure/Pipeline/Exceptions.cs
src/PSRule.Rules.Azure/Pipeline/TemplatePipeline.cs
src/PSRule.Rules.Azure/Pipeline/TemplateSource.cs
src/PSRule.Rules.Azure/Resources/PSRuleResources.Designer.cs
src/PSRule.Rules.Azure/Resources/PSRuleResources.resx
tests/PSRule.Rules.Azure.Tests/Cmdlet.Common.Tests.ps1
tests/PSRule.Rules.Azure.Tests/ExpressionParserTests.cs
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
tests/PSRule.Rules.Azure.Tests/Resources.Parameters.json
tests/PSRule.Rules.Azure.Tests/Resources.Template.json
tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs

- Added support for nested templates.
- Added support for `array`, `createArray`, `coalesce`, `intersection`, `dataUri` and `dataUriToString` functions.

Improved template support #145

---

CHANGELOG.md
src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Resource.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.Template.json

- Fixed processing of `Azure.Resource.UseTags` to exclude `*/providers/roleAssignments`. #155
- Provider role assignments do not support tags.
- Fixed processing of `Azure.Resource.AllowedRegions`. #156
- Exclude `*/providers/roleAssignments`, `Microsoft.Authorization/*` and `Microsoft.Consumption/*`.
Fixes #155 
Fixes #156 

Fix processing for resource rules #155 #156

---

CHANGELOG.md

- Fixed processing of `Azure.Resource.UseTags` to exclude `*/providers/roleAssignments`. #155
- Provider role assignments do not support tags.
- Fixed processing of `Azure.Resource.AllowedRegions`. #156
- Exclude `*/providers/roleAssignments`, `Microsoft.Authorization/*` and `Microsoft.Consumption/*`.

Pre-release v0.6.0-B1911027

---

CHANGELOG.md
docs/commands/PSRule.Rules.Azure/en-US/Export-AzTemplateRuleData.md
src/PSRule.Rules.Azure/Pipeline/PipelineBuilder.cs
src/PSRule.Rules.Azure/Pipeline/TemplatePipeline.cs

- Fixed `Export-AzTemplateRuleData` does not return FileInfo objects. #162
- Fixed Automatically name outputs from `Export-AzTemplateRuleData`. #163
Fixed #162 
Fixed #163 

Fix template export #162 #163

---

CHANGELOG.md
pipeline.build.ps1
src/PSRule.Rules.Azure/Data/Template/ExpressionBuilder.cs
src/PSRule.Rules.Azure/Data/Template/Functions.cs
src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
tests/PSRule.Rules.Azure.Tests/Resources.Template.json

- Fixed resource segmentation issue when `ResourceType` includes trailing slash. #165
- Fixed expand resource template property as null fails. #167
- Fixed case-sensitivity of variables, parameters and functions. #168
Fixed #165 
Fixed #167 
Fixed #168 

Fix quickstart templates #165 #167 #168

---

CHANGELOG.md

- Fixed null reference without parameters file. #189
- Added new rule to check presence of classic Co-Administrators. #188
- Added new rule to check AKS node pool version matches cluster version. #186
- Added new rule to check AKS clusters use pod security policies. #142
- Added new rule to check AKS clusters use network policies. #143
- Added new rule to check AKS node pools use scale sets. #187
- Added new baseline to include rules for preview features. #190
- Updated `Azure.AKS.Version` to check for node pool version. #191
- **Breaking change**: RBAC rules have been renamed from `Azure.Subscription.*` to `Azure.RBAC.*`. #119
- **Breaking change**: Security Center rules have been renamed from `Azure.Subscription.*` to `Azure.SecureCenter.*`. #119
- **Breaking change**: Renamed default …

Pre-release v0.7.0-B1912008

---

CHANGELOG.md
src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json

- Fixed AKS templates without node pool orchestratorVersion fail. #198
Fixes #198 

Fixed missing node pool version fail #198

---

.azure-pipelines/azure-pipelines.yaml
tests/PSRule.Rules.Azure.Tests/Module.PSGallery.Tests.ps1

- PSScriptAnalyzer tests are flaky so have been disabled until issue is resolved.
- Updated tasks in CI pipeline.

Disable PSScriptAnalyzer in CI process

---

CHANGELOG.md

- Updated documentation to use parent culture `en`. #224
- Added rules for ARM template and parameter file structure. #225
- **Breaking change**: Application Gateway rules have been renamed from `Azure.VirtualNetwork.*` to `Azure.AppGW.*`. #119
- **Breaking change**: Load balancer rules have been renamed from `Azure.VirtualNetwork.*` to `Azure.LB.*`. #119
- **Breaking change**: NSG rules have been renamed from `Azure.VirtualNetwork.*` to `Azure.NSG.*`. #119
- **Breaking change**: VNET rules have been renamed from `Azure.VirtualNetwork.*` to `Azure.VNET.*`. #119
- **Breaking change**: NIC rules have been renamed from `Azure.VirtualNetwork.*` to `Azure.VM.*`. #119
- **Breaking change**: Renamed storage account rule `Azure.Storage.SecureTransferRequired` to `Azure.Storage.SecureTransfer`. …

Pre-release v0.8.0-B2001006

---

CHANGELOG.md
src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1

- Fix `Azure.Resource.UseTags` applying to template and parameter files. #230
Fixes #230 

Fix Azure.Resource.UseTags filter #230

---

CHANGELOG.md
src/PSRule.Rules.Azure/en-AU/PSRule-rules.psd1
src/PSRule.Rules.Azure/en-GB/PSRule-rules.psd1
src/PSRule.Rules.Azure/en-US/PSRule-rules.psd1
src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.VirtualNetwork.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.VirtualNetwork.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json
tests/PSRule.Rules.Azure.Tests/Resources.AKS.json

- Updated `Azure.VNET.UseNSGs` to apply to subnet resources from templates. #246
- Updated `Azure.AKS.Version` to 1.15.7. #247
Fixes #246 
Fixes #247 

Updated Azure.VNET.UseNSGs for subnets #246 #247

---

CHANGELOG.md

- Updated `Azure.VNET.UseNSGs` to apply to subnet resources from templates. #246
- Updated `Azure.AKS.Version` to 1.15.7. #247
- **Breaking change**: Renamed `Azure.File.*` rules to `Azure.Template.*`. #252

Pre-release v0.8.0-B2001029

---

CHANGELOG.md
docs/rules/en/Azure.AppGw.SSLPolicy.md
docs/rules/en/Azure.VNET.UseNSGs.md
src/PSRule.Rules.Azure/rules/Azure.VirtualNetwork.Rule.ps1

- Fixed `Azure.VNET.UseNSGs` to exclude `AzureFirewallSubnet`. #261
Fixes #261 

Fixed Azure.VNET.UseNSGs #261

---

CHANGELOG.md

- Fixed incorrect string formatting in POSIX culture.  #262
- Fixed `Azure.VNET.UseNSGs` to exclude `AzureFirewallSubnet`. #261

Pre-release v0.9.0-B2002011

---

.azure-pipelines/azure-pipelines.yaml
docs/scenarios/install-instructions.md
tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj

- Remove reference to `Az.Security` which is no longer a dependency in module install instructions.

Remove Az.Security in install instructions

---

docs/scenarios/install-instructions.md

- Updated manual build instructions for using .NET Core 3.1 SDK instead of 2.1.

Updated install instructions for .NET Core 3.1

---

CHANGELOG.md
src/PSRule.Rules.Azure/rules/Azure.Resource.Rule.ps1

- Removed warning message for `azureAllowedRegions` option. #328
Fixes #328 

Removed warning for azureAllowedRegions #328

---

CHANGELOG.md
src/PSRule.Rules.Azure/rules/Azure.PublicIP.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.VirtualMachine.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.PublicIP.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.VirtualMachine.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.Template3.json
tests/PSRule.Rules.Azure.Tests/Resources.VirtualMachine.json

- Bug fixes:
- Fixed false positive for unused public IP in templates. #336
- Fixed false positive for use of managed disks in templates. #337
- Fixed false positive for disk caching when no VM data disks is null in templates. #338
Fixes #336 
Fixes #337 
Fixes #338 

Fix false positives for resources #336 #337 #338

---

CHANGELOG.md
README.md
docs/concepts/PSRule.Rules.Azure/en-US/about_PSRule_Azure_Configuration.md
docs/rules/en/Azure.AKS.NodeMinPods.md
docs/rules/en/Azure.AKS.Version.md
docs/rules/en/Azure.APIM.CertificateExpiry.md
src/PSRule.Rules.Azure/en/PSRule-rules.psd1
src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.Resource.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Resource.Tests.ps1

- **Breaking change**: Renamed configuration options to use a standard prefix. #327
- Configuration options use the `Azure_` prefix.
- Update configuration settings to use the new name, old configuration names are ignored.
- Renamed `minAKSVersion` to `Azure_AKSMinimumVersion`.
- Renamed `azureAllowedRegions` to `Azure_AllowedRegions`.
- Added configuration option documentation.
Fixes #327 

Renamed configuration options to use a standard prefix #327

---

CHANGELOG.md

- New rules:
- Check AKS nodes use a minimum number of pods. #274
- **Breaking change**: Renamed configuration options to use a standard prefix. #327
- Configuration options use the `Azure_` prefix.
- Update configuration settings to use the new name, old configuration names are ignored.
- Renamed `minAKSVersion` to `Azure_AKSMinimumVersion`.
- Renamed `azureAllowedRegions` to `Azure_AllowedRegions`.
- Added configuration option documentation. See [about_PSRule_Azure_Configuration](https://github.com/Microsoft/PSRule.Rules.Azure/blob/master/docs/concepts/PSRule.Rules.Azure/en-US/about_PSRule_Azure_Configuration.md) for details.

Pre-release v0.11.0-B2004012

---

CHANGELOG.md
src/PSRule.Rules.Azure/rules/Azure.VirtualNetwork.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.VirtualNetwork.Tests.ps1

- Fixed handling of subnet sub-resource name with slash. #381
Fixes #381 

Fix subnet sub-resource name with slash #381

---

CHANGELOG.md
src/PSRule.Rules.Azure/rules/Azure.VirtualNetwork.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.VirtualNetwork.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.VirtualNetwork.json

- Fixed subnet name check for VNET with no subnets. #386
Fixes #386 

Fixed subnet name check for VNET with no subnets #386

---

CHANGELOG.md
pipeline.build.ps1
src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json
tests/PSRule.Rules.Azure.Tests/Resources.AKS.json

- Updated `Azure.AKS.Version` to 1.16.9. #394
Fixes #394 

Updated Azure.AKS.Version version to v1.16.9 #394

---

CHANGELOG.md
docs/rules/en/Azure.AKS.AzurePolicyAddOn.md
docs/rules/en/Azure.AKS.ManagedIdentity.md
docs/rules/en/Azure.AKS.NodeMinPods.md
docs/rules/en/Azure.AKS.StandardLB.md
docs/rules/en/module.md
docs/rules/en/resource.md
src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json
tests/PSRule.Rules.Azure.Tests/Resources.AKS.json

- New rules:
- Check AKS clusters use a Standard load balancer SKU. #334
- Check AKS clusters use Managed Identities for cluster infrastructure. #333
- Check AKS clusters use Azure Policy add-on (preview). #405
Fixes #333 
Fixes #334 
Fixes #405 

Added new AKS rules #334 #333 #405

---

CHANGELOG.md
src/PSRule.Rules.Azure/en/PSRule-rules.psd1
src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.AppService.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.Automation.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.MySQL.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.PostgreSQL.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.Redis.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.SQL.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.VirtualNetwork.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.MySQL.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.PostgreSQL.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.SQL.Tests.ps1

Updated rule reasons and logic for:
- Azure.AKS.MinNodeCount
- Azure.AppService.PlanInstanceCount
- Azure.Automation.EncryptVariables
- Azure.Automation.WebHookExpiry
- Azure.MySQL.UseSSL
- Azure.MySQL.FirewallRuleCount
- Azure.MySQL.FirewallIPRange
- Azure.PostgreSQL.UseSSL
- Azure.PostgreSQL.FirewallRuleCount
- Azure.PostgreSQL.FirewallIPRange
- Azure.Redis.NonSslPort
- Azure.Redis.MinTLS
- Azure.SQL.FirewallRuleCount
- Azure.SQL.FirewallIPRange
- Azure.VNET.SingleDNS
- Azure.VNET.PeerState
- Azure.AppGw.MinInstance
- Azure.AppGw.Prevention
- Azure.AppGw.WAFEnabled
- Azure.AppGw.OWASP
Fixes #424 

Updated rule reasons and logic #424

---

CHANGELOG.md
src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.Resource.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Rule.Common.Tests.ps1

- Fixed resource tags rule to exclude diagnostic settings. #448
Fixes #448 

Fix resource tags rule to exclude diagnostic settings #448

---

CHANGELOG.md
docs/baselines/en/Azure.All.md
docs/baselines/en/Azure.Default.md
docs/baselines/en/Azure.Preview.md
docs/rules/en/Azure.Storage.BlobAccessType.md
docs/rules/en/Azure.Storage.BlobPublicAccess.md
docs/rules/en/Azure.Storage.MinTLS.md
docs/rules/en/module.md
docs/rules/en/resource.md
src/PSRule.Rules.Azure/rules/Azure.Storage.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Storage.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.Storage.json

- Check Storage Accounts reject TLS versions older than 1.2. #455 
- Check Storage Accounts only accept authorized requests. #456
Fixes #455 
Fixes #456 

Storage Account public access and TLS #455 #456

---

CHANGELOG.md
src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
tests/PSRule.Rules.Azure.Tests/Cmdlet.Common.Tests.ps1

- Fixed export of non-blob Storage Accounts. #464
- Fixed export of subscription Security Center data based on API version. #465
- Fixed masking of sharedKey when property does not exist. #466
Fixes #464 
Fixes #465 
Fixes #466 

Export fixes for #464 #465 #466

---

CHANGELOG.md

What's changed since pre-release v0.15.0-B2008026:
- Bug fixes:
- Fixed export of non-blob Storage Accounts. #464
- Fixed export of subscription Security Center data based on API version. #465
- Fixed masking of sharedKey when property does not exist. #466

Pre-release v0.15.0-B2008034

---

CHANGELOG.md
docs/baselines/en/Azure.All.md
docs/baselines/en/Azure.Default.md
docs/baselines/en/Azure.Preview.md
docs/rules/en/Azure.MySQL.MinTLS.md
docs/rules/en/Azure.PostgreSQL.MinTLS.md
docs/rules/en/Azure.Redis.MinTLS.md
docs/rules/en/Azure.SQL.MinTLS.md
docs/rules/en/module.md
docs/rules/en/resource.md
src/PSRule.Rules.Azure/rules/Azure.MySQL.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.PostgreSQL.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.SQL.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.MySQL.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.PostgreSQL.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.SQL.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.MySQL.json
tests/PSRule.Rules.Azure.Tests/Resources.PostgreSQL.json
tests/PSRule.Rules.Azure.Tests/Resources.SQL.json

- New rules:
- Database for MySQL:
- Check database servers reject TLS versions older than 1.2. #469
- Database for PostgreSQL:
- Check database servers reject TLS versions older than 1.2. #470
- Check database servers reject TLS versions older than 1.2. #471
Fixes #469 
Fixes #470 
Fixes #471 

Database TLS checks #469 #470 #471

---

CHANGELOG.md

What's changed since pre-release v0.15.0-B2008034:
- New rules:
- Database for MySQL:
- Check database servers reject TLS versions older than 1.2. #469
- Database for PostgreSQL:
- Check database servers reject TLS versions older than 1.2. #470
- Check database servers reject TLS versions older than 1.2. #471
- Bug fixes:
- Fixed use variables check when no variables are defined. #462

Pre-release v0.15.0-B2008043

---

CHANGELOG.md
docs/baselines/en/Azure.All.md
docs/baselines/en/Azure.Default.md
docs/baselines/en/Azure.Preview.md
docs/rules/en/Azure.CDN.EndpointName.md
docs/rules/en/Azure.CDN.MinTLS.md
docs/rules/en/module.md
docs/rules/en/resource.md
src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
src/PSRule.Rules.Azure/rules/Azure.CDN.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.CDN.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.CDN.json

- Check CDN endpoint naming requirements. #486 
- Check CDN endpoints use TLS 1.2. #487
Fixes #486 
Fixes #487 

Add CDN endpoint TLS and naming rule #486 #487

---

CHANGELOG.md

What's changed since pre-release v0.17.0-B2009009:
- New rules:
- Check App Configuration stores meet name requirements. #528
- Check App Configuration stores use standard SKU. #528
- App Service:
- Check App Service apps use Always On. #521
- Check App Service apps have remote debugging disabled. #521
- Check App Service apps use newer .NET Framework versions. #521
- Check App Service apps use newer PHP runtime versions. #521
- Logic App:
- Check Logic App apps limit IP range for HTTP triggers. #526
- Promote `Azure.AKS.AzurePolicyAddOn` to GA rule set. #524
- Removed rules:
- Remove `Azure.AKS.PodSecurityPolicy` as this AKS feature is replaced by Azure Policy. #523

Pre-release v0.17.0-B2010006

---

CHANGELOG.md
docs/baselines/en/Azure.All.md
docs/baselines/en/Azure.Default.md
docs/baselines/en/Azure.GA_2020_06.md
docs/baselines/en/Azure.GA_2020_09.md
docs/baselines/en/Azure.Preview.md
docs/rules/en/Azure.Storage.UseReplication.md
docs/rules/en/module.md
docs/rules/en/resource.md
src/PSRule.Rules.Azure/rules/Azure.AppService.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.Storage.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.AppService.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Storage.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.AppService.Parameters.json
tests/PSRule.Rules.Azure.Tests/Resources.AppService.Template.json
tests/PSRule.Rules.Azure.Tests/Resources.Storage.json

- Storage:
- Updated `Azure.Storage.UseReplication` for additional use cases.
- Added support for geo-zone-redundant storage. #535
- Exclude storage tagged with `resource-usage = 'azure-functions'` or `resource-usage = 'azure-monitor'`. #534
- Bug fixes:
- Fixed App Service rule site config false positives in templates. #533
Fixes #533 
Fixes #534 
Fixes #535 

Update app service and storage rules #533 #534 #535

---

CHANGELOG.md

What's changed since pre-release v0.17.0-B2010022:
- New rules:
- Check cache instances use Standard C1 or greater SKU. #501
- Cache cache instances configure `maxmemory-reserved` setting. #502

Pre-release v0.17.0-B2010028

---

CHANGELOG.md
src/PSRule.Rules.Azure/Configuration/PSRuleOption.cs
src/PSRule.Rules.Azure/Pipeline/PathBuilder.cs
src/PSRule.Rules.Azure/en/PSRule-rules.psd1

- Bug fixes:
- Fixed reason typo on template parameter metadata. #567
- Fixed `Get-AzRuleTemplateLink` reports incorrect parameter with file path. #568
Fixes #567 
Fixes #568 

Fixed reason string and template link path handling #567 #568

---

CHANGELOG.md
src/PSRule.Rules.Azure/Data/Template/ExpressionBuilder.cs
src/PSRule.Rules.Azure/Data/Template/Functions.cs
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
tests/PSRule.Rules.Azure.Tests/Resources.Template.json

- Added support for `true`, `false`, and `null` template functions. #579
Fixes #579 

Added support for true false and null template functions #579

---

CHANGELOG.md
src/PSRule.Rules.Azure/Data/Template/Functions.cs
tests/PSRule.Rules.Azure.Tests/Cmdlet.Common.Tests.ps1
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
tests/PSRule.Rules.Azure.Tests/Resources.Template.json

- Added support for `createObject` template function. #580
Fixes #580 

Added support for createObject function #580

---

CHANGELOG.md

What's changed since pre-release v0.19.0-B2011008:
- Updated `Azure.AKS.Version` to 1.19.3. #590
- Engineering:
- Bump PSRule dependency to v1.0.0. #588

Pre-release v0.19.0-B2012008

---

CHANGELOG.md
README.md
docs/baselines/en/Azure.GA_2020_12.md
src/PSRule.Rules.Azure/rules/Baseline.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1

- Added `Azure.GA_2020_12` baseline. #593
- Includes rules released before or during December 2020 for Azure GA features.
- Marked baseline `Azure.GA_2020_09` as obsolete.
Fixes #593

Added Azure.GA_2020_12 baseline #593

---

src/PSRule.Rules.Azure/PSRule.Rules.Azure.csproj

- Migrate from deprecated FxCop analyzers to .NET analyzers. #605
Fixes #605

Migrate from deprecated FxCop analyzers to .NET analyzers #605

---

CHANGELOG.md
docs/rules/en/Azure.FrontDoor.Probe.md
docs/rules/en/Azure.FrontDoor.ProbeMethod.md
docs/rules/en/Azure.FrontDoor.ProbePath.md
src/PSRule.Rules.Azure/en/PSRule-rules.psd1
src/PSRule.Rules.Azure/rules/Azure.FrontDoor.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.FrontDoor.Tests.ps1

- Fixed reason `Azure.FrontDoor.ProbePath` so the probe name is included.
Fixes #617

Fixed Azure.FrontDoor.ProbePath reason #617

---

CHANGELOG.md
README.md
docs/commands/PSRule.Rules.Azure/en-US/Export-AzRuleTemplateData.md
docs/features.md
docs/scenarios/azure-pipelines-ci/azure-pipelines-ci.md
docs/scenarios/azure-pipelines-ci/azure-pipelines.yaml
docs/scenarios/azure-template-ci/azure-template-ci.md
docs/scenarios/azure-template-ci/validate-template.ps1
src/PSRule.Rules.Azure/PSRule.Rules.Azure.psd1
src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
tests/Integration/QuickStartTemplate.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.AppService.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.FrontDoor.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.KeyVault.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Policy.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.PublicIP.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Resource.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.ServiceFabric.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Storage.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.VM.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.VirtualNetwork.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Cmdlet.Common.Tests.ps1

- Renamed `Export-AzTemplateRuleData` to `Export-AzRuleTemplateData`.
- New name `Export-AzRuleTemplateData` aligns with prefix of other cmdlets.
- Use of `Export-AzTemplateRuleData` is now deprecated and will be removed in the next major version.
- Added alias to allow `Export-AzTemplateRuleData` to continue to be used.
- Using `Export-AzTemplateRuleData` returns a deprecation warning.
Fixes #596 

Rename cmdlet Export-AzTemplateRuleData #596

---

CHANGELOG.md
README.md
docs/features.md

What's changed since pre-release v1.0.0-B2101016:
- New rules:
- Check parameter default value type matches type. #311
- Renamed `Export-AzTemplateRuleData` to `Export-AzRuleTemplateData`. #596
- New name `Export-AzRuleTemplateData` aligns with prefix of other cmdlets.
- Use of `Export-AzTemplateRuleData` is now deprecated and will be removed in the next major version.
- Added alias to allow `Export-AzTemplateRuleData` to continue to be used.
- Using `Export-AzTemplateRuleData` returns a deprecation warning.

Pre-release v1.0.0-B2101028

---

docs/CHANGELOG-v1.md
docs/rules/en/Azure.VM.ADE.md
src/PSRule.Rules.Azure/rules/Azure.VM.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.VM.Tests.ps1

- Fixed `Azure.VM.ADE` to limit rule to exports only. #644
Fixes #644 

Fixed Azure.VM.ADE to limit rule to exports #644

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/ExpressionBuilder.cs
src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs
src/PSRule.Rules.Azure/Data/Template/ExpressionStream.cs
src/PSRule.Rules.Azure/Data/Template/Functions.cs
src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
src/PSRule.Rules.Azure/Resources/PSRuleResources.Designer.cs
src/PSRule.Rules.Azure/Resources/PSRuleResources.resx
tests/PSRule.Rules.Azure.Tests/ExpressionParserTests.cs
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs

- Fixed `if` condition values evaluation order. #652
- Fixed handling of `int` parameters with large values. #653
- Fixed handling of expressions split over multiple lines. #654
- Fixed handling of bool parameter values within logical expressions. #655
Fixes #652 
Fixes #653 
Fixes #654 
Fixes #655

Bug fixes for #652 #653 #654 #655

---

README.md
ThirdPartyNotices.txt
docs/CHANGELOG-v1.md
docs/commands/PSRule.Rules.Azure/en-US/Export-AzRuleTemplateData.md
docs/commands/PSRule.Rules.Azure/en-US/Get-AzRuleTemplateLink.md
docs/concepts/PSRule.Rules.Azure/en-US/about_PSRule_Azure_Configuration.md
docs/scenarios/deployment-objects/export.template.json
src/PSRule.Rules.Azure/Common/DictionaryExtensions.cs
src/PSRule.Rules.Azure/Configuration/ConfigurationOption.cs
src/PSRule.Rules.Azure/Configuration/OutputOption.cs
src/PSRule.Rules.Azure/Configuration/PSRuleOption.cs
src/PSRule.Rules.Azure/Configuration/ResourceGroupOption.cs
src/PSRule.Rules.Azure/Configuration/SubscriptionOption.cs
src/PSRule.Rules.Azure/Data/Template/Models.cs
src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
src/PSRule.Rules.Azure/PSRule.Rules.Azure.csproj
src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
src/PSRule.Rules.Azure/Pipeline/PipelineBuilder.cs
src/PSRule.Rules.Azure/Pipeline/TemplatePipeline.cs
tests/PSRule.Rules.Azure.Tests/Cmdlet.Common.Tests.ps1
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
tests/PSRule.Rules.Azure.Tests/OptionsTests.cs
tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
tests/PSRule.Rules.Azure.Tests/Resources.Template.json
tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
tests/PSRule.Rules.Azure.Tests/ps-rule-options.yaml

- Exporting template with `Export-AzRuleTemplateData` supports custom resource group and subscription. #651
- Subscription and resource group used for deployment can be specified instead of using defaults.
- `ResourceGroupName` parameter of `Export-AzRuleTemplateData` has been renamed to `ResourceGroup`.
- Added a parameter alias for `ResourceGroupName` on `Export-AzRuleTemplateData`.
Fixes #651 

Export template with custom subscription and resource group #651

---

docs/CHANGELOG-v1.md
docs/commands/PSRule.Rules.Azure/en-US/Get-AzRuleTemplateLink.md
src/PSRule.Rules.Azure/Pipeline/TemplateLinkPipeline.cs

- Added support for matching template by name. #661
- `Get-AzRuleTemplateLink` discovers `<templateName>.json` from `<templateName>.parameters.json`.
Fixes #661 

Added support for matching template by name #661

---

docs/CHANGELOG-v1.md
docs/scenarios/deployment-objects/export.template.json
src/PSRule.Rules.Azure/Common/JsonExtensions.cs
src/PSRule.Rules.Azure/Data/Template/Exceptions.cs
src/PSRule.Rules.Azure/Data/Template/ExpressionBuilder.cs
src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs
src/PSRule.Rules.Azure/Data/Template/Functions.cs
src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
src/PSRule.Rules.Azure/Data/Template/TokenStream.cs
src/PSRule.Rules.Azure/Pipeline/PipelineBuilder.cs
src/PSRule.Rules.Azure/Pipeline/PipelineContext.cs
src/PSRule.Rules.Azure/Pipeline/PipelineWriter.cs
src/PSRule.Rules.Azure/Pipeline/TemplateLinkPipeline.cs
src/PSRule.Rules.Azure/Pipeline/TemplatePipeline.cs
src/PSRule.Rules.Azure/Resources/PSRuleResources.Designer.cs
src/PSRule.Rules.Azure/Resources/PSRuleResources.resx
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
tests/PSRule.Rules.Azure.Tests/Template.Parsing.1.json
tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs

- Fixed copy loop value does not fall within the expected range. #664
- Fixed template comparison functions handling of large integer values. #666
- Fixed handling of `createArray` function with no arguments. #667
Fixes #664 
Fixes #666 
Fixes #667 

Fixes template expansion issues #664 #666 #667

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/ExpressionStream.cs
tests/PSRule.Rules.Azure.Tests/Template.Parsing.1.json
tests/PSRule.Rules.Azure.Tests/Template.Parsing.2.json

- Fixed parsing of property names for functions across multiple lines. #683
Fixes #683 

Fixed parsing of property names for functions across multiple lines #683

---

docs/CHANGELOG-v0.md
docs/CHANGELOG-v1.md
docs/baselines/en/Azure.GA_2021_03.md
src/PSRule.Rules.Azure/rules/Baseline.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Rule.Common.Tests.ps1

- Added `Azure.GA_2021_03` baseline. #673
- Includes rules released before or during March 2021 for Azure GA features.
- Marked baseline `Azure.GA_2020_12` as obsolete.
Fixes #673

Added quarterly baseline for March 2021 #673

---

docs/CHANGELOG-v1.md

What's changed since v1.1.4:
- Added `Azure.GA_2021_03` baseline. #673
- Includes rules released before or during March 2021 for Azure GA features.
- Marked baseline `Azure.GA_2020_12` as obsolete.
- New rules:
- Key Vault:
- Check vaults, keys, and secrets meet name requirements. #646
- Updated `Azure.AKS.Version` to 1.19.7. #696
- Engineering:
- Bump PSRule dependency to v1.1.0. #692
- Added support for user defined functions in templates. #682
What's changed since pre-release v1.2.0-B2103044:
- No additional changes.

Release v1.2.0

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Metadata/TemplateLink.cs
src/PSRule.Rules.Azure/Pipeline/TemplateLinkPipeline.cs
tests/PSRule.Rules.Azure.Tests/Cmdlet.Common.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.Parameters.json

- Additional metadata added in parameter file is passed through with `Get-AzRuleTemplateLink`. #706
Fixes #706 

Pass through metadata from parameter file #706

---

docs/CHANGELOG-v1.md

What's changed since v1.2.0:
- Removed rules:
- Storage:
- Remove `Azure.Storage.UseEncryption` as Storage Service Encryption (SSE) is always on. #630
- SSE is on by default and can not be disabled.
- Additional metadata added in parameter files is passed through with `Get-AzRuleTemplateLink`. #706

Pre-release v1.3.0-B2103007

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.3.0-B2104034:
- Bug fixes:
- Fixed could not load file or assembly YamlDotNet. #741
- This fix pins the PSRule version to v1.2.0 until the next stable release of PSRule for Azure.

Pre-release v1.3.0-B2104040

---

docs/CHANGELOG-v1.md

What's changed since v1.2.1:
- New rules:
- Policy:
- Check policy assignment display name and description are set. #725
- Check policy assignment assigned by metadata is set. #726
- Check policy exemption display name and description are set. #723
- Check policy waiver exemptions have an expiry date set. [#724
- Removed rules:
- Storage:
- Remove `Azure.Storage.UseEncryption` as Storage Service Encryption (SSE) is always on. #630
- SSE is on by default and can not be disabled.
- Additional metadata added in parameter files is passed through with `Get-AzRuleTemplateLink`. #706
- Improved binding support for File inputs. #480
- Template and parameter file names now return a relative path instead of full path.
- Added API version for each module resource. #729
- …

Release v1.3.0

---

docs/CHANGELOG-v1.md
pipeline.build.ps1
ps-project.yaml
src/PSRule.Rules.Azure/PSRule.Rules.Azure.csproj

- Bump PSRule dependency to v1.3.0. #749
- Bump YamlDotNet dependency to v11.1.1. #742
Fixes #749 
Fixes #742

Bump PSRule dependency to v1.3.0 #749 #742

---

.vscode/settings.json
.vscode/tasks.json
docs/CHANGELOG-v1.md
docs/commands/PSRule.Rules.Azure/en-US/Export-AzRuleTemplateData.md
pipeline.build.ps1
src/PSRule.Rules.Azure/Common/JsonExtensions.cs
src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
src/PSRule.Rules.Azure/Pipeline/TemplatePipeline.cs
src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Storage.Tests.ps1
tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json
tests/PSRule.Rules.Azure.Tests/Resources.AKS.json
tests/PSRule.Rules.Azure.Tests/Resources.KeyVault.Template.json
tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs

- Automatically nest template sub-resources for analysis. #746
- Sub-resources such as diagnostic logs or configurations are automatically nested.
- Automatic nesting a resource requires:
- The parent resource is defined in the same template.
- The sub-resource depends on the parent resource.
Fixes #746 

Nest sub-resources resources for analysis #746

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Configuration/ConfigurationOption.cs
src/PSRule.Rules.Azure/Configuration/PSRuleOption.cs
src/PSRule.Rules.Azure/Configuration/ResourceGroupOption.cs
src/PSRule.Rules.Azure/Configuration/SubscriptionOption.cs
src/PSRule.Rules.Azure/Data/Template/TemplateHelper.cs
src/PSRule.Rules.Azure/Data/Template/TemplateLinkHelper.cs
src/PSRule.Rules.Azure/Pipeline/LoggingExtensions.cs
src/PSRule.Rules.Azure/Pipeline/TemplateLinkPipeline.cs
src/PSRule.Rules.Azure/Pipeline/TemplatePipeline.cs
src/PSRule.Rules.Azure/Runtime/Helper.cs
src/PSRule.Rules.Azure/rules/Config.Rule.yaml
src/PSRule.Rules.Azure/rules/Conventions.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Convention.Tests.ps1

- Automatically expand template from parameter files for analysis. #772
- Previously templates needed to be exported with `Export-AzRuleTemplateData`.
- To export template data automatically use PSRule cmdlets with `-Format File`.
Fixes #772 

Automatically expand parameters for analysis #772

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/ExpressionParser.cs
tests/PSRule.Rules.Azure.Tests/ExpressionParserTests.cs

- Fixed string index parsing in expressions with whitespace. #775
Fixes #775 

Fix string index parsing with whitespace #775

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs
src/PSRule.Rules.Azure/Data/Template/Functions.cs
tests/PSRule.Rules.Azure.Tests/ExpressionBuilderTests.cs

- Fixed base for DateTimeAdd is not a valid string. #777
Fixes #777

Fixed base for DateTimeAdd not a valid string #777

---

docs/CHANGELOG-v1.md
docs/baselines/en/Azure.All.md
docs/baselines/en/Azure.Default.md
docs/baselines/en/Azure.Preview.md
docs/concepts/PSRule.Rules.Azure/en-US/about_PSRule_Azure_Configuration.md
docs/rules/en/Azure.AKS.AuthorizedIPs.md
docs/rules/en/Azure.AKS.AutoUpgrade.md
docs/rules/en/Azure.AKS.AzurePolicyAddOn.md
docs/rules/en/Azure.AKS.AzureRBAC.md
docs/rules/en/Azure.AKS.LocalAccounts.md
docs/rules/en/Azure.AKS.ManagedAAD.md
docs/rules/en/Azure.AKS.PoolVersion.md
docs/rules/en/Azure.AKS.UseRBAC.md
docs/rules/en/Azure.AKS.Version.md
docs/rules/en/Azure.Resource.AllowedRegions.md
docs/rules/en/module.md
docs/rules/en/resource.md
src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json
tests/PSRule.Rules.Azure.Tests/Resources.AKS.json

- New rules:
- Check clusters use AKS-managed Azure AD integration. #436
- Check clusters have local account disabled (preview). #786
- Check clusters have an auto-upgrade channel set (preview). #787
- Check clusters limit access network access to the API server. #788
- Check clusters used Azure RBAC for Kubernetes authorization. #789)
- Updated rules
- Updated `Azure.AKS.Version` to 1.20.5. #767
Fixes #436 
Fixes #786 
Fixes #787 
Fixes #788 
Fixes #789 
Fixes #767

AKS rules #436 #786 #787 #788 #789 #767

---

docs/CHANGELOG-v1.md

What's changed since v1.3.2:
- Automatically expand template from parameter files for analysis. #772
- Previously templates needed to be exported with `Export-AzRuleTemplateData`.
- To export template data automatically use PSRule cmdlets with `-Format File`.
- New rules:
- Cognitive Search:
- Check search services meet index SLA replica requirement. #761
- Check search services meet query SLA replica requirement. #762
- Check search services meet naming requirements. #763
- Check search services use a minimum SKU. #764
- Check search services use managed identities. #765
- Check clusters use AKS-managed Azure AD integration. #436
- Check clusters have local account disabled (preview). #786
- Check clusters have an auto-upgrade channel set …

Release v1.4.0

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/ExpressionBuilder.cs
src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs
src/PSRule.Rules.Azure/Data/Template/Functions.cs
tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
tests/PSRule.Rules.Azure.Tests/Template.Parsing.6.json
tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs

- Fixed boolean string conversion case. #793
- Fixed case sensitive property matching. #794
Fixes #793 
Fixes #794 

Fix case and bool parsing issues #793 #794

---

README.md
docs/CHANGELOG-v1.md
docs/concepts/PSRule.Rules.Azure/en-US/about_PSRule_Azure_Configuration.md
src/PSRule.Rules.Azure/rules/Config.Rule.yaml
src/PSRule.Rules.Azure/rules/Conventions.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Convention.Tests.ps1

- Fixed automatic expansion of template parameter files. #796
- Template parameter files are not automatically expanded by default.
- To enable this, set the `AZURE_PARAMETER_FILE_EXPANSION` configuration option.
Fixes #796 

Fixed automatic expansion of parameter files #796

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.5.0-B2106018:
- Added `Azure.GA_2021_06` baseline. #822
- Includes rules released before or during June 2021 for Azure GA features.
- Marked baseline `Azure.GA_2021_03` as obsolete.
- Updated rule help to use docs pages for online version. #824
- Engineering:
- Bump PSDocs dependency to v1.4.0. #823
- Bump YamlDotNet dependency to v11.2.1. #821

Pre-release v1.5.0-B2107002

---

docs/CHANGELOG-v1.md

What's changed since v1.4.1:
- Added `Azure.GA_2021_06` baseline. #822
- Includes rules released before or during June 2021 for Azure GA features.
- Marked baseline `Azure.GA_2021_03` as obsolete.
- New rules:
- Application Insights:
- Check App Insights resources use workspace-based configuration. #813
- Check App Insights resources meet naming requirements. #814
- Exclude not applicable rules for templates generated with Bicep and PSArm. #815
- Updated rule help to use docs pages for online version. #824
- Engineering:
- Bump PSDocs dependency to v1.4.0. #823
- Bump YamlDotNet dependency to v11.2.1. #821
- Migrate project to Azure GitHub organization and updated links. #800
- Bug fixes:
- Fixed detection of parameters and variables with line …

Release v1.5.0

---

docs/CHANGELOG-v1.md
docs/en/baselines/Azure.All.md
docs/en/baselines/Azure.Default.md
docs/en/baselines/Azure.GA_2020_06.md
docs/en/baselines/Azure.GA_2020_09.md
docs/en/baselines/Azure.GA_2020_12.md
docs/en/baselines/Azure.GA_2021_03.md
docs/en/baselines/Azure.GA_2021_06.md
docs/en/baselines/Azure.Preview.md
docs/en/rules/Azure.VNET.UseNSGs.md
docs/en/rules/module.md
docs/en/rules/resource.md
docs/examples.bicep
docs/examples.json
src/PSRule.Rules.Azure/rules/Azure.VNET.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Resources.VirtualNetwork.json

- Excluded `AzureFirewallManagementSubnet` from `Azure.VNET.UseNSGs`. #869

Updated Azure.VNET.UseNSGs #869

---

docs/en/baselines/Azure.All.md
docs/en/baselines/Azure.Default.md
docs/en/baselines/Azure.Preview.md
docs/en/rules/Azure.AKS.AutoScaling.md
docs/en/rules/module.md
docs/en/rules/resource.md
src/PSRule.Rules.Azure/en/PSRule-rules.psd1
src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json
tests/PSRule.Rules.Azure.Tests/Resources.AKS.json

Fix #218
Added a `Azure.AKS.AutoScaling` rule for release `GA` and baseline `2021_09`. 
The rule checks boths the following types:
- `Microsoft.ContainerService/managedClusters`
- `Microsoft.ContainerService/managedClusters/agentPools`
Also only checks agent pools of type `VirtualMachineScaleSets`, and agent pools that are any other type(such as `AvailabilitySets` just pass. Correct me if this needs to be handled differently. 
Also let me know if I should provide more detail in `docs/en/rules/Azure.AKS.AutoScaling.md`.

Enable AKS autoscaler rule

---

docs/CHANGELOG-v1.md

What's changed since v1.6.0:
- New rules:
- Check clusters use auto-scale node pools. #218
- Excluded `AzureFirewallManagementSubnet` from `Azure.VNET.UseNSGs`. #869
- Engineering:
- Bump PSRule dependency to v1.6.0. #871

Pre-release v1.7.0-B2108020

---

README.md
docs/CHANGELOG-v1.md
docs/en/baselines/Azure.All.md
docs/en/baselines/Azure.Default.md
docs/en/baselines/Azure.Preview.md
docs/en/rules/Azure.Template.MetadataLink.md
docs/en/rules/module.md
docs/en/rules/resource.md
docs/setup/configuring-expansion.md
docs/using-templates.md
src/PSRule.Rules.Azure/Data/Template/TemplateLinkHelper.cs
src/PSRule.Rules.Azure/Runtime/Helper.cs
src/PSRule.Rules.Azure/rules/Azure.Template.Rule.ps1
src/PSRule.Rules.Azure/rules/Config.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.Template.Tests.ps1

- Check template parameter files use metadata links. #846
- Configure the `AZURE_PARAMETER_FILE_METADATA_LINK` option to enable this rule.
Fixes #846

Use parameter file metadata link #846

---

docs/en/baselines/Azure.All.md
docs/en/baselines/Azure.Default.md
docs/en/baselines/Azure.Preview.md
docs/en/rules/Azure.AKS.AzureCNI.md
docs/en/rules/Azure.AKS.CNISubnetSize.md
docs/en/rules/module.md
docs/en/rules/resource.md
docs/setup/configuring-rules.md
src/PSRule.Rules.Azure/en/PSRule-rules.psd1
src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.AKS.json

Fix #273 
Added a `Azure.AKS.CNISubnetSize` rule for release `GA` and ruleset `2021_09`. 
Handles the following types:
- Microsoft.ContainerService/managedClusters
- Microsoft.ContainerService/managedClusters/agentPools
And only works for exported in-flight resource data. 

AKS Subnet AzureCNI rule

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.7.0-B2108020:
- New rules:
- Check template parameter files use metadata links. #846
- Configure the `AZURE_PARAMETER_FILE_METADATA_LINK` option to enable this rule.
- Check clusters using Azure CNI should use large subnets. Thanks [@ArmaanMcleod](https://github.com/ArmaanMcleod). #273
- By default, a minimum of a `/23` subnet is required.
- Configure `AZURE_AKS_CNI_MINIMUM_CLUSTER_SUBNET_SIZE` to change the default minimum subnet size.
- Check Storage Accounts only accept explicitly allowed network traffic. #884

Pre-release v1.7.0-B2108040

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs
tests/PSRule.Rules.Azure.Tests/ExpressionBuilderTests.cs
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs

- Fixed DateTimeAdd function and tests within timezones with DST.
Fixes #891

Fixed DateTimeAdd function with DST #891

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/en/PSRule-rules.psd1
src/PSRule.Rules.Azure/rules/Azure.Template.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Template.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.VPN.Parameters2.json

- Fixed `Azure.Template.ParameterValue` failing on empty value. #901
Fixes #901 

Fixed parameter value failing on empty value #901

---

docs/CHANGELOG-v1.md

What's changed since v1.6.0:
- New rules:
- Check template parameter files use metadata links. #846
- Configure the `AZURE_PARAMETER_FILE_METADATA_LINK` option to enable this rule.
- Check template files use a recent schema. #845
- Check template files use a https schema scheme. #894
- Check template parameter files use a https schema scheme. #894
- Check template parameters set a value. #896
- Check template parameters use a valid secret reference. #897
- Check clusters using Azure CNI should use large subnets. Thanks [@ArmaanMcleod](https://github.com/ArmaanMcleod). #273
- Check clusters use auto-scale node pools. Thanks [@ArmaanMcleod](https://github.com/ArmaanMcleod). #218
- By default, a minimum of a `/23` subnet is required.
- Configure …

Release v1.7.0

---

.vscode/settings.json
data/providers.json
docs/en/baselines/Azure.All.md
docs/en/baselines/Azure.Default.md
docs/en/baselines/Azure.Preview.md
docs/en/rules/Azure.AKS.AvailabilityZone.md
docs/en/rules/module.md
docs/en/rules/resource.md
docs/setup/configuring-rules.md
src/PSRule.Rules.Azure/Data/Template/Models.cs
src/PSRule.Rules.Azure/Data/Template/ResourceProviderHelper.cs
src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
src/PSRule.Rules.Azure/Runtime/Helper.cs
src/PSRule.Rules.Azure/en/PSRule-rules.psd1
src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json
tests/PSRule.Rules.Azure.Tests/Resources.AKS.json
tests/PSRule.Rules.Azure.Tests/ps-rule-options.yaml

Fix #880
Added a `Azure.AKS.AvailabilityZone` option for the following types:
- Microsoft.ContainerService/managedClusters
Added the zone mappings from https://docs.microsoft.com/en-us/rest/api/resources/providers/list to `providers.json` with the regions that support availability zones. Rule configures extra zones with the `AZURE_AKS_ADDITIONAL_REGION_AVAILABILITY_ZONE_LIST` configuration option
Also did a bit of refactoring and made a `ResourceProviderHelper` class to share those common methods to read the `providers.json` file. Let me know if you'd like this to be different. I didn't want to copy the methods over to the `Helper` class since it seems like these methods could be reused a lot if interacting with `provders.json` data. 
Also added some tests but can add more to avoid …

AKS Azure AvailabilityZone Rule

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.8.0-B2108026:
- New rules:
- Check clusters have control plane audit logs enabled. Thanks [@ArmaanMcleod](https://github.com/ArmaanMcleod). #882
- Check clusters have control plane diagnostics enabled. Thanks [@ArmaanMcleod](https://github.com/ArmaanMcleod). #922
- Engineering:
- Bump PSRule dependency to v1.7.0. #938

Pre-release v1.8.0-B2109020

---

pipeline.build.ps1
tests/PSRule.Rules.Azure.Tests/Cmdlet.Common.Tests.ps1

Upgraded to latest Pester 5.3.0 version which is stable.
https://github.com/pester/Pester/releases/tag/5.3.0
Had to make some tweaks to module scoping in `Cmdlet.Common.Tests.ps1` but other than that quite a straightforward upgrade. The benefit of upgrading is now CI errors are red in the build log, and has a bunch of handy new features in that release I added 😄 . 

Upgraded to Pester v5.3.0

---

.vscode/settings.json
docs/en/baselines/Azure.All.md
docs/en/baselines/Azure.Default.md
docs/en/baselines/Azure.Preview.md
docs/en/rules/Azure.AppGw.AvailabilityZone.md
docs/en/rules/module.md
docs/en/rules/resource.md
docs/setup/configuring-rules.md
src/PSRule.Rules.Azure/en/PSRule-rules.psd1
src/PSRule.Rules.Azure/rules/Azure.AppGw.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.AppGw.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.AppGw.json
tests/PSRule.Rules.Azure.Tests/ps-rule-options.yaml

Fix #928
Created a `Azure.AppGw.AvailabilityZone` rule for the following types:
- Microsoft.Network/applicationGateways

Added Application Gateway Availability Zone Rule

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.AppService.AlwaysOn.md
docs/en/rules/Azure.AppService.HTTP2.md
docs/en/rules/Azure.AppService.MinPlan.md
docs/en/rules/Azure.AppService.MinTLS.md
docs/en/rules/Azure.AppService.NETVersion.md
docs/en/rules/Azure.AppService.PHPVersion.md
docs/en/rules/Azure.AppService.PlanInstanceCount.md
docs/en/rules/Azure.VM.NICAttached.md
docs/en/rules/module.md
docs/en/rules/resource.md
docs/examples-appservice.bicep
docs/examples-appservice.json
src/PSRule.Rules.Azure/rules/Azure.AppService.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.VM.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.AppService.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.VM.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.AppService.Template.json
tests/PSRule.Rules.Azure.Tests/Resources.VirtualMachine.json

- Fixed plan instance count is not applicable to Elastic Premium plans. #946
- Fixed minimum App Service Plan fails Elastic Premium plans. #945
- Fixed App Service Plan should include PremiumV3 plan. #944
- Fixed Azure.VM.NICAttached with private endpoints. #932
Fixes #946
Fixes #945
Fixes #944
Fixes #932

Fixes app service plan rules #946 #945 #944 #932

---

docs/setup/configuring-rules.md
src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.AppGw.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.AppGw.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Cmdlet.Common.Tests.ps1

Added precondition for `Azure.AppGw.AvailabilityZone` rule to check V2 SKU. 
Also did some tidying up of the code to make it more reusable across AZ rules:
- Refactored null or empty checks and added a `AllowEmptyString` attribute to `GetNormalLocation`.
- Wrap code where AZ is fetched into a separate `GetAvailabilityZone` function. 
- Created `PrependConfigurationZoneWithProviderZone` function to prepend configuration zones to providers.
Also fixing up markdown docs after running `mkdocs` locally. 
Adding more tests.

Added V2 AppGw precondition for AZ rule and refactored code to be more reusable across AZ rules

---

README.md
docs/CHANGELOG-v1.md
docs/en/baselines/Azure.GA_2021_09.md
src/PSRule.Rules.Azure/rules/Baseline.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1

- Added `Azure.GA_2021_09` baseline.
- Includes rules released before or during September 2021 for Azure GA features.
- Marked baseline `Azure.GA_2021_06` as obsolete.
Fixes #961 

Added Azure.GA_2021_09 baseline #961

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.8.0-B2109046:
- Added `Azure.GA_2021_09` baseline. #961
- Includes rules released before or during September 2021 for Azure GA features.
- Marked baseline `Azure.GA_2021_06` as obsolete.
- New rules:
- Load Balancer:
- Check Load Balancers are configured with zone-redundancy. Thanks [@ArmaanMcleod](https://github.com/ArmaanMcleod). #927

Pre-release v1.8.0-B2109060

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Bicep/BicepHelper.cs

- Fixed Bicep CLI fails with unexpected end of content.
- Refactored Bicep CLI code to reduce the chance of locking and no being able to get the full output from Bicep. Fairly sure we have this fixed but since it cannot be reproduced consistently further testing is required. 
Fixes #889

Fixes Bicep unexpected end of content #889

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.Storage.UseReplication.md
src/PSRule.Rules.Azure/rules/Azure.Storage.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Storage.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.Storage.json

- Fixed incomplete reason message for `Azure.Storage.MinTLS`. #971
- Fixed false positive of `Azure.Storage.UseReplication` with large file storage. #965
Fixes #971 
Fixes #965 

Fixes for storage account rules #971 #965

---

docs/hooks.py

- Fix bug in docs where `` is added into examples that include a line comment.

Fix docs tags insertion for examples

---

pipeline.build.ps1
src/PSRule.Rules.Azure/PSRule.Rules.Azure.psd1
src/PSRule.Rules.Azure/PSRule.Rules.Azure.psm1
tests/PSRule.Rules.Azure.Tests/Cmdlet.Common.Tests.ps1

Apologise for not bringing this up in the previous PR, but I pulled out some code that I stashed that uses the Rest API to get the zones instead of the `Get-AzPublicIpAddress` cmdlet. 
Thought it was a good idea to suggest this instead since we can remove the `Az.Network` dependency and have some cmdlets available to fetch resources from API when this issue happens again. This prevents the need to bring in other Az module dependencies. 
Let me know what you think. Perfectly happy to not merge this is the current approach is fine with you 🙂. 
To me it seems better to do this given alot of resources from `Get-AzResource` have missing properties, and means we don't need to introduce new Az modules everytime and just call the API instead. 
Related: …

Use REST API to fetch zones instead of Get-AzPublicIpAddress cmdlet

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/Functions.cs
tests/PSRule.Rules.Azure.Tests/ExpressionBuilderTests.cs
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs

- Fixed `ToUpper` fails to convert character.
Fixes #986

Fixed ToUpper fails to convert character #986

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/rules/Azure.Template.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Template.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.Parameters.json
tests/PSRule.Rules.Azure.Tests/Resources.Policy.Template.json
tests/PSRule.Rules.Azure.Tests/Resources.Template.json

- Fixed handling of comments with template and parameter file rules. #996
- Fixed `Azure.Template.UseLocationParameter` to only apply to templates deployed as RG scope #995
Fixes #996 
Fixes #995 

Fixes issues with template rules #996 #995

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/Functions.cs
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs

Fixed expand template fails with `createObject` when no parameters are specified.
Fixes #1000

Fixes createObject function with no params #1000

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/Functions.cs
src/PSRule.Rules.Azure/rules/Azure.Template.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Template.Tests.ps1
tests/PSRule.Rules.Azure.Tests/ExpressionBuilderTests.cs
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
tests/PSRule.Rules.Azure.Tests/Resources.Parameters.json
tests/PSRule.Rules.Azure.Tests/Resources.Policy.Template.json
tests/PSRule.Rules.Azure.Tests/Resources.Template.json

This merges fixes for v1.8 from v1.9 pre-releases.
- Bug fixes:
- Fixed handling of comments with template and parameter file rules. #996
- Fixed `Azure.Template.UseLocationParameter` to only apply to templates deployed as RG scope #995
- Fixed expand template fails with `createObject` when no parameters are specified. #1000
- Fixed `ToUpper` fails to convert character. #986

Patch v1.8 with #996 #995 #986 #1000

---

docs/CHANGELOG-v1.md
docs/using-templates.md
src/PSRule.Rules.Azure/Data/Template/ExpressionStream.cs
src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
src/PSRule.Rules.Azure/Resources/PSRuleResources.Designer.cs
src/PSRule.Rules.Azure/Resources/PSRuleResources.resx
tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
tests/PSRule.Rules.Azure.Tests/Template.Parsing.7.json
tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs

Merge fixes from v1.9.0-B2110014 pre-release.
- Fixes expression out of range of valid values. #1005
- Fixes template expand fails in nested reference expansion. #1007

Fixes for template bugs #1005 #1007 (#1008)

---

docs/CHANGELOG-v1.md

What's changed since v1.8.0:
- Bug fixes:
- Fixed handling of comments with template and parameter file rules. #996
- Fixed `Azure.Template.UseLocationParameter` to only apply to templates deployed as RG scope #995
- Fixed expand template fails with `createObject` when no parameters are specified. #1000
- Fixed `ToUpper` fails to convert character. #986
- Fixes expression out of range of valid values. #1005
- Fixes template expand fails in nested reference expansion. #1007

Release v1.8.1

---

docs/CHANGELOG-v1.md

What's changed since v1.10.0:
- New rules:
- Application Security Group:
- Check Application Security Groups meet naming requirements. [#1110](https://github.com/Azure/PSRule.Rules.Azure/issues/1110)
- Firewall:
- Check Firewalls meet naming requirements. [#1110](https://github.com/Azure/PSRule.Rules.Azure/issues/1110)
- Check Firewall policies meet naming requirements. [#1110](https://github.com/Azure/PSRule.Rules.Azure/issues/1110)
- Private Endpoint:
- Check Private Endpoints meet naming requirements. [#1110](https://github.com/Azure/PSRule.Rules.Azure/issues/1110)
- Virtual WAN:
- Check Virtual WANs meet naming requirements. [#1110](https://github.com/Azure/PSRule.Rules.Azure/issues/1110)
- Engineering:
- Rule refactoring of rules from PowerShell to YAML. …

Pre-release v1.11.0-B2111014

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/rules/Azure.Policy.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Policy.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.Policy.Parameters.2.json
tests/PSRule.Rules.Azure.Tests/Resources.Policy.Template.2.json

- Fixed `Azure.Policy.WaiverExpiry` date conversion. #1118
Fixes #1118 

Fixes policy exception date conversion #1118

---

.vscode/settings.json
docs/CHANGELOG-v1.md
docs/en/baselines/Azure.All.md
docs/en/baselines/Azure.Default.md
docs/en/baselines/Azure.Preview.md
docs/en/rules/Azure.AKS.HttpAppRouting.md
docs/en/rules/Azure.AKS.SecretStore.md
docs/en/rules/Azure.AKS.SecretStoreRotation.md
docs/en/rules/module.md
docs/en/rules/resource.md
docs/examples-aks.bicep
docs/examples-aks.json
src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json
tests/PSRule.Rules.Azure.Tests/Resources.AKS.json

- New rules:
- Check clusters have the HTTP application routing add-on disabled. #1131
- Check clusters use the Secrets Store CSI Driver add-on. #992
- Check clusters autorotation with the Secrets Store CSI Driver add-on. #993
- Update rules:
- Promoted `Azure.AKS.AutoUpgrade` to GA rule set. #1130
Fixes #992 
Fixes #993 
Fixes #1130 
Fixes #1131 

Added AKS rules #992 #993 #1130 #1131

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/Functions.cs
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
tests/PSRule.Rules.Azure.Tests/Template.Parsing.11.json
tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs

- Fixed template function `equals` parameter count mismatch.
Fixes #1137

Fixes equals parameter count mismatch #1137

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/Functions.cs
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
tests/PSRule.Rules.Azure.Tests/Template.Parsing.11.json
tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs

- Bug fixes:
- Fixed template function `equals` parameter count mismatch. #1137

Merge from v1.10.2 release

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.yaml

- Rule refactoring of AKS rules from PowerShell to YAML. #1109
- The following rules where refactored:
- `Azure.AKS.MinNodeCount`
- `Azure.AKS.ManagedIdentity`
- `Azure.AKS.StandardLB`
- `Azure.AKS.AzurePolicyAddOn`
- `Azure.AKS.ManagedAAD`
- `Azure.AKS.AuthorizedIPs`
- `Azure.AKS.LocalAccounts`
- `Azure.AKS.AzureRBAC`

Refactored AKS powershell rules to YAML #1109

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.11.0-B2112073:
- New rules:
- Check clusters use Azure AD Pod Managed Identities (preview). #991
- Engineering:
- Rule refactoring of rules from PowerShell to YAML. #1109
- The following rules were refactored:
- `Azure.AppConfig.SKU`
- `Azure.AppConfig.Name`
- `Azure.AppInsights.Workspace`
- `Azure.AppInsights.Name`
- `Azure.Cosmos.AccountName`
- `Azure.FrontDoor.State`
- `Azure.FrontDoor.Name`
- `Azure.FrontDoor.WAF.Mode`
- `Azure.FrontDoor.WAF.Enabled`
- `Azure.FrontDoor.WAF.Name`
- `Azure.AKS.MinNodeCount`
- `Azure.AKS.ManagedIdentity`
- `Azure.AKS.StandardLB`
- `Azure.AKS.AzurePolicyAddOn`
- `Azure.AKS.ManagedAAD`
- `Azure.AKS.AuthorizedIPs`
- `Azure.AKS.LocalAccounts`
- `Azure.AKS.AzureRBAC`
- Bug fixes:
- Fixed output …

Pre-release v1.11.0-B2112104

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.11.0-B2112104:
- New rules:
- Azure Redis Cache:
- Use availability zones for Azure Cache for Redis for regions that support it. #1078
- `Azure.Redis.AvailabilityZone`
- `Azure.RedisEnterprise.Zones`

Pre-release v1.11.0-B2112112

---

src/PSRule.Rules.Azure/rules/Azure.LB.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.PublicIP.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Automation.Tests.ps1

Just a small change to replace `Compare-Object` with assertions from LB and Public IP AZ rules.
Let me know if this looks ok to you.

Replace Compare-Object with SetOf assertion for LB and Public IP AZ rules

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1

Fix #1178 
Small fix. Added `Azure.AKS.Azure.CNI` selector to `Azure.AKS.CNISubnetSize` rule. Makes sense to make sure this rule just checks CNI clusters. 

Ensure Azure.AKS.CNISubnetSize rule uses AzureCNI selector

---

docs/CHANGELOG-v1.md

What's changed since v1.11.0:
- Bug fixes:
- Fixed `Azure.AKS.CNISubnetSize` rule to use CNI selector. #1178

Release v1.11.1

---

docs/CHANGELOG-v1.md
docs/deprecations.md
docs/en/rules/Azure.AKS.Version.md
docs/en/rules/module.md
docs/examples-aks.bicep
docs/examples-aks.json
docs/setup/configuring-options.md
docs/setup/configuring-rules.md
docs/upgrade-notes.md
mkdocs.yml
src/PSRule.Rules.Azure/en/PSRule-rules.psd1
src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
src/PSRule.Rules.Azure/rules/Baseline.Rule.yaml
src/PSRule.Rules.Azure/rules/Config.Rule.yaml
src/PSRule.Rules.Azure/rules/Conventions.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json
tests/PSRule.Rules.Azure.Tests/Resources.AKS.json
tests/PSRule.Rules.Azure.Tests/ps-rule-options.yaml
tests/PSRule.Rules.Azure.Tests/ps-rule-options2.yaml

- Updated `Azure.AKS.Version` to use latest stable version `1.21.7`. #1188
- Pinned latest GA baseline `Azure.GA_2021_12` to previous version `1.20.5`.
- **Important change:** Replaced `Azure_AKSMinimumVersion` option with `AZURE_AKS_CLUSTER_MINIMUM_VERSION`. #941
- For compatiblity, if `Azure_AKSMinimumVersion` is set it will be used instead of `AZURE_AKS_CLUSTER_MINIMUM_VERSION`.
- If only `AZURE_AKS_CLUSTER_MINIMUM_VERSION` is set, this value will be used.
- The default will be used neither options are configured.
- If `Azure_AKSMinimumVersion` is set a warning will be generated until the configuration is removed.
- Support for `Azure_AKSMinimumVersion` is deprecated and will be removed in v2. …

Updated AKS version to latest #1188 #941

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.APIM.Ciphers.md
src/PSRule.Rules.Azure/rules/Azure.APIM.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.APIM.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.APIM.json

Adding to the APIM rules a new rule to check if deprecated ciphers are in use. This is related to issue [1128](https://github.com/Azure/PSRule.Rules.Azure/issues/1128). 
I have broken out the existing APIM Cipher And Protocol rule into different rules. 

Adding rule to disable insecure APIM ciphers support

---

docs/CHANGELOG-v1.md
docs/en/baselines/Azure.All.md
docs/en/baselines/Azure.Default.md
docs/en/baselines/Azure.GA_2021_12.md
docs/en/baselines/Azure.Preview.md
docs/en/rules/module.md
docs/en/rules/resource.md

What's changed since v1.11.1:
- Updated `Azure.AKS.Version` to use latest stable version `1.21.7`. #1188
- Pinned latest GA baseline `Azure.GA_2021_12` to previous version `1.20.5`.
- Azure API Management:
- Check service disabled insecure ciphers.
#1128
- Refactored the cipher and protocol rule into individual rules.
- `Azure.APIM.Protocols`
- `Azure.APIM.Ciphers`
- **Important change:** Replaced `Azure_AKSMinimumVersion` option with `AZURE_AKS_CLUSTER_MINIMUM_VERSION`. #941
- For compatibility, if `Azure_AKSMinimumVersion` is set it will be used instead of `AZURE_AKS_CLUSTER_MINIMUM_VERSION`.
- If only …

Pre-release v1.12.0-B2201054

---

.github/ISSUE_TEMPLATE/bug-report.md
docs/CHANGELOG-v1.md

What's changed since v1.11.1:
- New rules:
- Data Explorer:
- Check clusters use Managed Identities. #1207
- Check clusters use a SKU with a SLA. #1208
- Check clusters use disk encryption. #1209
- Check clusters are in use with databases. #1215
- Event Hub:
- Check namespaces are in use with event hubs. #1216
- Check namespaces only accept identity-based authentication. #1217
- Azure Recovery Services Vault:
- Check vaults use geo-redundant storage. #5
- Service Bus:
- Check namespaces are in use with queues and topics. #1218
- Check namespaces only accept identity-based authentication. #1219
- Updated `Azure.AKS.Version` to use latest stable version `1.21.7`. #1188
- Pinned latest GA baseline `Azure.GA_2021_12` to previous version `1.20.5`.
- …

Release v1.12.0

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Common/ResourceHelper.cs
src/PSRule.Rules.Azure/Data/Template/Functions.cs
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs

- Fixed resource id is incorrectly built for sub resource types. #1279
Fixes #1279 

Fixes sub resource id is incorrectly built #1279

---

.github/ISSUE_TEMPLATE/bug-report.md
docs/CHANGELOG-v1.md

What's changed since v1.12.2:
- Added support for setting defaults for required parameters. #1065
- When specified, the value will be used when a parameter value is not provided.
- Added support expanding Bicep from parameter files. #1160
- New rules:
- Limit public access for Azure Cache for Redis instances. #935
- Check insecure ingress is not enabled (preview). #1252
- Key Vault:
- Check key auto-rotation is enabled (preview). #1159
- Recovery Services Vault:
- Check vaults have replication alerts configured. #7
- Engineering:
- Automatically build baseline docs. #1242
- Bump PSRule dependency to v1.11.1. #1269
- Bug fixes:
- Fixed empty value with strong type. #1258
- Fixed error with empty logic app trigger. #1249
- Fixed out …

Release v1.13.0

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.ACR.ContentTrust.md
docs/en/rules/Azure.ACR.Retention.md
src/PSRule.Rules.Azure/rules/Azure.ACR.Rule.yaml
src/PSRule.Rules.Azure/rules/Azure.VNET.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.ACR.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.VNET.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.ACR.json
tests/PSRule.Rules.Azure.Tests/Resources.VirtualNetwork.json

- Fixed virtual network without any subnets is invalid. #1303
- Fixed container registry rules that require a premium tier. #1304
- Rules `Azure.ACR.Retention` and `Azure.ACR.ContentTrust` are now only run against premium instances.
Fixes #1303 
Fixes #1304 

Fixes VNET and ACR bugs #1303 #1304

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.ACR.ContentTrust.md
docs/en/rules/Azure.ACR.Retention.md
src/PSRule.Rules.Azure/rules/Azure.ACR.Rule.yaml
src/PSRule.Rules.Azure/rules/Azure.VNET.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.ACR.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.VNET.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.ACR.json
tests/PSRule.Rules.Azure.Tests/Resources.VirtualNetwork.json

Merged from main:
- Bug fixes:
- Fixed virtual network without any subnets is invalid. #1303
- Fixed container registry rules that require a premium tier. #1304
- Rules `Azure.ACR.Retention` and `Azure.ACR.ContentTrust` are now only run against premium instances.

Fixes VNET and ACR bugs #1303 #1304 #1305 into v1.13.x

---

docs/CHANGELOG-v1.md
docs/commands/Export-AzRuleTemplateData.md
docs/expanding-source-files.md
src/PSRule.Rules.Azure/Common/JsonExtensions.cs
src/PSRule.Rules.Azure/Common/LazyValue.cs
src/PSRule.Rules.Azure/Common/ResourceDependencyComparer.cs
src/PSRule.Rules.Azure/Common/ResourceHelper.cs
src/PSRule.Rules.Azure/Data/Template/ExpressionBuilder.cs
src/PSRule.Rules.Azure/Data/Template/Functions.cs
src/PSRule.Rules.Azure/Data/Template/Models.cs
src/PSRule.Rules.Azure/Data/Template/ResourceValue.cs
src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Cmdlet.Common.Tests.ps1
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
tests/PSRule.Rules.Azure.Tests/ResourceDependencyComparerTests.cs
tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json
tests/PSRule.Rules.Azure.Tests/Resources.Template.json
tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.1.bicep
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.2.bicep
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.2.json

- Added support for referencing resources in template. #1315
- The `reference()` function can be used to reference resources in template.
- A placeholder value is still used for resources outside of the template.
- Fixed processing of deployment outputs. #1316
Fixes #1315 
Fixes #1316 

Fixes processing deployment outputs #1316 #1315

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/ExpressionBuilder.cs
src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs
src/PSRule.Rules.Azure/Data/Template/Functions.cs
src/PSRule.Rules.Azure/Data/Template/Mocks.cs
src/PSRule.Rules.Azure/Data/Template/Models.cs
src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.1.bicep
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.2.bicep
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.2.json

- Fixed expand of runtime properties on reference objects.
Fixes #1324

Fixes expand of runtime properties #1324

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.14.0-B2203066:
- Added March 2022 baselines `Azure.GA_2022_03` and `Azure.Preview_2022_03`. #1334
- Includes rules released before or during March 2022.
- Marked `Azure.GA_2021_12` and `Azure.Preview_2021_12` baselines as obsolete.
- Bug fixes:
- Fixed expand of runtime properties on reference objects. #1324

Pre-release v1.14.0-B2203088

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.14.0-B2203088:
- **Experimental**: Cmdlets to validate objects with Azure policy conditions:
- `Export-AzPolicyAssignmentData` - Exports policy assignment data. #1266
- `Export-AzPolicyAssignmentRuleData` - Exports JSON rules from policy assignment data. #1278
- `Get-AzPolicyAssignmentDataSource` - Discovers policy assignment data. #1340
- See cmdlet help for limitations and usage.
- Engineering:
- Cache Azure Policy Aliases. #1277
- Bug fixes:
- Fixed index was out of range with split on mock properties. #1327

Pre-release v1.14.0-B2203117

---

docs/CHANGELOG-v1.md

What's changed since v1.13.4:
- Added support for referencing resources in template. #1315
- The `reference()` function can be used to reference resources in template.
- A placeholder value is still used for resources outside of the template.
- Added March 2022 baselines `Azure.GA_2022_03` and `Azure.Preview_2022_03`. #1334
- Includes rules released before or during March 2022.
- Marked `Azure.GA_2021_12` and `Azure.Preview_2021_12` baselines as obsolete.
- **Experimental**: Cmdlets to validate objects with Azure policy conditions:
- `Export-AzPolicyAssignmentData` - Exports policy assignment data. #1266
- `Export-AzPolicyAssignmentRuleData` - Exports JSON rules from policy assignment data. #1278
- `Get-AzPolicyAssignmentDataSource` - Discovers policy assignment data. …

Release v1.14.0

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Common/DictionaryExtensions.cs
src/PSRule.Rules.Azure/Configuration/ParameterDefaultsOption.cs
src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
tests/PSRule.Rules.Azure.Tests/Template.Parsing.10.Parameters.json
tests/PSRule.Rules.Azure.Tests/Template.Parsing.10.json
tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
tests/PSRule.Rules.Azure.Tests/ps-rule-options.yaml

- Fixed unable to set parameter defaults option with type object.
Fixes #1355 

Fixes object parameter defaults #1355

---

docs/CHANGELOG-v1.md

What's changed since v1.14.3:
- **Important change**: Added `Azure.Resource.SupportsTags` selector by @BernieWhite.
[#1339](https://github.com/Azure/PSRule.Rules.Azure/issues/1339)
- Use this selector in custom rules to filter rules to only run against resources that support tags.
- This selector replaces the `SupportsTags` PowerShell function.
- Using the `SupportsTag` function will now result in a warning.
- The `SupportsTags` function will be removed in v2.
- See [upgrade notes][1] for more information.
- Updated `Azure.AKS.Version` to use latest stable version `1.22.6` by @BernieWhite.
[#1386](https://github.com/Azure/PSRule.Rules.Azure/issues/1386)
- Use `AZURE_AKS_CLUSTER_MINIMUM_VERSION` to configure the minimum version …

Release v1.15.0

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs
src/PSRule.Rules.Azure/Data/Template/Functions.cs
src/PSRule.Rules.Azure/Data/Template/Mocks.cs
src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs

- Fixed could not determine JSON object type for MockObject using CreateObject.
Fixes #1411

Fixed MockObject with CreateObject fn #1411

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/rules/Azure.ADX.Rule.yaml
src/PSRule.Rules.Azure/rules/Azure.APIM.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.APIM.Rule.yaml
src/PSRule.Rules.Azure/rules/Azure.AppService.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.AppService.Rule.yaml
src/PSRule.Rules.Azure/rules/Azure.EventGrid.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.AppService.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.EventGrid.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.AppService.Template.json
tests/PSRule.Rules.Azure.Tests/Resources.EventGrid.Template.json

- Fixed `Azure.AppService.ManagedIdentity` does not accept both system and user assigned by @BernieWhite. #1415
- This also applies to:
- `Azure.ADX.ManagedIdentity`
- `Azure.APIM.ManagedIdentity`
- `Azure.EventGrid.ManagedIdentity`
- `Azure.Automation.ManagedIdentity`
- Fixed Web apps with .NET 6 do not meet version constraint of `Azure.AppService.NETVersion` by @BernieWhite. #1414
- This also applies to `Azure.AppService.PHPVersion`.
Fixes #1415 
Fixes #1414 

Fixes for app service and managed id #1414 #1415

---

docs/CHANGELOG-v1.md

What's changed since v1.15.1:
- Bug fixes:
- Fixed `Azure.AppService.ManagedIdentity` does not accept both system and user assigned by @BernieWhite.
#1415
- This also applies to:
- `Azure.ADX.ManagedIdentity`
- `Azure.APIM.ManagedIdentity`
- `Azure.EventGrid.ManagedIdentity`
- `Azure.Automation.ManagedIdentity`
- Fixed Web apps with .NET 6 do not meet version constraint of `Azure.AppService.NETVersion` by @BernieWhite.
#1414
- This also applies to `Azure.AppService.PHPVersion`.

Release v1.15.2

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.PublicIP.AvailabilityZone.md
src/PSRule.Rules.Azure/rules/Azure.PublicIP.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.PublicIP.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.PublicIP.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.PublicIP.json

- Updated `Azure.PublicIP.AvailabilityZone` to exclude IP addresses for Azure Bastion.
Fixes #1442 

Exclude Bastion public IP from AZ #1442

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.16.0-B0017:
- Public IP:
- Updated `Azure.PublicIP.AvailabilityZone` to exclude IP addresses for Azure Bastion by @BernieWhite.
[#1442](https://github.com/Azure/PSRule.Rules.Azure/issues/1442)
- Public IP addresses with the `resource-usage` tag set to `azure-bastion` are excluded.
- Added support for `dateTimeFromEpoch` and `dateTimeToEpoch` ARM functions by @BernieWhite.
[#1451](https://github.com/Azure/PSRule.Rules.Azure/issues/1451)
- Engineering:
- Updated built documentation to include rule ref and metadata by @BernieWhite.
[#1432](https://github.com/Azure/PSRule.Rules.Azure/issues/1432)
- Added ref properties for several rules by @BernieWhite.
[#1430](https://github.com/Azure/PSRule.Rules.Azure/issues/1430) …

Pre-release v1.16.0-B0041

---

.github/ISSUE_TEMPLATE/bug-report.md
docs/CHANGELOG-v1.md

What's changed since v1.15.2:
- New rules:
- App Service:
- Check web apps have insecure FTP disabled by @BernieWhite.
[#1436](https://github.com/Azure/PSRule.Rules.Azure/issues/1436)
- Check web apps use a dedicated health probe by @BernieWhite.
[#1437](https://github.com/Azure/PSRule.Rules.Azure/issues/1437)
- Public IP:
- Updated `Azure.PublicIP.AvailabilityZone` to exclude IP addresses for Azure Bastion by @BernieWhite.
[#1442](https://github.com/Azure/PSRule.Rules.Azure/issues/1442)
- Public IP addresses with the `resource-usage` tag set to `azure-bastion` are excluded.
- Added support for `dateTimeFromEpoch` and `dateTimeToEpoch` ARM functions by @BernieWhite.
[#1451](https://github.com/Azure/PSRule.Rules.Azure/issues/1451)
- Engineering:
- …

Release v1.16.0

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.AppGw.AvailabilityZone.md
docs/examples-appgw.bicep
docs/examples-appgw.json
src/PSRule.Rules.Azure/rules/Azure.AppGw.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.AppGw.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.AppGw.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.AppGw.json

- Fixed TLS 1.3 support in `Azure.AppGw.SSLPolicy`.
- Fixed Application Gateway referencing a WAF policy.
Fixes #1466
Fixes #1469

Fixes app gateway TLS and WAF policy #1469 #1466

---

src/PSRule.Rules.Azure/PSRule.Rules.Azure-nodeps.psd1
src/PSRule.Rules.Azure/PSRule.Rules.Azure.csproj
src/PSRule.Rules.Azure/PSRule.Rules.Azure.psd1

- Update assembly naming for NuGet packaging towards #1428

Update assembly naming for packaging #1428

---

README.md
docs/CHANGELOG-v1.md
docs/en/baselines/Azure.GA_2022_06.md
docs/en/baselines/Azure.Preview_2022_06.md
docs/working-with-baselines.md
src/PSRule.Rules.Azure/rules/Baseline.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1

- Added June 2022 baselines `Azure.GA_2022_06` and `Azure.Preview_2022_06`.
- Marked `Azure.GA_2022_03` and `Azure.Preview_2022_03` baselines as obsolete.
Fixes #1499

Added June 2022 baselines #1499

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.17.0-B0014:
- Added June 2022 baselines `Azure.GA_2022_06` and `Azure.Preview_2022_06` by @BernieWhite.
[#1499](https://github.com/Azure/PSRule.Rules.Azure/issues/1499)
- Includes rules released before or during June 2022.
- Marked `Azure.GA_2022_03` and `Azure.Preview_2022_03` baselines as obsolete.
- Engineering:
- Bump Newtonsoft.Json to v13.0.1.
[#1494](https://github.com/Azure/PSRule.Rules.Azure/pull/1494)
- Updated NuGet packaging metadata by @BernieWhite.
[#1428](https://github.com/Azure/PSRule.Rules.Azure/pull/1428)

Pre-release v1.17.0-B0035

---

src/PSRule.Rules.Azure/rules/Azure.SQL.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Resources.SQL.json

Fixed transparentDataEncryption property status to state

---

src/SDK/SDK.csproj

- Fix double slashes in NuGet package build.

Fix double slash in NuGet

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs
src/PSRule.Rules.Azure/Data/Template/Functions.cs
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs

- Fixed union returns null when merged with built-in expansion objects.
Fixes #1515 

Fixes union with expansion object #1515

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs
src/PSRule.Rules.Azure/Data/Template/Functions.cs
tests/PSRule.Rules.Azure.Tests/ExpressionHelpersTests.cs
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs

- Added support for array `indexOf`, `lastIndexOf`, and `items` ARM functions.
Fixes #1440 

Added support for new array ARM functions #1440

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/RuleDataExportVisitor.cs
src/PSRule.Rules.Azure/rules/Azure.SQL.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.SQL.Tests.ps1
tests/PSRule.Rules.Azure.Tests/cognitive.tests.bicep
tests/PSRule.Rules.Azure.Tests/sql.tests.bicep
tests/PSRule.Rules.Azure.Tests/sql.tests.json

- Fixed `Azure.SQL.TDE` is not required to enable Transparent Data Encryption for IaC.
Fixes #1530 

Fixed Azure.SQL.TDE for IaC #1530

---

docs/CHANGELOG-v1.md

What's changed since v1.18.1:
- Updated rule level for the following rules by @BernieWhite:
[#1551](https://github.com/Azure/PSRule.Rules.Azure/issues/1551)
- Set `Azure.APIM.APIDescriptors` to warning from error.
- Set `Azure.APIM.ProductDescriptors` to warning from error.
- Set `Azure.Template.UseLocationParameter` to warning from error.
- Set `Azure.Template.UseComments` to information from error.
- Set `Azure.Template.UseDescriptions` to information from error.
- Engineering:
- Added publishing of symbols for NuGet packages by @BernieWhite.
[#1549](https://github.com/Azure/PSRule.Rules.Azure/issues/1549)
- Bump PSRule to v2.3.1.
[#1561](https://github.com/Azure/PSRule.Rules.Azure/pull/1561)
- Bump Az.Resources to v6.1.0. …

Pre-release v1.19.0-B0010

---

.editorconfig
.vscode/settings.json
.vscode/yaml.code-snippets
docs/CHANGELOG-v1.md
docs/install-instructions.md
pipeline.build.ps1
src/PSRule.Rules.Azure.Benchmark/PSRule.Rules.Azure.Benchmark.csproj
src/PSRule.Rules.Azure.BuildTool/PSRule.Rules.Azure.BuildTool.csproj
src/PSRule.Rules.Azure/.editorconfig
src/PSRule.Rules.Azure/Configuration/ConfigurationOption.cs
src/PSRule.Rules.Azure/Configuration/DeploymentOption.cs
src/PSRule.Rules.Azure/Configuration/ManagementGroupOption.cs
src/PSRule.Rules.Azure/Configuration/OutputEncoding.cs
src/PSRule.Rules.Azure/Configuration/OutputOption.cs
src/PSRule.Rules.Azure/Configuration/ParameterDefaultsOption.cs
src/PSRule.Rules.Azure/Configuration/ResourceGroupOption.cs
src/PSRule.Rules.Azure/Configuration/SubscriptionOption.cs
src/PSRule.Rules.Azure/Configuration/TenantOption.cs
src/PSRule.Rules.Azure/Pipeline/PipelineBuilder.cs
src/PSRule.Rules.Azure/Pipeline/PolicyAssignmentPipeline.cs
src/PSRule.Rules.Azure/Pipeline/PolicyAssignmentPipelineBuilder.cs
src/PSRule.Rules.Azure/Pipeline/PolicyAssignmentSearchPipeline.cs
src/PSRule.Rules.Azure/Pipeline/PolicyAssignmentSearchPipelineBuilder.cs
src/PSRule.Rules.Azure/Pipeline/TemplateLinkPipeline.cs
src/PSRule.Rules.Azure/Pipeline/TemplatePipeline.cs
src/SDK/SDK.csproj
tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj

- Bump support projects to .NET 6.
- Additional linting settings added for c#.
- Additional comment documentation added to classes.
Fixes #1560

Bump support projects to .NET 6 #1560

---

.vscode/settings.json
docs/CHANGELOG-v1.md
docs/expanding-source-files.md
docs/troubleshooting.md
docs/using-bicep.md
docs/using-templates.md
src/PSRule.Rules.Azure/Data/Template/TemplateLinkHelper.cs
tests/PSRule.Rules.Azure.Tests/Azure.Template.Tests.ps1
tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
tests/PSRule.Rules.Azure.Tests/PathBuilderTests.cs
tests/PSRule.Rules.Azure.Tests/TemplateLinkTests.cs
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.1.metalink.json
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.1.parameters.json
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.2.parameters.json

Fixes parameter files linked to bicep code via naming convention is not working.
Fixes #1582

Fixed parameter file name link with bicep #1582

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.19.0-B0077:
- New rules:
- Check clusters use uptime SLA by @bengeset96.
[#1601](https://github.com/Azure/PSRule.Rules.Azure/issues/1601)

Pre-release v1.19.0-B0077

---

docs/CHANGELOG-v1.md

What's changed since v1.18.1:
- New rules:
- Check clusters use uptime SLA by @bengeset96.
[#1601](https://github.com/Azure/PSRule.Rules.Azure/issues/1601)
- Updated rule level for the following rules by @BernieWhite.
[#1551](https://github.com/Azure/PSRule.Rules.Azure/issues/1551)
- Set `Azure.APIM.APIDescriptors` to warning from error.
- Set `Azure.APIM.ProductDescriptors` to warning from error.
- Set `Azure.Template.UseLocationParameter` to warning from error.
- Set `Azure.Template.UseComments` to information from error.
- Set `Azure.Template.UseDescriptions` to information from error.
- Improve reporting of failing resource property for rules by @BernieWhite.
[#1429](https://github.com/Azure/PSRule.Rules.Azure/issues/1429)
- …

Release v1.19.0

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs
src/PSRule.Rules.Azure/Data/Template/Functions.cs
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs

- Fixed function `dateTimeAdd` errors handling `utcNow` output.
Fixes #1637 

Fixes dateTimeAdd function #1637

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs
src/PSRule.Rules.Azure/Data/Template/Functions.cs
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs

Apply fix from main on to v1.19.x for patch release.
- Fixed function `dateTimeAdd` errors handling `utcNow` output.
#1637

Fixes dateTimeAdd function #1637 (#1641)

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.20.0-B0004:
- New rules:
- AKS:
- Check clusters use Ephemeral OS disk by @bengeset96.
[#1618](https://github.com/Azure/PSRule.Rules.Azure/issues/1618)
- CDN:
- Check CDN profile uses Front Door Standard or Premium tier by @bengeset96.
[#1612](https://github.com/Azure/PSRule.Rules.Azure/issues/1612)
- VMSS:
- Check Linux VMSS has disabled password authentication by @bengeset96.
[#1635](https://github.com/Azure/PSRule.Rules.Azure/issues/1635)
- Updated `Azure.AKS.Version` to use latest stable version `1.23.8` by @BernieWhite.
[#1627](https://github.com/Azure/PSRule.Rules.Azure/issues/1627)
- Event Grid:
- Promoted …

Pre-release v1.20.0-B0028

---

.github/workflows/stale.yaml
docs/CHANGELOG-v1.md
docs/en/rules/Azure.Redis.FirewallIPRange.md
docs/en/rules/Azure.Redis.FirewallRuleCount.md
src/PSRule.Rules.Azure/rules/Azure.Redis.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Redis.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.Redis.json

- Created Azure.Redis.FirewallRuleCount (AZR-000293) in Azure.Redis.Rule.ps1
- Created Azure.Redis.FirewallIPRule (AZR-000294) in Azure.Redis.Rule.ps1
- Created Azure.Redis.FirewallRuleCount documentation
- Created Azure.Redis.FirewallIpRule documentation.
- Created tests for both rules in Azure.Redis.Tests.ps1. 
- Updated redis-A, B, C, D, and E in Resources.Redis.json

Limit connectivity to Redis instances with firewall rules #544

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/Functions.cs
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs

- Fixed error expanding with `json()` and single quotes.
Fixes #1656

Fixes error expanding json single quotes #1656

---

.vscode/launch.json
docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Common/JsonConverters.cs
src/PSRule.Rules.Azure/Configuration/DeploymentOption.cs
src/PSRule.Rules.Azure/Data/Policy/Models.cs
src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitor.cs
src/PSRule.Rules.Azure/Data/Template/ExpressionBuilder.cs
src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs
src/PSRule.Rules.Azure/Data/Template/Functions.cs
src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
src/PSRule.Rules.Azure/Pipeline/TemplatePipeline.cs
tests/PSRule.Rules.Azure.Tests/Cmdlet.Common.Tests.ps1
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
tests/PSRule.Rules.Azure.Tests/emittedJsonRulesData.jsonc
tests/PSRule.Rules.Azure.Tests/test11.assignment.json

Related to #1653.
Fixes key collisions with definitions using same parameters.
Also refactored a bit of csharp code.

Handle key collision with duplicate definitions using same parameters

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/rules/Azure.Deployment.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Deployment.Tests.ps1
tests/PSRule.Rules.Azure.Tests/deployment-1.tests.bicep
tests/PSRule.Rules.Azure.Tests/deployment.tests.bicep
tests/PSRule.Rules.Azure.Tests/deployment.tests.json

- Fixed `Azure.Deployment.AdminUsername` incorrectly fails with nested deployments.
Fixes #1762 

Fixes adminUsername with nested deployments #1762

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.AppConfig.PurgeProtect.md
src/PSRule.Rules.Azure/en/PSRule-rules.psd1
src/PSRule.Rules.Azure/rules/Azure.AppConfig.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.AppConfig.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.AppConfig.json

Fixes #1689 
Added Azure.AppConfig.PurgeProtect rule for ensuring that app configuration stores with supporting SKU has it enabled.

Added Azure.AppConfig.PurgeProtect

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.20.0-B0389:
- Added hash to `name` and `ref` properties for policy rules by @ArmaanMcleod.
[#1653](https://github.com/Azure/PSRule.Rules.Azure/issues/1653)
- Use `AZURE_POLICY_RULE_PREFIX` or `Export-AzPolicyAssignmentRuleData -RulePrefix` to override rule prefix.

Pre-release v1.20.0-B0477

---

data/policy-ignore.json
docs/CHANGELOG-v1.md
docs/concepts/about_PSRule_Azure_Configuration.md
src/PSRule.Rules.Azure.BuildTool/ProviderResource.cs
src/PSRule.Rules.Azure/Configuration/ConfigurationOption.cs
src/PSRule.Rules.Azure/Data/CloudEnvironment.cs
src/PSRule.Rules.Azure/Data/EnvironmentData.cs
src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitor.cs
src/PSRule.Rules.Azure/Data/PolicyIgnoreData.cs
src/PSRule.Rules.Azure/Data/ProviderData.cs
src/PSRule.Rules.Azure/Data/TypeIndex.cs
src/PSRule.Rules.Azure/Pipeline/PipelineBuilder.cs
src/PSRule.Rules.Azure/Pipeline/TemplateLinkPipelineBuilder.cs
src/PSRule.Rules.Azure/Pipeline/TemplatePipelineBuilder.cs
src/PSRule.Rules.Azure/Resources/PSRuleResources.Designer.cs
src/PSRule.Rules.Azure/Resources/PSRuleResources.resx
tests/PSRule.Rules.Azure.Tests/PolicyAssignmentVisitorTests.cs

- Added built-in list of ignored policy definitions.
- To ignore additional policy definitions, use the `AZURE_POLICY_IGNORE_LIST` configuration option.
Fixes #1730 

Added policy definition ignore list #1730

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.20.1:
- Mapping of Azure Security Benchmark v3 to security rules by @jagoodwin.
[#1610](https://github.com/Azure/PSRule.Rules.Azure/issues/1610)
- New rules:
- Check VNETs with a GatewaySubnet also has a AzureBastionSubnet by @bengeset96.
[#1761](https://github.com/Azure/PSRule.Rules.Azure/issues/1761)
- Added built-in list of ignored policy definitions by @BernieWhite.
[#1730](https://github.com/Azure/PSRule.Rules.Azure/issues/1730)
- To ignore additional policy definitions, use the `AZURE_POLICY_IGNORE_LIST` configuration option.
- Engineering:
- Bump PSRule to v2.5.1.
[#1782](https://github.com/Azure/PSRule.Rules.Azure/pull/1782)
- Bump Az.Resources to v6.3.0. …

Pre-release v1.21.0-B0011

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.ServiceBus.MinTLS.md
docs/examples-servicebus.bicep
docs/examples-servicebus.json
docs/license-contributing/hackathons.md
src/PSRule.Rules.Azure/en/PSRule-rules.psd1
src/PSRule.Rules.Azure/rules/Azure.ServiceBus.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.ServiceBus.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.ServiceBus.json

Fixes #1777 
Added Azure.ServiceBus.MinTLS rule.
This rule checks for that service bus namespaces uses minimum TLS 1.2 version.

Added Azure.ServiceBus.MinTLS

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Common/JsonExtensions.cs
src/PSRule.Rules.Azure/Data/Template/Functions.cs
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs

-  Fixed contains function unable to match array.
Fixes #1793 

Fixes contains function with array #1793

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Common/JsonExtensions.cs
src/PSRule.Rules.Azure/Data/Template/Functions.cs
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs

Merge updates from v1.20.2:
- Bug fixes:
- Fixed contains function unable to match array by @BernieWhite.
[#1793](https://github.com/Azure/PSRule.Rules.Azure/issues/1793)
Fixes #1793

Merge patch v1.20.2

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.VM.MigrateAMA.md
docs/en/rules/Azure.VMSS.MigrateAMA.md
src/PSRule.Rules.Azure/en/PSRule-rules.psd1
src/PSRule.Rules.Azure/rules/Azure.Common.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.VM.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.VMSS.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.VM.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.VMSS.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.VMSS.json
tests/PSRule.Rules.Azure.Tests/Resources.VirtualMachine.json

Fixes  #1792
Added Azure.VM.MigrateAMA and Azure.VMSS.MigrateAMA rules.
Rules used to ensure that virtual machines and virtual machine scale sets using the new modern `Azure Monitor Agent` instead of the old legacy agent `Log Analytics Agent`. 

Added Azure.VM.MigrateAMA and Azure.VMSS.MigrateAMA

---

README.md
docs/CHANGELOG-v1.md
docs/features.md
overrides/home.html

What's changed since pre-release v1.21.0-B0027:
- New rules:
- Check virtual machines uses Azure Monitor Agent instead of old legacy Log Analytics Agent by @bengeset96.
[#1792](https://github.com/Azure/PSRule.Rules.Azure/issues/1792)
- Check virtual machine scale sets uses Azure Monitor Agent instead of old legacy Log Analytics Agent by @bengeset96.
[#1792](https://github.com/Azure/PSRule.Rules.Azure/issues/1792)
- Engineering:
- Bump PSRule to v2.5.3.
[#1800](https://github.com/Azure/PSRule.Rules.Azure/pull/1800)
- Bump Az.Resources to v6.3.1.
[#1800](https://github.com/Azure/PSRule.Rules.Azure/pull/1800)
- Bug fixes:
- Fixed contains function unable to match array by @BernieWhite. …

Pre-release v1.21.0-B0050

---

docs/CHANGELOG-v1.md

What's changed since v1.20.2:
- Mapping of Azure Security Benchmark v3 to security rules by @jagoodwin.
[#1610](https://github.com/Azure/PSRule.Rules.Azure/issues/1610)
- New rules:
- Deployment:
- Check sensitive resource values use secure parameters by @VeraBE @BernieWhite.
[#1773](https://github.com/Azure/PSRule.Rules.Azure/issues/1773)
- Service Bus:
- Check service bus namespaces uses TLS 1.2 version by @bengeset96.
[#1777](https://github.com/Azure/PSRule.Rules.Azure/issues/1777)
- Check virtual machines uses Azure Monitor Agent instead of old legacy Log Analytics Agent by @bengeset96.
[#1792](https://github.com/Azure/PSRule.Rules.Azure/issues/1792)
- Check virtual machine scale sets uses Azure Monitor Agent instead of …

Release v1.21.0

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.ASE.MigrateV3.md
docs/examples-ase.bicep
docs/examples-ase.json
src/PSRule.Rules.Azure/en/PSRule-rules.psd1
src/PSRule.Rules.Azure/rules/Azure.ASE.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.ASE.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.ASE.json

Fixes #1805 
Added Azure.ASE.MigrateV3 rule to check for app service environments running with classic versions that will be fully retired on August 31, 2024.

Added Azure.ASE.MigrateV3

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.ACR.ContentTrust.md
src/PSRule.Rules.Azure/rules/Azure.ACR.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.ACR.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.ACR.json

- Fixed `Azure.ACR.ContentTrust` when customer managed keys are enabled.
Fixes #1810

Fixes ACR content trust with CMK #1810

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.FrontDoor.UseCaching.md
docs/examples-frontdoor.bicep
docs/examples-frontdoor.json
src/PSRule.Rules.Azure/en/PSRule-rules.psd1
src/PSRule.Rules.Azure/rules/Azure.FrontDoor.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.FrontDoor.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.FrontDoor.json

Fixes #548 
Added Azure.FrontDoor.UseCaching rule.
This rule ensures that front door instances uses caching to reduce retrieving contents from origins and improve overall performance.

Added Azure.FrontDoor.UseCaching

---

.github/ISSUE_TEMPLATE/bug-report.md
docs/CHANGELOG-v1.md

What's changed since pre-release v1.22.0-B0011:
- New rules:
- Check api management instances limits control plane API calls to apim with version `'2021-08-01'` or newer by @bengeset96.
[#1819](https://github.com/Azure/PSRule.Rules.Azure/issues/1819)
- Engineering:
- Bump Az.Resources to v6.4.0.
[#1829](https://github.com/Azure/PSRule.Rules.Azure/pull/1829)
- Bug fixes:
- Fixed non-Linux VM images flagged as Linux by @BernieWhite.
[#1825](https://github.com/Azure/PSRule.Rules.Azure/issues/1825)
- Fixed failed to expand with last function on runtime property by @BernieWhite.
[#1830](https://github.com/Azure/PSRule.Rules.Azure/issues/1830)

Pre-release v1.22.0-B0026

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.MySQL.GeoRedundantBackup.md
src/PSRule.Rules.Azure/rules/Azure.MySQL.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.MySQL.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.MySQL.json

Fixes #1840 
Added support for the flexible server deployment model in `Azure.MySQL.GeoRedundantBackup` rule.

Added support for the flexible server deployment model in Azure.MySQL.GeoRedundantBackup

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.KeyVault.Logs.md
src/PSRule.Rules.Azure/en/PSRule-rules.psd1
src/PSRule.Rules.Azure/rules/Azure.KeyVault.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.KeyVault.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.KeyVault.json

Fixes #1873 
Fixed missing support for category groups in Azure.KeyVault.Logs rule.

Fixed missing support for category groups in Azure.KeyVault.Logs

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.MariaDB.DatabaseName.md
docs/en/rules/Azure.MariaDB.FirewallRuleName.md
docs/en/rules/Azure.MariaDB.ServerName.md
docs/en/rules/Azure.MariaDB.VNETRuleName.md
src/PSRule.Rules.Azure/rules/Azure.MariaDB.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.MariaDB.Tests.ps1

Fixes #1854
Added `Azure.MariaDB.ServerName`, `Azure.MariaDB.DatabaseName`, `MariaDB.FirewallRuleName` and `Azure.MariaDB.VNETRuleName` rule.

Added Azure Database for MariaDB resources names meet naming requirements

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Common/StringExtensions.cs
src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitor.cs
src/PSRule.Rules.Azure/Data/ResourceManagerVisitor.cs
src/PSRule.Rules.Azure/Data/Template/ExpressionBuilder.cs
src/PSRule.Rules.Azure/Data/Template/Functions.cs
src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
src/PSRule.Rules.Azure/Data/Template/TokenStream.cs
tests/PSRule.Rules.Azure.Tests/Policy.assignment.json
tests/PSRule.Rules.Azure.Tests/PolicyAssignmentVisitorTests.cs

- Fixed policy parse of `requestContext` function. Working towards #1654, some upstream updates are required for completion.
- Fixed handling of policy type field. Working towards #1323, some upstream updates are required for completion.

Fixes for policy function handling #1654 #1323

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Common/JsonExtensions.cs
src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.7.good.bicep
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.7.json

- Fixed managed identity flagged as secret by `Azure.Deployment.OutputSecretValue`.
Fixes #1826 
Fixes #1886 

Fixes empty secure parameter #1826 #1886

---

.github/ISSUE_TEMPLATE/bug-report.md
README.md
docs/CHANGELOG-v1.md
docs/creating-your-pipeline.md
docs/features.md
docs/install-instructions.md
docs/setup/setup-azure-monitor-logs.md
docs/troubleshooting.md
docs/using-bicep.md
docs/working-with-baselines.md
overrides/home.html

What's changed since v1.21.2:
- New rules:
- Check API management instances uses multi-region deployment by @BenjaminEngeset.
[#1030](https://github.com/Azure/PSRule.Rules.Azure/issues/1030)
- Check api management instances limits control plane API calls to apim with version `'2021-08-01'` or newer by @BenjaminEngeset.
[#1819](https://github.com/Azure/PSRule.Rules.Azure/issues/1819)
- App Service Environment:
- Check app service environments uses version 3 (ASEv3) instead of classic version 1 (ASEv1) and version 2 (ASEv2) by @BenjaminEngeset.
[#1805](https://github.com/Azure/PSRule.Rules.Azure/issues/1805)
- Azure Database for MariaDB:
- Check Azure Database for MariaDB servers, databases, firewall rules and VNET rules names meet naming requirements by @BenjaminEngeset. …

Release v1.22.0

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.AKS.Version.md
src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.AKS.json

Fixes #1918 
Added support in Azure.AKS.Version for ignoring clusters with auto-upgrade enabled.

Added support in Azure.AKS.Version for ignoring clusters with auto-upgrade enabled

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/TokenStreamValidator.cs
src/PSRule.Rules.Azure/Runtime/Helper.cs
src/PSRule.Rules.Azure/rules/Azure.Deployment.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Deployment.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.9.bicep
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.9.goodReference.bicep
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.9.json
tests/PSRule.Rules.Azure.Tests/TokenStreamValidatorTests.cs

- Fixed `Azure.Deployment.SecureValue` with `reference` function expression.
Fixes #1882 

Fixes SecureValue with reference function #1882

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Policy/Models.cs
src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitor.cs
src/PSRule.Rules.Azure/Data/Policy/PolicyJsonRuleMapper.cs
src/PSRule.Rules.Azure/Data/Policy/PolicyMode.cs
tests/PSRule.Rules.Azure.Tests/PolicyAssignmentVisitorTests.cs
tests/PSRule.Rules.Azure.Tests/emittedJsonRulesData.jsonc
tests/PSRule.Rules.Azure.Tests/emittedJsonRulesPrefixData.jsonc

- Improves handling for policy definition modes by using support tags selector.
Fixes #1946 

Add supports tag selector for indexed mode #1946

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.23.0-B0046:
- Added December 2022 baselines `Azure.GA_2022_12` and `Azure.Preview_2022_12` by @BernieWhite.
[#1961](https://github.com/Azure/PSRule.Rules.Azure/issues/1961)
- Includes rules released before or during December 2022.
- Marked `Azure.GA_2022_09` and `Azure.Preview_2022_09` baselines as obsolete.
- Updated `Azure.AKS.Version` to use latest stable version `1.25.4` by @BernieWhite.
[#1960](https://github.com/Azure/PSRule.Rules.Azure/issues/1960)
- Improves handling for policy definition modes by using support tags selector by @BernieWhite. …

Pre-release v1.23.0-B0072

---

docs/CHANGELOG-v1.md

What's changed since release v1.22.2:
- Added December 2022 baselines `Azure.GA_2022_12` and `Azure.Preview_2022_12` by @BernieWhite.
[#1961](https://github.com/Azure/PSRule.Rules.Azure/issues/1961)
- Includes rules released before or during December 2022.
- Marked `Azure.GA_2022_09` and `Azure.Preview_2022_09` baselines as obsolete.
- New rules:
- Check API management instances has multi-region deployment gateways enabled by @BenjaminEngeset.
[#1910](https://github.com/Azure/PSRule.Rules.Azure/issues/1910)
- Check Application Gateways names meet naming requirements by @BenjaminEngeset.
[#1943](https://github.com/Azure/PSRule.Rules.Azure/issues/1943)
- Check Azure Cache for Redis instances uses Redis 6 by …

Release v1.23.0

---

docs/CHANGELOG-v1.md

What's changed since v1.23.0:
- Updated `Export-AzRuleData` to improve export performance by @BernieWhite.
[#1341](https://github.com/Azure/PSRule.Rules.Azure/issues/1341)
- Removed `Az.Resources` dependency.
- Added async threading for export concurrency.
- Improved performance by using automatic look up of API versions by using provider cache.
- Engineering:
- Bump PSRule to v2.7.0.
[#1973](https://github.com/Azure/PSRule.Rules.Azure/pull/1973)
- Bump Az.Resources to v6.5.1.
[#1973](https://github.com/Azure/PSRule.Rules.Azure/pull/1973)
- Bump Newtonsoft.Json to v13.0.2.
[#1903](https://github.com/Azure/PSRule.Rules.Azure/pull/1903)
- Bump Pester to v5.4.0.
[#1994](https://github.com/Azure/PSRule.Rules.Azure/pull/1994)
- Bug fixes:
- Fixed `Export-AzRuleData` may …

Pre-release v1.24.0-B0013

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitor.cs
src/PSRule.Rules.Azure/Data/Template/Functions.cs
src/PSRule.Rules.Azure/Data/Template/ITemplateContext.cs
src/PSRule.Rules.Azure/Data/Template/IValidationContext.cs
src/PSRule.Rules.Azure/Data/Template/LambdaExpressionFn.cs
src/PSRule.Rules.Azure/Data/Template/ResourceValue.cs
src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.13.bicep
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.13.json

- Added support for Bicep lambda functions.
- Bicep `filter`, `map`, `reduce`, and `sort` are supported.
- Support for `flatten` was previously added in v1.23.0.
Fixes #1536 

Added support for Bicep lambda functions #1536

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitor.cs

- Fixed `apiVersion` comparison of `requestContext`.
Fixes #1654 

Fixes apiVersion compare of requestContext #1654

---

.github/ISSUE_TEMPLATE/bug-report.md
README.md
docs/CHANGELOG-v1.md
docs/creating-your-pipeline.md
docs/install-instructions.md
docs/setup/setup-azure-monitor-logs.md
docs/troubleshooting.md
docs/using-bicep.md
docs/working-with-baselines.md

What's changed since v1.23.0:
- Updated `Export-AzRuleData` to improve export performance by @BernieWhite.
[#1341](https://github.com/Azure/PSRule.Rules.Azure/issues/1341)
- Removed `Az.Resources` dependency.
- Added async threading for export concurrency.
- Improved performance by using automatic look up of API versions by using provider cache.
- Added support for Bicep lambda functions by @BernieWhite.
[#1536](https://github.com/Azure/PSRule.Rules.Azure/issues/1536)
- Bicep `filter`, `map`, `reduce`, and `sort` are supported.
- Support for `flatten` was previously added in v1.23.0.
- Added optimization for policy type conditions by @BernieWhite.
[#1966](https://github.com/Azure/PSRule.Rules.Azure/issues/1966)
- Engineering:
- Bump PSRule to v2.7.0. …

Release v1.24.0

---

docs/CHANGELOG-v1.md

This is republished v1.24.1 to fix a release issue.
What's changed since v1.24.0:
- Bug fixes:
- Fixes Bicep expand object or null by @BernieWhite.
[#2021](https://github.com/Azure/PSRule.Rules.Azure/issues/2021)

Release v1.24.2

---

.vscode/settings.json
docs/CHANGELOG-v1.md
docs/setup/setup-bicep.md
docs/troubleshooting.md
src/PSRule.Rules.Azure/Data/Bicep/BicepHelper.cs
src/PSRule.Rules.Azure/Runtime/Helper.cs
src/PSRule.Rules.Azure/Runtime/IService.cs
src/PSRule.Rules.Azure/Runtime/RuntimeService.cs
src/PSRule.Rules.Azure/en/PSRule-rules.psd1
src/PSRule.Rules.Azure/rules/Config.Rule.yaml
src/PSRule.Rules.Azure/rules/Conventions.Rule.ps1
tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.16.bicep
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.16.json

- Added warning for minimum Bicep version.
- Configure this option to increase the visibility of the version of the Bicep CLI used by PSRule for Azure.
- Set `AZURE_BICEP_MINIMUM_VERSION` to configure the minimum version.
- By default, this option default to `0.4.451`.
Related to #1935.

Added Bicep minimum version warning #1935

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/Functions.cs
src/PSRule.Rules.Azure/Data/Template/LambdaExpressionFn.cs
tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.13.bicep
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.13.json

- Added support for Bicep `toObject` function.
Fixes #2014 

Added support for toObject #2014

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/rules/Azure.SQL.Rule.ps1

This fixes #2059 where exported resources are sometime flaged as failed with TDE.
I have simplified the check in order so it would verifiy the precense of the two potential fields.

Azure SQL Transparent Encryption: ensure proper result on exported resources

---

docs/CHANGELOG-v1.md
docs/en/baselines/Azure.Preview.md
docs/en/rules/Azure.KeyVault.Firewall.md
src/PSRule.Rules.Azure/rules/Azure.KeyVault.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.KeyVault.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.KeyVault.json

This closes #2067 by checking if a Keyvault as a deny value into its network ACLs.
It does not check for VNET integration or for a list of IP adresses.
- [ X ] PR has a meaningful title
- [ X ] Summarized changes
- [ X ] This PR is ready to merge and is not **Work in Progress**
- [ X ] Unit tests created/ updated
- [ X ] Rule documentation created/ updated
- [ X ] Link to a filed issue
- [ X ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

Added Rules for check public endpoints access on keyvault #2067

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.25.0-B0100:
- New rules:
- Event Hub:
- Check Event Hub namespaces only uses TLS 1.2 version by @BenjaminEngeset.
[#1995](https://github.com/Azure/PSRule.Rules.Azure/issues/1995)

Pre-release v1.25.0-B0138

---

docs/CHANGELOG-v1.md

What's changed since v1.24.2:
- **Experimental**: Added `Azure.MCSB.v1` which include rules aligned to the Microsoft Cloud Security Benchmark by @BernieWhite.
[#1634](https://github.com/Azure/PSRule.Rules.Azure/issues/1634)
- New rules:
- Check Microsoft Defender for Key Vault is enabled by @BernieWhite.
[#1632](https://github.com/Azure/PSRule.Rules.Azure/issues/1632)
- Check Microsoft Defender for DNS is enabled by @BernieWhite.
[#1632](https://github.com/Azure/PSRule.Rules.Azure/issues/1632)
- Check Microsoft Defender for ARM is enabled by @BernieWhite.
[#1632](https://github.com/Azure/PSRule.Rules.Azure/issues/1632)
- Event Hub:
- Check Event Hub namespaces only uses TLS 1.2 version by @BenjaminEngeset. …

Release v1.25.0

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
src/PSRule.Rules.Azure/rules/Azure.Deployment.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.Deployment.Tests.ps1
tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs

- Fixed false positive with `Azure.Deployment.Name`.
Fixes #2109 

Fixes Azure.Deployment.Name false positive #2109

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.AKS.Version.md
docs/examples-aks.bicep
docs/setup/configuring-options.md
docs/setup/configuring-rules.md
docs/upgrade-notes.md
src/PSRule.Rules.Azure/rules/Config.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json
tests/PSRule.Rules.Azure.Tests/Resources.AKS.json

- Updated `Azure.AKS.Version` to use latest stable version `1.25.6`.
Fixes #2136 

Update AKS version to 1.25.6 #2136

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.27.0-B0003:
- New rules:
- Check that base element for any policy element in a section is configured by @BenjaminEngeset.
[#2072](https://github.com/Azure/PSRule.Rules.Azure/issues/2072)
- Check that Microsoft Defender Cloud Security Posture Management is using `Standard` plan by @BenjaminEngeset.
[#2151](https://github.com/Azure/PSRule.Rules.Azure/issues/2151)
- Promoted `Azure.ContainerApp.Insecure` to GA rule set by @BernieWhite.
[#2174](https://github.com/Azure/PSRule.Rules.Azure/issues/2174)
- Bug fixes:
- Fixed ignoring Redis firewall rules when Redis is configured to allow private connectivity by @BenjaminEngeset.
[#2171](https://github.com/Azure/PSRule.Rules.Azure/issues/21 …

Pre-release v1.27.0-B0015

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.MariaDB.DatabaseName.md
src/PSRule.Rules.Azure/rules/Azure.MariaDB.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.MariaDB.Tests.ps1

- Fixed handling of database name in `Azure.MariaDB.Database`.
Fixes #2191

Fixes handling of MariaDB database name #2191

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/Functions.cs
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs

- Fixed length function counting properties in object.
Fixes #2263 

Fixes length function for object #2263

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs
src/PSRule.Rules.Azure/Data/Template/Functions.cs
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs

Merged bug fixes from v1.27.2:
- Bug fixes:
- Fixed union function for merge of object properties by @BernieWhite.
[#2264](https://github.com/Azure/PSRule.Rules.Azure/issues/2264)
- Fixed length function counting properties in object by @BernieWhite.
[#2263](https://github.com/Azure/PSRule.Rules.Azure/issues/2263)
Fixes #2264 
Fixes #2263

Merge patch v1.27.2

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.28.0-B0024:
- Removed rules:
- Removed `Azure.AKS.PodIdentity` as pod identities has been replaced by workload identities by @BernieWhite.
[#2273](https://github.com/Azure/PSRule.Rules.Azure/issues/2273)
- Engineering:
- Bump Microsoft.NET.Test.Sdk to v17.6.2.
[#2266](https://github.com/Azure/PSRule.Rules.Azure/pull/2266)
- Bump Az.Resources to v6.7.0.
[#2274](https://github.com/Azure/PSRule.Rules.Azure/pull/2274)
- Bug fixes:
- Fixed false positive of `IsolatedV2` with `Azure.AppService.MinPlan` by @BernieWhite.
[#2277](https://github.com/Azure/PSRule.Rules.Azure/issues/2277)

Pre-release v1.28.0-B0045

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Common/ResourceHelper.cs
src/PSRule.Rules.Azure/Data/Template/Functions.cs
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
tests/PSRule.Rules.Azure.Tests/ResourceHelperTests.cs

- Added support for `managementGroupResourceId` Bicep function.
Fixes #2294.

Add support for managementGroupResourceId #2294

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.28.0-B0045:
- Added support for `managementGroupResourceId` Bicep function by @BernieWhite.
[#2294](https://github.com/Azure/PSRule.Rules.Azure/issues/2294)
- Engineering:
- Bump PSRule to v2.9.0.
[#2293](https://github.com/Azure/PSRule.Rules.Azure/pull/2293)
- Bump Microsoft.CodeAnalysis.NetAnalyzers to v7.0.3.
[#2281](https://github.com/Azure/PSRule.Rules.Azure/pull/2281)
- Bump Microsoft.NET.Test.Sdk to v17.6.3.
[#2290](https://github.com/Azure/PSRule.Rules.Azure/pull/2290)
- Bump coverlet.collector to v6.0.0.
[#2232](https://github.com/Azure/PSRule.Rules.Azure/pull/2232)
- Bug fixes:
- Fixed handling of JArray outputs with runtime values by @BernieWhite.
[#2159](https://github.com/Azure/PSRule.Rules.Azure/issues/2159)

Pre-release v1.28.0-B0079

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.28.0-B0115:
- Added June 2023 baselines `Azure.GA_2023_06` and `Azure.Preview_2023_06` by @BernieWhite.
[#2310](https://github.com/Azure/PSRule.Rules.Azure/issues/2310)
- Includes rules released before or during June 2023.
- Marked `Azure.GA_2023_03` and `Azure.Preview_2023_03` baselines as obsolete.
- Engineering:
- Bump xunit to v2.5.0.
[#2306](https://github.com/Azure/PSRule.Rules.Azure/pull/2306)
- Bump xunit.runner.visualstudio to v2.5.0.
[#2307](https://github.com/Azure/PSRule.Rules.Azure/pull/2307)
- Bug fixes:
- Fixed Redis firewall rules can not bind to start by @BernieWhite.
[#2303](https://github.com/Azure/PSRule.Rules.Azure/issues/2303)

Pre-release v1.28.0-B0159

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Common/DictionaryExtensions.cs
src/PSRule.Rules.Azure/Common/TypeExtensions.cs
src/PSRule.Rules.Azure/Data/Template/ExpressionBuilder.cs
src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs
src/PSRule.Rules.Azure/Data/Template/Functions.cs
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.19.bicep
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.19.json
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.23.bicep
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.23.json

- Added support for safe dereference operator.
- Fixed late binding of `coalesce` function.
Fixes #2322 
Fixes #2328 

Added support for safe dereference operator #2322

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.28.0-B0159:
- Added support for safe dereference operator by @BernieWhite.
[#2322](https://github.com/Azure/PSRule.Rules.Azure/issues/2322)
- Added support for `tryGet` Bicep function.
- Engineering:
- Bump BenchmarkDotNet to v0.13.6.
[#2317](https://github.com/Azure/PSRule.Rules.Azure/pull/2317)
- Bump BenchmarkDotNet.Diagnostics.Windows to v0.13.6.
[#2318](https://github.com/Azure/PSRule.Rules.Azure/pull/2318)
- Bug fixes:
- Fixed null condition handling by @BernieWhite.
[#2316](https://github.com/Azure/PSRule.Rules.Azure/issues/2316)
- Fixed reference expression in property name by @BernieWhite.
[#2321](https://github.com/Azure/PSRule.Rules.Azure/issues/2321)
- Fixed handling of nested mock objects by @BernieWhite. …

Pre-release v1.28.0-B0213

---

docs/CHANGELOG-v1.md

What's changed since v1.27.3:
- Added June 2023 baselines `Azure.GA_2023_06` and `Azure.Preview_2023_06` by @BernieWhite.
[#2310](https://github.com/Azure/PSRule.Rules.Azure/issues/2310)
- Includes rules released before or during June 2023.
- Marked `Azure.GA_2023_03` and `Azure.Preview_2023_03` baselines as obsolete.
- New rules:
- Check that Azure AD authentication is configured for Azure Database for MySQL databases by @BenjaminEngeset.
[#2226](https://github.com/Azure/PSRule.Rules.Azure/issues/2226)
- Check that Azure AD-only authentication is configured for Azure Database for PostgreSQL databases by @BenjaminEngeset.
[#2250](https://github.com/Azure/PSRule.Rules.Azure/issues/2250)
- Check that Azure AD …

Release v1.28.0

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/CidrParsing.cs
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs

- Fixed `parseCidr` with `/32` is not valid by @BernieWhite.
[#2336](https://github.com/Azure/PSRule.Rules.Azure/issues/2336)
Fixes #2336

Fixes parseCidr with 32 is not valid #2336

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitor.cs
tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
tests/PSRule.Rules.Azure.Tests/Policy.assignment.2.json
tests/PSRule.Rules.Azure.Tests/PolicyAssignmentVisitorTests.cs

- Fixed mismatch of resource group type on policy as code rules.
Fixes #2338 

Fixes mismatch of RG policy type #2338

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.Firewall.Name.md
docs/en/rules/Azure.MariaDB.DatabaseName.md
docs/en/rules/Azure.MariaDB.GeoRedundantBackup.md
docs/en/rules/Azure.MariaDB.MinTLS.md
docs/en/rules/Azure.MariaDB.ServerName.md
docs/en/rules/Azure.MariaDB.UseSSL.md
docs/en/rules/Azure.MariaDB.VNETRuleName.md
docs/examples-firewall.bicep
docs/examples-firewall.json
docs/examples-mariadb.bicep
docs/examples-mariadb.json
src/PSRule.Rules.Azure/en/PSRule-rules.psd1
src/PSRule.Rules.Azure/rules/Azure.MariaDB.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.MariaDB.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.MariaDB.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.MariaDB.json

- Fixed naming rules for MariaDB.
- Updated `Azure.MariaDB.VNETRuleName` to allow for parent resources.
- Updated `Azure.MariaDB.FirewallRuleName` to allow for parent resources.
Fixes #2335 

Fixed naming rules for MariaDB #2335

---

docs/CHANGELOG-v1.md

What's changed since v1.28.0:
- Bug fixes:
- Fixed `parseCidr` with `/32` is not valid by @BernieWhite.
[#2336](https://github.com/Azure/PSRule.Rules.Azure/issues/2336)
- Fixed mismatch of resource group type on policy as code rules by @BernieWhite.
[#2338](https://github.com/Azure/PSRule.Rules.Azure/issues/2338)
- Fixed length cannot be less than zero when converting policy to rules by @BernieWhite.
[#1802](https://github.com/Azure/PSRule.Rules.Azure/issues/1802)
- Fixed naming rules for MariaDB by @BernieWhite.
[#2335](https://github.com/Azure/PSRule.Rules.Azure/issues/2335)
- Updated `Azure.MariaDB.VNETRuleName` to allow for parent resources.
- Updated `Azure.MariaDB.FirewallRuleName` to allow for parent resources.
- Fixed network watcher existence check by @BernieWhite. …

Release v1.28.1

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Policy/Models.cs
src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitor.cs
src/PSRule.Rules.Azure/Data/Policy/PolicyJsonRuleMapper.cs
tests/PSRule.Rules.Azure.Tests/PolicyAssignmentVisitorTests.cs
tests/PSRule.Rules.Azure.Tests/emittedJsonRulesData.jsonc
tests/PSRule.Rules.Azure.Tests/emittedJsonRulesPrefixData.jsonc

- Use policy definition name when generating a rule from it.
Fixes #1959 

Use policy definition name #1959

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/Functions.cs
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.13.bicep
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.13.json

- Fixed index out of bounds of array with first function on empty array.
Fixes #2372 

Fixes out of bounds for first on empty array #2372

---

docs/CHANGELOG-v1.md

What's changed since v1.28.2:
- New rules:
- Databricks:
- Check that workspaces use secure cluster connectivity by @BernieWhite.
[#2334](https://github.com/Azure/PSRule.Rules.Azure/issues/2334)
- Use policy definition name when generating a rule from it by @BernieWhite.
[#1959](https://github.com/Azure/PSRule.Rules.Azure/issues/1959)
- Added export in-flight data for Defender for Storage from Storage Accounts by @BernieWhite.
[#2248](https://github.com/Azure/PSRule.Rules.Azure/issues/2248)
- Added export in-flight data for Defender for APIs from API Management by @BernieWhite.
[#2247](https://github.com/Azure/PSRule.Rules.Azure/issues/2247)
- Bug fixes:
- Fixed policy expansion with unquoted field property by @BernieWhite. …

Release v1.29.0

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/LambdaExpressionFn.cs
tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.13.bicep
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.13.json

- Fixed lambda map in map variable.
Fixes #2410 

Fixed lambda map in map variable #2410

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.30.0-B0026:
- Engineering:
- Bump Microsoft.CodeAnalysis.NetAnalyzers to v7.0.4.
[#2405](https://github.com/Azure/PSRule.Rules.Azure/pull/2405)
- Bug fixes:
- Fixed lambda map in map variable by @BernieWhite.
[#2410](https://github.com/Azure/PSRule.Rules.Azure/issues/2410)

Pre-release v1.30.0-B0047

---

docs/en/baselines/Azure.All.md
docs/en/baselines/Azure.Default.md
docs/en/baselines/Azure.GA_2022_09.md
docs/en/baselines/Azure.GA_2022_12.md
docs/en/baselines/Azure.GA_2023_03.md
docs/en/baselines/Azure.GA_2023_06.md
docs/en/baselines/Azure.MCSB.v1.md
docs/en/baselines/Azure.Preview.md
docs/en/rules/Azure.Storage.BlobAccessType.md
docs/en/rules/Azure.Storage.BlobPublicAccess.md
docs/en/rules/Azure.Storage.ContainerSoftDelete.md
docs/en/rules/Azure.Storage.DefenderCloud.MalwareScan.md
docs/en/rules/Azure.Storage.DefenderCloud.md
docs/en/rules/Azure.Storage.FileShareSoftDelete.md
docs/en/rules/Azure.Storage.Firewall.md
docs/en/rules/Azure.Storage.MinTLS.md
docs/en/rules/Azure.Storage.SoftDelete.md
docs/en/rules/Azure.Storage.UseReplication.md
docs/en/rules/index.md
docs/en/rules/module.md
docs/en/rules/resource.md
docs/es/rules/index.md
docs/es/rules/module.md
docs/es/rules/resource.md
src/PSRule.Rules.Azure/rules/Azure.SQLMI.Rule.yaml
src/PSRule.Rules.Azure/rules/Azure.Storage.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.Storage.Rule.yaml

- Improvements and fixes to storage account rule documentation.

Quality updates to storage rule docs

---

docs/CHANGELOG-v1.md
docs/deprecations.md
docs/en/rules/Azure.Resource.AllowedRegions.md
docs/setup/configuring-rules.md
docs/upgrade-notes.md
src/PSRule.Rules.Azure/Runtime/Helper.cs
src/PSRule.Rules.Azure/Runtime/RuntimeService.cs
src/PSRule.Rules.Azure/en/PSRule-rules.psd1
src/PSRule.Rules.Azure/rules/Azure.Resource.Rule.ps1
src/PSRule.Rules.Azure/rules/Conventions.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Resource.Tests.ps1

- Replaced `Azure_AllowedRegions` option with `AZURE_RESOURCE_ALLOWED_LOCATIONS`.
Working towards #941

Replaced Azure_AllowedRegions #941

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.30.0-B0047:
- **Important change:** Replaced the `Azure_AllowedRegions` option with `AZURE_RESOURCE_ALLOWED_LOCATIONS`.
[#941](https://github.com/Azure/PSRule.Rules.Azure/issues/941)
- For compatibility, if `Azure_AllowedRegions` is set it will be used instead of `AZURE_RESOURCE_ALLOWED_LOCATIONS`.
- If only `AZURE_RESOURCE_ALLOWED_LOCATIONS` is set, this value will be used.
- The default will be used neither options are configured.
- If `Azure_AllowedRegions` is set a warning will be generated until the configuration is removed.
- Support for `Azure_AllowedRegions` is deprecated and will be removed in v2.
- Engineering:
- Bump Microsoft.NET.Test.Sdk to v17.7.2.
[#2407](https://github.com/Azure/PSRule.Rules.Azure/pull/2407)
- …

Pre-release v1.30.0-B0080

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.AKS.Version.md
docs/examples-aks.bicep
docs/examples-aks.json
docs/setup/configuring-options.md
docs/setup/configuring-rules.md
docs/upgrade-notes.md
src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.yaml
src/PSRule.Rules.Azure/rules/Config.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json
tests/PSRule.Rules.Azure.Tests/Resources.AKS.json

- Updated `Azure.AKS.Version` to use latest stable version `1.26.6`.
- Fixed `Azure.AKS.Version` by excluding `node-image` channel.
Fixes #2404 
Fixes #2446 

Updates for Azure.AKS.Version #2404 #2446

---

docs/CHANGELOG-v1.md
docs/setup/configuring-options.md
docs/using-bicep.md
docs/using-templates.md

What's changed since v1.29.0:
- Added September 2023 baselines `Azure.GA_2023_09` and `Azure.Preview_2023_09` by @BernieWhite.
[#2451](https://github.com/Azure/PSRule.Rules.Azure/issues/2451)
- Includes rules released before or during September 2023.
- Marked `Azure.GA_2023_06` and `Azure.Preview_2023_06` baselines as obsolete.
- New rules:
- Azure Container Apps:
- Check that Container Apps uses a supported API version by @BenjaminEngeset.
[#2398](https://github.com/Azure/PSRule.Rules.Azure/issues/2398)
- Azure Container Registry:
- Check that Container Registries restricts network access by @BenjaminEngeset.
[#2423](https://github.com/Azure/PSRule.Rules.Azure/issues/2423)
- Check that Container Registries disables anonymous pull access by @BenjaminEngeset. …

Release v1.30.0

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/ExpressionBuilder.cs
src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs
src/PSRule.Rules.Azure/Runtime/RuntimeService.cs
src/PSRule.Rules.Azure/rules/Conventions.Rule.ps1
tests/PSRule.Rules.Azure.Tests/RuntimeHelperTests.cs

- Fixed `Azure.Resource.AllowedRegions` which was failing when no allowed regions were configured.
Fixes #2461 

Fixes Azure.Resource.AllowedRegions #2461

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Pipeline/Export/ResourceExportVisitor.cs
src/PSRule.Rules.Azure/rules/Config.Rule.yaml
tests/PSRule.Rules.Azure.Tests/ResourceExportVisitorTests.cs

- Fixed binding of results resourceId and resourceGroupName.
Fixes #2460

Fixed Azure field binding #2460

---

docs/CHANGELOG-v1.md

What's changed since v1.30.3:
- New rules:
- Deployment:
- Check parameters potentially containing secure values by @BernieWhite.
[#1476](https://github.com/Azure/PSRule.Rules.Azure/issues/1476)
- Machine Learning:
- Check compute instances are configured for an idle shutdown by @batemansogq.
[#2484](https://github.com/Azure/PSRule.Rules.Azure/issues/2484)
- Check workspace compute has local authentication disabled by @batemansogq.
[#2484](https://github.com/Azure/PSRule.Rules.Azure/issues/2484)
- Check workspace compute is connected to a VNET by @batemansogq.
[#2484](https://github.com/Azure/PSRule.Rules.Azure/issues/2484)
- Check public access to a workspace is disabled by @batemansogq.
[#2484](https://github.com/Azure/PSRule.Rules.Azure/issues/2484)
- Check workspaces use a …

Release v1.31.0

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.Deployment.AdminUsername.md
docs/en/rules/Azure.Deployment.SecureParameter.md
docs/setup/configuring-rules.md
src/PSRule.Rules.Azure/rules/Azure.Deployment.Rule.ps1
src/PSRule.Rules.Azure/rules/Config.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.Deployment.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.Deployments.json

- Fixed additional non-sensitive parameter name patterns.
- Added support for configuration of the rule by setting `AZURE_DEPLOYMENT_NONSENSITIVE_PARAMETER_NAMES`.
Fixes #2528 

Fixed non-sensitive parameter name patterns #2528

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitor.cs
src/PSRule.Rules.Azure/Data/Template/DeploymentSymbol.cs
src/PSRule.Rules.Azure/Data/Template/ExpressionBuilder.cs
src/PSRule.Rules.Azure/Data/Template/ITemplateContext.cs
src/PSRule.Rules.Azure/Data/Template/LambdaExpressionFn.cs
src/PSRule.Rules.Azure/Data/Template/Mocks.cs
src/PSRule.Rules.Azure/Data/Template/RuleDataExportVisitor.cs
src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
src/PSRule.Rules.Azure/Pipeline/Export/ResourceExportVisitor.cs
tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.27.bicep
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.27.child.bicep
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.27.json

- Fixed null dereferenced properties in map lambda.
- Fixed handling of for array index symbols.
Fixes #2535 
Fixes #2548
Related to microsoft/PSRule#1640

Fixes null and array index handling #2535 #2548

---

.ps-rule/Rule.Rule.ps1
docs/CHANGELOG-v1.md
docs/en/rules/Azure.Deployment.SecureParameter.md
src/PSRule.Rules.Azure/rules/Azure.Deployment.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Resources.Deployments.json

- Fixed additional false positives of `Azure.Deployment.SecureParameter`.
Fixes #2556 

Fixed false positives for secure parameter #2556

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.32.0-B0021:
- Network Interface:
- **Important change**: Renamed NIC rules to reflect current usage by @BernieWhite.
[#2574](https://github.com/Azure/PSRule.Rules.Azure/issues/2574)
- Rename `Azure.VM.NICAttached` to `Azure.NIC.Attached`.
- Rename `Azure.VM.NICName` to `Azure.NIC.Name`.
- Rename `Azure.VM.UniqueDns` to `Azure.NIC.UniqueDns`.
- Added aliases to reference the old names for suppression and exclusion.
- Old names will be removed from v2.
- Added support for private link services to `Azure.VM.NICAttached` by @BernieWhite.
[#2563](https://github.com/Azure/PSRule.Rules.Azure/issues/2563)
- Quality updates to documentation by @BernieWhite.
[#2570](https://github.com/Azure/PSRule.Rules.Azure/issues/2570) …

Pre-release v1.32.0-B0053

---

mkdocs.yml
overrides/main.html
overrides/partials/actions.html
overrides/partials/comments.html
overrides/reference.html

Improvements to templates and configuration used for building docs.

Update docs build templates

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/rules/Baseline.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1

- Added December 2023 baselines `Azure.GA_2023_12` and `Azure.Preview_2023_12` by @BernieWhite.
- Includes rules released before or during December 2023.
- Marked `Azure.GA_2023_09` and `Azure.Preview_2023_09` baselines as obsolete.
Fixes #2580

Added december baselines #2580

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.APIM.DefenderCloud.md
docs/en/rules/Azure.Defender.Api.md
docs/examples-defender.bicep
docs/examples-defender.json
src/PSRule.Rules.Azure/rules/Azure.APIM.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.Defender.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.Defender.json

- Promoted `Azure.APIM.DefenderCloud` to GA rule set.
- Promoted `Azure.Defender.Api` to GA rule set.
Fixes #2591 

Promote defender for APIs rules to GA #2591

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.32.0-B0053:
- Added December 2023 baselines `Azure.GA_2023_12` and `Azure.Preview_2023_12` by @BernieWhite.
[#2580](https://github.com/Azure/PSRule.Rules.Azure/issues/2580)
- Includes rules released before or during December 2023.
- Marked `Azure.GA_2023_09` and `Azure.Preview_2023_09` baselines as obsolete.
- Promoted `Azure.AppConfig.GeoReplica` to GA rule set by @BernieWhite.
[#2592](https://github.com/Azure/PSRule.Rules.Azure/issues/2592)
- Promoted `Azure.APIM.DefenderCloud` to GA rule set by @BernieWhite.
[#2591](https://github.com/Azure/PSRule.Rules.Azure/issues/2591)
- Updated `Azure.AKS.Version` to use latest stable version `1.27.7` by …

Pre-release v1.32.0-B0099

---

docs/CHANGELOG-v1.md

What's changed since v1.31.3:
- Added December 2023 baselines `Azure.GA_2023_12` and `Azure.Preview_2023_12` by @BernieWhite.
[#2580](https://github.com/Azure/PSRule.Rules.Azure/issues/2580)
- Includes rules released before or during December 2023.
- Marked `Azure.GA_2023_09` and `Azure.Preview_2023_09` baselines as obsolete.
- Promoted `Azure.AppConfig.GeoReplica` to GA rule set by @BernieWhite.
[#2592](https://github.com/Azure/PSRule.Rules.Azure/issues/2592)
- Promoted `Azure.APIM.DefenderCloud` to GA rule set by @BernieWhite.
[#2591](https://github.com/Azure/PSRule.Rules.Azure/issues/2591)
- Updated `Azure.AKS.Version` to use latest stable version `1.27.7` by @BernieWhite. …

Release v1.32.0

---

.vscode/settings.json
docs/CHANGELOG-v1.md
docs/en/rules/Azure.VNET.UseNSGs.md
docs/setup/configuring-rules.md
src/PSRule.Rules.Azure/rules/Azure.VNET.Rule.ps1
src/PSRule.Rules.Azure/rules/Config.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.VNET.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.VirtualNetwork.json

- Added option for excluding subnets to `Azure.VNET.UseNSGs`.
- To add a subnet exlcusion, set the `AZURE_VNET_SUBNET_EXCLUDED_FROM_NSG` option.
Fixes #2572

Add option for excluding subnets from NSG #2572

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.AppGwWAF.RuleGroups.md
pipeline.build.ps1
src/PSRule.Rules.Azure/rules/Azure.AppGwWAF.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.AppGwWAF.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.AppGwWAF.json

Fixes #2629
Updated `Azure.AppGwWAF.RuleGroups` to use the rule sets:
- The latest Bot Manager rule set is now `1.0`.
- The latest OWASP rule set is now `3.2`.

feat: Updated Azure.AppGwWAF.RuleGroups to use the rule sets

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/Functions.cs

- Fixed `dateTimeAdd` may fail with different localization.
Fixes #2631

Fixes dateTimeAdd default format string #2631

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.VM.DiskSizeAlignment.md
docs/examples-vm.bicep
docs/examples-vm.json
src/PSRule.Rules.Azure/rules/Azure.VM.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.VM.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.VM.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.VirtualMachine.json

- Fixed `Azure.VM.DiskSizeAlignment` does not handle smaller sizes and ultra disks.
Fixes #2656 

Fixes Azure.VM.DiskSizeAlignment disk sizes #2656

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/rules/Azure.Template.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Template.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.Template.V2.json

Add `languageVersion` and `definitions` fields to AZR-000212
Ref: https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/syntax#template-format
fixes #2660

Add languageVersion 2.0 fields to AZR-000212

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.33.0-B0126:
- Exporting policy as rules also generates a baseline by @BernieWhite.
[#2482](https://github.com/Azure/PSRule.Rules.Azure/issues/2482)
- A baseline is automatically generated that includes for all rules exported.
If a policy rule has been replaced by a built-in rule, the baseline will include the built-in rule instead.
- The baseline is named `<Prefix>.PolicyBaseline.All`. i.e. `Azure.PolicyBaseline.All` by default.
- For details see [Policy as rules](./concepts/policy-as-rules.md#generated-baseline).
- Rules that are ignored during exporting policy as rules are now generate a verbose logs by @BernieWhite.
[#2482](https://github.com/Azure/PSRule.Rules.Azure/issues/2482)
- This is to improve …

Pre-release v1.33.0-B0169

---

docs/CHANGELOG-v1.md

What's changed since v1.32.1:
- Exporting policy as rules also generates a baseline by @BernieWhite.
[#2482](https://github.com/Azure/PSRule.Rules.Azure/issues/2482)
- A baseline is automatically generated that includes for all rules exported.
If a policy rule has been replaced by a built-in rule, the baseline will include the built-in rule instead.
- The baseline is named `<Prefix>.PolicyBaseline.All`. i.e. `Azure.PolicyBaseline.All` by default.
- For details see [Policy as rules](./concepts/policy-as-rules.md#generated-baseline).
- New rules:
- Databricks:
- Check that Databricks workspaces use a non-trial SKU by @batemansogq.
[#2646](https://github.com/Azure/PSRule.Rules.Azure/issues/2646)
- Check that Databricks workspaces require use of private endpoints by …

Release v1.33.0

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.AKS.AuthorizedIPs.md
docs/examples-aks.bicep
docs/examples-aks.json
src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.AKS.json

- Fixed `Azure.AKS.AuthorizedIPs` is not valid for a private cluster.
Fixes #2677

Fixes Azure.AKS.AuthorizedIPs for private cluster #2677

---

docs/CHANGELOG-v1.md

What's changed since v1.33.0:
- Bug fixes:
- Fixed `Azure.AKS.AuthorizedIPs` is not valid for a private cluster by @BernieWhite.
[#2677](https://github.com/Azure/PSRule.Rules.Azure/issues/2677)
- Fixed generating rule for VM extensions from policy is incorrect by @BernieWhite.
[#2608](https://github.com/Azure/PSRule.Rules.Azure/issues/2608)

Release v1.33.1

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.Resource.AllowedRegions.md
src/PSRule.Rules.Azure/rules/Azure.Resource.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Resource.Tests.ps1

- Fixed false positive of `Azure.Resource.AllowedRegions` raised during assertion call.
Fixes #2687 

Fixed false positive Azure.Resource.AllowedRegions #2687

---

.vscode/settings.json
docs/CHANGELOG-v1.md
docs/en/rules/Azure.AKS.MinNodeCount.md
docs/en/rules/Azure.AKS.MinUserPoolNodes.md
docs/setup/configuring-rules.md
src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.yaml
src/PSRule.Rules.Azure/rules/Config.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json
tests/PSRule.Rules.Azure.Tests/Resources.AKS.json

- New rules:
- Check that user mode pools have a minimum number of nodes by @BernieWhite.
- Added configuration to support changing the minimum number of node and to exclude node pools.
- Set `AZURE_AKS_CLUSTER_USER_POOL_MINIMUM_NODES` to set the minimum number of user nodes.
- Set `AZURE_AKS_CLUSTER_USER_POOL_EXCLUDED_FROM_MINIMUM_NODES` to exclude a specific node pool by name.
- Updated `Azure.AKS.MinNodeCount` the count nodes system node pools by @BernieWhite.
- Improved guidance and examples specifically for system node pools.
- Added configuration to support changing the minimum number of node.
- Set `AZURE_AKS_CLUSTER_MINIMUM_SYSTEM_NODES` to set the minimum number of system nodes.
Fixes #2683
- **Rule …

AKS min node improvements #2683

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.34.0-B0047:
- Microsoft Defender for Cloud:
- Renamed rules to align with recommended naming length by @BernieWhite.
[#2718](https://github.com/Azure/PSRule.Rules.Azure/issues/2718)
- Renamed `Azure.Defender.Storage.SensitiveData` to `Azure.Defender.Storage.DataScan`.
- Promoted `Azure.Defender.Storage.MalwareScan` to GA rule set by @BernieWhite.
[#2590](https://github.com/Azure/PSRule.Rules.Azure/issues/2590)
- Renamed rules to align with recommended naming length by @BernieWhite.
[#2718](https://github.com/Azure/PSRule.Rules.Azure/issues/2718)
- Renamed `Azure.Storage.DefenderCloud.MalwareScan` to `Azure.Storage.Defender.MalwareScan`.
- Renamed `Azure.Storage.DefenderCloud.SensitiveData` to …

Pre-release v1.34.0-B0077

---

docs/CHANGELOG-v1.md

What's changed since v1.33.2:
- New rules:
- Check that user mode pools have a minimum number of nodes by @BernieWhite.
[#2683](https://github.com/Azure/PSRule.Rules.Azure/issues/2683)
- Added configuration to support changing the minimum number of node and to exclude node pools.
- Set `AZURE_AKS_CLUSTER_USER_POOL_MINIMUM_NODES` to set the minimum number of user nodes.
- Set `AZURE_AKS_CLUSTER_USER_POOL_EXCLUDED_FROM_MINIMUM_NODES` to exclude a specific node pool by name.
- Updated `Azure.AKS.MinNodeCount` the count nodes system node pools by @BernieWhite.
[#2683](https://github.com/Azure/PSRule.Rules.Azure/issues/2683)
- Improved guidance and examples specifically for system node pools.
- Added configuration to …

Release v1.34.0

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.LB.AvailabilityZone.md
src/PSRule.Rules.Azure/rules/Azure.LB.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Resources.VirtualNetwork.json

This pull request includes a change to the `Azure.LB.AvailabilityZone` rule in the `Azure.LB.Rule.ps1` file. The change removes the condition that checks if the `zones` property of the `ipConfig` object is null or empty. This means that the rule will now only assert if the `zones` property is a set of '1', '2', '3'.
This is what needs to be true for the LB to be truly zone redundant

Update Azure.LB.Rule.ps1 for PIP Zones Condition

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.AppService.NETVersion.md
src/PSRule.Rules.Azure/rules/Azure.AppService.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.AppService.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.AppService.Template.json

- Updated `Azure.AppService.NETVersion` to detect out of date .NET versions including .NET 5/6/7.
Fixes #2766

Updated Azure.AppService.NETVersion .NET version #2766

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.35.0-B0030:
- Updated `Azure.AppService.NETVersion` to detect out of date .NET versions including .NET 5/6/7 by @BernieWhite.
[#2766](https://github.com/Azure/PSRule.Rules.Azure/issues/2766)
- Bumped rule set to `2024_03`.
- Updated `Azure.AppService.PHPVersion` to detect out of date PHP versions before 8.2 by @BernieWhite.
[#2768](https://github.com/Azure/PSRule.Rules.Azure/issues/2768)
- Fixed `Azure.AppService.PHPVersion` check fails when phpVersion is null.
- Bumped rule set to `2024_03`.
- Updated `Azure.AKS.Version` to use `1.27.9` as the minimum version by @BernieWhite.
[#2771](https://github.com/Azure/PSRule.Rules.Azure/issues/2771)
- Quality updates to rule documentation by @BernieWhite. …

Pre-release v1.35.0-B0055

---

docs/CHANGELOG-v1.md

What's changed since v1.34.2:
- Added WAF pillar specific baselines by @BernieWhite.
[#1633](https://github.com/Azure/PSRule.Rules.Azure/issues/1633)
[#2752](https://github.com/Azure/PSRule.Rules.Azure/issues/2752)
- Use pillar specific baselines to target a specific area of the Azure Well-Architected Framework.
- The following baselines have been added:
- `Azure.Pillar.CostOptimization`
- `Azure.Pillar.OperationalExcellence`
- `Azure.Pillar.PerformanceEfficiency`
- `Azure.Pillar.Reliability`
- `Azure.Pillar.Security`
- Added March 2024 baselines `Azure.GA_2024_03` and `Azure.Preview_2024_03` by @BernieWhite.
[#2781](https://github.com/Azure/PSRule.Rules.Azure/issues/2781)
- Includes rules released before or during March 2024.
- Marked `Azure.GA_2023_12` and …

Release v1.35.0

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.ContainerApp.MinReplicas.md
docs/examples-containerapp.bicep
docs/examples-containerapp.json
src/PSRule.Rules.Azure/rules/Azure.ContainerApp.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.ContainerApp.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.ContainerApp.json

- Check that Container Apps have a minimum number of replicas.
Fixes #2790

Check that Container Apps have a minimum number of replicas #2790

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.27.bicep
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.27.child.bicep
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.27.json

Merge bug fixes from patch release from v1.35.1:
- Bug fixes:
- Fixed null parameter overrides default value by @BernieWhite.
[#2795](https://github.com/Azure/PSRule.Rules.Azure/issues/2795)
Fixes #2795

Merge patch release v1.35.1

---

docs/about.md

This pull request includes a minor change to the `docs/about.md` file. The change removes the reference to the `Azure/bicep-registry-modules` repository from the list of first-party repositories that use PSRule for Azure.

Add AVM/BRM to about.md

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/Mocks.cs
tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.36.bicep
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.36.child.bicep
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.36.json

- Fixed regression when handing ambiguous mock array outputs.
Fixes #2801

Fixed regression when handing ambiguous mock array outputs #2801

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/Mocks.cs
tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.36.bicep
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.36.child.bicep
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.36.json

Merge fixes from v1.35.2:
- Bug fixes:
- Fixed regression when handing ambiguous mock array outputs by @BernieWhite.
[#2801](https://github.com/Azure/PSRule.Rules.Azure/issues/2801)
Fixes #2801

Merge fixes from v1.35.2

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Pipeline/Export/ResourceExportVisitor.cs

- Fixed not found warning when exporting firewall policy signatureOverrides.
Fixes #2806

Fix not found firewall policy signatureOverrides #2806

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.Cosmos.DefenderCloud.md
docs/en/rules/Azure.Cosmos.DisableMetadataWrite.md
docs/en/rules/Azure.Cosmos.MinTLS.md
docs/examples-cosmos.bicep
docs/examples-cosmos.json
src/PSRule.Rules.Azure/rules/Azure.Cosmos.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.Cosmos.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.Cosmos.json

- Check that database accounts only accept a minimum of TLS 1.2.
Fixes #2809

Add min TLS check for Cosmos DB #2809

---

.github/workflows/docs.yaml

- Updated pages deployment workflow.

Updated pages deployment

---

.vscode/markdown.code-snippets
data/policy-ignore.json
docs/CHANGELOG-v1.md
docs/en/rules/Azure.ContainerApp.AvailabilityZone.md
docs/en/rules/Azure.ContainerApp.ExternalIngress.md
docs/en/rules/Azure.ContainerApp.Insecure.md
docs/en/rules/Azure.ContainerApp.ManagedIdentity.md
docs/en/rules/Azure.EventHub.DisableLocalAuth.md
docs/en/rules/Azure.EventHub.MinTLS.md
docs/en/rules/Azure.SQL.Auditing.md
docs/en/rules/Azure.SQL.MinTLS.md
docs/en/rules/Azure.ServiceBus.DisableLocalAuth.md
docs/en/rules/Azure.ServiceBus.MinTLS.md
docs/en/rules/Azure.Storage.MinTLS.md
docs/examples-sql.bicep
docs/examples-sql.json
src/PSRule.Rules.Azure/rules/Azure.SQL.Rule.ps1
src/PSRule.Rules.Azure/rules/Azure.SQL.Rule.yaml
tests/PSRule.Rules.Azure.Tests/PolicyAssignmentVisitorTests.cs

- Quality updates to documentation.
- Additional policies added to default ignore list.
Working towards #2570 
Working towards #1731

Rule doc quality updates #2570 #1731

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.Storage.UseReplication.md
src/PSRule.Rules.Azure/rules/Azure.Storage.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Storage.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.Storage.json

WAF guidance is recommending either Geo or zone-redundant storage, I think we should allow for both to pass the test.
Fixes #2827 

[Azure.Storage.UseReplication] Update rule to allow for ZRS

---

docs/CHANGELOG-v1.md
requirements-docs.txt

What's changed since pre-release v1.36.0-B0020:
- Bug fixes:
- Fixed `Azure.Storage.UseReplication` to allow for zone-redundant replication by @sebassem.
[#2827](https://github.com/Azure/PSRule.Rules.Azure/issues/2827)
- Fixed nested usage of `listKeys` mocks by @BernieWhite.
[#2829](https://github.com/Azure/PSRule.Rules.Azure/issues/2829)

Pre-release v1.36.0-B0046

---

.ps-rule/Rule.Rule.ps1
CONTRIBUTING.md
docs/CHANGELOG-v1.md
docs/deprecations.md
docs/en/rules/Azure.Template.DefineParameters.md
docs/en/rules/Azure.Template.ResourceLocation.md
docs/en/rules/Azure.Template.UseParameters.md
docs/en/rules/Azure.Template.UseVariables.md
docs/en/rules/Azure.Template.ValidSecretRef.md
src/PSRule.Rules.Azure/rules/Azure.Template.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1

- **Important change**: Deprecated rules with no clear WAF alignment
- The following rules are deprecated:
- `Azure.Template.UseParameters`
- `Azure.Template.UseVariables`
- `Azure.Template.DefineParameters`
- `Azure.Template.ValidSecretRef`
Fixes #2493

WAF Alignments of rules - wave 1 #2493

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.ADX.SLA.md
docs/en/rules/Azure.AKS.UptimeSLA.md
docs/en/rules/Azure.SignalR.SLA.md
docs/en/rules/Azure.WebPubSub.SLA.md
docs/examples-adx.bicep
docs/examples-adx.json
docs/examples-signalr.bicep
docs/examples-signalr.json
docs/examples-webpubsub.bicep
docs/examples-webpubsub.json

- Quality updates to documentation.
Working towards #2570

Quality updates to documentation #2570

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.Deployment.SecureParameter.md
src/PSRule.Rules.Azure/rules/Azure.Deployment.Rule.ps1

- Add additional exclusions for `Azure.Deployment.SecureParameter`.
Fixes #2857 

Add additional exclusions for Azure.Deployment.SecureParameter #2857

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.Cosmos.PublicAccess.md
src/PSRule.Rules.Azure/rules/Azure.Cosmos.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.Cosmos.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.Cosmos.json

Fixes #2702
Added Azure.Cosmos.PublicAccess.

feat(new): Added Azure.Cosmos.PublicAccess

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.APIM.AvailabilityZone.md
src/PSRule.Rules.Azure/rules/Azure.APIM.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.APIM.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1

Fixes #2788
Updated Azure.APIM.AvailabilityZone.

feat: Updated Azure.APIM.AvailabilityZone

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/ExpressionHelpers.cs
src/PSRule.Rules.Azure/Data/Template/Functions.cs
src/PSRule.Rules.Azure/Data/Template/LambdaExpressionFn.cs
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
tests/PSRule.Rules.Azure.Tests/TestLengthObject.cs
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.39.bicep
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.39.json

- Added support for new Bicep language features introduced in v0.27.1.
- Added support for `shallowMerge`, `groupBy`, `objectKeys`, and `mapValues`.
- Updated syntax for Bicep lambda usage of `map`, `reduce`, and `filter` which now support indices.
- Added support for spread operator.
- Fixed `union` does not perform deep merge or keep property order.
Fixes #2859 
Fixes #2860 
Fixes #2885

Added new Bicep language features from v0.27.1 #2859 #2860 #2885

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.LogAnalytics.Replication.md
src/PSRule.Rules.Azure/rules/Azure.LogAnalytics.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.LogAnalytics.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.LogAnalytics.json

Fixes #2893
Added Azure.LogAnalytics.Replication.

feat(new): Added Azure.LogAnalytics.Replication

---

docs/CHANGELOG-v1.md

What's changed since v1.36.0:
- Added support for new Bicep language features introduced in v0.27.1 by @BernieWhite.
[#2860](https://github.com/Azure/PSRule.Rules.Azure/issues/2860)
[#2859](https://github.com/Azure/PSRule.Rules.Azure/issues/2859)
- Added support for `shallowMerge`, `groupBy`, `objectKeys`, and `mapValues`.
- Updated syntax for Bicep lambda usage of `map`, `reduce`, and `filter` which now support indices.
- Added support for spread operator.
- New rules:
- App Service:
- Check that applications uses supported Node.js runtime versions by @BenjaminEngeset.
[#2879](https://github.com/Azure/PSRule.Rules.Azure/issues/2879)
- Check that WAF v2 doesn't use legacy WAF configuration by @BenjaminEngeset. …

Release v1.37.0

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.AKS.Version.md
docs/examples-aks.bicep
docs/examples-aks.json
docs/setup/configuring-options.md
docs/setup/configuring-rules.md
src/PSRule.Rules.Azure/rules/Config.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json
tests/PSRule.Rules.Azure.Tests/Resources.AKS.json

- Updated `Azure.AKS.Version` to use `1.28.9` as the minimum version.
Fixes #2930 

Updated Azure.AKS.Version to use 1.28.9 #2930

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.38.0-B0011:
- New rules:
- Added check to automatically upgrade AKS cluster node image by @sharmilamusunuru.
[#2445](https://github.com/Azure/PSRule.Rules.Azure/issues/2445)
- Azure Virtual Desktop:
- Added check for scheduled agent updates on host pools by @BernieWhite.
[#2946](https://github.com/Azure/PSRule.Rules.Azure/issues/2946)
- Verify that virtual machine scale sets have best-effort zone balance configured by @BenjaminEngeset.
[#2901](https://github.com/Azure/PSRule.Rules.Azure/issues/2901)
- Verify that virtual machine scale sets have availability zones configured by @BenjaminEngeset.
[#2902](https://github.com/Azure/PSRule.Rules.Azure/issues/2902)
- Engineering:
- Quality updates to …

Pre-release v1.38.0-B0034

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Pipeline/ResourceDataPipeline.cs

- Fixed group by subscription casing when exporting in-flight resources.
Fixes #2957

Fixes group by subscription casing #2957

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.38.0-B0034:
- Added March 2024 baselines `Azure.GA_2024_06` and `Azure.Preview_2024_06` by @BernieWhite.
[#2961](https://github.com/Azure/PSRule.Rules.Azure/issues/2961)
- Includes rules released before or during June 2024.
- Marked `Azure.GA_2024_03` and `Azure.Preview_2024_03` baselines as obsolete.
- Engineering:
- Quality updates to rule documentation by @BernieWhite.
[#2570](https://github.com/Azure/PSRule.Rules.Azure/issues/2570)
- Bug fixes:
- Fixed support for `references` function by @BernieWhite.
[#2922](https://github.com/Azure/PSRule.Rules.Azure/issues/2922)
- Fixed group by subscription casing when exporting in-flight resources by @BernieWhite.
[#2957](https://github.com/Azure/PSRule.Rules.Azure/issues/2957)
- Fixed install …

Pre-release v1.38.0-B0068

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.38.0-B0068:
- New rules:
- Cosmos DB:
- Verify that Cosmos DB accounts have continuous backup configured by @BenjaminEngeset.
[#2954](https://github.com/Azure/PSRule.Rules.Azure/issues/2954)
- Bug fixes:
- Rollback Az.Resources to v6.7.0 by @BernieWhite.
[#2970](https://github.com/Azure/PSRule.Rules.Azure/issues/2970)
- Fixed handling of multi-line descriptions for policy definition and assignment exports by @BernieWhite.
[#2973](https://github.com/Azure/PSRule.Rules.Azure/issues/2973)

Pre-release v1.38.0-B0106

---

docs/CHANGELOG-v1.md

What's changed since v1.37.0:
- Added March 2024 baselines `Azure.GA_2024_06` and `Azure.Preview_2024_06` by @BernieWhite.
[#2961](https://github.com/Azure/PSRule.Rules.Azure/issues/2961)
- Includes rules released before or during June 2024.
- Marked `Azure.GA_2024_03` and `Azure.Preview_2024_03` baselines as obsolete.
- New rules:
- Verify that Azure Database for MySQL servers have a customer-controlled maintenance window configured by @BenjaminEngeset.
[#2916](https://github.com/Azure/PSRule.Rules.Azure/issues/2916)
- Verify that servers have zone-redundant high availability (HA) configured by @BenjaminEngeset.
[#2914](https://github.com/Azure/PSRule.Rules.Azure/issues/2914)
- Verify that Azure Database for …

Release v1.38.0

---

docs/CHANGELOG-v1.md

What's changed since v1.38.0:
- New rules:
- App Service:
- Verify that app service plans have availability zones configured by @BenjaminEngeset.
[#2964](https://github.com/Azure/PSRule.Rules.Azure/issues/2964)
- App Service Environment:
- Verify that app service environments have availability zones configured by @BenjaminEngeset.
[#2964](https://github.com/Azure/PSRule.Rules.Azure/issues/2964)
- Azure SQL Database:
- Verify that Azure SQL databases have a customer-controlled maintenance window configured by @BenjaminEngeset.
[#2956](https://github.com/Azure/PSRule.Rules.Azure/issues/2956)
- Azure SQL Managed Instance:
- Verify that Azure SQL Managed Instances have a customer-controlled maintenance window configured by @BenjaminEngeset. …

Pre-release v1.39.0-B0009

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.39.0-B0009:
- New rules:
- Verify that clusters have kube-audit logging disabled when not required by @BenjaminEngeset.
[#2450](https://github.com/Azure/PSRule.Rules.Azure/issues/2450)
- Verify that clusters have the customer-controlled maintenance windows 'aksManagedAutoUpgradeSchedule' and 'aksManagedNodeOSUpgradeSchedule' configured by @BenjaminEngeset.
[#2444](https://github.com/Azure/PSRule.Rules.Azure/issues/2444)
- Verify that zonal-deployed Azure firewalls uses Azure NAT Gateway for outbound access by @BenjaminEngeset.
[##3005](https://github.com/Azure/PSRule.Rules.Azure/issues/#3005)
- Verify that subnets have disabled default outbound access for virtual machines by @BenjaminEngeset. …

Pre-release v1.39.0-B0029

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/rules/Azure.AppService.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.AppService.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.AppService.json

Fixes #3034
Fixed `Azure.AppService.AvailabilityZone` only detects premium by tier property.

Fixed Azure.AppService.AvailabilityZone only detects premium by tier

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.39.0-B0029:
- New rules:
- Verify that virtual machines does not have public IPs attached by @BenjaminEngeset.
[#11](https://github.com/Azure/PSRule.Rules.Azure/issues/11)
- Verify that multi-tenant Hosting Rights are used for Windows client VMs by @BenjaminEngeset.
[#432](https://github.com/Azure/PSRule.Rules.Azure/issues/432)
- Verify that availability set members are in a backend pool by @BenjaminEngeset.
[#67](https://github.com/Azure/PSRule.Rules.Azure/issues/67)
- Verify that virtual machine scale set instances does not have public IPs attached by @BenjaminEngeset.
[#3014](https://github.com/Azure/PSRule.Rules.Azure/issues/3014)
- Updated …

Pre-release v1.39.0-B0072

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.39.0-B0072:
- Added September 2024 baselines `Azure.GA_2024_09` and `Azure.Preview_2024_09` by @BernieWhite.
[#3048](https://github.com/Azure/PSRule.Rules.Azure/issues/3048)
- Includes rules released before or during September 2024.
- Marked `Azure.GA_2024_06` and `Azure.Preview_2024_06` baselines as obsolete.

Pre-release v1.39.0-B0118

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.Redis.MinTLS.md
docs/en/rules/Azure.RedisEnterprise.MinTLS.md
docs/examples-redis.bicep
docs/examples-redis.json
docs/examples-redisenterprise.bicep
docs/examples-redisenterprise.json
src/PSRule.Rules.Azure/rules/Azure.Redis.Rule.yaml
src/PSRule.Rules.Azure/rules/Azure.RedisEnterprise.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.Redis.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.Redis.json

- Fixed TLS defaults for `Azure.Redis.MinTLS` and `Azure.RedisEnterprise.MinTLS`.
Fixces #3066 

Update TLS defaults for Azure.Redis.MinTLS #3066

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.ContainerApp.AvailabilityZone.md
src/PSRule.Rules.Azure/rules/Azure.ContainerApp.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.ContainerApp.Tests.ps1

- Updated `Azure.ContainerApp.AvailabilityZone` to check for infrastructure subnet by @BernieWhite.
- Configuring an infrastructure subnet is a requirement for enabling zone redundancy.
Both rule and documentation have been updated to clearly call this out.
Fixes #3068 

Updated Azure.ContainerApp.AvailabilityZone to check for infrastructure subnet #3068

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.38.0:
- Added September 2024 baselines `Azure.GA_2024_09` and `Azure.Preview_2024_09` by @BernieWhite.
[#3048](https://github.com/Azure/PSRule.Rules.Azure/issues/3048)
- Includes rules released before or during September 2024.
- Marked `Azure.GA_2024_06` and `Azure.Preview_2024_06` baselines as obsolete.
- New rules:
- Verify that clusters have kube-audit logging disabled when not required by @BenjaminEngeset.
[#2450](https://github.com/Azure/PSRule.Rules.Azure/issues/2450)
- Verify that clusters have the customer-controlled maintenance windows `aksManagedAutoUpgradeSchedule` and `aksManagedNodeOSUpgradeSchedule` configured by @BenjaminEngeset.
[#2444](https://github.com/Azure/PSRule.Rules.Azure/issues/2444)
- …

Release v1.39.0

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Common/JsonExtensions.cs
src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
tests/PSRule.Rules.Azure.Tests/Bicep/ExtensibilityTestCases/Tests.Bicep.1.bicep
tests/PSRule.Rules.Azure.Tests/Bicep/ExtensibilityTestCases/Tests.Bicep.1.json
tests/PSRule.Rules.Azure.Tests/Bicep/ExtensibilityTestCases/bicepconfig.json
tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs

- Fixed `GetBicepParamResources` exception when expanding `Microsoft.Graph/groups` resource.
Fixes #3062

Fixed GetBicepParamResources exception when expanding Microsoft Graph #3062

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.AppGw.AvailabilityZone.md
docs/examples/resources/appgw.bicep
docs/examples/resources/appgw.json
docs/setup/configuring-rules.md
src/PSRule.Rules.Azure/rules/Azure.AppGw.Rule.ps1
src/PSRule.Rules.Azure/rules/Config.Rule.yaml

- Fixed `Azure.AppGw.AvailabilityZone` passes when a zonal configuration is used.
Fixes #3061

Fixed `Azure.AppGw.AvailabilityZone` with zonal config #3061

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Template/ExistingResourceValue.cs
tests/PSRule.Rules.Azure.Tests/Bicep/SymbolicNameTestCases/Tests.Bicep.1.bicep
tests/PSRule.Rules.Azure.Tests/Bicep/SymbolicNameTestCases/Tests.Bicep.3.bicep
tests/PSRule.Rules.Azure.Tests/Bicep/SymbolicNameTestCases/Tests.Bicep.3.json
tests/PSRule.Rules.Azure.Tests/Bicep/UserDefinedFunctionTestCases/Tests.Bicep.1.bicep
tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.38.bicep

- Fixed name expand of existing resource references.
Fixes #3123

Fixes name expand of existing resource references #3123

---

data/secret-property.json
docs/CHANGELOG-v1.md
docs/en/rules/Azure.Deployment.SecureValue.md
src/PSRule.Rules.Azure.BuildTool/ClientBuilder.cs
src/PSRule.Rules.Azure.BuildTool/ProviderResource.cs
src/PSRule.Rules.Azure/Data/SecretPropertyData.cs
src/PSRule.Rules.Azure/Data/Template/ResourceProviderHelper.cs
src/PSRule.Rules.Azure/Runtime/Helper.cs
src/PSRule.Rules.Azure/Runtime/RuntimeService.cs
src/PSRule.Rules.Azure/rules/Azure.Deployment.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Deployment.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Data/SecretPropertyDataTests.cs
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.9.badContainerApps.bicep
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.9.bicep
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.9.json
tests/PSRule.Rules.Azure.Tests/TokenStreamValidatorTests.cs

- Updated `Azure.Deployment.SecureValue` to check additional resource types by @BernieWhite.
- Added support for container apps secret properties.
- Added support for deployment script secret properties.
Fixes #2650 
Fixes #2651 

 Updated Azure.Deployment.SecureValue #2650 #2651

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/Network/NetworkSecurityGroupEvaluator.cs
tests/PSRule.Rules.Azure.Tests/NetworkSecurityGroupEvaluatorTests.cs

- Fixed evaluation of `Azure.NSG.LateralTraversal` with empty string properties.
Fixes #3130

Fixes empty string handling in Azure.NSG.LateralTraversal #3130

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.40.0-B0029:
- Microsoft Defender for Cloud:
- Updated `Azure.DefenderCloud.Contact` to use `emails` property and removed `phone` by @BernieWhite.
[#3117](https://github.com/Azure/PSRule.Rules.Azure/issues/3117)
- Renamed rule to `Azure.Defender.SecurityContact` to better align with naming for defender rules.
- Bug fixes:
- Fixed evaluation of `Azure.NSG.LateralTraversal` with empty string properties by @BernieWhite.
[#3130](https://github.com/Azure/PSRule.Rules.Azure/issues/3130)
- Fixed evaluation of `Azure.Deployment.AdminUsername` with symbolic references by @BernieWhite.
[#3146](https://github.com/Azure/PSRule.Rules.Azure/issues/3146)

Pre-release v1.40.0-B0063

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Common/ResourceHelper.cs
src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
src/PSRule.Rules.Azure/DictionaryExtensions.cs
src/PSRule.Rules.Azure/PSObjectExtensions.cs
tests/PSRule.Rules.Azure.Tests/ResourceHelperTests.cs
tests/PSRule.Rules.Azure.Tests/RuntimeServiceTests.cs

- Fixed object to hashtable conversion for default parameter values.
Fixes #3033

Fixes object to hashtable conversion for default params #3033

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Common/ResourceHelper.cs
src/PSRule.Rules.Azure/Data/Template/Functions.cs
src/PSRule.Rules.Azure/Data/Template/RuleDataExportVisitor.cs
src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
tests/PSRule.Rules.Azure.Tests/Bicep/ScopeTestCases/BicepScopeTests.cs
tests/PSRule.Rules.Azure.Tests/Bicep/ScopeTestCases/Tests.Bicep.1.bicep
tests/PSRule.Rules.Azure.Tests/Bicep/ScopeTestCases/Tests.Bicep.1.json
tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
tests/PSRule.Rules.Azure.Tests/ResourceHelperTests.cs
tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs

- Fixed deployments with more than one module at tenant scope.
Fixes #3167

Fixes deployments with more than one module at tenant scope #3167

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Data/APIM/APIMPolicyReader.cs
src/PSRule.Rules.Azure/Runtime/Helper.cs
src/PSRule.Rules.Azure/rules/Azure.APIM.Rule.ps1
tests/PSRule.Rules.Azure.Tests/APIM/APIMPolicyTests.cs
tests/PSRule.Rules.Azure.Tests/APIM/Tests.Policy.1.xml
tests/PSRule.Rules.Azure.Tests/BaseTests.cs
tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
tests/PSRule.Rules.Azure.Tests/TemplateVisitorTestsBase.cs

- Fixed evaluation of APIM policies when using embedded C# with quotes.
Fixes #3184

Fixes APIM policies when using embedded C# with quotes #3184

---

.devcontainer/devcontainer.json
.gitignore
global.json

Update configuration for dev container.

Update Dev Container config

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Common/ResourceHelper.cs
src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
tests/PSRule.Rules.Azure.Tests/Bicep/ScopeTestCases/BicepScopeTests.cs
tests/PSRule.Rules.Azure.Tests/Bicep/ScopeTestCases/Tests.Bicep.2.bicep
tests/PSRule.Rules.Azure.Tests/Bicep/ScopeTestCases/Tests.Bicep.2.child1.bicep
tests/PSRule.Rules.Azure.Tests/Bicep/ScopeTestCases/Tests.Bicep.2.child2.bicep
tests/PSRule.Rules.Azure.Tests/Bicep/ScopeTestCases/Tests.Bicep.2.json
tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj

- Fixed Resource group ID is incorrect under subscription scope.
Fixes #3198 

Fixed Resource group ID is incorrect under subscription scope #3198

---

docs/CHANGELOG-v1.md

What's changed since v1.39.3:
- Added support for expanding from `.jsonc` parameter files by @BernieWhite.
[#2053](https://github.com/Azure/PSRule.Rules.Azure/issues/2053)
- Previously only parameter files with the `.json` extension where automatically expanded.
- This feature adds support so that JSON parameter files with the `.jsonc` extension are also discovered and expanded.
- No additional configuration is required if expansion of JSON parameter files is enabled.
- To enable parameter file expansion set the `AZURE_PARAMETER_FILE_EXPANSION` configuration option to `true`.
- Deployment:
- Updated `Azure.Deployment.SecureValue` to check additional resource types by @BernieWhite.
[#2650](https://github.com/Azure/PSRule.Rules.Azure/issues/2650) …

Release v1.40.0

---

data/policy-ignore.json
docs/CHANGELOG-v1.md
docs/en/rules/Azure.ACR.AnonymousAccess.md
docs/examples/avm/acr.bicep
src/PSRule.Rules.Azure/rules/Azure.ACR.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1

- Updated documentation and promoted `Azure.ACR.AnonymousAccess` to GA by @BernieWhite.
Fixed #3119

Promote Azure.ACR.AnonymousAccess to GA #3119

---

docs/CHANGELOG-v1.md
docs/concepts/about_PSRule_Azure_Configuration.md
docs/en/rules/Azure.AKS.NodeAutoUpgrade.md
docs/en/rules/Azure.AKS.NodeMinPods.md
docs/en/rules/Azure.AKS.PoolVersion.md
docs/en/rules/Azure.AKS.Version.md
docs/examples/resources/aks.bicep
docs/examples/resources/aks.json
docs/setup/configuring-rules.md
docs/setup/index.md
src/PSRule.Rules.Azure/rules/Config.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json
tests/PSRule.Rules.Azure.Tests/Resources.AKS.json

- Updated `Azure.AKS.Version` to use `1.30.6` as the minimum version.
Fixes #3206

Bump AKS version to v1.30.6 #3206

---

docs/en/rules/Azure.AKS.HttpAppRouting.md
src/PSRule.Rules.Azure/rules/Azure.AKS.Rule.yaml
src/PSRule.Rules.Azure/rules/Azure.Redis.Rule.yaml

Documentation quality updates

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/rules/Baseline.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1

- Added December 2024 baselines `Azure.GA_2024_12` and `Azure.Preview_2024_12`.
- Includes rules released before or during December 2024.
- Marked `Azure.GA_2024_09` and `Azure.Preview_2024_09` baselines as obsolete.
Fixes #3165

Added December 2024 baselines #3165

---

docs/CHANGELOG-v1.md
docs/deprecations.md
docs/en/rules/Azure.AKS.CNISubnetSize.md
docs/en/rules/Azure.APIM.ProductTerms.md
docs/en/rules/Azure.APIM.SampleProducts.md
docs/en/rules/Azure.LogicApp.LimitHTTPTrigger.md
docs/en/rules/Azure.VM.Agent.md
docs/examples/resources/logic-app-consumption.bicep
docs/examples/resources/logic-app-consumption.json
docs/examples/resources/vm.bicep
docs/examples/resources/vm.json
src/PSRule.Rules.Azure/rules/Azure.APIM.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1

- Updates to WAF rule documentation.
- Deprecated `Azure.APIM.ProductTerms` rule which no longer aligns to WAF.
Working towards #3102

WAF rule updates #3102

---

docs/CHANGELOG-v1.md
scripts/dependencies.psm1

What's changed since v1.40.0:
- Added December 2024 baselines `Azure.GA_2024_12` and `Azure.Preview_2024_12` by @BernieWhite.
[#3165](https://github.com/Azure/PSRule.Rules.Azure/issues/3165)
- Includes rules released before or during December 2024.
- Marked `Azure.GA_2024_09` and `Azure.Preview_2024_09` baselines as obsolete.
- Updated `Azure.AKS.Version` to use `1.30.6` as the minimum version by @BernieWhite.
[#3206](https://github.com/Azure/PSRule.Rules.Azure/issues/3206)
- Updated documentation and promoted `Azure.ACR.AnonymousAccess` to GA by @BernieWhite.
[#3119](https://github.com/Azure/PSRule.Rules.Azure/issues/3119)
- **Important change**: …

Release v1.41.0

---

.vscode/settings.json
docs/CHANGELOG-v1.md
ps-rule.lock.json

Minor update to change log and other repository files.

Updated change log

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Common/ResourceHelper.cs
src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
tests/PSRule.Rules.Azure.Tests/Bicep/ScopeTestCases/BicepScopeTests.cs
tests/PSRule.Rules.Azure.Tests/Bicep/ScopeTestCases/Tests.Bicep.3.bicep
tests/PSRule.Rules.Azure.Tests/Bicep/ScopeTestCases/Tests.Bicep.3.child1.bicep
tests/PSRule.Rules.Azure.Tests/Bicep/ScopeTestCases/Tests.Bicep.3.child2.bicep
tests/PSRule.Rules.Azure.Tests/Bicep/ScopeTestCases/Tests.Bicep.3.child3.bicep
tests/PSRule.Rules.Azure.Tests/Bicep/ScopeTestCases/Tests.Bicep.3.json
tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
tests/PSRule.Rules.Azure.Tests/ResourceHelperTests.cs

- Fixed incorrect generation of resource ID for tenant scoped deployments.
Fixes #3237

Fixes tenant scope resource ID #3237

---

docs/CHANGELOG-v1.md
src/PSRule.Rules.Azure/Common/ResourceHelper.cs
src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
src/PSRule.Rules.Azure/Pipeline/Export/ResourceExportVisitor.cs
src/PSRule.Rules.Azure/Pipeline/Export/SubscriptionExportContext.cs
src/PSRule.Rules.Azure/Pipeline/ResourceDataPipeline.cs
tests/PSRule.Rules.Azure.Tests/Bicep/ScopeTestCases/BicepScopeTests.cs
tests/PSRule.Rules.Azure.Tests/Bicep/ScopeTestCases/Tests.Bicep.3.bicep
tests/PSRule.Rules.Azure.Tests/Bicep/ScopeTestCases/Tests.Bicep.3.child1.bicep
tests/PSRule.Rules.Azure.Tests/Bicep/ScopeTestCases/Tests.Bicep.3.child2.bicep
tests/PSRule.Rules.Azure.Tests/Bicep/ScopeTestCases/Tests.Bicep.3.child3.bicep
tests/PSRule.Rules.Azure.Tests/Bicep/ScopeTestCases/Tests.Bicep.3.json
tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
tests/PSRule.Rules.Azure.Tests/ResourceHelperTests.cs

Merge patch v1.41.1:
- Bug fixes:
- Fixed incorrect generation of resource ID for tenant scoped deployments by @BernieWhite.
[#3237](https://github.com/Azure/PSRule.Rules.Azure/issues/3237)
- Fixed in-flight export of subscription resource type `Microsoft.Subscription` by @BernieWhite.
[#3231](https://github.com/Azure/PSRule.Rules.Azure/issues/3231)
Fixes #3237 
Fixes #3231

Merge patch v1.41.1

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.VM.Standalone.md
docs/examples/resources/vm.bicep
docs/examples/resources/vm.json
src/PSRule.Rules.Azure/rules/Azure.VM.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.VM.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.VirtualMachine.json

- Fixed Azure VM Standalone failing on data disks check.
Fixes #3263

Fixes Azure VM Standalone failing on data disks #3263

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.KeyVault.AutoRotationPolicy.md
src/PSRule.Rules.Azure/Pipeline/Export/ResourceExportVisitor.cs

- Fixed in-flight analysis of key rotation policy fails due to missing data.
Fixes #3261

Fixes key rotation policy fails due to missing data #3261

---

data/policy-ignore.json
docs/CHANGELOG-v1.md
docs/en/rules/Azure.ACR.AnonymousAccess.md
docs/en/rules/Azure.AppService.MinTLS.md
docs/en/rules/Azure.ImageBuilder.CustomizeHash.md
docs/en/rules/Azure.ImageBuilder.ValidateHash.md
docs/examples/resources/appservice.bicep
docs/examples/resources/appservice.json
src/PSRule.Rules.Azure/rules/Azure.AppService.Rule.ps1
tests/PSRule.Rules.Azure.Tests/PolicyAssignmentVisitorTests.cs
tests/PSRule.Rules.Azure.Tests/Resources.AppService.json

- Updated `Azure.AppService.MinTLS` to include TLS 1.3 as a valid minimum version.
- Added additional exclusions to policies for `Azure.AppService.MinTLS`.
Fixes #3269
- [ x] PR has a meaningful title

Updated minimum TLS for App Service #3269

---

docs/CHANGELOG-v1.md

What's changed since v1.41.4:
- New rules:
- Image Builder:
- Check that image builder build and validation scripts are pinned by @BernieWhite.
[#2903](https://github.com/Azure/PSRule.Rules.Azure/issues/2903)
- App Service:
- Updated `Azure.AppService.MinTLS` to include TLS 1.3 as a valid minimum version by @BernieWhite.
[#3269](https://github.com/Azure/PSRule.Rules.Azure/issues/3269)
- Added a new quickstart guide for using Azure Pipelines with PSRule by @that-ar-guy.
[#3220](https://github.com/Azure/PSRule.Rules.Azure/pull/3220)
- Added additional exclusions to policies for `Azure.AppService.MinTLS` by @BernieWhite.
[#1731](https://github.com/Azure/PSRule.Rules.Azure/issues/1731)
- Engineering:
- Updates to WAF documentation by @BernieWhite. …

Pre-release v1.42.0-B0021

---

docs/CHANGELOG-v1.md
docs/en/rules/Azure.Grafana.Version.md
docs/examples/resources/grafana.bicep
docs/examples/resources/grafana.json
src/PSRule.Rules.Azure/rules/Azure.Grafana.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Grafana.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.Grafana.json

- Bumped `Azure.Grafana.Version` to use version `11` as `10` is now depreciated.
Fixes #3293

Bump Azure.Grafana.Version to version 11 #3293

---

docs/CHANGELOG-v1.md
docs/setup/configuring-expansion.md
docs/troubleshooting.md
src/PSRule.Rules.Azure/Configuration/ConfigurationOption.cs
src/PSRule.Rules.Azure/Configuration/DeployerOption.cs
src/PSRule.Rules.Azure/Data/Policy/PolicyAssignmentVisitor.cs
src/PSRule.Rules.Azure/Data/Template/DeploymentFailureException.cs
src/PSRule.Rules.Azure/Data/Template/Functions.cs
src/PSRule.Rules.Azure/Data/Template/ITemplateContext.cs
src/PSRule.Rules.Azure/Data/Template/NestedTemplateContext.cs
src/PSRule.Rules.Azure/Data/Template/TemplateVisitor.cs
src/PSRule.Rules.Azure/Pipeline/PipelineContext.cs
src/PSRule.Rules.Azure/Resources/PSRuleResources.Designer.cs
src/PSRule.Rules.Azure/Resources/PSRuleResources.resx
tests/PSRule.Rules.Azure.Tests/FunctionTests.cs
tests/PSRule.Rules.Azure.Tests/PSRule.Rules.Azure.Tests.csproj
tests/PSRule.Rules.Azure.Tests/TemplateVisitorTests.cs
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.41.bicep
tests/PSRule.Rules.Azure.Tests/Tests.Bicep.41.json

- Added support for `fail` and `deployer` functions during Bicep expansion.
Fixes #3308
Fixes microsoft/PSRule#2840

Added support for fail and deployer Bicep functions #3308

---

docs/changelog.md

What's changed since v1.42.0:
- New rules:
- AI Search:
- Check if resource name matches the configured name format by @BernieWhite.
[#3325](https://github.com/Azure/PSRule.Rules.Azure/issues/3325)
- The name format can be configured by the `AZURE_AI_SEARCH_NAME_FORMAT` configuration option.
- AI Service:
- Check if resource name matches the configured name format by @BernieWhite.
[#3325](https://github.com/Azure/PSRule.Rules.Azure/issues/3325)
- The name format can be configured by the `AZURE_AI_SERVICES_NAME_FORMAT` configuration option.
- Check if resource tags match the required tags by @BernieWhite.
[#3325](https://github.com/Azure/PSRule.Rules.Azure/issues/3325)
- The required tags can be configured by the `AZURE_RESOURCE_REQUIRED_TAGS` configuration option.
- …

Release v1.43.0

---

docs/changelog.md
docs/en/rules/Azure.Deployment.SecureParameter.md
src/PSRule.Rules.Azure/rules/Azure.Deployment.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Deployment.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.Deployments.json

- Fixed identification of secure parameters with custom type for `Azure.Deployment.SecureParameter`.
Fixes #3347 

Fixed Azure.Deployment.SecureParameter with custom types #3347

---

.vscode/markdown.code-snippets
.vscode/settings.json
data/policy-ignore.json
docs/changelog.md
docs/en/rules/Azure.VMSS.AutoInstanceRepairs.md
docs/en/rules/Azure.VNET.PrivateSubnet.md
docs/examples/resources/vmss.bicep
docs/examples/resources/vmss.json
docs/examples/resources/vnet.bicep
docs/examples/resources/vnet.json
src/PSRule.Rules.Azure/rules/Azure.VMSS.Rule.yaml
src/PSRule.Rules.Azure/rules/Azure.VNET.Rule.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1

- Updated documentation and promoted `Azure.VNET.PrivateSubnet` to GA.
- Bumped rule set to `2025_06`.
- Updated documentation and promoted `Azure.VMSS.AutoInstanceRepairs` to GA.
- Bumped rule set to `2025_06`.
Fixes #3386
Fixes #3378

Updated and promoted GA rules #3386 #3378

---

docs/changelog.md
src/PSRule.Rules.Azure/Arm/Expressions/ExpressionStream.cs
src/PSRule.Rules.Azure/Arm/Expressions/Functions.cs
src/PSRule.Rules.Azure/Data/Template/NestedTemplateContext.cs
tests/PSRule.Rules.Azure.Tests/Arm/Expressions/ExpressionParserTests.cs

- Fixed not implemented exception for deployment name in lambda expression.
- Fixed incorrect parsing of double quoted string during expansion.
Fixes #3393 
Fixes #3394 

Fix expansion issues #3393 #3394

---

docs/changelog.md
src/PSRule.Rules.Azure/rules/Azure.Log.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.Log.Tests.ps1

- Fixes `Azure.Log.Replication` by removing `location` check.
Fixes #3411

Fix location check for Azure.Log.Replication #3411

---

docs/changelog.md
docs/en/rules/Azure.AppGw.MinInstance.md
docs/examples/resources/appgw.bicep
docs/examples/resources/appgw.json
src/PSRule.Rules.Azure/rules/Azure.AppGw.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Resources.AppGw.json

Fixed `Azure.AppGw.MinInstance` should allow 0 minimum capacity for v2 with autoscale by @BernieWhite @mbender-ms.
This update rule, tests and add more detailed examples.
Fixes #3452

Fixed `Azure.AppGw.MinInstance` should allow 0 minimum capacity #3452

---

docs/changelog.md
docs/concepts/about_PSRule_Azure_Configuration.md
docs/en/rules/Azure.AKS.NodeAutoUpgrade.md
docs/en/rules/Azure.AKS.Version.md
docs/examples/resources/aks.bicep
docs/examples/resources/aks.json
docs/setup/configuring-rules.md
src/PSRule.Rules.Azure/rules/Baseline.Rule.yaml
src/PSRule.Rules.Azure/rules/Config.Rule.yaml
tests/PSRule.Rules.Azure.Tests/Azure.AKS.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Azure.Baseline.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.AKS.Template.json
tests/PSRule.Rules.Azure.Tests/Resources.AKS.json

What's changed since pre-release v1.45.0-B0104:
- Added June 2025 baselines `Azure.GA_2025_06` and `Azure.Preview_2025_06`.
- Includes rules released before or during June 2025.
- Marked `Azure.GA_2025_03` and `Azure.Preview_2025_03` baselines as obsolete.
- Updated `Azure.AKS.Version` to use `1.32.5` as the minimum version.
Fixes #3463 
Fixes #3465 

Updated AKS version and added June baselines #3463 #3465

---

docs/changelog.md
docs/updates/v1.45.md

What's changed since v1.44.2:
- Added June 2025 baselines `Azure.GA_2025_06` and `Azure.Preview_2025_06` by @BernieWhite.
[#3465](https://github.com/Azure/PSRule.Rules.Azure/issues/3465)
- Includes rules released before or during June 2025.
- Marked `Azure.GA_2025_03` and `Azure.Preview_2025_03` baselines as obsolete.
- Added June 2025 CAF baseline `Azure.CAF_2025_06` for recent naming changes by @BernieWhite.
[#3464](https://github.com/Azure/PSRule.Rules.Azure/issues/3464)
- New rules:
- Check that App Configuration Key Values do not contain known secrets by @BernieWhite.
[#3439](https://github.com/Azure/PSRule.Rules.Azure/issues/3439)
- Event Grid:
- Check namespaces use a minimum of TLS 1.2 by @BernieWhite. …

Release v1.45.0

---

tests/PSRule.Rules.Azure.Tests/Azure.APIM.Tests.ps1
tests/PSRule.Rules.Azure.Tests/Resources.APIM.json

Bump certificate expiry for tests since we are now within the default interval that `Azure.APIM.CertificateExpiry` fails.

Update certificate expiry in tests
